import React, { useEffect, useState } from 'react';
import { Alert, Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { DEFAULT_ENTERPRISE_SETTINGS, EnterpriseSettings, readEnterpriseSettings, saveEnterpriseSettings } from './adminSettings';

const NAVY='#0B3558', BLUE='#1769E0', BG='#F3F6FA', TEXT='#17324D', MUTED='#78889A', BORDER='#DFE6EE';

function Num({label,value,onChange,unit,help}:{label:string;value:number;onChange:(n:number)=>void;unit:string;help:string}){
  return <View style={s.row}><View style={{flex:1}}><Text style={s.label}>{label}</Text><Text style={s.help}>{help}</Text></View><View style={s.numWrap}><TextInput style={s.num} keyboardType="numeric" value={String(value)} onChangeText={v=>onChange(Number(v.replace(/\D/g,''))||0)}/><Text style={s.unit}>{unit}</Text></View></View>;
}
function Toggle({label,help,value,onChange}:{label:string;help:string;value:boolean;onChange:(v:boolean)=>void}){return <View style={s.row}><View style={{flex:1}}><Text style={s.label}>{label}</Text><Text style={s.help}>{help}</Text></View><Switch value={value} onValueChange={onChange}/></View>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{children}</View>}

export default function AdminSettingsScreen({visible,onClose,onSaved}:{visible:boolean;onClose:()=>void;onSaved?:(v:EnterpriseSettings)=>void}){
 const [v,setV]=useState<EnterpriseSettings>(DEFAULT_ENTERPRISE_SETTINGS); const [saving,setSaving]=useState(false);
 useEffect(()=>{if(visible)readEnterpriseSettings().then(setV)},[visible]);
 const save=async()=>{setSaving(true);try{const n=await saveEnterpriseSettings(v);setV(n);onSaved?.(n);Alert.alert('Configurações salvas','As regras operacionais foram atualizadas neste dispositivo.');}finally{setSaving(false)}};
 return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><SafeAreaView style={s.root}><View style={s.header}><Pressable onPress={onClose} style={s.back}><Text style={s.backText}>‹</Text></Pressable><View><Text style={s.title}>Configuração administrativa</Text><Text style={s.headerSub}>Central de regras do Movvant</Text></View></View><ScrollView contentContainerStyle={s.content}>
 <View style={s.notice}><Text style={s.noticeTitle}>Configuração centralizada</Text><Text style={s.noticeText}>Este menu concentra parâmetros ajustáveis do aplicativo. Regras críticas podem ser refinadas conforme o tipo de negócio sem alterar o código.</Text></View>
 <Section title="Check-in e Check-out"><Num label="Raio de validação" value={v.visit.geofenceMeters} unit="m" help="Menor = mais preciso. Maior = tolera GPS e locais amplos." onChange={n=>setV({...v,visit:{...v.visit,geofenceMeters:n}})}/><Num label="Frequência de proximidade" value={v.visit.proximityCheckSeconds} unit="s" help="Menor = detecta paradas rápidas mais cedo; usa GPS com mais frequência." onChange={n=>setV({...v,visit:{...v.visit,proximityCheckSeconds:n}})}/><Num label="Janela da agenda" value={v.visit.scheduleWindowMinutes} unit="min" help="Quanto antes/depois do horário uma visita pode sugerir check-in." onChange={n=>setV({...v,visit:{...v.visit,scheduleWindowMinutes:n}})}/><Num label="Permanência mínima" value={v.visit.minimumVisitMinutes} unit="min" help="0 não exige permanência mínima para check-out." onChange={n=>setV({...v,visit:{...v.visit,minimumVisitMinutes:n}})}/><Toggle label="Sugerir check-in ao chegar" help="Mostra confirmação quando o usuário entra no raio." value={v.visit.suggestCheckin} onChange={x=>setV({...v,visit:{...v.visit,suggestCheckin:x}})}/><Toggle label="Exigir GPS no check-in" help="Valida a chegada contra o ponto cadastrado." value={v.visit.requireGpsCheckin} onChange={x=>setV({...v,visit:{...v.visit,requireGpsCheckin:x}})}/><Toggle label="Exigir GPS no check-out" help="Permite exigir presença no local também na saída." value={v.visit.requireGpsCheckout} onChange={x=>setV({...v,visit:{...v.visit,requireGpsCheckout:x}})}/></Section>
 <Section title="Mapa e Rastreamento"><Num label="Intervalo por distância" value={v.tracking.gpsDistanceIntervalMeters} unit="m" help="Distância mínima entre leituras solicitadas ao GPS." onChange={n=>setV({...v,tracking:{...v.tracking,gpsDistanceIntervalMeters:n}})}/><Num label="Intervalo por tempo" value={v.tracking.gpsTimeIntervalSeconds} unit="s" help="Menor melhora resposta em trajetos curtos e aumenta consumo." onChange={n=>setV({...v,tracking:{...v.tracking,gpsTimeIntervalSeconds:n}})}/><Toggle label="Manter trilha GPS completa" help="Preserva os pontos no aparelho para histórico detalhado." value={v.tracking.keepFullLocalTrack} onChange={x=>setV({...v,tracking:{...v.tracking,keepFullLocalTrack:x}})}/></Section>
 <Section title="Sincronização e Offline"><Toggle label="Sincronização automática" help="Envia pendências quando houver conexão." value={v.sync.autoSync} onChange={x=>setV({...v,sync:{...v.sync,autoSync:x}})}/><Num label="Nova tentativa" value={v.sync.retrySeconds} unit="s" help="Intervalo mínimo entre novas tentativas automáticas." onChange={n=>setV({...v,sync:{...v.sync,retrySeconds:n}})}/><Toggle label="Manter dados offline" help="Mantém registros locais para recuperação e histórico." value={v.sync.keepOfflineData} onChange={x=>setV({...v,sync:{...v.sync,keepOfflineData:x}})}/></Section>
 <Section title="Agenda"><Num label="Lembrete padrão" value={v.agenda.reminderMinutes} unit="min" help="Antecedência padrão dos lembretes." onChange={n=>setV({...v,agenda:{...v.agenda,reminderMinutes:n}})}/><Toggle label="Permitir compromissos locais" help="Permite criar agenda sem internet e sincronizar depois." value={v.agenda.allowLocalAppointments} onChange={x=>setV({...v,agenda:{...v.agenda,allowLocalAppointments:x}})}/></Section>
 <Section title="KM e Veículos"><Toggle label="Exigir veículo" help="Obriga selecionar veículo antes de registrar KM." value={v.km.requireVehicle} onChange={x=>setV({...v,km:{...v.km,requireVehicle:x}})}/><Toggle label="Exigir foto" help="Pode tornar foto do painel obrigatória." value={v.km.requirePhoto} onChange={x=>setV({...v,km:{...v.km,requirePhoto:x}})}/><Toggle label="Permitir KM manual" help="Permite digitação manual além do deslocamento por GPS." value={v.km.allowManualKm} onChange={x=>setV({...v,km:{...v.km,allowManualKm:x}})}/></Section>
 <Section title="Notificações"><Toggle label="Alertas operacionais" help="Check-in, check-out e deslocamentos." value={v.notifications.operational} onChange={x=>setV({...v,notifications:{...v.notifications,operational:x}})}/><Toggle label="Alertas de agenda" help="Compromissos e lembretes." value={v.notifications.agenda} onChange={x=>setV({...v,notifications:{...v.notifications,agenda:x}})}/><Toggle label="Erros de sincronização" help="Avisa quando algum registro não chegar ao servidor." value={v.notifications.syncErrors} onChange={x=>setV({...v,notifications:{...v.notifications,syncErrors:x}})}/></Section>
 <Pressable style={[s.save,saving&&{opacity:.55}]} onPress={save} disabled={saving}><Text style={s.saveText}>{saving?'Salvando...':'Salvar configurações'}</Text></Pressable><Text style={s.foot}>Próxima evolução: sincronizar estas regras por empresa no servidor, permitindo ao administrador controlar todos os dispositivos.</Text>
 </ScrollView></SafeAreaView></Modal>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:BG},header:{height:72,backgroundColor:NAVY,flexDirection:'row',alignItems:'center',paddingHorizontal:12,gap:10},back:{width:40,height:40,alignItems:'center',justifyContent:'center'},backText:{fontSize:28,color:'#fff'},title:{fontSize:17,fontWeight:'900',color:'#fff'},headerSub:{fontSize:10,color:'#B9CDDD',marginTop:2},content:{padding:16,paddingBottom:40,gap:14},notice:{backgroundColor:'#EAF2FE',borderRadius:18,padding:16,borderWidth:1,borderColor:'#D5E5FA'},noticeTitle:{fontSize:14,fontWeight:'900',color:NAVY},noticeText:{fontSize:11,color:MUTED,lineHeight:16,marginTop:4},section:{backgroundColor:'#fff',borderRadius:20,borderWidth:1,borderColor:BORDER,overflow:'hidden'},sectionTitle:{fontSize:14,fontWeight:'900',color:NAVY,padding:15,backgroundColor:'#F8FAFC',borderBottomWidth:1,borderBottomColor:BORDER},row:{minHeight:76,paddingHorizontal:15,paddingVertical:12,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:'#EDF1F5'},label:{fontSize:12,fontWeight:'900',color:TEXT},help:{fontSize:10,color:MUTED,lineHeight:14,marginTop:3},numWrap:{flexDirection:'row',alignItems:'center',gap:5},num:{width:72,height:42,borderRadius:11,borderWidth:1,borderColor:BORDER,textAlign:'center',fontSize:13,fontWeight:'900',color:TEXT,backgroundColor:'#fff'},unit:{fontSize:10,fontWeight:'800',color:MUTED,width:28},save:{minHeight:56,borderRadius:16,backgroundColor:BLUE,alignItems:'center',justifyContent:'center'},saveText:{color:'#fff',fontSize:14,fontWeight:'900'},foot:{fontSize:10,color:MUTED,lineHeight:15,textAlign:'center',paddingHorizontal:10}});
