import React,{useEffect,useMemo,useState}from'react';
import{Alert,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import{BootstrapData,Session,restSelect}from'./api';

type Action={opportunity_id?:number|string;branch_code?:string|null;customer_code?:string|null;customer_name?:string|null;seller_name?:string|null;revenue_gap?:number|string|null;status?:string|null;combined_score?:number|string|null;mix_gap?:number|string|null;lost_mix_items?:number|string|null;target_customer_id?:string|null;seller_user_id?:string|null;can_schedule_visit?:boolean|null;recommended_action?:string|null};

const C={navy:'#0B3558',blue:'#1769E0',bg:'#F3F6FA',text:'#17324D',muted:'#78889A',border:'#DFE6EE',green:'#22B77A',orange:'#F59E0B',red:'#E5484D'};
const money=(v:unknown)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const enc=(v:string)=>encodeURIComponent(v);
const label=(v?:string|null)=>({inactive:'Inativo',strong_drop:'Queda forte',strong_decline:'Queda forte',decline:'Em queda',lost_mix:'Mix perdido',anomaly:'Revisar devolução'} as Record<string,string>)[v||'']||v||'Oportunidade';

export default function CommercialActionsScreen({session,data,onSchedule}:{session:Session;data:BootstrapData|null;onSchedule?:(customerId:string,customerName:string)=>void}){
 const[rows,setRows]=useState<Action[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 const companyId=data?.companyId||'';const branchCode=data?.branches.find(b=>b.id===data?.branchId)?.code||'';const scope=data?.directory?.scope_level||'';
 const load=async()=>{if(!companyId)return;setLoading(true);setError('');try{const branchFilter=scope==='branch'&&branchCode?`&branch_code=eq.${enc(branchCode)}`:'';const r=await restSelect<Action>(session,'v_historical_commercial_action_center',`select=*&company_id=eq.${enc(companyId)}${branchFilter}&order=combined_score.desc.nullslast&limit=50`);setRows(r);}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar inteligência comercial.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[companyId,branchCode,scope]);
 const total=useMemo(()=>rows.reduce((s,x)=>s+Number(x.revenue_gap||0),0),[rows]);
 const sched=useMemo(()=>rows.filter(x=>x.can_schedule_visit&&x.target_customer_id),[rows]);
 return <ScrollView contentContainerStyle={s.content}>
   <View style={s.hero}><Text style={s.heroTop}>INTELIGÊNCIA COMERCIAL</Text><Text style={s.heroTitle}>Central de Ações</Text><Text style={s.heroText}>Mesma camada de oportunidades usada pela Web. O mobile foca em executar a próxima ação.</Text></View>
   <View style={s.metrics}><View style={s.metric}><Text style={s.metricValue}>{rows.length}</Text><Text style={s.metricLabel}>Prioridades</Text></View><View style={s.metric}><Text style={s.metricValue}>{money(total)}</Text><Text style={s.metricLabel}>Potencial analisado</Text></View><View style={s.metric}><Text style={s.metricValue}>{sched.length}</Text><Text style={s.metricLabel}>Prontas para visita</Text></View></View>
   <View style={s.section}><Text style={s.sectionTitle}>O que fazer agora</Text><Text style={s.sub}>Ordenado pelo score combinado de cliente, faturamento e perda de mix.</Text></View>
   {loading?<Text style={s.empty}>Carregando dados reais do Movvant Enterprise...</Text>:error?<View style={s.error}><Text style={s.errorTitle}>Não foi possível carregar</Text><Text style={s.sub}>{error}</Text><Pressable style={s.retry} onPress={load}><Text style={s.retryText}>Tentar novamente</Text></Pressable></View>:rows.length?rows.map((x,i)=><View key={String(x.opportunity_id||i)} style={s.card}>
      <View style={s.rowTop}><View style={{flex:1}}><Text style={s.customer}>{x.customer_name||x.customer_code||'Cliente'}</Text><Text style={s.sub}>{[x.branch_code&&`Filial ${x.branch_code}`,x.seller_name].filter(Boolean).join(' · ')||'Vendedor a reconciliar'}</Text></View><View style={s.score}><Text style={s.scoreValue}>{Math.round(Number(x.combined_score||0))}</Text><Text style={s.scoreLabel}>score</Text></View></View>
      <View style={s.tags}><Text style={[s.tag,(x.status||'').includes('inactive')?s.tagRed:s.tagOrange]}>{label(x.status)}</Text>{Number(x.lost_mix_items||0)>0?<Text style={[s.tag,s.tagBlue]}>{Number(x.lost_mix_items||0)} itens de mix</Text>:null}</View>
      <View style={s.line}><Text style={s.sub}>Potencial</Text><Text style={s.value}>{money(x.revenue_gap)}</Text></View>{Number(x.mix_gap||0)>0?<View style={s.line}><Text style={s.sub}>Gap de mix</Text><Text style={s.value}>{money(x.mix_gap)}</Text></View>:null}
      <Text style={s.actionText}>{x.recommended_action||'Revisar oportunidade comercial.'}</Text>
      <Pressable style={[s.primary,!x.can_schedule_visit&&s.disabled]} onPress={()=>{if(x.can_schedule_visit&&x.target_customer_id){onSchedule?.(x.target_customer_id,x.customer_name||x.customer_code||'Cliente')}else Alert.alert('Vínculo pendente','Cliente ou vendedor ainda precisa ser reconciliado antes de criar uma visita.')}}><Text style={s.primaryText}>{x.can_schedule_visit?'Agendar visita':'Vínculo pendente'}</Text></Pressable>
   </View>):<Text style={s.empty}>Nenhuma oportunidade disponível neste escopo.</Text>}
 </ScrollView>;
}

const s=StyleSheet.create({content:{padding:18,paddingBottom:34,backgroundColor:C.bg,gap:12},hero:{backgroundColor:C.navy,borderRadius:18,padding:20},heroTop:{color:'#9FD9C4',fontSize:11,fontWeight:'900',letterSpacing:1.3},heroTitle:{color:'#fff',fontSize:26,fontWeight:'900',marginTop:5},heroText:{color:'#D7E3EC',marginTop:8,lineHeight:20},metrics:{flexDirection:'row',gap:8},metric:{flex:1,backgroundColor:'#fff',borderWidth:1,borderColor:C.border,borderRadius:14,padding:12},metricValue:{fontWeight:'900',fontSize:16,color:C.text},metricLabel:{fontSize:11,color:C.muted,marginTop:4},section:{marginTop:6},sectionTitle:{fontSize:19,fontWeight:'900',color:C.text},sub:{fontSize:12,color:C.muted,lineHeight:17},card:{backgroundColor:'#fff',borderWidth:1,borderColor:C.border,borderRadius:16,padding:15,gap:10},rowTop:{flexDirection:'row',gap:8},customer:{fontSize:16,fontWeight:'900',color:C.text},score:{alignItems:'center',justifyContent:'center',backgroundColor:'#EAF2FE',minWidth:56,borderRadius:12,paddingVertical:7},scoreValue:{fontSize:18,fontWeight:'900',color:C.blue},scoreLabel:{fontSize:10,color:C.muted},tags:{flexDirection:'row',flexWrap:'wrap',gap:6},tag:{fontSize:11,fontWeight:'800',paddingVertical:5,paddingHorizontal:8,borderRadius:999,overflow:'hidden'},tagRed:{backgroundColor:'#FDEBEC',color:C.red},tagOrange:{backgroundColor:'#FFF3E5',color:C.orange},tagBlue:{backgroundColor:'#EAF2FE',color:C.blue},line:{flexDirection:'row',justifyContent:'space-between'},value:{fontWeight:'900',color:C.text},actionText:{fontSize:13,color:C.text,lineHeight:18},primary:{backgroundColor:C.blue,borderRadius:12,paddingVertical:12,alignItems:'center'},disabled:{backgroundColor:'#B9C5D1'},primaryText:{color:'#fff',fontWeight:'900'},error:{backgroundColor:'#fff',borderWidth:1,borderColor:'#F1C3C6',padding:16,borderRadius:14},errorTitle:{fontWeight:'900',color:C.red,marginBottom:4},retry:{marginTop:10,alignSelf:'flex-start'},retryText:{color:C.blue,fontWeight:'900'},empty:{color:C.muted,textAlign:'center',paddingVertical:30}});
