import React,{useEffect,useState} from 'react';
import {Modal,Pressable,StyleSheet,Text,View} from 'react-native';

const NAVY='#0B3558',BLUE='#1769E0',TEXT='#17324D',MUTED='#78889A',BORDER='#DFE6EE';
const pad=(n:number)=>String(n).padStart(2,'0');
const iso=(y:number,m:number,d:number)=>`${y}-${pad(m+1)}-${pad(d)}`;

export default function DatePickerField({label,value,onChange,compact=false}:{label?:string;value:string;onChange:(v:string)=>void;compact?:boolean}){
  const selected=new Date(`${value}T12:00:00`);
  const [open,setOpen]=useState(false),[cursor,setCursor]=useState(new Date(selected.getFullYear(),selected.getMonth(),1));
  useEffect(()=>{if(open){const d=new Date(`${value}T12:00:00`);setCursor(new Date(d.getFullYear(),d.getMonth(),1))}},[open,value]);
  const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();
  return <View style={compact?s.compactWrap:s.wrap}>{label?<Text style={s.label}>{label}</Text>:null}<Pressable style={[s.field,compact&&s.fieldCompact]} onPress={()=>setOpen(true)}><Text style={s.value}>{selected.toLocaleDateString('pt-BR')}</Text><Text style={s.icon}>▣</Text></Pressable><Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><Pressable style={s.overlay} onPress={()=>setOpen(false)}><Pressable style={s.card} onPress={()=>{}}><View style={s.head}><Pressable style={s.nav} onPress={()=>setCursor(new Date(y,m-1,1))}><Text style={s.navText}>‹</Text></Pressable><Text style={s.month}>{cursor.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</Text><Pressable style={s.nav} onPress={()=>setCursor(new Date(y,m+1,1))}><Text style={s.navText}>›</Text></Pressable></View><View style={s.week}>{['D','S','T','Q','Q','S','S'].map((x,i)=><Text key={i} style={s.weekText}>{x}</Text>)}</View><View style={s.days}>{Array.from({length:first+days},(_,i)=>{if(i<first)return <View key={`e-${i}`} style={s.cell}/>;const d=i-first+1,key=iso(y,m,d),on=key===value;return <Pressable key={key} style={s.cell} onPress={()=>{onChange(key);setOpen(false)}}><View style={[s.day,on&&s.dayOn]}><Text style={[s.dayText,on&&s.dayTextOn]}>{d}</Text></View></Pressable>})}</View><Pressable style={s.today} onPress={()=>{const n=new Date();onChange(iso(n.getFullYear(),n.getMonth(),n.getDate()));setOpen(false)}}><Text style={s.todayText}>Hoje</Text></Pressable></Pressable></Pressable></Modal></View>;
}
const s=StyleSheet.create({wrap:{gap:6,flex:1},compactWrap:{flex:1},label:{fontSize:11,fontWeight:'800',color:TEXT},field:{minHeight:52,borderRadius:14,borderWidth:1,borderColor:BORDER,backgroundColor:'#fff',paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},fieldCompact:{minHeight:50},value:{fontSize:14,color:TEXT,fontWeight:'700'},icon:{fontSize:16,color:BLUE},overlay:{flex:1,backgroundColor:'rgba(11,53,88,.38)',justifyContent:'center',padding:24},card:{backgroundColor:'#fff',borderRadius:24,padding:18},head:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},nav:{width:42,height:42,alignItems:'center',justifyContent:'center'},navText:{fontSize:30,color:NAVY},month:{fontSize:16,fontWeight:'900',color:TEXT,textTransform:'capitalize'},week:{flexDirection:'row',marginTop:10},weekText:{width:'14.285%',textAlign:'center',fontSize:10,color:MUTED,fontWeight:'800'},days:{flexDirection:'row',flexWrap:'wrap',marginTop:6},cell:{width:'14.285%',height:44,alignItems:'center',justifyContent:'center'},day:{width:36,height:36,borderRadius:18,alignItems:'center',justifyContent:'center'},dayOn:{backgroundColor:BLUE},dayText:{color:TEXT,fontSize:13},dayTextOn:{color:'#fff',fontWeight:'900'},today:{minHeight:44,borderRadius:13,borderWidth:1,borderColor:BORDER,alignItems:'center',justifyContent:'center',marginTop:10},todayText:{fontWeight:'900',color:NAVY}});
