import React, { useCallback, useEffect, useMemo, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import NetInfo from '@react-native-community/netinfo';
import * as Location from 'expo-location';
import { Alert, Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import AppRC11Final from '../AppRC11Final';
import AdminSettingsScreen from './AdminSettingsScreen';
import { EnterpriseSettings, DEFAULT_ENTERPRISE_SETTINGS, readEnterpriseSettings } from './adminSettings';
import { BootstrapData, CustomerRow, Session, VisitRow, checkInVisit, checkOutVisit, loadBootstrap } from './api';
import { distanceMeters, getCurrentPoint, Point } from './location';
import { clearVisitLocal, enqueueReplacingLocal, readLocalState, saveVisitLocal, syncPending } from './offline';
import { mergeTimeline, summarizeTimeline, TimelineEvent } from './timeline';

const SESSION_KEY='movvant.rc11.session', BLUE='#1769E0', NAVY='#0B3558', GREEN='#22B77A', ORANGE='#F59E0B', RED='#E5484D', BG='#F3F6FA', TEXT='#17324D', MUTED='#78889A', BORDER='#DFE6EE';
const DATA_REFRESH_MS=45000;
type NearbyVisit={visit:VisitRow;customer:CustomerRow;distance:number};
type Notice={tone:'success'|'warning'|'error'|'info';title:string;text:string}|null;
const customerName=(c?:CustomerRow|null)=>c?.trade_name||c?.legal_name||'Loja';
const clock=(v:number)=>{const d=new Date(v);return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`};
const duration=(ms:number)=>{const m=Math.max(0,Math.round(ms/60000));if(m<60)return `${m} min`;return `${Math.floor(m/60)}h${m%60?` ${m%60}min`:''}`};
const distance=(m:number)=>m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(1)} km`;
const icon=(t:TimelineEvent['type'])=>t==='trip'?'⌖':t==='checkin'?'✓':t==='checkout'?'↗':t==='km'?'◎':'▦';
const tone=(t:TimelineEvent['type'])=>t==='checkin'?GREEN:t==='checkout'?ORANGE:t==='trip'?BLUE:t==='km'?NAVY:'#7A899A';
const isNetworkError=(e:unknown)=>/network|fetch|timeout|conex|internet|offline/i.test(e instanceof Error?e.message:String(e||''));
const canAdmin=(d:BootstrapData|null)=>{const raw=`${d?.directory?.role_slug||''} ${d?.directory?.role_name||''} ${d?.directory?.job_title||''} ${d?.directory?.scope_level||''}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return ['owner','propriet','admin','master','gerente','manager','supervisor'].some(x=>raw.includes(x))};

export default function OperationalLayerV2(){
 const [session,setSession]=useState<Session|null>(null),[data,setData]=useState<BootstrapData|null>(null),[timeline,setTimeline]=useState<TimelineEvent[]>([]),[timelineOpen,setTimelineOpen]=useState(false),[adminOpen,setAdminOpen]=useState(false),[nearby,setNearby]=useState<NearbyVisit|null>(null),[activeVisit,setActiveVisit]=useState<VisitRow|null>(null),[busy,setBusy]=useState(false),[settings,setSettings]=useState<EnterpriseSettings>(DEFAULT_ENTERPRISE_SETTINGS),[online,setOnline]=useState(true),[notice,setNotice]=useState<Notice>(null),[syncNotice,setSyncNotice]=useState<{title:string;message:string}|null>(null);
 const showNotice=useCallback((n:Exclude<Notice,null>)=>{setNotice(n);setTimeout(()=>setNotice(cur=>cur===n?null:cur),4500)},[]);
 const reload=useCallback(async()=>{const raw=await AsyncStorage.getItem(SESSION_KEY);if(!raw){setSession(null);setData(null);setTimeline([]);setNearby(null);setActiveVisit(null);return}try{const ss=JSON.parse(raw) as Session;setSession(ss);const remote=await loadBootstrap(ss);const [local,cfg]=await Promise.all([readLocalState(),readEnterpriseSettings(remote.companyId)]);setSettings(cfg);const overlays=new Map(local.visits.map(v=>[v.visitId,v]));const mergedVisits=remote.visits.map(v=>{const o=overlays.get(v.id);return o?{...v,checkin_at:o.checkinAt??v.checkin_at,checkout_at:o.checkoutAt??v.checkout_at,geofence_valid:o.geofenceValid??v.geofence_valid,status:o.status||v.status}:v});const merged={...remote,visits:mergedVisits};setData(merged);const customers=new Map(merged.customers.map(c=>[c.id,c]));setTimeline(mergeTimeline(local,mergedVisits,id=>customerName(customers.get(id))));setActiveVisit(mergedVisits.find(v=>Boolean(v.checkin_at)&&!v.checkout_at)||null)}catch{}},[]);
 useEffect(()=>{reload();const t=setInterval(reload,DATA_REFRESH_MS);return()=>clearInterval(t)},[reload]);
 useEffect(()=>NetInfo.addEventListener(s=>setOnline(Boolean(s.isConnected))),[]);
 useEffect(()=>{const original=Alert.alert;Alert.alert=((title:any,message?:any,buttons?:any,options?:any)=>{if(String(title)==='Sincronização parcial'){setSyncNotice({title:'Sincronização parcial',message:String(message||'Há registros aguardando envio.')});return}return original(title,message,buttons,options)}) as typeof Alert.alert;return()=>{Alert.alert=original}},[]);
 const candidates=useMemo(()=>{if(!data)return[];const now=Date.now(),w=settings.visit.scheduleWindowMinutes*60000;return data.visits.filter(v=>{if(v.checkin_at||v.checkout_at||!v.scheduled_start)return false;const x=new Date(v.scheduled_start).getTime();return x>=now-w&&x<=now+w})},[data,settings.visit.scheduleWindowMinutes]);
 const checkProximity=useCallback(async()=>{if(!settings.visit.suggestCheckin||!data||!candidates.length||activeVisit){setNearby(null);return}try{const p=await Location.getForegroundPermissionsAsync();if(!p.granted)return;const r=await getCurrentPoint();if(!r.ok)return;const here:Point=r.point;let best:NearbyVisit|null=null;for(const visit of candidates){const c=data.customers.find(x=>x.id===visit.customer_id),lat=Number(c?.latitude),lng=Number(c?.longitude);if(!c||!Number.isFinite(lat)||!Number.isFinite(lng))continue;const d=distanceMeters(here,{latitude:lat,longitude:lng,timestamp:Date.now()});if(d<=settings.visit.geofenceMeters&&(!best||d<best.distance))best={visit,customer:c,distance:d}}setNearby(best)}catch{}},[activeVisit,candidates,data,settings.visit.geofenceMeters,settings.visit.suggestCheckin]);
 useEffect(()=>{checkProximity();const t=setInterval(checkProximity,Math.max(5000,settings.visit.proximityCheckSeconds*1000));return()=>clearInterval(t)},[checkProximity,settings.visit.proximityCheckSeconds]);
 const queueCheckIn=async(visit:VisitRow,valid:boolean,at:string)=>{await saveVisitLocal({visitId:visit.id,checkinAt:at,checkoutAt:null,geofenceValid:valid,status:'in_progress',updatedAt:at,synced:false});await enqueueReplacingLocal('visit',visit.id,{entity:'visit',action:'checkin',payload:{localId:visit.id,visitId:visit.id,checkinAt:at,geofenceValid:valid}});setActiveVisit({...visit,checkin_at:at,checkout_at:null,geofence_valid:valid,status:'in_progress'});setNearby(null)};
 const queueCheckOut=async(visit:VisitRow,at:string)=>{const checkinAt=visit.checkin_at||at;await saveVisitLocal({visitId:visit.id,checkinAt,checkoutAt:at,geofenceValid:visit.geofence_valid??null,status:'completed',updatedAt:at,synced:false});await enqueueReplacingLocal('visit',visit.id,{entity:'visit',action:'checkout',payload:{localId:visit.id,visitId:visit.id,checkinAt,checkoutAt:at,geofenceValid:visit.geofence_valid??false}});setActiveVisit(null)};
 const doCheckIn=async()=>{if(!session||!nearby||busy)return;setBusy(true);const at=new Date().toISOString();try{const valid=nearby.distance<=settings.visit.geofenceMeters;if(settings.visit.requireGpsCheckin&&!valid)throw new Error(`Aproxime-se até ${settings.visit.geofenceMeters} m do ponto cadastrado.`);if(online){try{const u=await checkInVisit(session,nearby.visit.id,valid);await clearVisitLocal(u.id);setActiveVisit(u);setNearby(null);await reload();showNotice({tone:'success',title:'Check-in realizado',text:`${customerName(nearby.customer)} · ${Math.round(nearby.distance)} m do ponto cadastrado.`});return}catch(e){if(!isNetworkError(e))throw e}}await queueCheckIn(nearby.visit,valid,at);showNotice({tone:'warning',title:'Check-in salvo offline',text:'O registro está protegido no aparelho e será enviado automaticamente quando a conexão estiver disponível.'})}catch(e){showNotice({tone:'error',title:'Check-in não concluído',text:e instanceof Error?e.message:'Não foi possível concluir.'})}finally{setBusy(false)}};
 const doCheckOut=async()=>{if(!session||!activeVisit||busy)return;setBusy(true);const at=new Date().toISOString();try{const started=activeVisit.checkin_at?new Date(activeVisit.checkin_at).getTime():Date.now(),elapsed=Date.now()-started,min=settings.visit.minimumVisitMinutes*60000;if(min>0&&elapsed<min)throw new Error(`Permanência mínima configurada: ${settings.visit.minimumVisitMinutes} min.`);if(settings.visit.requireGpsCheckout){const c=data?.customers.find(x=>x.id===activeVisit.customer_id),lat=Number(c?.latitude),lng=Number(c?.longitude);if(!c||!Number.isFinite(lat)||!Number.isFinite(lng))throw new Error('Loja sem coordenadas para validar o check-out.');const r=await getCurrentPoint();if(!r.ok)throw new Error(r.reason);const d=distanceMeters(r.point,{latitude:lat,longitude:lng,timestamp:Date.now()});if(d>settings.visit.geofenceMeters)throw new Error(`Check-out exige presença até ${settings.visit.geofenceMeters} m da loja. Distância atual: ${Math.round(d)} m.`)}const local=(await readLocalState()).visits.find(v=>v.visitId===activeVisit.id&&!v.synced);if(online&&!local){try{const u=await checkOutVisit(session,activeVisit.id),c=data?.customers.find(x=>x.id===u.customer_id),end=u.checkout_at?new Date(u.checkout_at).getTime():Date.now();await clearVisitLocal(u.id);setActiveVisit(null);await reload();showNotice({tone:'success',title:'Check-out realizado',text:`${customerName(c)} · permanência ${duration(Math.max(0,end-started))}.`});return}catch(e){if(!isNetworkError(e))throw e}}await queueCheckOut(activeVisit,at);if(online&&data?.companyId){const r=await syncPending(session,data.companyId).catch(()=>null);if(r&&r.pending===0){await clearVisitLocal(activeVisit.id);await reload();showNotice({tone:'success',title:'Check-out sincronizado',text:`${customerName(data.customers.find(x=>x.id===activeVisit.customer_id))} · permanência ${duration(Math.max(0,Date.now()-started))}.`});return}}showNotice({tone:'warning',title:'Check-out salvo offline',text:'A visita foi finalizada no aparelho e continuará na fila até o servidor confirmar o envio.'})}catch(e){showNotice({tone:'error',title:'Check-out não concluído',text:e instanceof Error?e.message:'Não foi possível concluir.'})}finally{setBusy(false)}};
 const summary=useMemo(()=>summarizeTimeline(timeline),[timeline]),activeCustomer=activeVisit&&data?data.customers.find(c=>c.id===activeVisit.customer_id):null,admin=useMemo(()=>canAdmin(data),[data]);
 const noticeColor=notice?.tone==='success'?GREEN:notice?.tone==='warning'?ORANGE:notice?.tone==='error'?RED:BLUE;
 return <View style={s.root}><AppRC11Final/>
 {notice&&<View style={[s.notice,{borderLeftColor:noticeColor}]}><View style={[s.noticeIcon,{backgroundColor:`${noticeColor}18`}]}><Text style={[s.noticeIconText,{color:noticeColor}]}>{notice.tone==='success'?'✓':notice.tone==='warning'?'!':notice.tone==='error'?'×':'i'}</Text></View><View style={{flex:1}}><Text style={s.noticeTitle}>{notice.title}</Text><Text style={s.noticeText}>{notice.text}</Text></View><Pressable onPress={()=>setNotice(null)} style={s.noticeClose}><Text style={s.noticeCloseText}>×</Text></Pressable></View>}
 {nearby&&!activeVisit&&<View style={s.arrival}><View style={s.dot}/><View style={{flex:1}}><Text style={s.cardTitle}>Você chegou a {customerName(nearby.customer)}</Text><Text style={s.cardSub}>{Math.round(nearby.distance)} m · raio configurado {settings.visit.geofenceMeters} m</Text></View><Pressable style={s.green} onPress={doCheckIn}><Text style={s.white}>Check-in</Text></Pressable><Pressable style={s.dismiss} onPress={()=>setNearby(null)}><Text>×</Text></Pressable></View>}
 {activeVisit&&<View style={s.active}><View style={{flex:1}}><Text style={s.activeTop}>VISITA EM ANDAMENTO{online?'':' · OFFLINE'}</Text><Text style={s.activeTitle}>{customerName(activeCustomer)}</Text><Text style={s.activeSub}>Check-in {activeVisit.checkin_at?clock(new Date(activeVisit.checkin_at).getTime()):''}{activeVisit.geofence_valid?' · GPS validado':''}</Text></View><Pressable style={s.checkout} onPress={doCheckOut}><Text style={s.checkoutText}>Check-out</Text></Pressable></View>}
 <View style={s.fabs}><Pressable style={s.fab} onPress={()=>setTimelineOpen(true)}><Text style={s.fabText}>≡ Linha do Tempo</Text></Pressable>{admin&&<Pressable style={s.adminFab} onPress={()=>setAdminOpen(true)}><Text style={s.adminFabText}>⚙ Admin</Text></Pressable>}</View>
 <AdminSettingsScreen visible={adminOpen} onClose={()=>setAdminOpen(false)} companyId={data?.companyId} companyName={data?.directory?.branch_name||'Empresa atual'} onSaved={x=>{setSettings(x);setAdminOpen(false);showNotice({tone:'success',title:'Regras atualizadas',text:'As configurações desta empresa já estão valendo neste aparelho.'})}}/>
 <Modal visible={Boolean(syncNotice)} transparent animationType="fade" onRequestClose={()=>setSyncNotice(null)}><View style={s.overlay}><View style={s.popup}><View style={s.popupIcon}><Text style={s.popupIconText}>↻</Text></View><Text style={s.eyebrow}>MOVVANT ENTERPRISE</Text><Text style={s.popupTitle}>{syncNotice?.title}</Text><Text style={s.popupMessage}>{syncNotice?.message}</Text><View style={s.hint}><View style={s.hintDot}/><Text style={s.hintText}>O registro permanece protegido no aparelho e será reenviado automaticamente.</Text></View><Pressable style={s.popupButton} onPress={()=>setSyncNotice(null)}><Text style={s.popupButtonText}>Entendi</Text></Pressable></View></View></Modal>
 <Modal visible={timelineOpen} animationType="slide" onRequestClose={()=>setTimelineOpen(false)}><SafeAreaView style={s.modal}><View style={s.header}><Pressable onPress={()=>setTimelineOpen(false)} style={s.back}><Text style={s.backText}>‹</Text></Pressable><View><Text style={s.headerTitle}>Linha do Tempo</Text><Text style={s.headerSub}>Deslocamentos, visitas e KM</Text></View><Pressable style={s.refresh} onPress={reload}><Text style={s.refreshText}>↻</Text></Pressable></View><ScrollView contentContainerStyle={s.content}><View style={s.summary}><View style={s.metric}><Text style={s.metricV}>{distance(summary.distanceMeters)}</Text><Text style={s.metricL}>Deslocamento</Text></View><View style={s.metric}><Text style={s.metricV}>{duration(summary.tripDurationMs)}</Text><Text style={s.metricL}>Tempo em rota</Text></View></View><View style={s.summary}><View style={s.metric}><Text style={s.metricV}>{summary.visits}</Text><Text style={s.metricL}>Check-ins</Text></View><View style={s.metric}><Text style={s.metricV}>{duration(summary.visitDurationMs)}</Text><Text style={s.metricL}>Tempo em clientes</Text></View></View><Text style={s.section}>Histórico operacional</Text>{!timeline.length&&<View style={s.empty}><Text style={s.cardTitle}>Sem eventos ainda</Text><Text style={s.cardSub}>Deslocamentos, KM e visitas aparecerão aqui.</Text></View>}{timeline.slice(0,120).map(e=><View style={s.event} key={e.id}><View style={[s.eventIcon,{borderColor:tone(e.type)}]}><Text style={{color:tone(e.type),fontWeight:'900'}}>{icon(e.type)}</Text></View><View style={{flex:1}}><View style={s.eventHead}><Text style={s.eventTitle}>{e.title}</Text><Text style={s.eventTime}>{clock(e.startedAt)}</Text></View>{!!e.subtitle&&<Text style={s.cardSub}>{e.subtitle}</Text>}{e.synced===false&&<Text style={s.pending}>Aguardando sincronização</Text>}</View></View>)}</ScrollView></SafeAreaView></Modal>
 </View>
}

const s=StyleSheet.create({
 root:{flex:1,backgroundColor:BG},notice:{position:'absolute',zIndex:60,top:76,left:14,right:14,minHeight:82,backgroundColor:'#fff',borderRadius:18,borderWidth:1,borderColor:BORDER,borderLeftWidth:5,padding:13,flexDirection:'row',alignItems:'center',gap:11,elevation:18},noticeIcon:{width:38,height:38,borderRadius:19,alignItems:'center',justifyContent:'center'},noticeIconText:{fontSize:18,fontWeight:'900'},noticeTitle:{fontSize:13,fontWeight:'900',color:TEXT},noticeText:{fontSize:10,color:MUTED,lineHeight:14,marginTop:3},noticeClose:{width:28,height:28,alignItems:'center',justifyContent:'center'},noticeCloseText:{fontSize:20,color:MUTED},
 arrival:{position:'absolute',left:12,right:12,bottom:88,minHeight:84,backgroundColor:'#fff',borderRadius:18,borderWidth:1,borderColor:'#CFE7DB',padding:12,flexDirection:'row',alignItems:'center',gap:10,elevation:16},dot:{width:10,height:10,borderRadius:5,backgroundColor:GREEN},cardTitle:{fontSize:13,fontWeight:'900',color:TEXT},cardSub:{fontSize:10,color:MUTED,marginTop:3,lineHeight:14},green:{minHeight:42,paddingHorizontal:13,borderRadius:12,backgroundColor:GREEN,alignItems:'center',justifyContent:'center'},white:{color:'#fff',fontSize:11,fontWeight:'900'},dismiss:{position:'absolute',top:-8,right:-6,width:25,height:25,borderRadius:13,backgroundColor:'#fff',borderWidth:1,borderColor:BORDER,alignItems:'center',justifyContent:'center'},
 active:{position:'absolute',left:12,right:12,bottom:88,minHeight:82,backgroundColor:NAVY,borderRadius:18,padding:13,flexDirection:'row',alignItems:'center',gap:10,elevation:16},activeTop:{fontSize:8,letterSpacing:1.3,fontWeight:'900',color:'#9CC6E7'},activeTitle:{fontSize:14,fontWeight:'900',color:'#fff',marginTop:3},activeSub:{fontSize:10,color:'#D5E3EE',marginTop:3},checkout:{minHeight:44,paddingHorizontal:14,borderRadius:12,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},checkoutText:{color:NAVY,fontSize:11,fontWeight:'900'},
 fabs:{position:'absolute',right:14,bottom:178,gap:8,alignItems:'flex-end'},fab:{minHeight:42,borderRadius:21,backgroundColor:'#FFFFFFF2',borderWidth:1,borderColor:'#D6E0E9',paddingHorizontal:12,alignItems:'center',justifyContent:'center',elevation:10},fabText:{fontSize:10,fontWeight:'900',color:NAVY},adminFab:{minHeight:38,borderRadius:19,backgroundColor:NAVY,paddingHorizontal:12,alignItems:'center',justifyContent:'center',elevation:10},adminFabText:{fontSize:10,fontWeight:'900',color:'#fff'},
 overlay:{flex:1,backgroundColor:'#09243A99',alignItems:'center',justifyContent:'center',padding:24},popup:{width:'100%',maxWidth:420,backgroundColor:'#fff',borderRadius:26,padding:22,borderWidth:1,borderColor:'#D7E2EB',elevation:24},popupIcon:{width:46,height:46,borderRadius:15,backgroundColor:'#FFF3E5',alignItems:'center',justifyContent:'center',marginBottom:14},popupIconText:{fontSize:23,color:ORANGE,fontWeight:'900'},eyebrow:{fontSize:9,letterSpacing:1.8,color:BLUE,fontWeight:'900'},popupTitle:{fontSize:22,fontWeight:'900',color:NAVY,marginTop:5},popupMessage:{fontSize:14,color:TEXT,lineHeight:21,marginTop:9},hint:{marginTop:16,borderRadius:15,backgroundColor:'#F4F7FA',padding:12,flexDirection:'row',alignItems:'flex-start',gap:9},hintDot:{width:8,height:8,borderRadius:4,backgroundColor:ORANGE,marginTop:4},hintText:{flex:1,fontSize:11,lineHeight:16,color:MUTED},popupButton:{minHeight:50,backgroundColor:NAVY,borderRadius:14,alignItems:'center',justifyContent:'center',marginTop:18},popupButtonText:{fontSize:13,fontWeight:'900',color:'#fff'},
 modal:{flex:1,backgroundColor:BG},header:{height:70,backgroundColor:NAVY,flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:12},back:{width:40,height:40,alignItems:'center',justifyContent:'center'},backText:{color:'#fff',fontSize:28},headerTitle:{color:'#fff',fontSize:18,fontWeight:'900'},headerSub:{color:'#B9CDDD',fontSize:10},refresh:{marginLeft:'auto',width:40,height:40,alignItems:'center',justifyContent:'center'},refreshText:{color:'#fff',fontSize:22},content:{padding:16,paddingBottom:34,gap:10},summary:{flexDirection:'row',gap:10},metric:{flex:1,minHeight:96,backgroundColor:'#fff',borderWidth:1,borderColor:BORDER,borderRadius:18,padding:14,justifyContent:'center'},metricV:{fontSize:20,fontWeight:'900',color:NAVY},metricL:{fontSize:10,color:MUTED,marginTop:3},section:{fontSize:16,fontWeight:'900',color:TEXT,marginTop:6},empty:{backgroundColor:'#fff',borderWidth:1,borderColor:BORDER,borderRadius:18,padding:18},event:{minHeight:74,backgroundColor:'#fff',borderRadius:17,borderWidth:1,borderColor:BORDER,padding:12,flexDirection:'row',alignItems:'center',gap:11},eventIcon:{width:38,height:38,borderRadius:19,borderWidth:2,alignItems:'center',justifyContent:'center'},eventHead:{flexDirection:'row',justifyContent:'space-between',gap:8},eventTitle:{flex:1,fontSize:12,fontWeight:'900',color:TEXT},eventTime:{fontSize:11,fontWeight:'800',color:MUTED},pending:{fontSize:9,color:ORANGE,fontWeight:'900',marginTop:3}
});
