import React, { useEffect, useMemo, useState } from 'react';
import { Pressable, ScrollView, Share, StyleSheet, Text, View } from 'react-native';
import DatePickerField from '../src/DatePickerField';
import { BootstrapData, DirectoryRow, Session, restSelect } from './api';
import { LocalState } from './offline';
import { readExpenses, summarizeExpenses } from './expenses';

const NAVY='#0B3558', BLUE='#1769E0', BG='#F3F6FA', TEXT='#17324D', MUTED='#78889A', BORDER='#DFE6EE', GREEN='#22B77A', ORANGE='#F59E0B';
const money=(v:unknown)=>(Number(v||0)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const pad=(n:number)=>String(n).padStart(2,'0');
const iso=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const normalize=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const canViewTeam=(d:BootstrapData|null)=>['owner','propriet','admin','master','gerente','manager','supervisor'].some(x=>normalize(`${d?.directory?.role_slug||''} ${d?.directory?.role_name||''} ${d?.directory?.job_title||''} ${d?.directory?.scope_level||''}`).includes(x));
const roleKind=(u:DirectoryRow)=>{const t=normalize(`${u.role_slug||''} ${u.role_name||''} ${u.job_title||''}`);if(/motor|driver|entrega|logistic/.test(t))return'driver';if(/vend|seller|comercial|represent/.test(t))return'seller';return'other'};

type RouteRow={route_id:string;assigned_user_id?:string|null;route_date:string;route_type?:string|null;status?:string|null;planned_km?:number|string|null;actual_km?:number|string|null;planned_minutes?:number|string|null;actual_minutes?:number|string|null;adherence_pct?:number|string|null;total_stops?:number|null;completed_stops?:number|null;exception_stops?:number|null};
type ExpenseRow={id:string;user_id?:string|null;expense_type?:string|null;amount?:number|string|null;occurred_at:string;notes?:string|null;vendor_name?:string|null;vehicle_id?:string|null};

type Props={session:Session;data:BootstrapData|null;local:LocalState};

export default function ReportsHierarchicalScreen({session,data,local}:Props){
 const manager=canViewTeam(data);
 const [period,setPeriod]=useState<'day'|'week'|'month'|'custom'>('month');
 const [from,setFrom]=useState(iso(new Date())),[to,setTo]=useState(iso(new Date()));
 const [users,setUsers]=useState<DirectoryRow[]>([]),[scope,setScope]=useState<'self'|'all'|'seller'|'driver'|'user'>('self'),[selectedUser,setSelectedUser]=useState(session.user.id);
 const [remoteRoutes,setRemoteRoutes]=useState<RouteRow[]>([]),[remoteExpenses,setRemoteExpenses]=useState<ExpenseRow[]>([]),[localExpenses,setLocalExpenses]=useState<any[]>([]),[loading,setLoading]=useState(false),[warning,setWarning]=useState('');
 const start=useMemo(()=>{const d=new Date();d.setHours(0,0,0,0);if(period==='day')return d;if(period==='week'){d.setDate(d.getDate()-6);return d}if(period==='month'){d.setDate(1);return d}return new Date(`${from}T00:00:00`)},[period,from]);
 const end=useMemo(()=>period==='custom'?new Date(`${to}T23:59:59`):new Date(),[period,to]);
 const startDate=iso(start),endDate=iso(end);
 useEffect(()=>{readExpenses(data?.companyId||'local').then(setLocalExpenses).catch(()=>setLocalExpenses([]))},[data?.companyId]);
 useEffect(()=>{if(!data?.companyId){setUsers(data?.directory?[data.directory]:[]);return}if(!manager){setUsers(data.directory?[data.directory]:[]);setScope('self');setSelectedUser(session.user.id);return}(async()=>{try{const rows=await restSelect<DirectoryRow>(session,'v_user_directory',`select=*&company_id=eq.${encodeURIComponent(data.companyId!)}&assignment_active=eq.true&order=full_name.asc&limit=500`);setUsers(rows)}catch{setUsers(data.directory?[data.directory]:[])}})()},[manager,data?.companyId,session.user.id]);
 const allowedUsers=useMemo(()=>{if(!manager)return[session.user.id];if(scope==='all')return users.map(u=>u.user_id);if(scope==='seller')return users.filter(u=>roleKind(u)==='seller').map(u=>u.user_id);if(scope==='driver')return users.filter(u=>roleKind(u)==='driver').map(u=>u.user_id);if(scope==='user')return[selectedUser];return[session.user.id]},[manager,scope,users,selectedUser,session.user.id]);
 useEffect(()=>{if(!data?.companyId)return;let active=true;(async()=>{setLoading(true);setWarning('');try{const userFilter=allowedUsers.length===1?`&assigned_user_id=eq.${encodeURIComponent(allowedUsers[0])}`:allowedUsers.length>1?`&assigned_user_id=in.(${allowedUsers.map(encodeURIComponent).join(',')})`:'';const expenseUserFilter=allowedUsers.length===1?`&user_id=eq.${encodeURIComponent(allowedUsers[0])}`:allowedUsers.length>1?`&user_id=in.(${allowedUsers.map(encodeURIComponent).join(',')})`:'';const [routes,expenses]=await Promise.all([restSelect<RouteRow>(session,'v_route_performance',`select=*&company_id=eq.${encodeURIComponent(data.companyId!)}&route_date=gte.${startDate}&route_date=lte.${endDate}${userFilter}&order=route_date.desc&limit=1000`),restSelect<ExpenseRow>(session,'vehicle_expenses',`select=id,user_id,expense_type,amount,occurred_at,notes,vendor_name,vehicle_id&company_id=eq.${encodeURIComponent(data.companyId!)}&occurred_at=gte.${encodeURIComponent(start.toISOString())}&occurred_at=lte.${encodeURIComponent(end.toISOString())}${expenseUserFilter}&order=occurred_at.desc&limit=1000`)]);if(active){setRemoteRoutes(routes);setRemoteExpenses(expenses)}}catch(e){if(active){setRemoteRoutes([]);setRemoteExpenses([]);setWarning('Parte dos dados empresariais ainda não pôde ser carregada para este perfil.')}}finally{if(active)setLoading(false)}})();return()=>{active=false}},[data?.companyId,startDate,endDate,allowedUsers.join('|')]);
 const ownScope=allowedUsers.length===1&&allowedUsers[0]===session.user.id;
 const localKm=ownScope?local.km.filter(x=>{const t=new Date(x.createdAt);return t>=start&&t<=end}):[];
 const localTrips=ownScope?local.trips.filter(x=>{const t=new Date(x.finishedAt);return t>=start&&t<=end}):[];
 const appExpenses=ownScope?localExpenses.filter(x=>{const t=new Date(`${x.date}T12:00:00`);return t>=start&&t<=end}):[];
 const appExpenseSummary=summarizeExpenses(appExpenses);
 const routeKm=remoteRoutes.reduce((n,x)=>n+Number(x.actual_km||0),0),manualKm=localKm.reduce((n,x)=>n+x.total,0),gpsKm=localTrips.reduce((n,x)=>n+x.distanceMeters/1000,0),kmTotal=Math.max(routeKm,gpsKm,manualKm);
 const remoteExpenseTotal=remoteExpenses.reduce((n,x)=>n+Number(x.amount||0),0),expenseTotal=Math.max(remoteExpenseTotal,appExpenseSummary.actual||0);
 const fuelTotal=remoteExpenses.filter(x=>/fuel|combust|gasolina|diesel|etanol/i.test(x.expense_type||'')).reduce((n,x)=>n+Number(x.amount||0),0);
 const timeMinutes=remoteRoutes.reduce((n,x)=>n+Number(x.actual_minutes||0),0)||Math.round(localTrips.reduce((n,x)=>n+x.elapsedMs/60000,0));
 const selectedLabel=scope==='all'?'Todos os usuários':scope==='seller'?'Todos os vendedores':scope==='driver'?'Todos os motoristas':scope==='user'?(users.find(u=>u.user_id===selectedUser)?.full_name||'Usuário selecionado'):(data?.directory?.full_name||'Meu relatório');
 const detailRows=remoteRoutes.map(r=>({date:r.route_date,title:r.route_type||'Deslocamento',km:Number(r.actual_km||0),expense:0}));
 remoteExpenses.forEach(e=>{const d=e.occurred_at.slice(0,10),found=detailRows.find(x=>x.date===d);if(found)found.expense+=Number(e.amount||0);else detailRows.push({date:d,title:e.notes||e.expense_type||'Despesa de viagem',km:0,expense:Number(e.amount||0)})});
 detailRows.sort((a,b)=>b.date.localeCompare(a.date));
 const share=async()=>Share.share({title:'Relatório Movvant',message:[`Movvant Enterprise — ${selectedLabel}`,`Período: ${start.toLocaleDateString('pt-BR')} a ${end.toLocaleDateString('pt-BR')}`,`Deslocamentos: ${remoteRoutes.length||localTrips.length}`,`KM total: ${kmTotal.toFixed(1)} km`,`Gastos: ${money(expenseTotal)}`,`Combustível: ${money(fuelTotal)}`,`Tempo em rota: ${timeMinutes} min`].join('\n')});
 return <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled" automaticallyAdjustKeyboardInsets>
  <View style={s.hero}><Text style={s.eyebrow}>RELATÓRIO OPERACIONAL</Text><Text style={s.heroTitle}>KM, gastos e deslocamentos</Text><Text style={s.heroText}>{manager?'Selecione quem deseja analisar e acompanhe o período completo.':'Seu acesso exibe somente os seus próprios dados.'}</Text></View>
  {manager&&<><Text style={s.section}>Visualização</Text><View style={s.chips}>{[['all','Todos'],['seller','Vendedores'],['driver','Motoristas'],['self','Meu']].map(([k,l])=><Pressable key={k} style={[s.chip,scope===k&&s.chipOn]} onPress={()=>setScope(k as any)}><Text style={[s.chipText,scope===k&&s.chipTextOn]}>{l}</Text></Pressable>)}<Pressable style={[s.chip,scope==='user'&&s.chipOn]} onPress={()=>setScope('user')}><Text style={[s.chipText,scope==='user'&&s.chipTextOn]}>Selecionar</Text></Pressable></View>{scope==='user'&&<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.userRow}>{users.map(u=><Pressable key={u.user_id} style={[s.userChip,selectedUser===u.user_id&&s.userChipOn]} onPress={()=>setSelectedUser(u.user_id)}><Text style={[s.userName,selectedUser===u.user_id&&s.userNameOn]}>{u.full_name||u.email||'Usuário'}</Text><Text style={[s.userRole,selectedUser===u.user_id&&s.userNameOn]}>{u.job_title||u.role_name||'Usuário'}</Text></Pressable>)}</ScrollView>}</>}
  <Text style={s.section}>Período</Text><View style={s.chips}>{[['day','Dia'],['week','Semana'],['month','Mês'],['custom','Período']].map(([k,l])=><Pressable key={k} style={[s.chip,period===k&&s.chipOn]} onPress={()=>setPeriod(k as any)}><Text style={[s.chipText,period===k&&s.chipTextOn]}>{l}</Text></Pressable>)}</View>{period==='custom'&&<View style={s.dates}><DatePickerField label="De" value={from} onChange={setFrom}/><DatePickerField label="Até" value={to} onChange={setTo}/></View>}
  <View style={s.periodCard}><Text style={s.periodTop}>{selectedLabel.toUpperCase()}</Text><Text style={s.periodValue}>{start.toLocaleDateString('pt-BR')} — {end.toLocaleDateString('pt-BR')}</Text></View>
  <View style={s.grid}><View style={s.card}><Text style={s.label}>DESLOCAMENTOS</Text><Text style={s.value}>{remoteRoutes.length||localTrips.length}</Text></View><View style={s.card}><Text style={s.label}>KM TOTAL</Text><Text style={s.value}>{kmTotal.toLocaleString('pt-BR',{maximumFractionDigits:1})} km</Text></View><View style={s.card}><Text style={s.label}>DESPESAS DE VIAGEM</Text><Text style={s.value}>{money(expenseTotal)}</Text></View><View style={s.card}><Text style={s.label}>COMBUSTÍVEL</Text><Text style={s.value}>{money(fuelTotal)}</Text></View><View style={s.card}><Text style={s.label}>TEMPO EM ROTA</Text><Text style={s.value}>{timeMinutes} min</Text></View><View style={s.card}><Text style={s.label}>MÉDIA POR DESLOCAMENTO</Text><Text style={s.value}>{money((remoteRoutes.length||localTrips.length)?expenseTotal/(remoteRoutes.length||localTrips.length):0)}</Text></View></View>
  {warning?<View style={s.warning}><Text style={s.warningText}>{warning}</Text></View>:null}
  <View style={s.table}><View style={s.tableHead}><Text style={[s.th,{flex:.8}]}>DATA</Text><Text style={[s.th,{flex:2}]}>DESTINO / TRABALHO</Text><Text style={[s.th,{flex:.8}]}>KM</Text><Text style={[s.th,{flex:1}]}>DESPESAS</Text></View>{detailRows.length?detailRows.map((r,i)=><View key={`${r.date}-${i}`} style={s.tr}><Text style={[s.td,{flex:.8}]}>{new Date(`${r.date}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}</Text><Text style={[s.td,{flex:2}]}>{r.title}</Text><Text style={[s.td,{flex:.8}]}>{r.km?r.km.toLocaleString('pt-BR',{maximumFractionDigits:1})+' km':'—'}</Text><Text style={[s.td,{flex:1}]}>{money(r.expense)}</Text></View>):<Text style={s.empty}>{loading?'Carregando dados...':'Nenhum registro neste período.'}</Text>}</View>
  <Pressable style={s.primary} onPress={share}><Text style={s.primaryText}>Compartilhar relatório</Text></Pressable>
 </ScrollView>
}

const s=StyleSheet.create({content:{padding:16,paddingBottom:40,gap:12,backgroundColor:BG},hero:{backgroundColor:'#fff',borderRadius:20,padding:18,borderWidth:1,borderColor:BORDER},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.6,color:BLUE},heroTitle:{fontSize:24,fontWeight:'900',color:TEXT,marginTop:4},heroText:{fontSize:12,color:MUTED,marginTop:6,lineHeight:18},section:{fontSize:14,fontWeight:'900',color:TEXT,marginTop:4},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:13,paddingVertical:9,borderRadius:18,backgroundColor:'#E8EEF5'},chipOn:{backgroundColor:NAVY},chipText:{fontSize:12,fontWeight:'800',color:MUTED},chipTextOn:{color:'#fff'},userRow:{gap:8},userChip:{minWidth:150,padding:11,borderRadius:14,backgroundColor:'#fff',borderWidth:1,borderColor:BORDER},userChipOn:{backgroundColor:NAVY,borderColor:NAVY},userName:{fontSize:12,fontWeight:'900',color:TEXT},userRole:{fontSize:10,color:MUTED,marginTop:3},userNameOn:{color:'#fff'},dates:{flexDirection:'row',gap:8},periodCard:{backgroundColor:'#fff',padding:16,borderRadius:16,borderWidth:1,borderColor:BORDER},periodTop:{fontSize:10,fontWeight:'900',color:MUTED},periodValue:{fontSize:16,fontWeight:'900',color:TEXT,marginTop:5},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},card:{width:'48.5%',backgroundColor:'#fff',padding:15,borderRadius:16,borderWidth:1,borderColor:BORDER,minHeight:92},label:{fontSize:10,fontWeight:'800',color:MUTED},value:{fontSize:18,fontWeight:'900',color:TEXT,marginTop:9},warning:{backgroundColor:'#FFF8E8',padding:12,borderRadius:12,borderWidth:1,borderColor:'#F3D69A'},warningText:{fontSize:11,color:'#7B6428'},table:{backgroundColor:'#fff',borderRadius:16,borderWidth:1,borderColor:BORDER,overflow:'hidden'},tableHead:{flexDirection:'row',padding:11,backgroundColor:'#F4F7FB'},th:{fontSize:9,fontWeight:'900',color:MUTED},tr:{flexDirection:'row',padding:11,borderTopWidth:1,borderTopColor:'#EDF1F5',alignItems:'center'},td:{fontSize:10.5,color:TEXT,paddingRight:4},empty:{padding:20,textAlign:'center',color:MUTED},primary:{minHeight:54,borderRadius:15,backgroundColor:NAVY,alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontSize:14,fontWeight:'900'}});