import React,{useEffect,useMemo,useState}from'react';
import{Pressable,ScrollView,Share,StyleSheet,Text,View}from'react-native';
import DatePickerField from'./DatePickerField';
import VehicleFuelSettingsCard from'./VehicleFuelSettingsCard';
import{BootstrapData,DirectoryRow,Session,restSelect}from'./api';
import{LocalState}from'./offline';
import{readExpenses,summarizeExpenses}from'./expenses';

const NAVY='#0B3558',BLUE='#1769E0',BG='#F3F6FA',TEXT='#17324D',MUTED='#78889A',BORDER='#DFE6EE';
const money=(v:unknown)=>(Number(v||0)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const pad=(n:number)=>String(n).padStart(2,'0');const iso=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;const norm=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const canViewTeam=(d:BootstrapData|null)=>['owner','propriet','admin','master','gerente','manager','supervisor'].some(x=>norm(`${d?.directory?.role_slug||''} ${d?.directory?.role_name||''} ${d?.directory?.job_title||''} ${d?.directory?.scope_level||''}`).includes(x));
const roleKind=(u:DirectoryRow)=>{const t=norm(`${u.role_slug||''} ${u.role_name||''} ${u.job_title||''}`);if(/motor|driver|entrega|logistic/.test(t))return'driver';if(/vend|seller|comercial|represent/.test(t))return'seller';return'other'};
type RouteRow={route_id:string;assigned_user_id?:string|null;route_date:string;route_type?:string|null;actual_km?:number|string|null;actual_minutes?:number|string|null};
type ExpenseRow={id:string;user_id?:string|null;expense_type?:string|null;amount?:number|string|null;occurred_at:string;notes?:string|null;vehicle_id?:string|null;fuel_liters?:number|string|null;fuel_unit_price?:number|string|null};
type VehicleRef={id:string;plate:string;fuel_type?:string|null;avg_km_per_liter?:number|string|null;reference_fuel_price?:number|string|null;tank_capacity_liters?:number|string|null};
type Props={session:Session;data:BootstrapData|null;local:LocalState};

export default function ReportsHierarchicalScreen({session,data,local}:Props){
 const manager=canViewTeam(data);const[period,setPeriod]=useState<'day'|'week'|'month'|'custom'>('month');const[from,setFrom]=useState(iso(new Date())),[to,setTo]=useState(iso(new Date()));const[users,setUsers]=useState<DirectoryRow[]>([]),[scope,setScope]=useState<'self'|'all'|'seller'|'driver'|'user'>('self'),[selectedUser,setSelectedUser]=useState(session.user.id);const[routes,setRoutes]=useState<RouteRow[]>([]),[expenses,setExpenses]=useState<ExpenseRow[]>([]),[vehicles,setVehicles]=useState<VehicleRef[]>([]),[localExpenses,setLocalExpenses]=useState<any[]>([]),[loading,setLoading]=useState(false),[warning,setWarning]=useState(''),[fuelRefresh,setFuelRefresh]=useState(0);
 const start=useMemo(()=>{const d=new Date();d.setHours(0,0,0,0);if(period==='week')d.setDate(d.getDate()-6);if(period==='month')d.setDate(1);return period==='custom'?new Date(`${from}T00:00:00`):d},[period,from]);const end=useMemo(()=>period==='custom'?new Date(`${to}T23:59:59`):new Date(),[period,to]);const startDate=iso(start),endDate=iso(end);
 useEffect(()=>{readExpenses(data?.companyId||'local').then(setLocalExpenses).catch(()=>setLocalExpenses([]))},[data?.companyId]);
 useEffect(()=>{if(!data?.companyId){setUsers(data?.directory?[data.directory]:[]);return}if(!manager){setUsers(data.directory?[data.directory]:[]);setScope('self');setSelectedUser(session.user.id);return}(async()=>{try{setUsers(await restSelect<DirectoryRow>(session,'v_user_directory',`select=*&company_id=eq.${encodeURIComponent(data.companyId!)}&assignment_active=eq.true&order=full_name.asc&limit=500`))}catch{setUsers(data.directory?[data.directory]:[])}})()},[manager,data?.companyId,session.user.id]);
 const allowed=useMemo(()=>{if(!manager)return[session.user.id];if(scope==='all')return users.map(u=>u.user_id);if(scope==='seller')return users.filter(u=>roleKind(u)==='seller').map(u=>u.user_id);if(scope==='driver')return users.filter(u=>roleKind(u)==='driver').map(u=>u.user_id);if(scope==='user')return[selectedUser];return[session.user.id]},[manager,scope,users,selectedUser,session.user.id]);
 useEffect(()=>{if(!data?.companyId)return;let active=true;(async()=>{setLoading(true);setWarning('');try{const uf=allowed.length===1?`&assigned_user_id=eq.${encodeURIComponent(allowed[0])}`:allowed.length>1?`&assigned_user_id=in.(${allowed.map(encodeURIComponent).join(',')})`:'';const ef=allowed.length===1?`&user_id=eq.${encodeURIComponent(allowed[0])}`:allowed.length>1?`&user_id=in.(${allowed.map(encodeURIComponent).join(',')})`:'';const[r,e,v]=await Promise.all([restSelect<RouteRow>(session,'v_route_performance',`select=route_id,assigned_user_id,route_date,route_type,actual_km,actual_minutes&company_id=eq.${encodeURIComponent(data.companyId!)}&route_date=gte.${startDate}&route_date=lte.${endDate}${uf}&order=route_date.desc&limit=1000`),restSelect<ExpenseRow>(session,'vehicle_expenses',`select=id,user_id,expense_type,amount,occurred_at,notes,vehicle_id,fuel_liters,fuel_unit_price&company_id=eq.${encodeURIComponent(data.companyId!)}&occurred_at=gte.${encodeURIComponent(start.toISOString())}&occurred_at=lte.${encodeURIComponent(end.toISOString())}${ef}&order=occurred_at.desc&limit=1000`),restSelect<VehicleRef>(session,'vehicles',`select=id,plate,fuel_type,avg_km_per_liter,reference_fuel_price,tank_capacity_liters&company_id=eq.${encodeURIComponent(data.companyId!)}&active=eq.true&order=plate.asc`)]);if(active){setRoutes(r);setExpenses(e);setVehicles(v)}}catch{if(active){setRoutes([]);setExpenses([]);setWarning('Parte dos dados empresariais ainda não pôde ser carregada.')}}finally{if(active)setLoading(false)}})();return()=>{active=false}},[data?.companyId,startDate,endDate,allowed.join('|'),fuelRefresh]);
 const own=allowed.length===1&&allowed[0]===session.user.id;const localKm=own?local.km.filter(x=>{const t=new Date(x.createdAt);return t>=start&&t<=end}):[];const localTrips=own?local.trips.filter(x=>{const t=new Date(x.finishedAt);return t>=start&&t<=end}):[];const appExp=own?localExpenses.filter(x=>{const t=new Date(`${x.date}T12:00:00`);return t>=start&&t<=end}):[];const appSum=summarizeExpenses(appExp);
 const routeKm=routes.reduce((n,x)=>n+Number(x.actual_km||0),0),manualKm=localKm.reduce((n,x)=>n+x.total,0),gpsKm=localTrips.reduce((n,x)=>n+x.distanceMeters/1000,0),kmTotal=Math.max(routeKm,gpsKm,manualKm);const expRemote=expenses.reduce((n,x)=>n+Number(x.amount||0),0),expenseTotal=Math.max(expRemote,appSum.actual||0);
 const realFuelRows=expenses.filter(x=>/fuel|combust|gasolina|diesel|etanol/i.test(x.expense_type||'')||Number(x.fuel_liters||0)>0);const realFuelCost=realFuelRows.reduce((n,x)=>n+Number(x.amount||0),0);const realLiters=realFuelRows.reduce((n,x)=>n+Number(x.fuel_liters||0),0);
 const vehicleIds=[...new Set(expenses.map(x=>x.vehicle_id).filter(Boolean))] as string[];const refs=vehicleIds.length?vehicles.filter(v=>vehicleIds.includes(v.id)):vehicles;const validRefs=refs.filter(v=>Number(v.avg_km_per_liter||0)>0&&Number(v.reference_fuel_price||0)>0);const refAvg=validRefs.length?validRefs.reduce((n,v)=>n+Number(v.avg_km_per_liter||0),0)/validRefs.length:0;const refPrice=validRefs.length?validRefs.reduce((n,v)=>n+Number(v.reference_fuel_price||0),0)/validRefs.length:0;const estimatedLiters=refAvg>0?kmTotal/refAvg:0;const estimatedFuelCost=estimatedLiters*refPrice;const actualConsumption=realLiters>0?kmTotal/realLiters:0;const fuelMode=realFuelCost>0||realLiters>0?'real':'estimated';const fuelCost=fuelMode==='real'?realFuelCost:estimatedFuelCost;
 const count=routes.length||localTrips.length;const selectedLabel=scope==='all'?'Todos os usuários':scope==='seller'?'Todos os vendedores':scope==='driver'?'Todos os motoristas':scope==='user'?(users.find(u=>u.user_id===selectedUser)?.full_name||'Usuário selecionado'):(data?.directory?.full_name||'Meu relatório');
 const detail=routes.map(r=>({date:r.route_date,title:r.route_type||'Deslocamento',km:Number(r.actual_km||0),expense:0}));expenses.forEach(e=>{const d=e.occurred_at.slice(0,10),f=detail.find(x=>x.date===d);if(f)f.expense+=Number(e.amount||0);else detail.push({date:d,title:e.notes||e.expense_type||'Despesa de viagem',km:0,expense:Number(e.amount||0)})});detail.sort((a,b)=>b.date.localeCompare(a.date));
 const share=async()=>Share.share({title:'Relatório Movvant',message:[`Movvant Enterprise — ${selectedLabel}`,`Período: ${start.toLocaleDateString('pt-BR')} a ${end.toLocaleDateString('pt-BR')}`,`KM total: ${kmTotal.toFixed(1)} km`,`Despesas: ${money(expenseTotal)}`,`${fuelMode==='real'?'Combustível realizado':'Combustível estimado'}: ${money(fuelCost)}`,`Litros ${fuelMode==='real'?'realizados':'estimados'}: ${(fuelMode==='real'?realLiters:estimatedLiters).toFixed(1)} L`,actualConsumption?`Média real: ${actualConsumption.toFixed(2)} km/l`:refAvg?`Média cadastrada: ${refAvg.toFixed(2)} km/l`:'Média de consumo não cadastrada'].join('\n')});
 return <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled" automaticallyAdjustKeyboardInsets>
  <View style={s.hero}><Text style={s.eyebrow}>RELATÓRIO OPERACIONAL</Text><Text style={s.heroTitle}>KM, gastos e deslocamentos</Text><Text style={s.heroText}>{manager?'Selecione quem deseja analisar e acompanhe dados reais e estimativas identificadas.':'Seu acesso exibe somente os seus próprios dados.'}</Text></View>
  {manager&&<VehicleFuelSettingsCard session={session} companyId={data?.companyId} enabled onSaved={()=>setFuelRefresh(x=>x+1)}/>} 
  {manager&&<><Text style={s.section}>Visualização</Text><View style={s.chips}>{[['all','Todos'],['seller','Vendedores'],['driver','Motoristas'],['self','Meu'],['user','Selecionar']].map(([k,l])=><Pressable key={k} style={[s.chip,scope===k&&s.chipOn]} onPress={()=>setScope(k as any)}><Text style={[s.chipText,scope===k&&s.chipTextOn]}>{l}</Text></Pressable>)}</View>{scope==='user'&&<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.userRow}>{users.map(u=><Pressable key={u.user_id} style={[s.userChip,selectedUser===u.user_id&&s.userChipOn]} onPress={()=>setSelectedUser(u.user_id)}><Text style={[s.userName,selectedUser===u.user_id&&s.on]}>{u.full_name||u.email||'Usuário'}</Text><Text style={[s.userRole,selectedUser===u.user_id&&s.on]}>{u.job_title||u.role_name||'Usuário'}</Text></Pressable>)}</ScrollView>}</>}
  <Text style={s.section}>Período</Text><View style={s.chips}>{[['day','Dia'],['week','Semana'],['month','Mês'],['custom','Período']].map(([k,l])=><Pressable key={k} style={[s.chip,period===k&&s.chipOn]} onPress={()=>setPeriod(k as any)}><Text style={[s.chipText,period===k&&s.chipTextOn]}>{l}</Text></Pressable>)}</View>{period==='custom'&&<View style={s.dates}><DatePickerField label="De" value={from} onChange={setFrom}/><DatePickerField label="Até" value={to} onChange={setTo}/></View>}
  <View style={s.periodCard}><Text style={s.periodTop}>{selectedLabel.toUpperCase()}</Text><Text style={s.periodValue}>{start.toLocaleDateString('pt-BR')} — {end.toLocaleDateString('pt-BR')}</Text></View>
  <View style={s.grid}><Card label="DESLOCAMENTOS" value={String(count)}/><Card label="KM TOTAL" value={`${kmTotal.toLocaleString('pt-BR',{maximumFractionDigits:1})} km`}/><Card label="DESPESAS DE VIAGEM" value={money(expenseTotal)}/><Card label={fuelMode==='real'?'COMBUSTÍVEL REALIZADO':'COMBUSTÍVEL ESTIMADO'} value={refAvg||realFuelCost?money(fuelCost):'Sem base'}/><Card label={actualConsumption?'MÉDIA REAL':'MÉDIA CADASTRADA'} value={(actualConsumption||refAvg)?`${(actualConsumption||refAvg).toFixed(2)} km/l`:'Sem base'}/><Card label={fuelMode==='real'?'LITROS ABASTECIDOS':'LITROS ESTIMADOS'} value={(fuelMode==='real'?realLiters:estimatedLiters)>0?`${(fuelMode==='real'?realLiters:estimatedLiters).toFixed(1)} L`:'Sem base'}/></View>
  {fuelMode==='estimated'&&refAvg>0&&<View style={s.info}><Text style={s.infoTitle}>Estimativa de combustível</Text><Text style={s.infoText}>Calculada com {refAvg.toFixed(2)} km/l e preço médio de referência {money(refPrice)}/L. Quando houver abastecimento registrado com litros/valor, o relatório prioriza o realizado.</Text></View>}
  {warning?<View style={s.warning}><Text style={s.warningText}>{warning}</Text></View>:null}
  <View style={s.table}><View style={s.tableHead}><Text style={[s.th,{flex:.8}]}>DATA</Text><Text style={[s.th,{flex:2}]}>DESTINO / TRABALHO</Text><Text style={[s.th,{flex:.8}]}>KM</Text><Text style={[s.th,{flex:1}]}>DESPESAS</Text></View>{detail.length?detail.map((r,i)=><View key={`${r.date}-${i}`} style={s.tr}><Text style={[s.td,{flex:.8}]}>{new Date(`${r.date}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}</Text><Text style={[s.td,{flex:2}]}>{r.title}</Text><Text style={[s.td,{flex:.8}]}>{r.km?`${r.km.toLocaleString('pt-BR',{maximumFractionDigits:1})} km`:'—'}</Text><Text style={[s.td,{flex:1}]}>{money(r.expense)}</Text></View>):<Text style={s.empty}>{loading?'Carregando dados...':'Nenhum registro neste período.'}</Text>}</View>
  <Pressable style={s.primary} onPress={share}><Text style={s.primaryText}>Compartilhar relatório</Text></Pressable>
 </ScrollView>
}
function Card({label,value}:{label:string;value:string}){return <View style={s.card}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>}
const s=StyleSheet.create({content:{padding:16,paddingBottom:40,gap:12,backgroundColor:BG},hero:{backgroundColor:'#fff',borderRadius:20,padding:18,borderWidth:1,borderColor:BORDER},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.6,color:BLUE},heroTitle:{fontSize:24,fontWeight:'900',color:TEXT,marginTop:4},heroText:{fontSize:12,color:MUTED,marginTop:6,lineHeight:18},section:{fontSize:14,fontWeight:'900',color:TEXT,marginTop:4},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:13,paddingVertical:9,borderRadius:18,backgroundColor:'#E8EEF5'},chipOn:{backgroundColor:NAVY},chipText:{fontSize:12,fontWeight:'800',color:MUTED},chipTextOn:{color:'#fff'},userRow:{gap:8},userChip:{minWidth:150,padding:11,borderRadius:14,backgroundColor:'#fff',borderWidth:1,borderColor:BORDER},userChipOn:{backgroundColor:NAVY,borderColor:NAVY},userName:{fontSize:12,fontWeight:'900',color:TEXT},userRole:{fontSize:10,color:MUTED,marginTop:3},on:{color:'#fff'},dates:{flexDirection:'row',gap:8},periodCard:{backgroundColor:'#fff',padding:16,borderRadius:16,borderWidth:1,borderColor:BORDER},periodTop:{fontSize:10,fontWeight:'900',color:MUTED},periodValue:{fontSize:16,fontWeight:'900',color:TEXT,marginTop:5},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},card:{width:'48.5%',backgroundColor:'#fff',padding:15,borderRadius:16,borderWidth:1,borderColor:BORDER,minHeight:92},label:{fontSize:10,fontWeight:'800',color:MUTED},value:{fontSize:18,fontWeight:'900',color:TEXT,marginTop:9},info:{backgroundColor:'#EEF6FF',padding:13,borderRadius:14,borderWidth:1,borderColor:'#CFE2FA'},infoTitle:{fontSize:12,fontWeight:'900',color:NAVY},infoText:{fontSize:11,color:TEXT,lineHeight:16,marginTop:4},warning:{backgroundColor:'#FFF8E8',padding:12,borderRadius:12,borderWidth:1,borderColor:'#F3D69A'},warningText:{fontSize:11,color:'#7B6428'},table:{backgroundColor:'#fff',borderRadius:16,borderWidth:1,borderColor:BORDER,overflow:'hidden'},tableHead:{flexDirection:'row',backgroundColor:'#F6F8FA',padding:10},th:{fontSize:9,fontWeight:'900',color:MUTED},tr:{flexDirection:'row',padding:10,borderTopWidth:1,borderTopColor:'#EEF2F5',alignItems:'center'},td:{fontSize:10,color:TEXT,paddingRight:4},empty:{padding:18,color:MUTED,fontSize:11},primary:{minHeight:52,borderRadius:14,backgroundColor:BLUE,alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontSize:13,fontWeight:'900'}});