import React,{useEffect,useMemo,useState}from'react';
import{Pressable,ScrollView,Share,StyleSheet,Text,View}from'react-native';
import DatePickerField from'./DatePickerField';
import{BootstrapData,DirectoryRow,Session,restSelect}from'./api';
import{LocalState}from'./offline';
import{readExpenses,summarizeExpenses}from'./expenses';

const NAVY='#0B3558',BLUE='#1769E0',BG='#F3F6FA',TEXT='#17324D',MUTED='#78889A',BORDER='#DFE6EE',GREEN='#22B77A',ORANGE='#F59E0B',RED='#E5484D';
const money=(v:unknown)=>(Number(v||0)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const pad=(n:number)=>String(n).padStart(2,'0');
const iso=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const norm=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const canViewTeam=(d:BootstrapData|null)=>['owner','propriet','admin','master','gerente','manager','supervisor'].some(x=>norm(`${d?.directory?.role_slug||''} ${d?.directory?.role_name||''} ${d?.directory?.job_title||''}`).includes(x));
const roleKind=(u:DirectoryRow)=>{const t=norm(`${u.role_slug||''} ${u.role_name||''} ${u.job_title||''}`);if(/motor|driver|entrega|logistic/.test(t))return'driver';if(/vend|seller|comercial|represent/.test(t))return'seller';return'other'};

type RouteRow={route_id:string;assigned_user_id?:string|null;route_date:string;route_type?:string|null;status?:string|null;planned_km?:number|string|null;actual_km?:number|string|null;actual_minutes?:number|string|null};
type ExpenseRow={id:string;user_id?:string|null;expense_type?:string|null;amount?:number|string|null;occurred_at:string;notes?:string|null;vehicle_id?:string|null;fuel_liters?:number|string|null;fuel_unit_price?:number|string|null};
type VehicleRef={id:string;plate:string;fuel_type?:string|null;avg_km_per_liter?:number|string|null;reference_fuel_price?:number|string|null;tank_capacity_liters?:number|string|null};
type Props={session:Session;data:BootstrapData|null;local:LocalState};
type Detail={id:string;date:string;status:string;title:string;vehicle:string;plannedKm:number;actualKm:number;source:string;expense:number};

const statusLabel=(s?:string|null)=>{const v=norm(s||'planned');if(v.includes('cancel'))return'Cancelado';if(v.includes('complete')||v.includes('conclu'))return'Concluído';if(v.includes('progress')||v.includes('andamento'))return'Em andamento';if(v.includes('expir'))return'Expirado';return'Planejado'};

export default function ReportsHierarchicalScreen({session,data,local}:Props){
 const manager=canViewTeam(data);
 const[period,setPeriod]=useState<'day'|'week'|'month'|'custom'>('month');
 const[from,setFrom]=useState(iso(new Date())),[to,setTo]=useState(iso(new Date()));
 const[users,setUsers]=useState<DirectoryRow[]>([]),[scope,setScope]=useState<'self'|'all'|'seller'|'driver'|'user'>('self'),[selectedUser,setSelectedUser]=useState(session.user.id);
 const[routes,setRoutes]=useState<RouteRow[]>([]),[expenses,setExpenses]=useState<ExpenseRow[]>([]),[vehicles,setVehicles]=useState<VehicleRef[]>([]),[localExpenses,setLocalExpenses]=useState<any[]>([]),[loading,setLoading]=useState(false),[warning,setWarning]=useState('');
 const start=useMemo(()=>{const d=new Date();d.setHours(0,0,0,0);if(period==='week')d.setDate(d.getDate()-6);if(period==='month')d.setDate(1);return period==='custom'?new Date(`${from}T00:00:00`):d},[period,from]);
 const end=useMemo(()=>period==='custom'?new Date(`${to}T23:59:59`):new Date(),[period,to]);
 const startDate=iso(start),endDate=iso(end);
 useEffect(()=>{readExpenses(data?.companyId||'local').then(setLocalExpenses).catch(()=>setLocalExpenses([]))},[data?.companyId]);
 useEffect(()=>{if(!data?.companyId){setUsers(data?.directory?[data.directory]:[]);return}if(!manager){setUsers(data.directory?[data.directory]:[]);setScope('self');setSelectedUser(session.user.id);return}(async()=>{try{setUsers(await restSelect<DirectoryRow>(session,'v_user_directory',`select=*&company_id=eq.${encodeURIComponent(data.companyId!)}&assignment_active=eq.true&order=full_name.asc&limit=500`))}catch{setUsers(data.directory?[data.directory]:[])}})()},[manager,data?.companyId,session.user.id]);
 const allowed=useMemo(()=>{if(!manager)return[session.user.id];if(scope==='all')return users.map(u=>u.user_id);if(scope==='seller')return users.filter(u=>roleKind(u)==='seller').map(u=>u.user_id);if(scope==='driver')return users.filter(u=>roleKind(u)==='driver').map(u=>u.user_id);if(scope==='user')return[selectedUser];return[session.user.id]},[manager,scope,users,selectedUser,session.user.id]);
 useEffect(()=>{if(!data?.companyId)return;let active=true;(async()=>{setLoading(true);setWarning('');try{const uf=allowed.length===1?`&assigned_user_id=eq.${encodeURIComponent(allowed[0])}`:allowed.length>1?`&assigned_user_id=in.(${allowed.map(encodeURIComponent).join(',')})`:'';const ef=allowed.length===1?`&user_id=eq.${encodeURIComponent(allowed[0])}`:allowed.length>1?`&user_id=in.(${allowed.map(encodeURIComponent).join(',')})`:'';const[r,e,v]=await Promise.all([
  restSelect<RouteRow>(session,'v_route_performance',`select=route_id,assigned_user_id,route_date,route_type,status,planned_km,actual_km,actual_minutes&company_id=eq.${encodeURIComponent(data.companyId!)}&route_date=gte.${startDate}&route_date=lte.${endDate}${uf}&order=route_date.desc&limit=1000`),
  restSelect<ExpenseRow>(session,'vehicle_expenses',`select=id,user_id,expense_type,amount,occurred_at,notes,vehicle_id,fuel_liters,fuel_unit_price&company_id=eq.${encodeURIComponent(data.companyId!)}&occurred_at=gte.${encodeURIComponent(start.toISOString())}&occurred_at=lte.${encodeURIComponent(end.toISOString())}${ef}&order=occurred_at.desc&limit=1000`),
  restSelect<VehicleRef>(session,'vehicles',`select=id,plate,fuel_type,avg_km_per_liter,reference_fuel_price,tank_capacity_liters&company_id=eq.${encodeURIComponent(data.companyId!)}&active=eq.true&order=plate.asc`)
 ]);if(active){setRoutes(r);setExpenses(e);setVehicles(v)}}catch{if(active){setRoutes([]);setExpenses([]);setWarning('Parte dos dados empresariais ainda não pôde ser carregada. Os deslocamentos criados neste aparelho continuam visíveis abaixo.')}}finally{if(active)setLoading(false)}})();return()=>{active=false}},[data?.companyId,startDate,endDate,allowed.join('|')]);
 const own=allowed.length===1&&allowed[0]===session.user.id;
 const localKm=own?local.km.filter(x=>{const t=new Date(x.createdAt);return t>=start&&t<=end}):[];
 const localTrips=own?local.trips.filter(x=>{const t=new Date(x.finishedAt);return t>=start&&t<=end}):[];
 const plannedAppointments=own?local.appointments.filter(x=>x.type==='Viagem'&&x.travel&&x.date>=startDate&&x.date<=endDate):[];
 const appExp=own?localExpenses.filter(x=>{const t=new Date(`${x.date}T12:00:00`);return t>=start&&t<=end}):[];
 const appSum=summarizeExpenses(appExp);
 const vehicleById=new Map((data?.vehicles||vehicles).map(v=>[v.id,v]));
 const activeAssignedIds=(data?.assignments||[]).filter(a=>!a.ends_at||new Date(a.ends_at).getTime()>Date.now()).map(a=>a.vehicle_id);
 const defaultVehicle=activeAssignedIds.length===1?vehicleById.get(activeAssignedIds[0]):undefined;
 const plannerDetails:Detail[]=plannedAppointments.map(a=>{const trip=localTrips.find(t=>t.plannedTripId===a.id);const plannedKm=(a.travel?.distanceMeters||0)/1000;const actualKm=trip?trip.distanceMeters/1000:0;const st=a.routeStatus==='cancelled'?'Cancelado':trip||a.routeStatus==='completed'?'Concluído':'Planejado';return{id:a.id,date:a.date,status:st,title:`${a.travel?.origin||''} → ${a.travel?.destination||a.store}`,vehicle:defaultVehicle?.plate||'Não vinculado',plannedKm,actualKm,source:trip?'GPS':st==='Concluído'?'Planejador/estimado':'Planejado',expense:(a.travel?.plannedExpenses||[]).reduce((n,x)=>n+Number(x.amount||0),0)}});
 const remoteDetails:Detail[]=routes.map(r=>({id:r.route_id,date:r.route_date,status:statusLabel(r.status),title:r.route_type||'Deslocamento',vehicle:'—',plannedKm:Number(r.planned_km||0),actualKm:Number(r.actual_km||0),source:Number(r.actual_km||0)>0?'Real':'Planejado',expense:0}));
 const seen=new Set(plannerDetails.map(x=>x.id));const detail=[...plannerDetails,...remoteDetails.filter(x=>!seen.has(x.id))];
 expenses.forEach(e=>{const d=e.occurred_at.slice(0,10),f=detail.find(x=>x.date===d);if(f)f.expense+=Number(e.amount||0)});detail.sort((a,b)=>b.date.localeCompare(a.date));
 const comparable=detail.filter(x=>x.status==='Concluído');
 const plannedComparableKm=comparable.reduce((n,x)=>n+x.plannedKm,0);
 const actualDetailKm=comparable.reduce((n,x)=>n+(x.actualKm||x.plannedKm),0);
 const routeKm=routes.reduce((n,x)=>n+Number(x.actual_km||0),0),manualKm=localKm.reduce((n,x)=>n+x.total,0),gpsKm=localTrips.reduce((n,x)=>n+x.distanceMeters/1000,0);
 const kmTotal=Math.max(actualDetailKm,routeKm,gpsKm,manualKm);
 const futurePlannedKm=detail.filter(x=>x.status==='Planejado').reduce((n,x)=>n+x.plannedKm,0);
 const expRemote=expenses.reduce((n,x)=>n+Number(x.amount||0),0),expenseTotal=Math.max(expRemote,appSum.actual||0);
 const realFuelRows=expenses.filter(x=>/fuel|combust|gasolina|diesel|etanol/i.test(x.expense_type||'')||Number(x.fuel_liters||0)>0),realFuelCost=realFuelRows.reduce((n,x)=>n+Number(x.amount||0),0),realLiters=realFuelRows.reduce((n,x)=>n+Number(x.fuel_liters||0),0);
 const refs=vehicles.filter(v=>Number(v.avg_km_per_liter||0)>0&&Number(v.reference_fuel_price||0)>0),refAvg=refs.length?refs.reduce((n,v)=>n+Number(v.avg_km_per_liter||0),0)/refs.length:0,refPrice=refs.length?refs.reduce((n,v)=>n+Number(v.reference_fuel_price||0),0)/refs.length:0,estimatedLiters=refAvg>0?kmTotal/refAvg:0,estimatedFuelCost=estimatedLiters*refPrice,fuelMode=realFuelCost>0||realLiters>0?'real':'estimated',fuelCost=fuelMode==='real'?realFuelCost:estimatedFuelCost;
 const selectedLabel=scope==='all'?'Todos os usuários':scope==='seller'?'Todos os vendedores':scope==='driver'?'Todos os motoristas':scope==='user'?(users.find(u=>u.user_id===selectedUser)?.full_name||'Usuário selecionado'):(data?.directory?.full_name||'Meu relatório');
 const share=async()=>Share.share({title:'Relatório Movvant',message:[`Movvant Enterprise — ${selectedLabel}`,`Período: ${start.toLocaleDateString('pt-BR')} a ${end.toLocaleDateString('pt-BR')}`,`Deslocamentos: ${detail.length}`,`KM planejado comparável: ${plannedComparableKm.toFixed(1)} km`,`KM realizado: ${kmTotal.toFixed(1)} km`,`KM futuro planejado: ${futurePlannedKm.toFixed(1)} km`,`Despesas: ${money(expenseTotal)}`].join('\n')});
 return <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled" automaticallyAdjustKeyboardInsets>
  <View style={s.hero}><Text style={s.eyebrow}>RELATÓRIO OPERACIONAL</Text><Text style={s.heroTitle}>Deslocamentos, KM e gastos</Text><Text style={s.heroText}>Viagens criadas no planejador agora entram no relatório desde o status Planejado e passam a Realizado quando há execução.</Text></View>
  {manager&&<><Text style={s.section}>Visualização</Text><View style={s.chips}>{[['all','Todos'],['seller','Vendedores'],['driver','Motoristas'],['self','Meu'],['user','Selecionar']].map(([k,l])=><Pressable key={k} style={[s.chip,scope===k&&s.chipOn]} onPress={()=>setScope(k as any)}><Text style={[s.chipText,scope===k&&s.chipTextOn]}>{l}</Text></Pressable>)}</View>{scope==='user'&&<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.userRow}>{users.map(u=><Pressable key={u.user_id} style={[s.userChip,selectedUser===u.user_id&&s.userChipOn]} onPress={()=>setSelectedUser(u.user_id)}><Text style={[s.userName,selectedUser===u.user_id&&s.on]}>{u.full_name||u.email||'Usuário'}</Text><Text style={[s.userRole,selectedUser===u.user_id&&s.on]}>{u.job_title||u.role_name||'Usuário'}</Text></Pressable>)}</ScrollView>}</>}
  <Text style={s.section}>Período</Text><View style={s.chips}>{[['day','Dia'],['week','Semana'],['month','Mês'],['custom','Período']].map(([k,l])=><Pressable key={k} style={[s.chip,period===k&&s.chipOn]} onPress={()=>setPeriod(k as any)}><Text style={[s.chipText,period===k&&s.chipTextOn]}>{l}</Text></Pressable>)}</View>{period==='custom'&&<View style={s.dates}><DatePickerField label="De" value={from} onChange={setFrom}/><DatePickerField label="Até" value={to} onChange={setTo}/></View>}
  <View style={s.periodCard}><Text style={s.periodTop}>{selectedLabel.toUpperCase()}</Text><Text style={s.periodValue}>{start.toLocaleDateString('pt-BR')} — {end.toLocaleDateString('pt-BR')}</Text></View>
  <View style={s.grid}><Card label="DESLOCAMENTOS" value={String(detail.length)}/><Card label="CONCLUÍDOS" value={String(comparable.length)}/><Card label="KM PLANEJADO COMPARÁVEL" value={`${plannedComparableKm.toFixed(1)} km`}/><Card label="KM REALIZADO" value={`${kmTotal.toFixed(1)} km`}/><Card label="KM FUTURO PLANEJADO" value={`${futurePlannedKm.toFixed(1)} km`}/><Card label="DESPESAS" value={money(expenseTotal)}/><Card label={fuelMode==='real'?'COMBUSTÍVEL REALIZADO':'COMBUSTÍVEL ESTIMADO'} value={refAvg||realFuelCost?money(fuelCost):'Sem base'}/><Card label="LITROS" value={(fuelMode==='real'?realLiters:estimatedLiters)>0?`${(fuelMode==='real'?realLiters:estimatedLiters).toFixed(1)} L`:'Sem base'}/></View>
  {warning?<View style={s.warning}><Text style={s.warningText}>{warning}</Text></View>:null}
  <View style={s.table}>{detail.length?detail.map(r=><View key={r.id} style={s.tripCard}><View style={s.tripTop}><Text style={s.tripDate}>{new Date(`${r.date}T12:00:00`).toLocaleDateString('pt-BR')}</Text><Text style={[s.status,r.status==='Concluído'?s.statusDone:r.status==='Cancelado'?s.statusCancel:s.statusPlan]}>{r.status}</Text></View><Text style={s.tripTitle}>{r.title}</Text><Text style={s.tripMeta}>Veículo: {r.vehicle}</Text><View style={s.tripNumbers}><Text style={s.tripNumber}>Planejado: {r.plannedKm.toFixed(1)} km</Text><Text style={s.tripNumber}>Realizado: {r.actualKm>0?`${r.actualKm.toFixed(1)} km`:'—'}</Text></View><Text style={s.tripMeta}>Fonte KM: {r.source} · Despesas: {money(r.expense)}</Text></View>):<Text style={s.empty}>{loading?'Carregando dados...':'Nenhum deslocamento neste período.'}</Text>}</View>
  <Pressable style={s.primary} onPress={share}><Text style={s.primaryText}>Compartilhar relatório</Text></Pressable>
 </ScrollView>
}
function Card({label,value}:{label:string;value:string}){return <View style={s.card}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>}
const s=StyleSheet.create({content:{padding:16,paddingBottom:40,gap:12,backgroundColor:BG},hero:{backgroundColor:'#fff',borderRadius:20,padding:18,borderWidth:1,borderColor:BORDER},eyebrow:{fontSize:10,fontWeight:'900',color:BLUE},heroTitle:{fontSize:22,fontWeight:'900',color:NAVY,marginTop:4},heroText:{fontSize:12,color:MUTED,lineHeight:18,marginTop:6},section:{fontSize:14,fontWeight:'900',color:NAVY,marginTop:4},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:12,paddingVertical:9,borderRadius:999,backgroundColor:'#fff',borderWidth:1,borderColor:BORDER},chipOn:{backgroundColor:NAVY,borderColor:NAVY},chipText:{fontSize:10,fontWeight:'800',color:TEXT},chipTextOn:{color:'#fff'},userRow:{gap:8},userChip:{padding:10,borderRadius:12,backgroundColor:'#fff',borderWidth:1,borderColor:BORDER,minWidth:135},userChipOn:{backgroundColor:NAVY},userName:{fontSize:11,fontWeight:'900',color:TEXT},userRole:{fontSize:9,color:MUTED,marginTop:2},on:{color:'#fff'},dates:{gap:8},periodCard:{backgroundColor:NAVY,borderRadius:16,padding:14},periodTop:{fontSize:9,fontWeight:'900',color:'#B7CCDE'},periodValue:{fontSize:16,fontWeight:'900',color:'#fff',marginTop:4},grid:{flexDirection:'row',flexWrap:'wrap',gap:8},card:{width:'48%',minHeight:88,backgroundColor:'#fff',borderWidth:1,borderColor:BORDER,borderRadius:16,padding:12},label:{fontSize:9,fontWeight:'900',color:MUTED},value:{fontSize:18,fontWeight:'900',color:TEXT,marginTop:8},warning:{backgroundColor:'#FFF4E5',borderRadius:14,padding:12},warningText:{fontSize:10,color:'#8A5A00'},table:{gap:8},tripCard:{backgroundColor:'#fff',borderWidth:1,borderColor:BORDER,borderRadius:16,padding:13,gap:6},tripTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},tripDate:{fontSize:10,fontWeight:'900',color:MUTED},status:{fontSize:9,fontWeight:'900',paddingHorizontal:8,paddingVertical:4,borderRadius:999},statusDone:{backgroundColor:'#E7F7F0',color:GREEN},statusPlan:{backgroundColor:'#FFF3E5',color:ORANGE},statusCancel:{backgroundColor:'#FDEBEC',color:RED},tripTitle:{fontSize:13,fontWeight:'900',color:TEXT},tripMeta:{fontSize:10,color:MUTED},tripNumbers:{flexDirection:'row',justifyContent:'space-between',gap:8},tripNumber:{fontSize:11,fontWeight:'800',color:NAVY},empty:{padding:18,textAlign:'center',color:MUTED},primary:{minHeight:52,borderRadius:14,backgroundColor:BLUE,alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontWeight:'900'}});