const fs=require('fs');
fs.mkdirSync('dist',{recursive:true});
let s=fs.readFileSync('index.html','utf8');
const rep=(a,b,label)=>{if(!s.includes(a))throw new Error('Build anchor not found: '+label);s=s.replace(a,b)};
// Browser-safe stabilization: `window.status` is a native string in some browsers.
s=s.replace(/\bstatus\.textContent/g,"$('status').textContent")
   .replace(/\bstatus\.className/g,"$('status').className");
rep('Gestão de deslocamentos · versão 100.2','Gestão de deslocamentos · versão 100.7','version');
// SaaS settings: financial/allocation data now follows the organization across devices.
rep("const vk=Number(localStorage.getItem('km_valor_km')||0); nsaldo.textContent=moeda(kmMes*vk-despMes);\n  const consumo=Number(localStorage.getItem('km_consumo')||0),precoComb=Number(localStorage.getItem('km_combustivel')||0);\n  const oc=Number(localStorage.getItem('km_orc_fuel')||0),op=Number(localStorage.getItem('km_orc_toll')||0),oe=Number(localStorage.getItem('km_orc_parking')||0);", "const vk=Number(settings?.reimbursement_rate||0); nsaldo.textContent=moeda(kmMes*vk-despMes);\n  const consumo=Number(settings?.default_average_kmpl||0),precoComb=Number(settings?.default_fuel_price||0);\n  const budgets=settings?.category_budgets||{},oc=Number(budgets.fuel||0),op=Number(budgets.toll||0),oe=Number(budgets.parking||0);",'dashboard settings');
rep("const rateio=localStorage.getItem('km_rateio')==='1', base=Number(localStorage.getItem('km_base_odometro')||0);", "const rateio=!!settings?.allocation_enabled, base=Number(settings?.base_odometer||0);",'allocation settings');
rep("const prof=trips.filter(x=>!String(x.notes||'').includes('Uso: personal')).reduce((a,x)=>a+Number(x.distance_km||0),0), marcadoPessoal=trips.filter(x=>String(x.notes||'').includes('Uso: personal')).reduce((a,x)=>a+Number(x.distance_km||0),0), pessoal=Math.max(marcadoPessoal,totalUso-prof);", "const prof=trips.filter(x=>(x.usage_type||'business')==='business').reduce((a,x)=>a+Number(x.distance_km||0),0), marcadoPessoal=trips.filter(x=>x.usage_type==='personal').reduce((a,x)=>a+Number(x.distance_km||0),0), pessoal=Math.max(marcadoPessoal,totalUso-prof);",'usage calculation');
rep("const meta=Number(localStorage.getItem('km_meta_km')||0),lim=Number(localStorage.getItem('km_limite_desp')||0),mp=meta?Math.min(100,Math.round(kmMes/meta*100)):0;", "const meta=Number(settings?.monthly_km_goal||0),lim=Number(settings?.monthly_expense_limit||0),mp=meta?Math.min(100,Math.round(kmMes/meta*100)):0;",'goals settings');
rep("cfgValorKm.value=localStorage.getItem('km_valor_km')||''; cfgConsumo.value=localStorage.getItem('km_consumo')||''; cfgComb.value=localStorage.getItem('km_combustivel')||'';\n  orcComb.value=localStorage.getItem('km_orc_fuel')||'';orcPed.value=localStorage.getItem('km_orc_toll')||'';orcEst.value=localStorage.getItem('km_orc_parking')||'';\n  cfgMetaKm.value=localStorage.getItem('km_meta_km')||'';cfgLimiteDesp.value=localStorage.getItem('km_limite_desp')||'';", "cfgValorKm.value=settings?.reimbursement_rate??''; cfgConsumo.value=settings?.default_average_kmpl??''; cfgComb.value=settings?.default_fuel_price??'';\n  const budgets=settings?.category_budgets||{};orcComb.value=budgets.fuel??'';orcPed.value=budgets.toll??'';orcEst.value=budgets.parking??'';\n  cfgMetaKm.value=settings?.monthly_km_goal??'';cfgLimiteDesp.value=settings?.monthly_expense_limit??'';",'render financial settings');
rep("cfgRateio.checked=localStorage.getItem('km_rateio')==='1';cfgBaseKm.value=localStorage.getItem('km_base_odometro')||'';cfgBaseData.value=localStorage.getItem('km_base_data')||'';", "cfgRateio.checked=!!settings?.allocation_enabled;cfgBaseKm.value=settings?.base_odometer??'';cfgBaseData.value=settings?.base_date||'';",'render allocation');
rep("notes:[motivo.value.trim()?('Motivo: '+motivo.value.trim()):'',obs.value.trim()].filter(Boolean).join(' | ')||null,status:'in_progress'", "usage_type:tipoUso.value,purpose:motivo.value.trim()||null,notes:obs.value.trim()||null,status:'in_progress'",'trip usage');
rep("allow_manual_odometer_correction:cfgOdo.checked,updated_by:ses.user.id,updated_at:new Date().toISOString()", "allow_manual_odometer_correction:cfgOdo.checked,reimbursement_rate:Number(cfgValorKm.value||0),default_average_kmpl:Number(cfgConsumo.value||0),default_fuel_price:Number(cfgComb.value||0),monthly_km_goal:Number(cfgMetaKm.value||0),monthly_expense_limit:Number(cfgLimiteDesp.value||0),category_budgets:{fuel:Number(orcComb.value||0),toll:Number(orcPed.value||0),parking:Number(orcEst.value||0)},allocation_enabled:cfgRateio.checked,base_odometer:Number(cfgBaseKm.value||0),base_date:cfgBaseData.value||null,updated_by:ses.user.id,updated_at:new Date().toISOString()",'save backend settings');
// Remove the legacy local-only persistence after the successful backend upsert.
rep("settings=r.data;localStorage.setItem('km_valor_km',cfgValorKm.value||'0');localStorage.setItem('km_consumo',cfgConsumo.value||'0');localStorage.setItem('km_combustivel',cfgComb.value||'0');\nlocalStorage.setItem('km_orc_fuel',orcComb.value||'0');localStorage.setItem('km_orc_toll',orcPed.value||'0');localStorage.setItem('km_orc_parking',orcEst.value||'0');localStorage.setItem('km_meta_km',cfgMetaKm.value||'0');localStorage.setItem('km_limite_desp',cfgLimiteDesp.value||'0');localStorage.setItem('km_rateio',cfgRateio.checked?'1':'0');localStorage.setItem('km_base_odometro',cfgBaseKm.value||'0');localStorage.setItem('km_base_data',cfgBaseData.value||'');render();msg('Configurações salvas')", "settings=r.data;render();msg('Configurações salvas na empresa')",'remove local settings save');
rep("checks.push(['Versão','100']);", "checks.push(['Versão','100.7']);",'diagnostic version');
fs.writeFileSync('dist/index.html',s);
console.log('Controle KM v100.7: organization settings and trip usage backed by Supabase');
