const fs=require('fs');
const p='dist/index.html';
let s=fs.readFileSync(p,'utf8');
const rep=(a,b,label)=>{if(!s.includes(a))throw new Error('v102.3 anchor not found: '+label);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 102.2','Gestão de deslocamentos · versão 102.3','version');
rep('<span class="tag">102.2</span>','<span class="tag">102.3</span>','help version');
rep("checks.push(['Versão','102.2']);","checks.push(['Versão','102.3']);",'diag version');
rep('<option value="tax">IPVA / impostos</option>','<option value="ipva">IPVA / impostos</option>','vehicle cost ipva');
rep("cost_type:x.cost_type||x.type||'other'","cost_type:((x.cost_type||x.type)==='tax'?'ipva':(x.cost_type||x.type||'other'))",'backup legacy tax migration');
fs.writeFileSync(p,s);
console.log('Controle KM v102.3: vehicle cost type aligned to backend contract');
