const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v107 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 106.0','Gestão de deslocamentos · versão 107.0','version');rep('<span class="tag">106.0</span>','<span class="tag">107.0</span>','help');rep("checks.push(['Versão','106.0']);","checks.push(['Versão','107.0']);",'diag');
// Rotas: finalidade/motivo como no fluxo original.
rep('<div class="r3"><input id="rotaNome" placeholder="Nome da rota"><input id="rotaOrigem" placeholder="Origem"><input id="rotaDestino" placeholder="Destino"></div><button id="btRota"', '<div class="r3"><input id="rotaNome" placeholder="Nome da rota"><input id="rotaOrigem" placeholder="Origem"><input id="rotaDestino" placeholder="Destino"></div><input id="rotaMotivo" placeholder="Motivo / finalidade" style="margin-top:10px"><button id="btRota"','route ui');
rep("origem.value=x.origin||'';destino.value=x.destination;dataViagem.value=new Date().toISOString().slice(0,10);show('viagem');msg('Rota carregada')", "origem.value=x.origin||'';destino.value=x.destination;motivo.value=x.purpose||'';dataViagem.value=new Date().toISOString().slice(0,10);show('viagem');msg('Rota carregada')",'route use');
rep("destination:rotaDestino.value.trim(),created_by:ses.user.id", "destination:rotaDestino.value.trim(),purpose:rotaMotivo.value.trim()||null,created_by:ses.user.id",'route save purpose');
rep("rotaNome.value='';rotaOrigem.value='';rotaDestino.value='';await loadRotas()", "rotaNome.value='';rotaOrigem.value='';rotaDestino.value='';rotaMotivo.value='';await loadRotas()",'route clear');
// Agenda: observações agora persistem e voltam ao iniciar a viagem.
rep("reason:x.purpose,notes:''", "reason:x.purpose,notes:x.notes||''",'agenda notes load');
rep("x.reason=x.purpose;x.notes='';", "x.reason=x.purpose;x.notes=x.notes||'';",'agenda notes start');
rep("purpose:agMotivo.value.trim()||null,recurrence:agRec.value||null,status:'scheduled'", "purpose:agMotivo.value.trim()||null,notes:agObs.value.trim()||null,recurrence:agRec.value||null,status:'scheduled'",'agenda notes save');
// Custos fixos: recorrência e inclusão nos cálculos.
rep('<div class="r" style="margin-top:10px"><input id="custoData" type="date"><input id="custoDesc" placeholder="Descrição"></div>', '<div class="r" style="margin-top:10px"><input id="custoData" type="date"><input id="custoDesc" placeholder="Descrição"></div><div class="r" style="margin-top:10px"><select id="custoRec"><option value="">Lançamento único</option><option value="monthly">Mensal</option><option value="annual">Anual</option></select><label class="row" style="display:flex;align-items:center;gap:8px"><input id="custoInclui" type="checkbox" checked style="width:auto"> Incluir no custo total do veículo</label></div>','cost ui');
rep("description:custoDesc.value.trim()||null,created_by:ses.user.id", "description:custoDesc.value.trim()||null,recurrence:custoRec.value||null,include_in_total:custoInclui.checked,created_by:ses.user.id",'cost save');
// Agenda deixa claro o fluxo de conversão para deslocamento realizado.
rep('<button id="btAgenda" style="margin-top:10px">Agendar deslocamento</button>', '<button id="btAgenda" style="margin-top:10px">Agendar deslocamento</button><p class="muted small" style="margin-top:10px">Ao chegar o momento, use “Iniciar” no compromisso para transformar o planejamento em um deslocamento real. O agendamento permanece separado do histórico até essa confirmação.</p>','agenda conversion help');
// Novo deslocamento: explicita os dois momentos do fluxo original sem inventar distância.
rep('<textarea id="obs" placeholder="Observações" style="margin-top:10px"></textarea>\n        <button id="btViagem"', '<textarea id="obs" placeholder="Observações" style="margin-top:10px"></textarea><div class="row small muted" style="margin-top:10px"><b>Como funciona:</b> informe o KM inicial para começar. Durante o percurso você pode adicionar paradas, despesas e comprovantes. O KM final é informado no encerramento e a distância é calculada automaticamente.</div>\n        <button id="btViagem"','trip workflow');
// Relatório: reforça a saída consistente prevista no original.
rep('<button id="btImprimir" class="sec">Imprimir / PDF</button>', '<button id="btImprimir" class="sec">Imprimir / salvar PDF</button>','report pdf label');
rep('</style>',`\n/* v107 functional recovery */\n#p-rotas,#p-config,#p-equipe,#p-painel,#p-notificacoes,#p-auditoria,#p-backup,#p-perfil{max-width:760px;margin:0 auto}#p-rotas>.c,#p-config>.c,#p-equipe>.c,#p-painel>.c,#p-notificacoes>.c,#p-auditoria>.c,#p-backup>.c,#p-perfil>.c{border-radius:25px;padding:26px;background:#fff;border:1px solid #d9dee8;box-shadow:none}\n</style>`,'css');
fs.writeFileSync('dist/index.html',s);console.log('Controle KM v107.0: original functional behavior recovery applied');