const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v108 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 107.0','Gestão de deslocamentos · versão 108.0','version');rep('<span class="tag">107.0</span>','<span class="tag">108.0</span>','help');rep("checks.push(['Versão','107.0']);","checks.push(['Versão','108.0']);",'diag');
// Maps/GPS: real browser GPS + honest Google Maps deep-link, without pretending Places/Routes API exists.
rep('<input id="destino" placeholder="Destino">\n        </div>', '<input id="destino" placeholder="Destino">\n        </div><div class="actions" style="margin-top:10px"><button id="btPreviewRota" class="sec" type="button">Abrir percurso no Google Maps</button></div><p class="muted small">GPS do aparelho pode preencher a origem. O cálculo automático de rota/Places depende da integração Google Maps Platform e não é simulado.</p>','trip maps ui');
rep('<textarea id="agObs" placeholder="Observações" style="margin-top:10px"></textarea>', '<textarea id="agObs" placeholder="Observações" style="margin-top:10px"></textarea><div class="actions" style="margin-top:10px"><button id="btAgendaMaps" class="sec" type="button">Abrir percurso no Google Maps</button><button id="btAgendaNotif" class="sec" type="button">Ativar lembretes neste aparelho</button></div><div id="agendaAlertas" class="row" style="margin-top:12px"></div>','agenda maps alerts ui');
// Reports: print context and clearer output block.
rep('<div class="c">\n        <div class="eyebrow">RELATÓRIO</div><h2>Relatório por período</h2>', '<div class="c">\n        <div class="eyebrow">RELATÓRIO</div><h2>Relatório por período</h2><div id="relPrintContext" class="row muted small">Filtros, totalizadores, análise gerencial e lista detalhada dos deslocamentos.</div>','report context');
// Settings: restore Central de Configurações organization and direct shortcuts.
rep('<h2>Configurações</h2>\n<div class="row"><b>Empresa</b>', '<div class="eyebrow">CENTRAL DE CONFIGURAÇÕES</div><h2>Configurações</h2><p class="muted">Empresa, veículo, segurança, comprovantes, metas, rateio e preferências do aparelho em um único local.</p><div class="cfg-nav"><button class="sec" data-cfg-go="cfgEmpresaNome">Empresa</button><button class="sec" data-cfg-go="cfgValorKm">Veículo e reembolso</button><button class="sec" data-cfg-go="cfgTimeout">Segurança</button><button class="sec" data-cfg-go="cfgReqAll">Comprovantes</button><button class="sec" data-cfg-go="cfgMetaKm">Metas</button><button class="sec" data-cfg-go="cfgRateio">Uso profissional/pessoal</button></div>\n<div class="row"><b>Empresa</b>','config nav');
// Hook agenda rendering when page opens.
rep("if(n==='agenda')loadAgenda();", "if(n==='agenda'){loadAgenda();setTimeout(renderAgendaAlertsV108,80);}",'agenda show hook');
// Add behavior before app startup.
rep('carga();',`// v108 recovered interaction layer\nconst btPreviewRotaV108=document.getElementById('btPreviewRota');if(btPreviewRotaV108)btPreviewRotaV108.onclick=()=>{if(!destino.value.trim())return msg('Informe o destino',true);abrirMaps({origin:origem.value.trim(),destination:destino.value.trim()})};\nconst btAgendaMapsV108=document.getElementById('btAgendaMaps');if(btAgendaMapsV108)btAgendaMapsV108.onclick=()=>{if(!agDestino.value.trim())return msg('Informe o destino',true);abrirMaps({origin:agOrigem.value.trim(),destination:agDestino.value.trim()})};\nconst btAgendaNotifV108=document.getElementById('btAgendaNotif');if(btAgendaNotifV108)btAgendaNotifV108.onclick=async()=>{if(!('Notification' in window))return msg('Notificações do navegador não estão disponíveis neste aparelho',true);const p=await Notification.requestPermission();localStorage.setItem('km_agenda_browser_notifications',p==='granted'?'1':'0');msg(p==='granted'?'Lembretes ativados neste aparelho':'Permissão de notificações não concedida',p!=='granted');renderAgendaAlertsV108()};\nfunction renderAgendaAlertsV108(){const box=document.getElementById('agendaAlertas');if(!box)return;const now=Date.now(),day=86400000,up=(scheduledTrips||[]).filter(x=>x.status==='scheduled'&&new Date(x.scheduled_at).getTime()>=now&&new Date(x.scheduled_at).getTime()<=now+day).sort((a,b)=>new Date(a.scheduled_at)-new Date(b.scheduled_at));box.innerHTML=up.length?'<b>Próximas 24 horas</b>'+up.map(x=>'<div class="small" style="margin-top:8px">'+new Date(x.scheduled_at).toLocaleString('pt-BR')+' · '+esc(x.destination||'Destino')+'</div>').join(''):'<span class="muted small">Nenhum compromisso nas próximas 24 horas.</span>';if(localStorage.getItem('km_agenda_browser_notifications')==='1'&&window.Notification&&Notification.permission==='granted'){up.filter(x=>new Date(x.scheduled_at).getTime()-now<=3600000).forEach(x=>{const k='km_agenda_notified_'+x.id;if(localStorage.getItem(k))return;new Notification('Controle Fácil de KM',{body:'Viagem programada: '+(x.destination||x.purpose||'compromisso')});localStorage.setItem(k,'1')})}}\nsetInterval(()=>{if(!document.getElementById('p-agenda')?.classList.contains('hide'))renderAgendaAlertsV108()},60000);\ndocument.querySelectorAll('[data-cfg-go]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.cfgGo)?.scrollIntoView({behavior:'smooth',block:'center'}));\ncarga();`,'startup');
rep('</style>',`\n/* v108 functional recovery: Maps/GPS honesty, agenda reminders, print and settings */\n.cfg-nav{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin:18px 0 24px}.cfg-nav button{min-height:48px}.actions #btPreviewRota,.actions #btAgendaMaps,.actions #btAgendaNotif{background:#fff!important;color:#102451!important;border:1px solid #cfd6e2!important}#agendaAlertas{border-left:4px solid #174795;background:#f7f9fd}.print-only{display:none}@media print{body{background:white!important}.nav,header,.actions,button,#auth,#gm,.classic-home,.cfg-nav{display:none!important}#app{display:block!important}.w{max-width:none!important;padding:0!important}section{display:none!important}#p-relatorios{display:block!important;max-width:none!important}#p-relatorios>.c{border:0!important;padding:0!important}.print-only{display:block!important}#relPrintContext{border:0!important;padding:0 0 16px!important}.stat{break-inside:avoid}.row{break-inside:avoid}h1,h2,h3{color:#111!important}}@media(max-width:600px){.cfg-nav{grid-template-columns:1fr 1fr}#p-agenda .actions{display:grid;grid-template-columns:1fr 1fr}#p-agenda .actions button{width:100%}}\n</style>`,'css');
fs.writeFileSync('dist/index.html',s);console.log('Controle KM v108.0: Maps/GPS, agenda reminders, reports and settings recovered');