const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v117 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 116.0','Gestão de deslocamentos · versão 117.0','version');rep('<span class="tag">116.0</span>','<span class="tag">117.0</span>','help');rep("checks.push(['Versão','116.0']);","checks.push(['Versão','117.0']);",'diag');
rep('carga();',`// v117 access semantics and agenda lifecycle hardening
let allowedLocationIdsV117=[];
const refreshAllBaseV117=refreshAll;refreshAll=async function(){await refreshAllBaseV117();if(!org||!ses){allowedLocationIdsV117=[];return}if(['admin','manager'].includes(acc?.module_role)){allowedLocationIdsV117=locs.filter(x=>x.active!==false).map(x=>x.id);return}const r=await sb.from('km_user_location_access').select('location_id').eq('organization_id',org.id).eq('user_id',ses.user.id);allowedLocationIdsV117=(r.data||[]).map(x=>x.location_id)};
function scopeOperationalLocationsV117(){if(!org)return;const allowed=['admin','manager'].includes(acc?.module_role)?locs:locs.filter(x=>allowedLocationIdsV117.includes(x.id));const current=local?.value||'';opts('local',allowed.filter(x=>x.active!==false),x=>x.name);if(current&&allowed.some(x=>x.id===current))local.value=current;const note=document.getElementById('tripLocationAccessV117');if(note)note.textContent=allowed.length?allowed.length+' unidade(s) disponível(is) para seu acesso.':'Nenhuma unidade liberada para este usuário. Solicite acesso ao administrador.'}
const renderBaseV117=render;render=function(){renderBaseV117();scopeOperationalLocationsV117()};
const tripChecklist=document.getElementById('tripStartChecklist');if(tripChecklist&&!document.getElementById('tripLocationAccessV117'))tripChecklist.insertAdjacentHTML('afterend','<div id="tripLocationAccessV117" class="muted small" style="margin:8px 0 12px"></div>');
async function acceptInviteV117(){if(!pendingInvite)return;let r=await sb.from('km_user_access').insert({organization_id:pendingInvite.organization_id,user_id:ses.user.id,module_role:pendingInvite.module_role,active:true});if(r.error)return msg(r.error.message,true);let locationIds=[];if(pendingInvite.location_id)locationIds=[pendingInvite.location_id];else{r=await sb.from('km_locations').select('id').eq('organization_id',pendingInvite.organization_id).eq('active',true);if(r.error)return msg(r.error.message,true);locationIds=(r.data||[]).map(x=>x.id)}if(locationIds.length){r=await sb.from('km_user_location_access').insert(locationIds.map(location_id=>({organization_id:pendingInvite.organization_id,user_id:ses.user.id,location_id})));if(r.error)return msg(r.error.message,true)}r=await sb.from('km_invitations').update({accepted_at:new Date().toISOString(),accepted_by:ses.user.id}).eq('id',pendingInvite.id);if(r.error)return msg(r.error.message,true);pendingInvite=null;await entraApp();msg('Convite aceito. Unidades e perfil liberados.')}
btAceitarConvite.onclick=acceptInviteV117;
const manageUserLocationsBaseV117=manageUserLocationsV116;manageUserLocationsV116=async function(userId){await manageUserLocationsBaseV117(userId);await refreshAll();render()};
// Correct v116 agenda lifecycle: linked at start, completed only after the real trip finishes.
const startTripLinkedBaseV117=btViagem.onclick;btViagem.onclick=async()=>{const scheduled=pendingScheduledTripV116;await startTripLinkedBaseV117();if(scheduled&&activeTrip?.id){await sb.from('km_scheduled_trips').update({trip_id:activeTrip.id,status:'scheduled',updated_at:new Date().toISOString()}).eq('id',scheduled.id).eq('organization_id',org.id);await refreshAll();render()}};
const finishTripLinkedBaseV117=btFinalizar.onclick;btFinalizar.onclick=async()=>{const tripId=activeTrip?.id||null;await finishTripLinkedBaseV117();if(tripId&&!activeTrip){const r=await sb.from('km_scheduled_trips').update({status:'completed',updated_at:new Date().toISOString()}).eq('organization_id',org.id).eq('trip_id',tripId);if(!r.error){await refreshAll();render();msg('Deslocamento finalizado e compromisso da agenda marcado como realizado')}}};
loadAgenda=async function(){const r=await sb.from('km_scheduled_trips').select('*').eq('organization_id',org.id).order('scheduled_at');if(r.error)return msg(r.error.message,true);scheduledTrips=r.data||[];const all=scheduledTrips.map(x=>({...x,date:String(x.scheduled_at).slice(0,10),time:new Date(x.scheduled_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),reason:x.purpose}));agendaLista.innerHTML=all.map(x=>'<div class="row"><b>'+esc(x.date)+' '+esc(x.time||'')+' · '+esc(x.destination)+'</b><br><span class="muted">'+esc(x.origin||'—')+' → '+esc(x.destination)+' · '+esc(x.reason||'')+'</span><div class="actions">'+(x.trip_id?'<button class="sec" data-open-linked-v117="'+x.trip_id+'">Abrir deslocamento</button>':x.status==='cancelled'?'<button class="sec" disabled>Cancelada</button>':'<button data-start-agenda="'+x.id+'">Iniciar deslocamento</button><button class="danger" data-cancel-agenda-v117="'+x.id+'">Cancelar</button>')+'</div></div>').join('')||'<p class="muted">Nenhum deslocamento agendado.</p>';document.querySelectorAll('[data-start-agenda]').forEach(b=>b.onclick=()=>startAgenda(b.dataset.startAgenda));document.querySelectorAll('[data-cancel-agenda-v117]').forEach(b=>b.onclick=()=>cancelScheduledV116(b.dataset.cancelAgendaV117));document.querySelectorAll('[data-open-linked-v117]').forEach(b=>b.onclick=()=>{show('historico');abrirDetalheViagem(b.dataset.openLinkedV117)});renderAgendaAlertsV108();renderAgendaCalendarV109()};
const renderTeamBaseV117=renderTeam;renderTeam=function(){renderTeamBaseV117();document.querySelectorAll('#convitesLista .row').forEach((row,i)=>{const inv=invites[i];if(!inv||inv.accepted_at||!inv.active||acc?.module_role!=='admin')return;const a=document.createElement('div');a.className='actions';a.innerHTML='<button class="danger" data-cancel-invite-v117="'+inv.id+'">Cancelar convite</button>';row.appendChild(a)});document.querySelectorAll('[data-cancel-invite-v117]').forEach(b=>b.onclick=async()=>{const r=await sb.from('km_invitations').update({active:false,updated_at:new Date().toISOString()}).eq('id',b.dataset.cancelInviteV117).eq('organization_id',org.id);if(r.error)return msg(r.error.message,true);await refreshTeam();renderTeam();msg('Convite cancelado')})};
setTimeout(()=>{scopeOperationalLocationsV117();loadAgenda()},1000);
carga();`,'startup');
rep('</style>',`\n/* v117 access and agenda lifecycle */\n#tripLocationAccessV117{padding:9px 12px;background:#f5f7fb;border-radius:11px}.row button:disabled{opacity:.6;cursor:default}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v117.0: unit access enforcement and agenda lifecycle finalized');