const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v120 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 119.0','Gestão de deslocamentos · versão 120.0','version');rep('<span class="tag">119.0</span>','<span class="tag">120.0</span>','help');rep("checks.push(['Versão','119.0']);","checks.push(['Versão','120.0']);",'diag');
rep('<div class="r3"><input id="agData" type="date"><input id="agHora" type="time"><input id="agDestino" placeholder="Destino"></div>','<div class="r3"><input id="agData" type="date"><input id="agHora" type="time"><input id="agDestino" placeholder="Destino"></div><div class="r" style="margin-top:10px"><div class="field-wrap-v120"><label class="field-label-v119" for="agVeiculoV120">Veículo programado</label><select id="agVeiculoV120"></select></div><div class="field-wrap-v120"><label class="field-label-v119" for="agLocalV120">Unidade / filial</label><select id="agLocalV120"></select></div></div>','agenda vehicle location');
rep('carga();',`// v120 data binding review: agenda vehicle/unit, automatic field population and Google Calendar handoff
function localDateV120(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return y+'-'+m+'-'+day}
function fillAgendaSelectorsV120(){const av=document.getElementById('agVeiculoV120'),al=document.getElementById('agLocalV120');if(!av||!al)return;const oldV=av.value,oldL=al.value,vs=veics.filter(x=>x.active!==false);av.innerHTML='<option value="">Selecione o veículo</option>'+vs.map(x=>'<option value="'+x.id+'">'+esc(x.description+(x.plate?' · '+x.plate:''))+'</option>').join('');al.innerHTML='<option value="">Selecione a unidade</option>'+locs.filter(x=>x.active!==false).map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('');if(oldV&&vs.some(x=>x.id===oldV))av.value=oldV;if(oldL&&locs.some(x=>x.id===oldL))al.value=oldL;if(!av.value&&vs.length===1)av.value=vs[0].id;if(!al.value&&locs.filter(x=>x.active!==false).length===1)al.value=locs.find(x=>x.active!==false).id;syncAgendaUnitFromVehicleV120()}
function syncAgendaUnitFromVehicleV120(){const av=document.getElementById('agVeiculoV120'),al=document.getElementById('agLocalV120');if(!av||!al)return;const v=veics.find(x=>x.id===av.value);if(v?.location_id&&locs.some(x=>x.id===v.location_id))al.value=v.location_id}
function autoPopulateTripV120(){const activeV=veics.filter(x=>x.active!==false),activeL=locs.filter(x=>x.active!==false);if(!veiculo.value&&activeV.length===1)veiculo.value=activeV[0].id;if(!local.value&&activeL.length===1)local.value=activeL[0].id;const v=activeV.find(x=>x.id===veiculo.value);if(v){if(v.location_id&&activeL.some(x=>x.id===v.location_id))local.value=v.location_id;if(String(kmi.value).trim()===''&&v.current_odometer!=null)kmi.value=v.current_odometer}if(!dataViagem.value)dataViagem.value=localDateV120();updateTripChecklistV112?.()}
const vehicleChangeBaseV120=veiculo.onchange;veiculo.onchange=()=>{vehicleChangeBaseV120?.();const v=veics.find(x=>x.id===veiculo.value);if(v?.location_id&&locs.some(x=>x.id===v.location_id))local.value=v.location_id;if(v?.current_odometer!=null)kmi.value=v.current_odometer;updateTripChecklistV112?.()};
function googleCalendarUrlV120(x){const start=new Date(x.scheduled_at),end=new Date(start.getTime()+60*60*1000),fmt=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z'),title=encodeURIComponent(x.purpose||'Deslocamento - Controle Fácil de KM'),details=encodeURIComponent((x.origin?x.origin+' → ':'')+(x.destination||'')+(x.notes?'\\n'+x.notes:'')),loc=encodeURIComponent(x.destination||'');return 'https://calendar.google.com/calendar/render?action=TEMPLATE&text='+title+'&dates='+fmt(start)+'/'+fmt(end)+'&details='+details+'&location='+loc}
function openGoogleCalendarV120(id){const x=scheduledTrips.find(z=>z.id===id);if(!x)return msg('Compromisso não encontrado',true);window.open(googleCalendarUrlV120(x),'_blank')}
const agendaSaveBaseV120=btAgenda.onclick;btAgenda.onclick=async()=>{if(!agData.value||!agDestino.value.trim())return msg('Informe data e destino',true);const base=new Date(agData.value+'T'+(agHora.value||'12:00')+':00'),q=Math.max(1,Math.min(24,Number(agQtd.value||1))),rows=[];for(let i=0;i<q;i++){const d=new Date(base);if(agRec.value==='weekly')d.setDate(d.getDate()+7*i);else if(agRec.value==='monthly')d.setMonth(d.getMonth()+i);else if(i>0)break;rows.push({organization_id:org.id,user_id:ses.user.id,vehicle_id:document.getElementById('agVeiculoV120').value||null,location_id:document.getElementById('agLocalV120').value||null,scheduled_at:d.toISOString(),origin:agOrigem.value.trim()||null,destination:agDestino.value.trim(),purpose:agMotivo.value.trim()||null,notes:agObs.value.trim()||null,recurrence:agRec.value||null,status:'scheduled',created_by:ses.user.id})}const r=await sb.from('km_scheduled_trips').insert(rows);if(r.error)return msg(r.error.message,true);agDestino.value='';agOrigem.value='';agMotivo.value='';agObs.value='';await refreshAll();await loadAgenda();renderAgendaCalendarV109();renderHomeAgendaV111();msg('Deslocamento agendado com veículo e unidade')};
const startAgendaBaseV120=startAgenda;startAgenda=async function(id){const x=scheduledTrips.find(z=>z.id===id)||await getAgenda(id);if(!x)return;await startAgendaBaseV120(id);if(x.vehicle_id&&veics.some(v=>v.id===x.vehicle_id))veiculo.value=x.vehicle_id;if(x.location_id&&locs.some(l=>l.id===x.location_id))local.value=x.location_id;const v=veics.find(z=>z.id===veiculo.value);if(v?.current_odometer!=null)kmi.value=v.current_odometer;autoPopulateTripV120();updateTripChecklistV112?.()};
const loadAgendaBaseV120=loadAgenda;loadAgenda=async function(){await loadAgendaBaseV120();document.querySelectorAll('#agendaLista .row').forEach(row=>{const b=row.querySelector('[data-start-agenda]');if(!b)return;const id=b.dataset.startAgenda,x=scheduledTrips.find(z=>z.id===id);if(!x)return;const meta=document.createElement('div');meta.className='agenda-meta-v120 muted small';const v=veics.find(z=>z.id===x.vehicle_id),l=locs.find(z=>z.id===x.location_id);meta.textContent=(v?('Veículo: '+v.description):'Veículo não definido')+' · '+(l?('Unidade: '+l.name):'Unidade não definida');row.insertBefore(meta,b.parentElement);if(!row.querySelector('[data-google-cal-v120]')){const g=document.createElement('button');g.className='sec';g.dataset.googleCalV120=id;g.textContent='Adicionar ao Google Agenda';g.onclick=()=>openGoogleCalendarV120(id);b.parentElement.appendChild(g)}if(!row.querySelector('[data-map-agenda-v120]')){const m=document.createElement('button');m.className='sec';m.dataset.mapAgendaV120=id;m.textContent='Abrir no Maps';m.onclick=()=>abrirMaps({origin:x.origin,destination:x.destination});b.parentElement.appendChild(m)}})};
const renderBaseV120=render;render=function(){renderBaseV120();fillAgendaSelectorsV120();autoPopulateTripV120()};
document.getElementById('agVeiculoV120')?.addEventListener('change',syncAgendaUnitFromVehicleV120);
setTimeout(()=>{fillAgendaSelectorsV120();autoPopulateTripV120();loadAgenda()},1100);
carga();`,'startup');
rep('</style>',`\n/* v120 data binding and Google Calendar handoff */\n.field-wrap-v120{display:flex;flex-direction:column;gap:6px;min-width:0}.agenda-meta-v120{margin-top:7px;padding:7px 9px;background:#f4f7fb;border-radius:10px}#agendaLista .actions button{flex:0 1 auto}@media(max-width:650px){#agendaLista .actions button{flex:1 1 46%}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v120.0: agenda binding, automatic field population and Google Calendar handoff added');