const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v121 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 120.0','Gestão de deslocamentos · versão 121.0','version');rep('<span class="tag">120.0</span>','<span class="tag">121.0</span>','help');rep("checks.push(['Versão','120.0']);","checks.push(['Versão','121.0']);",'diag');
rep('carga();',`// v121 cross-module data binding and field audit
function localTodayV121(){const d=new Date(),p=n=>String(n).padStart(2,'0');return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate())}
function fillOperationalDefaultsV121(){if(dataViagem&&!dataViagem.value)dataViagem.value=localTodayV121();if(custoData&&!custoData.value)custoData.value=localTodayV121();if(agData&&!agData.value)agData.value=localTodayV121();if(fIni&&!fIni.value){const d=new Date();d.setDate(1);fIni.value=localTodayV121.call(null,d)}if(fFim&&!fFim.value)fFim.value=localTodayV121();const av=veics.filter(v=>v.active!==false),al=typeof allowedLocationIdsV117==='function'?locs.filter(l=>allowedLocationIdsV117().includes(l.id)):locs;if(veiculo&&!veiculo.value&&av.length===1){veiculo.value=av[0].id;veiculo.dispatchEvent(new Event('change'))}if(local&&!local.value&&al.length===1)local.value=al[0].id;if(custoVeiculo&&!custoVeiculo.value&&av.length===1)custoVeiculo.value=av[0].id;if(manVeiculo&&!manVeiculo.value&&av.length===1)manVeiculo.value=av[0].id;if(localVeic&&!localVeic.value&&al.length===1)localVeic.value=al[0].id}
function syncVehicleContextV121(){const v=veics.find(x=>x.id===veiculo?.value);if(!v)return;if(local&&v.location_id&&[...local.options].some(o=>o.value===v.location_id))local.value=v.location_id;if(kmi&&!kmi.value&&v.current_odometer!=null)kmi.value=Number(v.current_odometer).toFixed(1);if(typeof updateTripChecklistV112==='function')updateTripChecklistV112()}
function auditFieldBindingsV121(){const ids=Object.keys(fieldLabelsV119||{}),missing=ids.filter(id=>!document.getElementById(id)),emptySelects=ids.map(id=>document.getElementById(id)).filter(el=>el?.tagName==='SELECT'&&el.options.length===0).map(el=>fieldLabelsV119[el.id]||el.id);const box=document.getElementById('bindingAuditV121');if(box)box.innerHTML='<b>Revisão automática de campos</b><div class="muted small">'+(missing.length?'Campos estruturais ausentes: '+missing.join(', '):'Campos estruturais identificados: OK')+'</div><div class="muted small">'+(emptySelects.length?'Listas sem dados neste momento: '+emptySelects.join(', '):'Listas relacionadas carregadas: OK')+'</div>'}
const renderBaseV121=render;render=function(){renderBaseV121();fillOperationalDefaultsV121();auditFieldBindingsV121()};const refreshBaseV121=refreshAll;refreshAll=async function(){await refreshBaseV121();fillOperationalDefaultsV121();auditFieldBindingsV121()};
setTimeout(()=>{if(veiculo)veiculo.addEventListener('change',syncVehicleContextV121);fillOperationalDefaultsV121();auditFieldBindingsV121();const cfg=document.querySelector('#p-config .card:last-of-type')||document.getElementById('p-config');if(cfg&&!document.getElementById('bindingAuditV121')){const d=document.createElement('div');d.id='bindingAuditV121';d.className='row binding-audit-v121';cfg.appendChild(d);auditFieldBindingsV121()}},1100);
carga();`,'startup');
rep('</style>',`\n/* v121 data binding audit */\n.binding-audit-v121{margin-top:12px;border:1px solid #dbe3ef;background:#f8faff}.binding-audit-v121 .muted{margin-top:5px}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v121.0: cross-module field/data binding audit complete');