const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v122 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 121.0','Gestão de deslocamentos · versão 122.0','version');rep('<span class="tag">121.0</span>','<span class="tag">122.0</span>','help');rep("checks.push(['Versão','121.0']);","checks.push(['Versão','122.0']);",'diag');
rep('carga();',`// v122 guided empty states + date safety
function localDateV122(d=new Date()){const p=n=>String(n).padStart(2,'0');return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate())}
function operationalDefaultsV122(){if(dataViagem&&!dataViagem.value)dataViagem.value=localDateV122();if(custoData&&!custoData.value)custoData.value=localDateV122();if(agData&&!agData.value)agData.value=localDateV122();if(fIni&&!fIni.value){const d=new Date();d.setDate(1);fIni.value=localDateV122(d)}if(fFim&&!fFim.value)fFim.value=localDateV122()}
function ensureEmptyStateV122(pageId,id,title,text,target,label){const page=document.getElementById(pageId);if(!page)return;let box=document.getElementById(id);if(!box){box=document.createElement('div');box.id=id;box.className='empty-state-v122';page.prepend(box)}box.innerHTML='<b>'+title+'</b><div class="muted small">'+text+'</div>'+(target?'<button class="secondary small-btn" data-v122-go="'+target+'">'+label+'</button>':'');box.style.display='block'}
function hideEmptyV122(id){const e=document.getElementById(id);if(e)e.style.display='none'}
function renderEmptyStatesV122(){const activeVehicles=(veics||[]).filter(v=>v.active!==false),activeLocs=(locs||[]).filter(l=>l.active!==false);if(!activeLocs.length)ensureEmptyStateV122('p-viagem','emptyLocV122','Nenhuma unidade disponível','Cadastre ou solicite acesso a uma unidade antes de iniciar deslocamentos.','admin','Configurar unidades');else hideEmptyV122('emptyLocV122');if(!activeVehicles.length){ensureEmptyStateV122('p-viagem','emptyVehTripV122','Nenhum veículo cadastrado','Cadastre um veículo para liberar deslocamentos, custos e manutenção.','veiculos','Cadastrar veículo');ensureEmptyStateV122('p-custos','emptyVehCostV122','Custos aguardando veículo','O primeiro lançamento de custo depende de um veículo cadastrado.','veiculos','Cadastrar veículo');ensureEmptyStateV122('p-agenda','emptyVehAgendaV122','Agenda sem veículo disponível','Cadastre um veículo antes de programar um deslocamento.','veiculos','Cadastrar veículo')}else{hideEmptyV122('emptyVehTripV122');hideEmptyV122('emptyVehCostV122');hideEmptyV122('emptyVehAgendaV122')}if(!(savedRoutes||[]).length)ensureEmptyStateV122('p-rotas','emptyRouteV122','Nenhuma rota salva','Crie rotas frequentes para preencher origem, destino e finalidade mais rapidamente.',null,null);else hideEmptyV122('emptyRouteV122');if(!(scheduledTrips||[]).length)ensureEmptyStateV122('p-agenda','emptyAgendaV122','Nenhum deslocamento agendado','A agenda está pronta. Programe o primeiro deslocamento quando houver veículo e unidade disponíveis.',null,null);else hideEmptyV122('emptyAgendaV122');if(!(trips||[]).length){ensureEmptyStateV122('p-historico','emptyHistoryV122','Nenhum deslocamento realizado','O histórico será preenchido automaticamente quando os deslocamentos forem iniciados e finalizados.','viagem','Novo deslocamento');ensureEmptyStateV122('p-relatorios','emptyReportV122','Relatórios aguardando movimentação','Os indicadores aparecerão após o primeiro deslocamento registrado.','viagem','Novo deslocamento')}else{hideEmptyV122('emptyHistoryV122');hideEmptyV122('emptyReportV122')}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-v122-go]');if(!b)return;const id=b.dataset.v122Go;if(typeof showPage==='function')showPage(id);else document.querySelector('[data-page="'+id+'"]')?.click()});
const renderBaseV122=render;render=function(){renderBaseV122();operationalDefaultsV122();renderEmptyStatesV122()};const refreshBaseV122=refreshAll;refreshAll=async function(){await refreshBaseV122();operationalDefaultsV122();renderEmptyStatesV122()};setTimeout(()=>{operationalDefaultsV122();renderEmptyStatesV122()},1300);
carga();`,'startup');
rep('</style>',`\n/* v122 guided empty states */\n.empty-state-v122{margin:10px 0 14px;padding:14px;border:1px solid #dbe3ef;border-radius:14px;background:#f8faff}.empty-state-v122 .muted{margin:5px 0 10px}.small-btn{padding:8px 11px!important;font-size:12px!important}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v122.0: guided empty states and local date safety complete');