const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v122 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 121.0','Gestão de deslocamentos · versão 122.0','version');rep('<span class="tag">121.0</span>','<span class="tag">122.0</span>','help');rep("checks.push(['Versão','121.0']);","checks.push(['Versão','122.0']);",'diag');
rep('carga();',`// v122 guided states + local dates + relationship coherence
function localDateV122(d=new Date()){const p=n=>String(n).padStart(2,'0');return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate())}
function operationalDefaultsV122(){if(dataViagem&&!dataViagem.value)dataViagem.value=localDateV122();if(custoData&&!custoData.value)custoData.value=localDateV122();if(agData&&!agData.value)agData.value=localDateV122();if(fIni&&!fIni.value){const d=new Date();d.setDate(1);fIni.value=localDateV122(d)}if(fFim&&!fFim.value)fFim.value=localDateV122()}
function ensureStateV122(pageId,id,title,text,target,label,kind='empty'){const page=document.getElementById(pageId);if(!page)return;let box=document.getElementById(id);if(!box){box=document.createElement('div');box.id=id;page.prepend(box)}box.className='empty-state-v122 state-'+kind;box.innerHTML='<b>'+title+'</b><div class="muted small">'+text+'</div>'+(target?'<button class="secondary small-btn" data-v122-go="'+target+'">'+label+'</button>':'');box.style.display='block'}
function hideStateV122(id){const e=document.getElementById(id);if(e)e.style.display='none'}
function currentRoleV122(){return String((typeof acc!=='undefined'&&acc?.module_role)||(typeof myAccess!=='undefined'&&(myAccess?.module_role||myAccess?.role))||'').toLowerCase()}
function allowedLocsV122(){const all=(locs||[]).filter(l=>l.active!==false),role=currentRoleV122();if(role==='admin'||role==='manager')return all;if(typeof allowedLocationIdsV117==='undefined')return all;return all.filter(l=>allowedLocationIdsV117.includes(l.id))}
function visibleVehiclesV122(){const ids=new Set(allowedLocsV122().map(l=>l.id)),role=currentRoleV122();return (veics||[]).filter(v=>v.active!==false&&((role==='admin'||role==='manager')||!v.location_id||ids.has(v.location_id)))}
function syncVehicleRelationsV122(source='trip'){const agV=document.getElementById('agVeiculoV120'),agL=document.getElementById('agLocalV120'),map={trip:[veiculo,local,kmi],agenda:[agV,agL,null],cost:[custoVeiculo,null,null],maintenance:[manVeiculo,null,null]};const [vs,ls,odo]=map[source]||[];const v=(veics||[]).find(x=>x.id===vs?.value);if(!v)return;if(ls&&v.location_id&&[...ls.options].some(o=>o.value===v.location_id))ls.value=v.location_id;if(odo&&String(odo.value||'').trim()===''&&v.current_odometer!=null)odo.value=Number(v.current_odometer).toFixed(1)}
function pruneSelectV122(el,allowed){if(!el)return;[...el.options].forEach(o=>{if(o.value&&!allowed.has(o.value))o.remove()})}
function enforceScopedSelectorsV122(){const locIds=new Set(allowedLocsV122().map(x=>x.id)),vehIds=new Set(visibleVehiclesV122().map(x=>x.id));[local,document.getElementById('agLocalV120'),localVeic].forEach(el=>pruneSelectV122(el,locIds));[veiculo,document.getElementById('agVeiculoV120'),custoVeiculo,manVeiculo].forEach(el=>pruneSelectV122(el,vehIds));syncVehicleRelationsV122('trip');syncVehicleRelationsV122('agenda')}
function vehicleLocationMismatchV122(vehicleId,locationId){if(!vehicleId||!locationId)return false;const v=(veics||[]).find(x=>x.id===vehicleId);return !!(v?.location_id&&v.location_id!==locationId)}
function bindCoherenceGuardsV122(){const guard=(button,getPair,label)=>{if(!button||button.dataset.v122Guard)return;button.dataset.v122Guard='1';button.addEventListener('click',e=>{const [v,l]=getPair();if(vehicleLocationMismatchV122(v,l)){e.preventDefault();e.stopImmediatePropagation();msg('O veículo selecionado pertence a outra unidade. Ajuste '+label+' antes de continuar.',true)}},true)};guard(btViagem,()=>[veiculo?.value,local?.value],'a unidade da viagem');guard(btAgenda,()=>[document.getElementById('agVeiculoV120')?.value,document.getElementById('agLocalV120')?.value],'a unidade da agenda')}
function renderStatesV122(){const allLocs=(locs||[]).filter(l=>l.active!==false),visibleLocs=allowedLocsV122(),activeVehicles=visibleVehiclesV122(),role=currentRoleV122();if(!allLocs.length){ensureStateV122('p-viagem','emptyLocV122','Nenhuma unidade cadastrada','A empresa precisa de ao menos uma unidade para organizar veículos, usuários e deslocamentos.',role==='admin'||role==='manager'?'admin':null,role==='admin'||role==='manager'?'Configurar unidades':null)}else if(!visibleLocs.length){ensureStateV122('p-viagem','emptyLocV122','Sem acesso a unidades','Existem unidades cadastradas, mas seu usuário não possui uma unidade liberada. Solicite acesso ao administrador.',null,null,'access')}else hideStateV122('emptyLocV122');if(!activeVehicles.length){ensureStateV122('p-viagem','emptyVehTripV122','Nenhum veículo disponível','Não há veículo ativo liberado para as suas unidades. Cadastre um veículo ou revise seu acesso.','veiculos',role==='admin'||role==='manager'?'Cadastrar veículo':'Ver veículos');ensureStateV122('p-custos','emptyVehCostV122','Custos aguardando veículo','O primeiro lançamento de custo depende de um veículo ativo disponível.','veiculos','Ver veículos');ensureStateV122('p-agenda','emptyVehAgendaV122','Agenda sem veículo disponível','É necessário um veículo ativo disponível para programar um deslocamento.','veiculos','Ver veículos')}else{hideStateV122('emptyVehTripV122');hideStateV122('emptyVehCostV122');hideStateV122('emptyVehAgendaV122')}if(!(savedRoutes||[]).length)ensureStateV122('p-rotas','emptyRouteV122','Nenhuma rota salva','Crie rotas frequentes para preencher origem, destino e finalidade mais rapidamente.',null,null);else hideStateV122('emptyRouteV122');if(!(scheduledTrips||[]).length)ensureStateV122('p-agenda','emptyAgendaV122','Nenhum deslocamento agendado','A agenda está pronta para receber o primeiro compromisso.',null,null);else hideStateV122('emptyAgendaV122');if(!(trips||[]).length){ensureStateV122('p-historico','emptyHistoryV122','Nenhum deslocamento realizado','O histórico será preenchido automaticamente quando os deslocamentos forem iniciados e finalizados.','viagem','Novo deslocamento');ensureStateV122('p-relatorios','emptyReportV122','Relatórios aguardando movimentação','Os indicadores aparecerão após o primeiro deslocamento registrado.','viagem','Novo deslocamento')}else{hideStateV122('emptyHistoryV122');hideStateV122('emptyReportV122')}}
function fixTeamAccessCopyV122(){document.querySelectorAll('.team-row-v116').forEach(row=>{const role=(row.querySelector('.tag')?.textContent||'').toLowerCase(),box=row.querySelector('.team-locations-v116');if(!box)return;const empty=!box.querySelector('.tag');if(!empty)return;const managerial=role.includes('administr')||role.includes('gerente');box.innerHTML='<span class="muted small">'+(managerial?'Todas as unidades':'Nenhuma unidade liberada')+'</span>'})}
function routeToAgendaV122(id){const x=(savedRoutes||[]).find(z=>z.id===id);if(!x)return;show('agenda');agOrigem.value=x.origin||'';agDestino.value=x.destination||'';agMotivo.value=x.purpose||'';if(x.location_id){const al=document.getElementById('agLocalV120');if(al&&[...al.options].some(o=>o.value===x.location_id))al.value=x.location_id}operationalDefaultsV122();msg('Rota carregada na agenda')}
function enhanceRoutesV122(){document.querySelectorAll('.route-row-v118').forEach(row=>{const use=row.querySelector('[data-use-route]');if(!use)return;const id=use.dataset.useRoute,actions=use.parentElement;if(!actions.querySelector('[data-agenda-route-v122]')){const b=document.createElement('button');b.className='sec';b.dataset.agendaRouteV122=id;b.textContent='Agendar';b.onclick=()=>routeToAgendaV122(id);actions.appendChild(b)}})}
function clarifyRecurringCostsV122(){const page=document.getElementById('p-custos');if(!page||document.getElementById('costRecurrenceHintV122'))return;const p=document.createElement('p');p.id='costRecurrenceHintV122';p.className='muted small cost-hint-v122';p.textContent='Recorrência classifica o custo para análise; ela não cria lançamentos futuros automaticamente.';const form=page.querySelector('.card')||page;p.style.marginTop='8px';form.appendChild(p)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-v122-go]');if(b){const id=b.dataset.v122Go;if(typeof showPage==='function')showPage(id);else document.querySelector('[data-page="'+id+'"]')?.click();return}const r=e.target.closest('[data-use-route]');if(r?.dataset?.useRoute){const x=(savedRoutes||[]).find(z=>z.id===r.dataset.useRoute);setTimeout(()=>{if(x?.location_id&&local&&[...local.options].some(o=>o.value===x.location_id))local.value=x.location_id},0)}});
function bindRelationsV122(){if(veiculo&&!veiculo.dataset.v122Rel){veiculo.dataset.v122Rel='1';veiculo.addEventListener('change',()=>syncVehicleRelationsV122('trip'))}const agV=document.getElementById('agVeiculoV120');if(agV&&!agV.dataset.v122Rel){agV.dataset.v122Rel='1';agV.addEventListener('change',()=>syncVehicleRelationsV122('agenda'))}if(custoVeiculo&&!custoVeiculo.dataset.v122Rel){custoVeiculo.dataset.v122Rel='1';custoVeiculo.addEventListener('change',()=>syncVehicleRelationsV122('cost'))}if(manVeiculo&&!manVeiculo.dataset.v122Rel){manVeiculo.dataset.v122Rel='1';manVeiculo.addEventListener('change',()=>syncVehicleRelationsV122('maintenance'))}}
function finalizeBindingsV122(){operationalDefaultsV122();enforceScopedSelectorsV122();renderStatesV122();bindRelationsV122();bindCoherenceGuardsV122();clarifyRecurringCostsV122();fixTeamAccessCopyV122();enhanceRoutesV122()}
const renderBaseV122=render;render=function(){renderBaseV122();finalizeBindingsV122()};const refreshBaseV122=refreshAll;refreshAll=async function(){await refreshBaseV122();finalizeBindingsV122()};const loadRotasBaseV122=loadRotas;loadRotas=async function(){await loadRotasBaseV122();enhanceRoutesV122()};setTimeout(finalizeBindingsV122,1300);
carga();`,'startup');
rep('</style>',`\n/* v122 guided operational states */\n.empty-state-v122{margin:10px 0 14px;padding:14px;border:1px solid #dbe3ef;border-radius:14px;background:#f8faff}.empty-state-v122.state-access{border-style:dashed}.empty-state-v122 .muted{margin:5px 0 10px}.small-btn{padding:8px 11px!important;font-size:12px!important}.cost-hint-v122{padding:8px 10px;background:#f8faff;border-radius:10px}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v122.0: guided states, access semantics and route-agenda coherence complete');