const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v122 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 121.0','Gestão de deslocamentos · versão 122.0','version');rep('<span class="tag">121.0</span>','<span class="tag">122.0</span>','help');rep("checks.push(['Versão','121.0']);","checks.push(['Versão','122.0']);",'diag');
rep('carga();',`// v122 guided states + local dates + relationship context
function localDateV122(d=new Date()){const p=n=>String(n).padStart(2,'0');return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate())}
function operationalDefaultsV122(){if(dataViagem&&!dataViagem.value)dataViagem.value=localDateV122();if(custoData&&!custoData.value)custoData.value=localDateV122();if(agData&&!agData.value)agData.value=localDateV122();if(fIni&&!fIni.value){const d=new Date();d.setDate(1);fIni.value=localDateV122(d)}if(fFim&&!fFim.value)fFim.value=localDateV122()}
function ensureStateV122(pageId,id,title,text,target,label,kind='empty'){const page=document.getElementById(pageId);if(!page)return;let box=document.getElementById(id);if(!box){box=document.createElement('div');box.id=id;page.prepend(box)}box.className='empty-state-v122 state-'+kind;box.innerHTML='<b>'+title+'</b><div class="muted small">'+text+'</div>'+(target?'<button class="secondary small-btn" data-v122-go="'+target+'">'+label+'</button>':'');box.style.display='block'}
function hideStateV122(id){const e=document.getElementById(id);if(e)e.style.display='none'}
function currentRoleV122(){return String((typeof myAccess!=='undefined'&&myAccess?.role)||'').toLowerCase()}
function allowedLocsV122(){const all=(locs||[]).filter(l=>l.active!==false);if(typeof allowedLocationIdsV117!=='function')return all;const ids=allowedLocationIdsV117();return all.filter(l=>ids.includes(l.id))}
function syncVehicleRelationsV122(source='trip'){const map={trip:[veiculo,local,kmi],agenda:[typeof agVeiculoV120!=='undefined'?agVeiculoV120:null,typeof agLocalV120!=='undefined'?agLocalV120:null,null],cost:[custoVeiculo,null,null],maintenance:[manVeiculo,null,null]};const [vs,ls,odo]=map[source]||[];const v=(veics||[]).find(x=>x.id===vs?.value);if(!v)return;if(ls&&v.location_id&&[...ls.options].some(o=>o.value===v.location_id))ls.value=v.location_id;if(odo&&!odo.value&&v.current_odometer!=null)odo.value=Number(v.current_odometer).toFixed(1)}
function renderStatesV122(){const allLocs=(locs||[]).filter(l=>l.active!==false),visibleLocs=allowedLocsV122(),activeVehicles=(veics||[]).filter(v=>v.active!==false),role=currentRoleV122();if(!allLocs.length){ensureStateV122('p-viagem','emptyLocV122','Nenhuma unidade cadastrada','A empresa precisa de ao menos uma unidade para organizar veículos, usuários e deslocamentos.',role==='admin'||role==='manager'?'admin':null,role==='admin'||role==='manager'?'Configurar unidades':null)}else if(!visibleLocs.length){ensureStateV122('p-viagem','emptyLocV122','Sem acesso a unidades','Existem unidades cadastradas, mas seu usuário não possui uma unidade liberada. Solicite acesso ao administrador.',null,null,'access')}else hideStateV122('emptyLocV122');if(!activeVehicles.length){ensureStateV122('p-viagem','emptyVehTripV122','Nenhum veículo disponível','Cadastre um veículo para liberar deslocamentos, custos e manutenção.','veiculos','Cadastrar veículo');ensureStateV122('p-custos','emptyVehCostV122','Custos aguardando veículo','O primeiro lançamento de custo depende de um veículo cadastrado.','veiculos','Cadastrar veículo');ensureStateV122('p-agenda','emptyVehAgendaV122','Agenda sem veículo disponível','Cadastre um veículo antes de programar um deslocamento.','veiculos','Cadastrar veículo')}else{hideStateV122('emptyVehTripV122');hideStateV122('emptyVehCostV122');hideStateV122('emptyVehAgendaV122')}if(!(savedRoutes||[]).length)ensureStateV122('p-rotas','emptyRouteV122','Nenhuma rota salva','Crie rotas frequentes para preencher origem, destino e finalidade mais rapidamente.',null,null);else hideStateV122('emptyRouteV122');if(!(scheduledTrips||[]).length)ensureStateV122('p-agenda','emptyAgendaV122','Nenhum deslocamento agendado','A agenda está pronta para receber o primeiro compromisso.',null,null);else hideStateV122('emptyAgendaV122');if(!(trips||[]).length){ensureStateV122('p-historico','emptyHistoryV122','Nenhum deslocamento realizado','O histórico será preenchido automaticamente quando os deslocamentos forem iniciados e finalizados.','viagem','Novo deslocamento');ensureStateV122('p-relatorios','emptyReportV122','Relatórios aguardando movimentação','Os indicadores aparecerão após o primeiro deslocamento registrado.','viagem','Novo deslocamento')}else{hideStateV122('emptyHistoryV122');hideStateV122('emptyReportV122')}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-v122-go]');if(!b)return;const id=b.dataset.v122Go;if(typeof showPage==='function')showPage(id);else document.querySelector('[data-page="'+id+'"]')?.click()});
function bindRelationsV122(){veiculo?.addEventListener('change',()=>syncVehicleRelationsV122('trip'));if(typeof agVeiculoV120!=='undefined')agVeiculoV120?.addEventListener('change',()=>syncVehicleRelationsV122('agenda'));custoVeiculo?.addEventListener('change',()=>syncVehicleRelationsV122('cost'));manVeiculo?.addEventListener('change',()=>syncVehicleRelationsV122('maintenance'))}
const renderBaseV122=render;render=function(){renderBaseV122();operationalDefaultsV122();renderStatesV122()};const refreshBaseV122=refreshAll;refreshAll=async function(){await refreshBaseV122();operationalDefaultsV122();renderStatesV122()};setTimeout(()=>{operationalDefaultsV122();renderStatesV122();bindRelationsV122()},1300);
carga();`,'startup');
rep('</style>',`\n/* v122 guided operational states */\n.empty-state-v122{margin:10px 0 14px;padding:14px;border:1px solid #dbe3ef;border-radius:14px;background:#f8faff}.empty-state-v122.state-access{border-style:dashed}.empty-state-v122 .muted{margin:5px 0 10px}.small-btn{padding:8px 11px!important;font-size:12px!important}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v122.0: guided states, local dates and relationship context complete');