const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v123 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 122.0','Gestão de deslocamentos · versão 123.0','version');rep('<span class="tag">122.0</span>','<span class="tag">123.0</span>','help');rep("checks.push(['Versão','122.0']);","checks.push(['Versão','123.0']);",'diag');
rep('<div class="r" style="margin-top:10px"><input id="agOrigem" placeholder="Origem"><input id="agMotivo" placeholder="Motivo / compromisso"></div>','<div class="r" style="margin-top:10px"><div class="field-wrap-v123"><label class="field-label-v119" for="agUsoV123">Tipo de uso</label><select id="agUsoV123"><option value="work">Profissional</option><option value="personal">Pessoal</option></select></div><div id="agVehicleContextV123" class="resource-context-v123 muted small"></div></div><div class="r" style="margin-top:10px"><input id="agOrigem" placeholder="Origem"><input id="agMotivo" placeholder="Motivo / compromisso"></div>','agenda usage');
rep('carga();',`// v123 restore resources hidden by the new journey presentation
function usageNameV123(v){return v==='personal'?'Pessoal':'Profissional'}
function agendaVehicleContextV123(){const box=document.getElementById('agVehicleContextV123'),av=document.getElementById('agVeiculoV120'),al=document.getElementById('agLocalV120');if(!box||!av||!al)return;const v=(veics||[]).find(x=>x.id===av.value),l=(locs||[]).find(x=>x.id===al.value);box.innerHTML=v?'<b>'+esc(v.description+(v.plate?' · '+v.plate:''))+'</b><br>KM atual: '+Number(v.current_odometer||0).toFixed(1)+(l?' · Unidade: '+esc(l.name):''):'Selecione o veículo para carregar unidade e KM atual.'}
function tripResourceContextV123(){const form=document.getElementById('novaViagem');if(!form)return;let box=document.getElementById('tripResourceContextV123');if(!box){box=document.createElement('div');box.id='tripResourceContextV123';box.className='resource-context-v123 muted small';const first=form.querySelector('.r');if(first)first.insertAdjacentElement('afterend',box)}const v=(veics||[]).find(x=>x.id===veiculo?.value),l=(locs||[]).find(x=>x.id===local?.value);box.innerHTML=v?'<b>Veículo: '+esc(v.description+(v.plate?' · '+v.plate:''))+'</b><br>Unidade: '+esc(l?.name||'não definida')+' · KM atual: '+Number(v.current_odometer||0).toFixed(1)+' · Uso: '+usageNameV123(tipoUso?.value):'Selecione veículo e unidade para carregar o contexto do deslocamento.'}
function scopeAgendaResourcesV123(){const av=document.getElementById('agVeiculoV120'),al=document.getElementById('agLocalV120');if(!av||!al)return;const vs=typeof visibleVehiclesV122==='function'?visibleVehiclesV122():(veics||[]).filter(x=>x.active!==false),ls=typeof allowedLocsV122==='function'?allowedLocsV122():(locs||[]).filter(x=>x.active!==false),oldV=av.value,oldL=al.value;av.innerHTML='<option value="">Selecione o veículo</option>'+vs.map(x=>'<option value="'+x.id+'">'+esc(x.description+(x.plate?' · '+x.plate:''))+'</option>').join('');al.innerHTML='<option value="">Selecione a unidade</option>'+ls.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('');if(oldV&&vs.some(x=>x.id===oldV))av.value=oldV;if(oldL&&ls.some(x=>x.id===oldL))al.value=oldL;if(!av.value&&vs.length===1)av.value=vs[0].id;const v=vs.find(x=>x.id===av.value);if(v?.location_id&&ls.some(x=>x.id===v.location_id))al.value=v.location_id;else if(!al.value&&ls.length===1)al.value=ls[0].id;agendaVehicleContextV123()}
function bindResourceBridgeV123(){const av=document.getElementById('agVeiculoV120'),al=document.getElementById('agLocalV120'),au=document.getElementById('agUsoV123');if(av&&!av.dataset.v123Bridge){av.dataset.v123Bridge='1';av.addEventListener('change',()=>{syncAgendaUnitFromVehicleV120?.();agendaVehicleContextV123()})}if(al&&!al.dataset.v123Bridge){al.dataset.v123Bridge='1';al.addEventListener('change',agendaVehicleContextV123)}if(au&&!au.dataset.v123Bridge){au.dataset.v123Bridge='1';au.addEventListener('change',agendaVehicleContextV123)}[veiculo,local,tipoUso].forEach(el=>{if(el&&!el.dataset.v123Bridge){el.dataset.v123Bridge='1';el.addEventListener('change',tripResourceContextV123)}})}
btAgenda.onclick=async()=>{if(!agData.value||!agDestino.value.trim())return msg('Informe data e destino',true);const av=document.getElementById('agVeiculoV120'),al=document.getElementById('agLocalV120'),au=document.getElementById('agUsoV123');if(!av?.value)return msg('Selecione o veículo',true);if(!al?.value)return msg('Selecione a unidade',true);if(vehicleLocationMismatchV122?.(av.value,al.value))return msg('O veículo selecionado pertence a outra unidade.',true);const base=new Date(agData.value+'T'+(agHora.value||'12:00')+':00'),q=Math.max(1,Math.min(24,Number(agQtd.value||1))),rows=[];for(let i=0;i<q;i++){const d=new Date(base);if(agRec.value==='weekly')d.setDate(d.getDate()+7*i);else if(agRec.value==='monthly')d.setMonth(d.getMonth()+i);else if(i>0)break;rows.push({organization_id:org.id,user_id:ses.user.id,vehicle_id:av.value,location_id:al.value,usage_type:au?.value||'work',scheduled_at:d.toISOString(),origin:agOrigem.value.trim()||null,destination:agDestino.value.trim(),purpose:agMotivo.value.trim()||null,notes:agObs.value.trim()||null,recurrence:agRec.value||null,status:'scheduled',created_by:ses.user.id})}const r=await sb.from('km_scheduled_trips').insert(rows);if(r.error)return msg(r.error.message,true);agDestino.value='';agOrigem.value='';agMotivo.value='';agObs.value='';await refreshAll();await loadAgenda();renderAgendaCalendarV109();renderHomeAgendaV111();msg('Deslocamento agendado com veículo, unidade e tipo de uso')};
const startAgendaBaseV123=startAgenda;startAgenda=async function(id){const x=(scheduledTrips||[]).find(z=>z.id===id)||await getAgenda(id);await startAgendaBaseV123(id);if(x?.usage_type&&tipoUso)tipoUso.value=x.usage_type;tripResourceContextV123();updateTripChecklistV112?.()};
const loadAgendaBaseV123=loadAgenda;loadAgenda=async function(){await loadAgendaBaseV123();document.querySelectorAll('#agendaLista .row').forEach(row=>{const b=row.querySelector('[data-start-agenda]'),id=b?.dataset?.startAgenda;if(!id)return;const x=(scheduledTrips||[]).find(z=>z.id===id),meta=row.querySelector('.agenda-meta-v120');if(x&&meta&&!meta.dataset.v123Usage){meta.dataset.v123Usage='1';meta.textContent+=' · Uso: '+usageNameV123(x.usage_type)}});scopeAgendaResourcesV123();bindResourceBridgeV123()};
function finalizeResourceBridgeV123(){scopeAgendaResourcesV123();tripResourceContextV123();bindResourceBridgeV123();agendaVehicleContextV123()}
const renderBaseV123=render;render=function(){renderBaseV123();finalizeResourceBridgeV123()};const refreshBaseV123=refreshAll;refreshAll=async function(){await refreshBaseV123();finalizeResourceBridgeV123()};setTimeout(finalizeResourceBridgeV123,1400);
carga();`,'startup');
rep('</style>',`\n/* v123 restored operational resources */\n.field-wrap-v123{display:flex;flex-direction:column;gap:6px;min-width:0}.resource-context-v123{border:1px solid #dbe3ef;background:#f8faff;border-radius:14px;padding:11px 12px;line-height:1.45;margin-top:10px}#p-agenda .resource-context-v123{margin-top:0;min-height:54px;display:flex;flex-direction:column;justify-content:center}@media(max-width:650px){#p-agenda .field-wrap-v123,#p-agenda .resource-context-v123{width:100%}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v123.0: vehicle, unit, usage and odometer context restored across agenda and trip flow');