const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v127 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 126.0','Gestão de deslocamentos · versão 127.0','version');rep('<span class="tag">126.0</span>','<span class="tag">127.0</span>','help');rep("checks.push(['Versão','126.0']);","checks.push(['Versão','127.0']);",'diag');
rep('carga();',`// v127 route-first direct trip, pre-trip stops and waypoint handoff
let preTripStopsV127=[];
function renderPreTripStopsV127(){const box=document.getElementById('preTripStopsListV127');if(!box)return;box.innerHTML=preTripStopsV127.length?preTripStopsV127.map((x,i)=>'<div class="pre-stop-row-v127"><span><b>'+esc(x.place_name)+'</b>'+(x.notes?'<small>'+esc(x.notes)+'</small>':'')+'</span><button type="button" class="danger" data-prestop-del-v127="'+i+'">×</button></div>').join(''):'<span class="muted small">Sem paradas. Adicione somente se fizer parte do percurso.</span>';box.querySelectorAll('[data-prestop-del-v127]').forEach(b=>b.onclick=()=>{preTripStopsV127.splice(+b.dataset.prestopDelV127,1);renderPreTripStopsV127()})}
function addPreTripStopV127(){const n=document.getElementById('preTripStopNameV127'),o=document.getElementById('preTripStopNoteV127');if(!n?.value.trim())return msg('Informe a cidade, endereço ou local da parada',true);preTripStopsV127.push({place_name:n.value.trim(),notes:o?.value.trim()||null});n.value='';if(o)o.value='';renderPreTripStopsV127();n.focus()}
function ensureDirectRouteV127(){const form=document.getElementById('novaViagem'),o=document.getElementById('origem'),d=document.getElementById('destino');if(!form||!o||!d)return;let stack=document.getElementById('directRouteStackV127');if(!stack){stack=document.createElement('div');stack.id='directRouteStackV127';stack.className='route-stack-v126 direct-route-v127';const oldRow=o.closest('.r');oldRow?.insertAdjacentElement('beforebegin',stack);stack.innerHTML='<div class="route-point-v126 origin"><span class="route-marker-v126">A</span><div class="route-point-body-v126" id="directOriginBodyV127"><small>ORIGEM</small></div></div><div class="route-point-v126 stops"><span class="route-marker-v126">＋</span><div class="route-point-body-v126"><small>PARADAS</small><div class="pre-stop-entry-v127"><input id="preTripStopNameV127" placeholder="Digite cidade, endereço ou local"><input id="preTripStopNoteV127" placeholder="Observação opcional"><button id="preTripStopAddV127" type="button" class="sec">Adicionar parada</button></div><div id="preTripStopsListV127"></div></div></div><div class="route-point-v126 destination"><span class="route-marker-v126">B</span><div class="route-point-body-v126" id="directDestBodyV127"><small>DESTINO</small></div></div>';const ow=nodeWrapV126(o),dw=nodeWrapV126(d),ob=document.getElementById('directOriginBodyV127'),db=document.getElementById('directDestBodyV127'),gps=document.getElementById('btMinhaOrigem');if(ow&&ob)ob.appendChild(ow);if(gps&&ob){gps.classList.add('route-gps-v127');ob.appendChild(gps)}if(dw&&db)db.appendChild(dw);if(oldRow)oldRow.classList.add('route-old-row-v127');document.getElementById('preTripStopAddV127').onclick=addPreTripStopV127;document.getElementById('preTripStopNameV127').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addPreTripStopV127()}});renderPreTripStopsV127()}['origem','destino','agOrigem','agDestino'].forEach(id=>{const el=document.getElementById(id);if(el)el.placeholder='Digite cidade, endereço ou local'});bindPlaceSuggestionsV125?.();const ps=document.getElementById('preTripStopNameV127');if(ps&&!ps.dataset.geoV125){ps.dataset.geoV125='1';ps.setAttribute('autocomplete','off');ps.addEventListener('input',()=>{clearTimeout(geoTimerV125);geoTimerV125=setTimeout(()=>searchPlacesV125(ps),350)});ps.addEventListener('focus',()=>{if(ps.value.trim().length>=3)searchPlacesV125(ps)})}}
async function currentPlaceToV127(el){if(!el)return;if(!navigator.geolocation)return msg('Geolocalização não disponível',true);msg('Buscando sua localização...');navigator.geolocation.getCurrentPosition(async p=>{const lat=p.coords.latitude,lon=p.coords.longitude;try{const x=await reversePlaceV125(lat,lon);el.value=formatPlaceV125(x)||x.display_name||lat.toFixed(6)+','+lon.toFixed(6);el.dataset.lat=lat;el.dataset.lon=lon;el.dispatchEvent(new Event('input',{bubbles:true}));msg('Localização identificada pelo endereço')}catch{el.value=lat.toFixed(6)+','+lon.toFixed(6);msg('Localização obtida; nome do endereço indisponível',true)}},()=>msg('Não foi possível obter a localização',true),{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}
function ensureAgendaGpsV127(){const o=document.getElementById('agOrigem'),body=o?.closest('.route-point-body-v126')||nodeWrapV126(o);if(!o||!body||document.getElementById('agGpsV127'))return;const b=document.createElement('button');b.id='agGpsV127';b.type='button';b.className='sec route-gps-v127';b.textContent='⌖ Usar minha localização';b.onclick=()=>currentPlaceToV127(o);body.appendChild(b)}
if(window.btMinhaOrigem)btMinhaOrigem.onclick=()=>currentPlaceToV127(origem);
function routeWaypointsV127(t){if(Array.isArray(t?.waypoints))return t.waypoints.filter(Boolean);if(activeTrip&&t?.id===activeTrip.id)return (stops||[]).map(x=>x.place_name).filter(Boolean);return []}
abrirMaps=function(t){const o=encodeURIComponent(t?.origin||''),d=encodeURIComponent(t?.destination||''),wp=routeWaypointsV127(t),w=wp.length?'&waypoints='+encodeURIComponent(wp.join('|')):'';window.open('https://www.google.com/maps/dir/?api=1&origin='+o+'&destination='+d+w,'_blank')};
const btPreviewV127=document.getElementById('btPreviewRota');if(btPreviewV127)btPreviewV127.onclick=()=>{if(!destino.value.trim())return msg('Informe o destino',true);abrirMaps({origin:origem.value.trim(),destination:destino.value.trim(),waypoints:preTripStopsV127.map(x=>x.place_name)})};
const btAgendaMapsV127=document.getElementById('btAgendaMaps');if(btAgendaMapsV127)btAgendaMapsV127.onclick=()=>{if(!agDestino.value.trim())return msg('Informe o destino',true);abrirMaps({origin:agOrigem.value.trim(),destination:agDestino.value.trim(),waypoints:(planStopsV124||[]).map(x=>x.place_name)})};
const startTripBaseV127=btViagem.onclick;btViagem.onclick=async()=>{const before=activeTrip?.id||null,planned=[...preTripStopsV127];await startTripBaseV127();if(!activeTrip?.id||activeTrip.id===before||!planned.length)return;const r=await sb.from('km_stops').insert(planned.map((x,i)=>({trip_id:activeTrip.id,stop_order:i+1,place_name:x.place_name,notes:x.notes||null})));if(r.error)return msg('Viagem iniciada, mas não foi possível incluir as paradas planejadas: '+r.error.message,true);preTripStopsV127=[];await refreshActive();renderActive();renderPreTripStopsV127();msg('Deslocamento iniciado com as paradas do percurso')};
function agendaPlannedToDirectV127(){if(!pendingScheduledTripV116)return;const x=pendingScheduledTripV116;if(Array.isArray(x.planned_stops)){preTripStopsV127=x.planned_stops.map(z=>({place_name:z.place_name||'',notes:z.notes||null})).filter(z=>z.place_name);renderPreTripStopsV127()}}
const startAgendaBaseV127=startAgenda;startAgenda=async function(id){await startAgendaBaseV127(id);agendaPlannedToDirectV127()};
function finishV127(){ensureDirectRouteV127();ensureAgendaGpsV127();renderPreTripStopsV127();bindPlaceSuggestionsV125?.()}
const renderBaseV127=render;render=function(){renderBaseV127();setTimeout(finishV127,0)};const loadAgendaBaseV127=loadAgenda;loadAgenda=async function(){await loadAgendaBaseV127();finishV127()};setTimeout(finishV127,1400);
carga();`,'startup');
rep('</style>',`\n/* v127 direct trip route-first UX */\n.route-old-row-v127{display:none!important}.direct-route-v127{margin:12px 0 14px}.route-gps-v127{width:auto!important;min-height:36px!important;margin-top:6px!important;padding:7px 10px!important;font-size:11px!important;background:#eef2f8!important;color:#102451!important;border:1px solid #d8deea!important}.pre-stop-entry-v127{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(0,1fr) auto;gap:7px;align-items:center}.pre-stop-entry-v127 input{min-height:42px!important;padding:9px 10px!important;font-size:14px!important}.pre-stop-entry-v127 button{width:auto!important;min-height:42px!important;padding:8px 11px!important;font-size:11px!important;white-space:nowrap!important}.pre-stop-row-v127{display:grid;grid-template-columns:minmax(0,1fr) 32px;gap:7px;align-items:center;padding:8px 0;border-bottom:1px solid #edf0f5}.pre-stop-row-v127 span{min-width:0}.pre-stop-row-v127 b,.pre-stop-row-v127 small{display:block;overflow-wrap:anywhere}.pre-stop-row-v127 b{font-size:12px}.pre-stop-row-v127 small{font-size:10px;color:#7b8491;margin-top:2px}.pre-stop-row-v127 button{width:32px!important;height:32px!important;min-height:32px!important;padding:0!important}.direct-route-v127 .geo-suggestions-v125{z-index:120}\n@media(max-width:700px){.direct-route-v127{margin:9px 0 12px}.pre-stop-entry-v127{grid-template-columns:1fr}.pre-stop-entry-v127 input{font-size:15px!important;min-height:44px!important}.pre-stop-entry-v127 button{width:100%!important;min-height:38px!important}.route-gps-v127{font-size:10.5px!important;min-height:34px!important}.route-point-v126 input{min-height:46px!important}.route-point-body-v126>small{margin-bottom:4px!important}.direct-route-v127 .route-point-v126{padding-top:9px!important;padding-bottom:9px!important}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v127.0: direct route stops, address UX and Maps waypoints applied');