const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v128 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 127.0','Gestão de deslocamentos · versão 128.0','version');rep('<span class="tag">127.0</span>','<span class="tag">128.0</span>','help');rep("checks.push(['Versão','127.0']);","checks.push(['Versão','128.0']);",'diag');
rep('carga();',`// v128 richer place search: cities, establishments and addresses
function placePartsV128(x){const a=x?.address||{},named=x?.namedetails||{},city=a.city||a.town||a.village||a.municipality||a.city_district||a.county||'',state=a.state||'',road=a.road||a.pedestrian||a.residential||a.neighbourhood||a.suburb||'',num=a.house_number||'',name=x?.name||named.name||a.amenity||a.shop||a.tourism||a.office||a.leisure||a.building||'';return {a,city,state,road,num,name}}
function placeKindV128(x){const t=String(x?.addresstype||x?.type||'').toLowerCase(),c=String(x?.category||x?.class||'').toLowerCase();if(['city','town','village','municipality','hamlet','county','state'].includes(t)||c==='boundary'||c==='place')return 'Cidade / região';if(['amenity','shop','tourism','office','leisure','craft','historic'].includes(c)||['restaurant','cafe','hotel','supermarket','school','hospital','bank','fuel','pharmacy','mall'].includes(t))return 'Estabelecimento';return 'Endereço'}
function placeValueV128(x){const p=placePartsV128(x),kind=placeKindV128(x);if(kind==='Cidade / região')return [p.city||p.name,p.state].filter(Boolean).join(' · ')||x.display_name||'';const distinctName=p.name&&p.name!==p.road&&p.name!==p.city;if(distinctName)return [p.name,p.city,p.state].filter(Boolean).join(' · ');return [p.road+(p.num?', '+p.num:''),p.city,p.state].filter(Boolean).join(' · ')||x.display_name||''}
formatPlaceV125=function(x){return placeValueV128(x)};
searchPlacesV125=async function(el){const q=el.value.trim(),box=ensureGeoBoxV125(el);if(q.length<2){box.classList.add('hide');box.innerHTML='';return}try{geoCtlV125?.abort();geoCtlV125=new AbortController();const u=GEO_BASE_V125+'/search?format=jsonv2&addressdetails=1&namedetails=1&extratags=1&dedupe=1&limit=10&countrycodes=br&q='+encodeURIComponent(q);const r=await fetch(u,{signal:geoCtlV125.signal,headers:{'Accept-Language':'pt-BR'}});if(!r.ok)throw Error('geo');const raw=await r.json(),seen=new Set(),d=raw.filter(x=>{const k=placeValueV128(x).toLowerCase();if(!k||seen.has(k))return false;seen.add(k);return true});box.innerHTML=d.map((x,i)=>'<button type="button" class="geo-option-v125 geo-option-v128" data-geo-i="'+i+'"><div class="geo-head-v128"><b>'+esc(placeValueV128(x))+'</b><em>'+esc(placeKindV128(x))+'</em></div><span>'+esc(x.display_name||'')+'</span></button>').join('')||'<div class="geo-empty-v125">Nenhuma cidade, estabelecimento ou endereço encontrado.</div>';box.classList.remove('hide');box.querySelectorAll('[data-geo-i]').forEach(b=>b.onclick=()=>{const x=d[+b.dataset.geoI];el.value=placeValueV128(x);el.dataset.lat=x.lat;el.dataset.lon=x.lon;el.dataset.placeKind=placeKindV128(x);box.classList.add('hide');el.dispatchEvent(new Event('input',{bubbles:true}))})}catch(e){if(e.name!=='AbortError'){box.innerHTML='<div class="geo-empty-v125">Não foi possível consultar locais agora.</div>';box.classList.remove('hide')}}};
function enrichPlaceInputsV128(){['origem','destino','agOrigem','agDestino','rotaOrigem','rotaDestino','stopNameV124','paradaNome','preTripStopNameV127'].forEach(id=>{const el=document.getElementById(id);if(el)el.placeholder='Cidade, estabelecimento ou endereço'})}
function finishV128(){enrichPlaceInputsV128();bindPlaceSuggestionsV125?.()}
const renderBaseV128=render;render=function(){renderBaseV128();setTimeout(finishV128,0)};const loadAgendaBaseV128=loadAgenda;loadAgenda=async function(){await loadAgendaBaseV128();finishV128()};setTimeout(finishV128,1450);
carga();`,'startup');
rep('</style>',`\n/* v128 richer place search */\n.geo-head-v128{display:flex;align-items:flex-start;justify-content:space-between;gap:8px}.geo-head-v128 b{flex:1;min-width:0}.geo-head-v128 em{flex:0 0 auto;font-style:normal;font-size:9px;font-weight:900;letter-spacing:.3px;color:#244b8d;background:#eef3fb;border-radius:999px;padding:4px 7px;white-space:nowrap}.geo-option-v128 span{line-height:1.35}.geo-suggestions-v125{max-height:340px}\n@media(max-width:700px){.geo-option-v128{padding:10px 11px!important}.geo-head-v128{gap:6px}.geo-head-v128 b{font-size:12.5px!important}.geo-head-v128 em{font-size:8px;padding:3px 6px}.geo-option-v128 span{font-size:10px!important}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v128.0: city, establishment and address search restored');