const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v130 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 129.0','Gestão de deslocamentos · versão 130.0','version');rep('<span class="tag">129.0</span>','<span class="tag">130.0</span>','help');rep("checks.push(['Versão','129.0']);","checks.push(['Versão','130.0']);",'diag');
rep('carga();',`// v130 Google Places official search, server-side key
const searchPlacesFallbackV130=searchPlacesV125;
let googlePlacesConfiguredV130=null;
function googlePlaceLabelV130(p){return p?.text||[p?.mainText,p?.secondaryText].filter(Boolean).join(', ')}
function googlePlaceKindV130(p){const t=(p?.types||[]).map(x=>String(x).toLowerCase());if(t.some(x=>['locality','administrative_area_level_1','administrative_area_level_2','country'].includes(x)))return 'Cidade / região';if(t.some(x=>['establishment','point_of_interest','store','premise'].includes(x)))return 'Estabelecimento';return 'Endereço'}
function renderGooglePlacesV130(el,box,items,q){box.innerHTML=items.map((p,i)=>'<button type="button" class="geo-option-v125 geo-option-v128 google-place-v130" data-google-place-v130="'+i+'"><div class="geo-head-v128"><b>'+esc(p.mainText||p.text||'Local')+'</b><em>'+esc(googlePlaceKindV130(p))+'</em></div><span>'+esc(p.secondaryText||p.text||'')+'</span></button>').join('')+'<div class="google-attrib-v130">Resultados fornecidos pelo Google</div>';box.classList.remove('hide');box.querySelectorAll('[data-google-place-v130]').forEach(b=>b.onclick=()=>{const p=items[+b.dataset.googlePlaceV130];el.value=googlePlaceLabelV130(p);el.dataset.placeId=p.placeId||'';el.dataset.placeKind=googlePlaceKindV130(p);box.classList.add('hide');el.dispatchEvent(new Event('input',{bubbles:true}))})}
searchPlacesV125=async function(el){const q=el.value.trim(),box=ensureGeoBoxV125(el);if(q.length<2){box.classList.add('hide');box.innerHTML='';return}try{geoCtlV125?.abort();geoCtlV125=new AbortController();const r=await fetch('/api/places?q='+encodeURIComponent(q),{signal:geoCtlV125.signal,headers:{Accept:'application/json'}});const j=await r.json().catch(()=>({}));googlePlacesConfiguredV130=j.configured!==false;if(r.ok&&Array.isArray(j.items)&&j.items.length){renderGooglePlacesV130(el,box,j.items,q);return}if(j.configured===false){googlePlacesConfiguredV130=false;return await searchPlacesFallbackV130(el)}if(r.ok&&Array.isArray(j.items)&&!j.items.length){box.innerHTML='<div class="geo-empty-v125">Nenhum resultado encontrado no Google para esta busca.</div><button type="button" class="google-search-v129" data-google-search-v129>Pesquisar “'+esc(q)+'” no Google Maps</button>';box.classList.remove('hide');box.querySelector('[data-google-search-v129]')?.addEventListener('click',()=>googleMapsSearchV129(q));return}throw Error(j.error||'places')}catch(e){if(e.name==='AbortError')return;googlePlacesConfiguredV130=googlePlacesConfiguredV130===false?false:null;return await searchPlacesFallbackV130(el)}};
async function refreshGoogleStatusV130(){try{const r=await fetch('/api/places?q=teste',{headers:{Accept:'application/json'}}),j=await r.json();googlePlacesConfiguredV130=!!j.configured}catch{googlePlacesConfiguredV130=null}const box=document.getElementById('googleStatusV119');if(!box)return;const row=[...box.querySelectorAll('.integration-row-v119')].find(x=>x.textContent.includes('Google Maps'));if(!row)return;const tag=row.querySelector('.tag'),p=row.querySelector('p');if(googlePlacesConfiguredV130===true){if(tag){tag.textContent='Ativo';tag.classList.remove('warn')}if(p)p.textContent='Google Places oficial ativo para nomes de empresas, cidades e endereços. Rotas continuam abrindo no Google Maps.'}else if(googlePlacesConfiguredV130===false){if(tag){tag.textContent='Aguardando chave';tag.classList.add('warn')}if(p)p.textContent='Integração pronta no app. Falta configurar GOOGLE_MAPS_API_KEY na Vercel para ativar o Google Places oficial.'}}
const renderBaseV130=render;render=function(){renderBaseV130();setTimeout(refreshGoogleStatusV130,50)};setTimeout(refreshGoogleStatusV130,1600);
carga();`,'startup');
rep('</style>',`\n/* v130 official Google Places */\n.google-attrib-v130{padding:8px 12px;text-align:right;font-size:10px;font-weight:700;color:#6d7684;background:#fff;border-top:1px solid #edf0f5}.google-place-v130 b{font-weight:800}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v130.0: Google Places official proxy ready');