const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v131 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 130.0','Gestão de deslocamentos · versão 131.0','version');rep('<span class="tag">130.0</span>','<span class="tag">131.0</span>','help');rep("checks.push(['Versão','130.0']);","checks.push(['Versão','131.0']);",'diag');
rep('carga();',`// v131 close suggestions after selection + intelligent route planning
renderGooglePlacesV130=function(el,box,items,q){box.innerHTML=items.map((p,i)=>'<button type="button" class="geo-option-v125 geo-option-v128 google-place-v130" data-google-place-v131="'+i+'"><div class="geo-head-v128"><b>'+esc(p.mainText||p.text||'Local')+'</b><em>'+esc(googlePlaceKindV130(p))+'</em></div><span>'+esc(p.secondaryText||p.text||'')+'</span></button>').join('')+'<div class="google-attrib-v130">Resultados fornecidos pelo Google</div>';box.classList.remove('hide');box.querySelectorAll('[data-google-place-v131]').forEach(b=>b.onclick=()=>{const p=items[+b.dataset.googlePlaceV131];el.value=googlePlaceLabelV130(p);el.dataset.placeId=p.placeId||'';el.dataset.placeKind=googlePlaceKindV130(p);box.classList.add('hide');box.innerHTML='';el.dispatchEvent(new Event('change',{bubbles:true}))})};
function fmtKmV131(m){return (Number(m||0)/1000).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})+' km'}
function fmtDurV131(v){const sec=Number(String(v||'0').replace('s',''))||0,min=Math.round(sec/60),h=Math.floor(min/60),m=min%60;return h?(h+'h '+String(m).padStart(2,'0')+'min'):(m+' min')}
function routeTitleV131(x,i){return i===0?'Rota recomendada':'Alternativa '+i}
function routeViaV131(x){const txt=(x.instructions||[]).filter(Boolean).slice(0,14).join(' · '),roads=[...txt.matchAll(/(?:BR|SC|PR|RS|SP|RJ|MG|BA|GO|ES|PE|CE|MT|MS|DF)[- ]?\\d{2,3}|[A-Z]{2,}[- ]\\d{2,3}/g)].map(m=>m[0]),uniq=[...new Set(roads)].slice(0,3);return uniq.length?'Via '+uniq.join(' / '):''}
function openRouteMapV131(){const o=document.getElementById('origem')?.value.trim(),d=document.getElementById('destino')?.value.trim(),wp=(preTripStopsV127||[]).map(x=>x.place_name).filter(Boolean);if(!d)return;abrirMaps({origin:o,destination:d,waypoints:wp})}
function renderRoutePlansV131(items){const box=document.getElementById('routePlanResultsV131');if(!box)return;box.innerHTML=(items||[]).map((x,i)=>{const toll=x.hasTolls?(x.tollTotalBRL>0?('Pedágios estimados: '+moeda(x.tollTotalBRL)):'Há pedágio no trajeto; valor não informado pelo Google'):'Sem pedágio identificado';const ferry=x.hasFerry?' · Balsa/ferry no trajeto':'';return '<button type="button" class="route-choice-v131 '+(i===0?'selected':'')+'" data-route-choice-v131="'+i+'"><div class="route-choice-head-v131"><b>'+esc(routeTitleV131(x,i))+'</b><span>'+esc(fmtDurV131(x.duration))+'</span></div><div class="route-choice-metrics-v131"><strong>'+esc(fmtKmV131(x.distanceMeters))+'</strong><span>'+esc(toll+ferry)+'</span></div>'+(routeViaV131(x)?'<small>'+esc(routeViaV131(x))+'</small>':'')+'</button>'}).join('')+'<button type="button" class="sec route-real-map-v131" id="routeRealMapV131">🗺️ Abrir mapa real da rota</button>';box.classList.remove('hide');box.querySelectorAll('[data-route-choice-v131]').forEach(b=>b.onclick=()=>{box.querySelectorAll('[data-route-choice-v131]').forEach(z=>z.classList.remove('selected'));b.classList.add('selected');localStorage.setItem('km_selected_route_v131',b.dataset.routeChoiceV131)});document.getElementById('routeRealMapV131').onclick=openRouteMapV131}
async function planRouteV131(){const o=document.getElementById('origem')?.value.trim(),d=document.getElementById('destino')?.value.trim(),btn=document.getElementById('routePlanBtnV131'),box=document.getElementById('routePlanResultsV131');if(!d)return msg('Informe o destino',true);if(btn){btn.disabled=true;btn.textContent='Calculando rotas...'}if(box){box.classList.remove('hide');box.innerHTML='<div class="route-loading-v131">Calculando alternativas, pedágios e possíveis balsas...</div>'}try{const r=await fetch('/api/routes',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({origin:o,destination:d,stops:(preTripStopsV127||[]).map(x=>x.place_name)})}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Não foi possível calcular a rota');if(!j.items?.length)throw Error('Nenhuma rota encontrada');renderRoutePlansV131(j.items);msg('Rotas calculadas pelo Google')}catch(e){if(box)box.innerHTML='<div class="route-error-v131"><b>Planejamento de rota indisponível</b><span>'+esc(e.message||'Erro ao calcular rota')+'</span></div>';msg(e.message||'Erro ao calcular rota',true)}finally{if(btn){btn.disabled=false;btn.textContent='🧭 Planejar rota e custos'}}}
function ensureRoutePlannerV131(){const stack=document.getElementById('directRouteStackV127');if(!stack||document.getElementById('routePlannerV131'))return;const p=document.createElement('div');p.id='routePlannerV131';p.className='route-planner-v131';p.innerHTML='<button type="button" id="routePlanBtnV131" class="pri">🧭 Planejar rota e custos</button><div id="routePlanResultsV131" class="route-plan-results-v131 hide"></div>';stack.insertAdjacentElement('afterend',p);document.getElementById('routePlanBtnV131').onclick=planRouteV131}
function finishV131(){ensureRoutePlannerV131()}
const renderBaseV131=render;render=function(){renderBaseV131();setTimeout(finishV131,0)};setTimeout(finishV131,1700);
carga();`,'startup');
rep('</style>',`\n/* v131 route planning */\n.route-planner-v131{margin:8px 0 14px}.route-planner-v131>.pri{width:100%!important;min-height:44px!important}.route-plan-results-v131{margin-top:8px;display:grid;gap:7px}.route-plan-results-v131.hide{display:none!important}.route-choice-v131{display:block!important;width:100%!important;text-align:left!important;background:#fff!important;color:#17213a!important;border:1px solid #dfe5ee!important;border-radius:12px!important;padding:11px 12px!important}.route-choice-v131.selected{border:2px solid #163b78!important;background:#f5f8fd!important}.route-choice-head-v131,.route-choice-metrics-v131{display:flex;justify-content:space-between;gap:10px;align-items:center}.route-choice-head-v131 b{font-size:13px}.route-choice-head-v131 span,.route-choice-metrics-v131 span{font-size:11px;color:#667085}.route-choice-metrics-v131{margin-top:5px}.route-choice-metrics-v131 strong{font-size:12px}.route-choice-v131 small{display:block;margin-top:5px;color:#667085;font-size:10px}.route-real-map-v131{width:100%!important;min-height:40px!important}.route-loading-v131,.route-error-v131{padding:12px;border:1px solid #e1e6ef;border-radius:12px;background:#f8fafc;font-size:12px}.route-error-v131 b,.route-error-v131 span{display:block}.route-error-v131 span{margin-top:4px;color:#667085}\n@media(max-width:700px){.route-planner-v131>.pri{font-size:12px!important}.route-choice-v131{padding:10px!important}.route-choice-head-v131 b{font-size:12px}.route-choice-head-v131 span,.route-choice-metrics-v131 span{font-size:10.5px}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v131.0: route planner and closed Google suggestions');