const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v132 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 131.0','Gestão de deslocamentos · versão 132.0','version');rep('<span class="tag">131.0</span>','<span class="tag">132.0</span>','help');rep("checks.push(['Versão','131.0']);","checks.push(['Versão','132.0']);",'diag');
rep('carga();',`// v132 round-trip planning and cleaner selected-location UX
function isRoundTripV132(){return !!document.getElementById('routeRoundTripV132')?.checked}
function roundTripLabelV132(){return isRoundTripV132()?'Ida e volta · retorno ao local de partida':'Somente ida'}
function clearGeoSuggestionsV132(el){const box=el?.parentElement?.querySelector('.geo-suggestions-v125')||el?.closest('.route-point-body-v126')?.querySelector('.geo-suggestions-v125');if(box){box.classList.add('hide');box.innerHTML=''}}
['origem','destino','agOrigem','agDestino','rotaOrigem','rotaDestino','stopNameV124','paradaNome','preTripStopNameV127'].forEach(id=>{const el=document.getElementById(id);if(!el||el.dataset.clearGeoV132)return;el.dataset.clearGeoV132='1';el.addEventListener('change',()=>clearGeoSuggestionsV132(el));el.addEventListener('blur',()=>setTimeout(()=>{if(el.dataset.placeId||el.dataset.lat)clearGeoSuggestionsV132(el)},120))});
openRouteMapV131=function(){const o=document.getElementById('origem')?.value.trim(),d=document.getElementById('destino')?.value.trim(),stops=(preTripStopsV127||[]).map(x=>x.place_name).filter(Boolean);if(!d)return;if(isRoundTripV132())abrirMaps({origin:o,destination:o,waypoints:[...stops,d]});else abrirMaps({origin:o,destination:d,waypoints:stops})};
renderRoutePlansV131=function(items){const box=document.getElementById('routePlanResultsV131');if(!box)return;const rt=isRoundTripV132();box.innerHTML='<div class="route-mode-v132"><b>'+esc(rt?'↩ Ida e volta':'→ Somente ida')+'</b><span>'+esc(rt?'O cálculo inclui o retorno ao ponto de partida.':'O cálculo termina no destino informado.')+'</span></div>'+(items||[]).map((x,i)=>{const toll=x.hasTolls?(x.tollTotalBRL>0?('Pedágios estimados: '+moeda(x.tollTotalBRL)):'Há pedágio no trajeto; valor não informado pelo Google'):'Sem pedágio identificado';const ferry=x.hasFerry?' · Balsa/ferry no trajeto':'';const title=rt?(i===0?'Rota ida e volta':'Alternativa '+i):routeTitleV131(x,i);return '<button type="button" class="route-choice-v131 '+(i===0?'selected':'')+'" data-route-choice-v131="'+i+'"><div class="route-choice-head-v131"><b>'+esc(title)+'</b><span>'+esc(fmtDurV131(x.duration))+'</span></div><div class="route-choice-metrics-v131"><strong>'+esc(fmtKmV131(x.distanceMeters))+'</strong><span>'+esc(toll+ferry)+'</span></div>'+(routeViaV131(x)?'<small>'+esc(routeViaV131(x))+'</small>':'')+'</button>'}).join('')+'<button type="button" class="sec route-real-map-v131" id="routeRealMapV131">🗺️ Abrir mapa real da rota</button>';box.classList.remove('hide');box.querySelectorAll('[data-route-choice-v131]').forEach(b=>b.onclick=()=>{box.querySelectorAll('[data-route-choice-v131]').forEach(z=>z.classList.remove('selected'));b.classList.add('selected');localStorage.setItem('km_selected_route_v131',b.dataset.routeChoiceV131)});document.getElementById('routeRealMapV131').onclick=openRouteMapV131};
planRouteV131=async function(){const o=document.getElementById('origem')?.value.trim(),d=document.getElementById('destino')?.value.trim(),btn=document.getElementById('routePlanBtnV131'),box=document.getElementById('routePlanResultsV131');if(!o)return msg('Informe a origem',true);if(!d)return msg('Informe o destino',true);const roundTrip=isRoundTripV132(),baseStops=(preTripStopsV127||[]).map(x=>x.place_name).filter(Boolean),apiDestination=roundTrip?o:d,apiStops=roundTrip?[...baseStops,d]:baseStops;if(btn){btn.disabled=true;btn.textContent='Calculando rotas...'}if(box){box.classList.remove('hide');box.innerHTML='<div class="route-loading-v131">Calculando '+(roundTrip?'ida, volta, ':'')+'distância, tempo, pedágios e possíveis balsas...</div>'}try{const r=await fetch('/api/routes',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({origin:o,destination:apiDestination,stops:apiStops,roundTrip})}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Não foi possível calcular a rota');if(!j.items?.length)throw Error('Nenhuma rota encontrada');localStorage.setItem('km_round_trip_v132',roundTrip?'1':'0');renderRoutePlansV131(j.items);msg(roundTrip?'Rota de ida e volta calculada pelo Google':'Rotas calculadas pelo Google')}catch(e){if(box)box.innerHTML='<div class="route-error-v131"><b>Planejamento de rota indisponível</b><span>'+esc(e.message||'Erro ao calcular rota')+'</span></div>';msg(e.message||'Erro ao calcular rota',true)}finally{if(btn){btn.disabled=false;btn.textContent='🧭 Planejar rota e custos'}}};
function ensureRoundTripV132(){const p=document.getElementById('routePlannerV131');if(!p||document.getElementById('routeRoundTripRowV132'))return;const row=document.createElement('label');row.id='routeRoundTripRowV132';row.className='round-trip-row-v132';row.innerHTML='<span><b>↩ Voltar ao local de partida</b><small>Marque quando o deslocamento for ida e volta.</small></span><input id="routeRoundTripV132" type="checkbox" aria-label="Voltar ao local de partida">';p.insertBefore(row,p.firstChild);const cb=document.getElementById('routeRoundTripV132');cb.checked=localStorage.getItem('km_round_trip_v132')==='1';cb.onchange=()=>{localStorage.setItem('km_round_trip_v132',cb.checked?'1':'0');const box=document.getElementById('routePlanResultsV131');if(box&&!box.classList.contains('hide')){box.classList.add('hide');box.innerHTML=''}msg(cb.checked?'Ida e volta ativada: o retorno à origem será incluído no cálculo':'Somente ida selecionada')}}
function finishV132(){ensureRoundTripV132();['origem','destino','agOrigem','agDestino','rotaOrigem','rotaDestino','stopNameV124','paradaNome','preTripStopNameV127'].forEach(id=>{const el=document.getElementById(id);if(!el||el.dataset.clearGeoV132)return;el.dataset.clearGeoV132='1';el.addEventListener('change',()=>clearGeoSuggestionsV132(el));el.addEventListener('blur',()=>setTimeout(()=>{if(el.dataset.placeId||el.dataset.lat)clearGeoSuggestionsV132(el)},120))})}
const renderBaseV132=render;render=function(){renderBaseV132();setTimeout(finishV132,0)};setTimeout(finishV132,1700);
carga();`,'startup');
rep('</style>',`\n/* v132 ida e volta */\n.round-trip-row-v132{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 12px;margin:0 0 8px;border:1px solid #dfe5ee;border-radius:12px;background:#f8fafc;cursor:pointer}.round-trip-row-v132 span{min-width:0}.round-trip-row-v132 b,.round-trip-row-v132 small{display:block}.round-trip-row-v132 b{font-size:12px;color:#17213a}.round-trip-row-v132 small{font-size:10px;color:#667085;margin-top:2px}.round-trip-row-v132 input{width:22px!important;height:22px!important;min-width:22px!important;accent-color:#163b78}.route-mode-v132{padding:9px 11px;border-radius:10px;background:#eef4ff;border:1px solid #d8e4f8}.route-mode-v132 b,.route-mode-v132 span{display:block}.route-mode-v132 b{font-size:11px;color:#163b78}.route-mode-v132 span{font-size:10px;color:#667085;margin-top:2px}\n@media(max-width:700px){.round-trip-row-v132{padding:10px}.round-trip-row-v132 b{font-size:11.5px}.round-trip-row-v132 small{font-size:9.5px}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v132.0: round-trip route planning ready');
// deployment touch v132
