const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v133 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 132.0','Gestão de deslocamentos · versão 133.0','version');rep('<span class="tag">132.0</span>','<span class="tag">133.0</span>','help');rep("checks.push(['Versão','132.0']);","checks.push(['Versão','133.0']);",'diag');
rep('carga();',`// v133 embedded route map using the real Google Routes polyline
let routeItemsV133=[];let routeMapV133=null;let routeLayerV133=null;let leafletPromiseV133=null;
function loadLeafletV133(){if(window.L)return Promise.resolve(window.L);if(leafletPromiseV133)return leafletPromiseV133;leafletPromiseV133=new Promise((resolve,reject)=>{if(!document.getElementById('leafletCssV133')){const l=document.createElement('link');l.id='leafletCssV133';l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';l.integrity='sha256-p4NxAoJBhIINfQ3ynsRYPQy5ZLZB2Q+MXJv4cW8mY4=';l.crossOrigin='';document.head.appendChild(l)}const existing=document.getElementById('leafletJsV133');if(existing){existing.addEventListener('load',()=>resolve(window.L),{once:true});existing.addEventListener('error',reject,{once:true});return}const j=document.createElement('script');j.id='leafletJsV133';j.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';j.integrity='sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=';j.crossOrigin='';j.onload=()=>resolve(window.L);j.onerror=()=>reject(new Error('Não foi possível carregar o mapa'));document.head.appendChild(j)});return leafletPromiseV133}
function decodePolylineV133(str){let index=0,lat=0,lng=0,out=[];while(index<str.length){let b,shift=0,result=0;do{b=str.charCodeAt(index++)-63;result|=(b&31)<<shift;shift+=5}while(b>=32);lat+=(result&1)?~(result>>1):(result>>1);shift=0;result=0;do{b=str.charCodeAt(index++)-63;result|=(b&31)<<shift;shift+=5}while(b>=32);lng+=(result&1)?~(result>>1):(result>>1);out.push([lat/1e5,lng/1e5])}return out}
async function renderEmbeddedMapV133(item,index=0){const box=document.getElementById('routeEmbeddedMapV133'),status=document.getElementById('routeMapStatusV133');if(!box)return;if(!item?.polyline){box.innerHTML='<div class="route-map-empty-v133">O Google não retornou o desenho desta rota.</div>';return}if(status)status.textContent='Carregando mapa da rota...';try{const L=await loadLeafletV133(),pts=decodePolylineV133(item.polyline);if(!pts.length)throw Error('Percurso sem coordenadas');if(routeMapV133){routeMapV133.remove();routeMapV133=null;routeLayerV133=null}box.innerHTML='';routeMapV133=L.map(box,{zoomControl:true,attributionControl:true});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(routeMapV133);routeLayerV133=L.polyline(pts,{weight:6,opacity:.85}).addTo(routeMapV133);L.marker(pts[0]).addTo(routeMapV133).bindTooltip('Origem');L.marker(pts[pts.length-1]).addTo(routeMapV133).bindTooltip(isRoundTripV132()?'Retorno à origem':'Destino');routeMapV133.fitBounds(routeLayerV133.getBounds(),{padding:[18,18]});setTimeout(()=>routeMapV133?.invalidateSize(),120);if(status)status.textContent=(index===0?'Rota recomendada':'Alternativa '+index)+' · '+fmtKmV131(item.distanceMeters)+' · '+fmtDurV131(item.duration)}catch(e){box.innerHTML='<div class="route-map-empty-v133">Não foi possível carregar o mapa agora. O cálculo da rota continua disponível.</div>';if(status)status.textContent=e.message||'Mapa indisponível'}}
function injectEmbeddedMapV133(items){const results=document.getElementById('routePlanResultsV131');if(!results)return;routeItemsV133=items||[];let wrap=document.getElementById('routeMapWrapV133');if(!wrap){wrap=document.createElement('div');wrap.id='routeMapWrapV133';wrap.className='route-map-wrap-v133';wrap.innerHTML='<div class="route-map-head-v133"><b>Mapa do percurso</b><span id="routeMapStatusV133">Rota calculada pelo Google</span></div><div id="routeEmbeddedMapV133" class="route-embedded-map-v133"></div>';const open=document.getElementById('routeRealMapV131');if(open)results.insertBefore(wrap,open);else results.appendChild(wrap)}results.querySelectorAll('[data-route-choice-v131]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.routeChoiceV131||0);renderEmbeddedMapV133(routeItemsV133[i],i)}));if(routeItemsV133[0])setTimeout(()=>renderEmbeddedMapV133(routeItemsV133[0],0),30)}
const renderRoutePlansBaseV133=renderRoutePlansV131;renderRoutePlansV131=function(items){renderRoutePlansBaseV133(items);injectEmbeddedMapV133(items)};
function destroyRouteMapIfHiddenV133(){const p=document.getElementById('routePlanResultsV131');if(p?.classList.contains('hide')&&routeMapV133){routeMapV133.remove();routeMapV133=null;routeLayerV133=null}}
const roundTripFinishBaseV133=finishV132;finishV132=function(){roundTripFinishBaseV133();const cb=document.getElementById('routeRoundTripV132');if(cb&&!cb.dataset.mapResetV133){cb.dataset.mapResetV133='1';cb.addEventListener('change',()=>{destroyRouteMapIfHiddenV133();routeItemsV133=[]})}}
setTimeout(()=>{finishV132();},1800);
carga();`,'startup');
rep('</style>',`\n/* v133 mapa embutido do percurso */\n.route-map-wrap-v133{margin-top:9px;border:1px solid #dfe5ee;border-radius:14px;overflow:hidden;background:#fff}.route-map-head-v133{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:10px 12px;background:#f8fafc;border-bottom:1px solid #e5e9f0}.route-map-head-v133 b{font-size:12px;color:#17213a}.route-map-head-v133 span{font-size:10px;color:#667085;text-align:right}.route-embedded-map-v133{height:320px;width:100%;background:#eef2f7}.route-map-empty-v133{height:100%;display:grid;place-items:center;padding:20px;text-align:center;color:#667085;font-size:12px}.route-embedded-map-v133 .leaflet-control-attribution{font-size:8px}.route-embedded-map-v133 .leaflet-control-zoom a{font-size:18px!important;line-height:30px!important;min-height:30px!important}\n@media(max-width:700px){.route-embedded-map-v133{height:270px}.route-map-head-v133{align-items:flex-start;flex-direction:column;gap:3px}.route-map-head-v133 span{text-align:left}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v133.0: embedded route map ready');