const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v134 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 133.0','Gestão de deslocamentos · versão 134.0','version');rep('<span class="tag">133.0</span>','<span class="tag">134.0</span>','help');rep("checks.push(['Versão','133.0']);","checks.push(['Versão','134.0']);",'diag');
rep('carga();',`// v134 persist selected route toll as an actual trip expense
let selectedRouteV134=null;
function selectedRouteIndexV134(){const n=Number(localStorage.getItem('km_selected_route_v131')||0);return Number.isFinite(n)&&n>=0?n:0}
function syncSelectedRouteV134(){const i=selectedRouteIndexV134();selectedRouteV134=(routeItemsV133||[])[i]||(routeItemsV133||[])[0]||null;return selectedRouteV134}
function selectedTollV134(){const x=syncSelectedRouteV134(),v=Number(x?.tollTotalBRL||0);return Number.isFinite(v)&&v>0?v:0}
function tollSummaryV134(){const x=syncSelectedRouteV134();if(!x?.hasTolls)return 'Sem pedágio identificado nesta rota.';const v=selectedTollV134();return v>0?('Pedágio estimado que será lançado na viagem: '+moeda(v)):'Há pedágio no trajeto, mas o Google não informou valor; não será criado lançamento automático.'}
function ensureTollNoticeV134(){const p=document.getElementById('routePlannerV131');if(!p)return;let n=document.getElementById('routeTollNoticeV134');if(!n){n=document.createElement('div');n.id='routeTollNoticeV134';n.className='route-toll-notice-v134';p.appendChild(n)}n.textContent=(routeItemsV133||[]).length?tollSummaryV134():'Quando o Google informar o valor do pedágio, ele será incluído automaticamente nas despesas ao iniciar a viagem.'}
const renderRoutePlansBaseV134=renderRoutePlansV131;renderRoutePlansV131=function(items){renderRoutePlansBaseV134(items);routeItemsV133=items||[];selectedRouteV134=(items||[])[0]||null;localStorage.setItem('km_selected_route_v131','0');document.querySelectorAll('[data-route-choice-v131]').forEach(b=>b.addEventListener('click',()=>{selectedRouteV134=(items||[])[Number(b.dataset.routeChoiceV131||0)]||null;ensureTollNoticeV134()}));ensureTollNoticeV134()};
async function persistRouteTollV134(tripId,toll){if(!tripId||!(toll>0))return {saved:false};const existing=await sb.from('km_expenses').select('id,amount,description').eq('trip_id',tripId).eq('expense_type','toll');if(existing.error)return {saved:false,error:existing.error};const duplicate=(existing.data||[]).some(x=>Math.abs(Number(x.amount||0)-toll)<0.01&&String(x.description||'').includes('Google Routes'));if(duplicate)return {saved:false,duplicate:true};const r=await sb.from('km_expenses').insert({trip_id:tripId,expense_type:'toll',description:'Pedágio estimado automaticamente pelo Google Routes',amount:toll});return {saved:!r.error,error:r.error||null}}
const startTripBaseV134=btViagem.onclick;btViagem.onclick=async()=>{const before=activeTrip?.id||null,toll=selectedTollV134(),hadPricedToll=toll>0;await startTripBaseV134();if(!activeTrip?.id||activeTrip.id===before)return;const tripId=activeTrip.id;if(hadPricedToll){const r=await persistRouteTollV134(tripId,toll);if(r.error){msg('Viagem iniciada, mas o pedágio estimado não pôde ser lançado: '+r.error.message,true)}else if(r.saved){await refreshActive();renderActive();msg('Viagem iniciada com pedágio estimado de '+moeda(toll)+' lançado nas despesas')}}};
function finishV134(){ensureRoundTripV132();ensureTollNoticeV134()}
const renderBaseV134=render;render=function(){renderBaseV134();setTimeout(finishV134,0)};setTimeout(finishV134,1900);
carga();`,'startup');
rep('</style>',`\n/* v134 pedágio automático */\n.route-toll-notice-v134{margin-top:8px;padding:9px 11px;border:1px solid #dfe5ee;border-radius:10px;background:#f8fafc;color:#536070;font-size:10px;line-height:1.4}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v134.0: automatic toll expense ready');