const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v135 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 134.0','Gestão de deslocamentos · versão 135.0','version');rep('<span class="tag">134.0</span>','<span class="tag">135.0</span>','help');rep("checks.push(['Versão','134.0']);","checks.push(['Versão','135.0']);",'diag');
rep("const typeName=t=>({toll:'Pedágio',fuel:'Combustível',parking:'Estacionamento',meal:'Alimentação',lodging:'Hospedagem',other:'Outros'}[t]||t);","const typeName=t=>({toll:'Pedágio',fuel:'Combustível',parking:'Estacionamento',meal:'Alimentação',lodging:'Hospedagem',maintenance:'Manutenção / conserto',other:'Outros'}[t]||t);",'expense labels');
rep('carga();',`// v135 complete expense capture inside the active trip, with optional receipt/file
function expenseIconV135(t){return ({toll:'🛣️',fuel:'⛽',parking:'🅿️',meal:'🍽️',lodging:'🏨',maintenance:'🔧',other:'🧾'}[t]||'🧾')}
function ensureExpenseUiV135(){
  const sel=document.getElementById('tipoDesp'),desc=document.getElementById('descDesp'),btn=document.getElementById('btDesp');if(!sel||!desc||!btn)return;
  if(!sel.querySelector('option[value="maintenance"]')){const o=document.createElement('option');o.value='maintenance';o.textContent='Manutenção / conserto';const other=sel.querySelector('option[value="other"]');sel.insertBefore(o,other||null)}
  if(!document.getElementById('expenseQuickV135')){const q=document.createElement('div');q.id='expenseQuickV135';q.className='expense-quick-v135';q.innerHTML=[['fuel','⛽ Combustível'],['toll','🛣️ Pedágio'],['parking','🅿️ Estacionamento'],['meal','🍽️ Alimentação'],['lodging','🏨 Hospedagem'],['maintenance','🔧 Manutenção'],['other','🧾 Outros']].map(x=>'<button type="button" class="sec" data-expense-quick-v135="'+x[0]+'">'+x[1]+'</button>').join('');sel.closest('.r')?.before(q);q.querySelectorAll('[data-expense-quick-v135]').forEach(b=>b.onclick=()=>{sel.value=b.dataset.expenseQuickV135;q.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));document.getElementById('valorDesp')?.focus()})}
  if(!document.getElementById('expenseExtraV135')){const x=document.createElement('div');x.id='expenseExtraV135';x.className='expense-extra-v135';x.innerHTML='<input id="expenseDateV135" type="date" aria-label="Data da despesa"><label class="expense-file-v135"><span>📎 Comprovante ou arquivo <small>opcional · foto, imagem ou PDF até 10 MB</small></span><input id="expenseFileV135" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"></label><div id="expenseFileNameV135" class="muted small"></div>';desc.insertAdjacentElement('afterend',x);const d=document.getElementById('expenseDateV135');if(d&&!d.value)d.value=new Date().toISOString().slice(0,10);const f=document.getElementById('expenseFileV135'),n=document.getElementById('expenseFileNameV135');f.onchange=()=>{n.textContent=f.files?.[0]?('Selecionado: '+f.files[0].name):''}}
  btn.textContent='＋ Adicionar despesa';
}
async function uploadExpenseReceiptV135(expenseId,file){if(!activeTrip||!expenseId||!file)return {saved:false};if(file.size>10*1024*1024)return {saved:false,error:new Error('Arquivo maior que 10 MB')};const ok=['image/jpeg','image/png','image/webp','application/pdf'];if(file.type&&!ok.includes(file.type))return {saved:false,error:new Error('Formato de arquivo não permitido')};const ext=(file.name.split('.').pop()||'bin').toLowerCase(),path=ses.user.id+'/'+activeTrip.id+'/'+crypto.randomUUID()+'.'+ext;let r=await sb.storage.from('km-receipts').upload(path,file,{upsert:false,contentType:file.type||undefined});if(r.error)return {saved:false,error:r.error};r=await sb.from('km_attachments').insert({trip_id:activeTrip.id,expense_id:expenseId,storage_path:path,file_name:file.name,mime_type:file.type||null,file_size:file.size,uploaded_by:ses.user.id});if(r.error){await sb.storage.from('km-receipts').remove([path]);return {saved:false,error:r.error}}return {saved:true}}
async function addExpenseV135(){
  if(!activeTrip)return msg('Nenhum deslocamento em andamento',true);const val=Number(valorDesp.value);if(!(val>0))return msg('Informe um valor válido',true);const similar=expenses.find(e=>e.expense_type===tipoDesp.value&&Math.abs(Number(e.amount)-val)<0.001);if(similar&&!confirm('Já existe uma despesa deste tipo com o mesmo valor nesta viagem. Deseja adicionar mesmo assim?'))return;
  const file=document.getElementById('expenseFileV135')?.files?.[0]||null,date=document.getElementById('expenseDateV135')?.value||new Date().toISOString().slice(0,10),button=document.getElementById('btDesp');button.disabled=true;button.textContent='Salvando despesa...';
  try{let r=await sb.from('km_expenses').insert({trip_id:activeTrip.id,expense_type:tipoDesp.value,description:descDesp.value.trim()||null,amount:val,expense_date:date}).select().single();if(r.error)throw r.error;let receiptSaved=false;if(file){const u=await uploadExpenseReceiptV135(r.data.id,file);if(u.error)msg('Despesa salva, mas o comprovante não foi enviado: '+u.error.message,true);else receiptSaved=u.saved}
    valorDesp.value='';descDesp.value='';const f=document.getElementById('expenseFileV135'),n=document.getElementById('expenseFileNameV135');if(f)f.value='';if(n)n.textContent='';await refreshActive();let rr=await sb.from('km_trip_report').select('*').eq('organization_id',org.id);reportCache=rr.data||[];render();msg(receiptSaved?'Despesa e comprovante adicionados':'Despesa adicionada');
  }catch(e){msg(e.message||'Não foi possível adicionar a despesa',true)}finally{button.disabled=false;button.textContent='＋ Adicionar despesa'}
}
function expenseSummaryV135(){const box=document.getElementById('despResumo');if(!box||!activeTrip)return;const sums={};expenses.forEach(e=>sums[e.expense_type]=(sums[e.expense_type]||0)+Number(e.amount||0));const total=expenses.reduce((a,e)=>a+Number(e.amount||0),0);box.className='expense-summary-v135';box.innerHTML='<div class="expense-total-v135"><span>Total da viagem</span><b>'+moeda(total)+'</b></div><div class="expense-breakdown-v135">'+Object.entries(sums).map(([k,v])=>'<span>'+expenseIconV135(k)+' '+esc(typeName(k))+' <b>'+moeda(v)+'</b></span>').join('')+'</div>'}
const renderActiveBaseV135=renderActive;renderActive=function(){renderActiveBaseV135();ensureExpenseUiV135();expenseSummaryV135()};
function finishV135(){ensureExpenseUiV135();const b=document.getElementById('btDesp');if(b&&!b.dataset.v135){b.dataset.v135='1';b.onclick=addExpenseV135}if(activeTrip)expenseSummaryV135()}
const renderBaseV135=render;render=function(){renderBaseV135();setTimeout(finishV135,0)};setTimeout(finishV135,2000);
carga();`,'startup');
rep('</style>',`\n/* v135 despesas completas da viagem */\n.expense-quick-v135{display:flex;gap:6px;overflow-x:auto;padding:2px 0 9px;scrollbar-width:none}.expense-quick-v135::-webkit-scrollbar{display:none}.expense-quick-v135 button{white-space:nowrap;min-height:38px!important;padding:8px 10px!important;font-size:10px!important;border-radius:11px!important}.expense-quick-v135 button.selected{border-color:#163b78;background:#eef4ff;color:#163b78}.expense-extra-v135{display:grid;grid-template-columns:150px 1fr;gap:8px;margin-top:8px}.expense-extra-v135>input,.expense-file-v135{min-height:46px}.expense-file-v135{border:1px solid #d8dee8;border-radius:12px;padding:8px 10px;display:flex;align-items:center;justify-content:space-between;gap:8px;background:#fff;cursor:pointer}.expense-file-v135 span{font-size:11px;font-weight:700;color:#26334a}.expense-file-v135 small{display:block;font-size:9px;font-weight:500;color:#778196;margin-top:2px}.expense-file-v135 input{max-width:128px;font-size:9px;padding:0;border:0}.expense-extra-v135 .muted{grid-column:1/-1;margin-top:-4px}.expense-summary-v135{margin:10px 0}.expense-total-v135{display:flex;align-items:end;justify-content:space-between;padding:12px;border-radius:12px;background:#eef4ff;border:1px solid #d8e4f8}.expense-total-v135 span{font-size:10px;color:#667085}.expense-total-v135 b{font-size:18px;color:#163b78}.expense-breakdown-v135{display:flex;flex-wrap:wrap;gap:6px;margin-top:7px}.expense-breakdown-v135 span{padding:6px 8px;border:1px solid #e1e6ee;border-radius:9px;background:#fff;font-size:9.5px;color:#536070}.expense-breakdown-v135 b{color:#17213a}\n@media(max-width:700px){.expense-extra-v135{grid-template-columns:1fr}.expense-file-v135{display:block}.expense-file-v135 input{display:block;max-width:100%;width:100%;margin-top:7px}.expense-extra-v135 .muted{grid-column:auto}.expense-total-v135 b{font-size:16px}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v135.0: complete trip expense capture and optional receipt ready');