const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v137 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 136.0','Gestão de deslocamentos · versão 137.0','version');rep('<span class="tag">136.0</span>','<span class="tag">137.0</span>','help');rep("checks.push(['Versão','136.0']);","checks.push(['Versão','137.0']);",'diag');
const js=`
// v137 enterprise plan, fleet documents and incidents
let subV137=null,fleetCatsV137=[],docsV137=[],incidentsV137=[];
function v137Esc(x){return esc(x)}
function v137RoleAdmin(){return ['admin','manager'].includes(acc?.module_role)}
function v137CreateUI(){
 if(document.getElementById('p-documentos'))return;
 const nav=document.getElementById('sideMenuV136')||document.querySelector('.classic-module-nav')||document.querySelector('.nav');
 if(nav){const sair=nav.querySelector('#sair');[['documentos','Documentos'],['sinistros','Sinistros']].forEach(([p,t])=>{const b=document.createElement('button');b.type='button';b.dataset.p=p;b.textContent=t;b.onclick=()=>{show(p);nav.classList.remove('open-v136');document.getElementById('sideMenuShadeV136')?.classList.remove('open-v136')};nav.insertBefore(b,sair)});}
 const app=document.getElementById('app');
 app.insertAdjacentHTML('beforeend',\`
 <section id="p-documentos" class="hide"><div class="c v137-card"><h2>Frota e documentos</h2><div id="fleetKpisV137" class="stat v137-kpis"></div>
 <div class="v137-grid"><div><h3>Cadastrar veículo de frota</h3><div class="r"><input id="fleetDescV137" placeholder="Descrição do veículo"><input id="fleetPlateV137" placeholder="Placa"></div><div class="r" style="margin-top:8px"><select id="fleetCatV137"></select><select id="fleetDriverV137"></select></div><div class="r" style="margin-top:8px"><input id="fleetKmV137" type="number" step="0.1" placeholder="KM atual"><label class="v137-check"><input id="fleetCargoV137" type="checkbox"> Transporte de carga</label></div><button id="fleetSaveV137" style="margin-top:8px">Cadastrar veículo</button></div>
 <div><h3>Anexar documento</h3><div class="r"><select id="docScopeV137"><option value="vehicle">Veículo</option><option value="driver">Condutor</option><option value="cargo">Transporte de carga</option><option value="incident">Sinistro</option></select><select id="docTargetV137"></select></div><div class="r" style="margin-top:8px"><input id="docTypeV137" placeholder="Tipo: CRLV, CNH, RNTRC..."><input id="docNumberV137" placeholder="Número do documento"></div><div class="r" style="margin-top:8px"><input id="docExpiryV137" type="date"><input id="docFileV137" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"></div><button id="docSaveV137" style="margin-top:8px">Enviar documento</button></div></div>
 <div class="sep"></div><h3>Central de vencimentos</h3><div id="docsListV137"></div><h3>Veículos da frota</h3><div id="fleetListV137"></div></div></section>
 <section id="p-sinistros" class="hide"><div class="c v137-card"><h2>Sinistros</h2><div class="v137-grid"><div><h3>Informar ocorrência</h3><div class="r"><select id="incVehicleV137"></select><select id="incTypeV137"><option value="collision">Colisão</option><option value="theft">Furto</option><option value="robbery">Roubo</option><option value="damage">Avaria</option><option value="cargo_damage">Avaria de carga</option><option value="mechanical">Ocorrência mecânica</option><option value="traffic">Ocorrência de trânsito</option><option value="other">Outro</option></select></div><div class="r" style="margin-top:8px"><select id="incSeverityV137"><option value="low">Baixa</option><option value="medium" selected>Média</option><option value="high">Alta</option><option value="critical">Crítica</option></select><input id="incWhenV137" type="datetime-local"></div><input id="incAddressV137" style="margin-top:8px" placeholder="Local / endereço"><textarea id="incDescV137" style="margin-top:8px" placeholder="Descreva o ocorrido"></textarea><button id="incGeoV137" class="sec" style="margin-top:8px">Usar localização atual</button><button id="incSaveV137" style="margin-top:8px">Registrar sinistro</button></div><div><h3>Resumo</h3><div id="incKpisV137" class="stat v137-kpis"></div><div class="row"><b>Documentos e imagens</b><p class="muted small">Após registrar o sinistro, use a Central de Documentos e selecione “Sinistro” para anexar fotos, boletim, seguro, orçamentos ou PDFs.</p><button id="incGoDocsV137" class="sec">Abrir documentos</button></div></div></div><div class="sep"></div><div id="incListV137"></div></div></section>\`);
 const eq=document.getElementById('p-equipe')?.querySelector('.c');if(eq&&!document.getElementById('planBoxV137'))eq.insertAdjacentHTML('afterbegin','<div id="planBoxV137" class="row v137-plan"></div>');
 docScopeV137.onchange=v137FillDocTargets;fleetSaveV137.onclick=v137SaveFleet;docSaveV137.onclick=v137UploadDoc;incSaveV137.onclick=v137SaveIncident;incGeoV137.onclick=v137UseGeo;incGoDocsV137.onclick=()=>show('documentos');
}
async function v137LoadPlan(){if(!org)return;const r=await sb.from('km_org_subscriptions').select('*').eq('organization_id',org.id).maybeSingle();if(r.error)return;subV137=r.data;const active=team.filter(x=>x.active!==false).length,pending=invites.filter(x=>x.active&& !x.accepted_at).length,limit=Number(subV137?.contracted_users||1),used=active+pending,free=Math.max(0,limit-used);const box=document.getElementById('planBoxV137');if(box){box.innerHTML='<b>Plano e usuários</b><div class="v137-planline"><span>Plano: '+v137Esc(subV137?.plan_code||'standard')+'</span><span>Contratados: <b>'+limit+'</b></span><span>Ativos: <b>'+active+'</b></span><span>Convites: <b>'+pending+'</b></span><span class="'+(free?'oktxt':'warntxt')+'">Disponíveis: <b>'+free+'</b></span></div><div class="muted small">O administrador da empresa pode liberar usuários até o volume contratado. A ampliação do contrato é controlada pela administração da plataforma.</div>';const bt=document.getElementById('btConvite');if(bt){bt.disabled=free<=0;bt.title=free<=0?'Limite contratado atingido':''}}}
async function v137LoadFleet(){if(!org)return;let r=await sb.from('km_fleet_categories').select('*').eq('organization_id',org.id).eq('active',true).order('name');fleetCatsV137=r.data||[];r=await sb.from('km_vehicles').select('*').eq('organization_id',org.id).order('description');const vv=r.data||[];const catSel=document.getElementById('fleetCatV137');if(catSel)catSel.innerHTML='<option value="">Categoria da frota</option>'+fleetCatsV137.map(x=>'<option value="'+x.id+'">'+v137Esc(x.name)+'</option>').join('');const drv=document.getElementById('fleetDriverV137');if(drv)drv.innerHTML='<option value="">Condutor principal</option>'+team.map(x=>'<option value="'+x.user_id+'">'+v137Esc(x.profile?.full_name||x.profile?.email||x.user_id)+'</option>').join('');const incv=document.getElementById('incVehicleV137');if(incv)incv.innerHTML='<option value="">Selecione o veículo</option>'+vv.map(x=>'<option value="'+x.id+'">'+v137Esc(x.description+(x.plate?' · '+x.plate:''))+'</option>').join('');const list=document.getElementById('fleetListV137');if(list)list.innerHTML=vv.length?vv.map(x=>{const c=fleetCatsV137.find(z=>z.id===x.category_id);const d=team.find(z=>z.user_id===x.primary_driver_user_id);return '<div class="row"><b>'+v137Esc(x.description)+'</b> '+(x.plate?'<span class="tag">'+v137Esc(x.plate)+'</span>':'')+'<div class="muted small">'+v137Esc(c?.name||'Sem categoria')+' · Condutor: '+v137Esc(d?.profile?.full_name||d?.profile?.email||'não definido')+(x.cargo_transport_enabled?' · Carga habilitada':'')+'</div></div>'}).join(''):'<div class="row muted">Nenhum veículo cadastrado.</div>';const k=document.getElementById('fleetKpisV137');if(k)k.innerHTML='<div>Veículos<br><b>'+vv.length+'</b></div><div>Categorias<br><b>'+fleetCatsV137.length+'</b></div><div>Carga<br><b>'+vv.filter(x=>x.cargo_transport_enabled).length+'</b></div><div>Sem condutor<br><b>'+vv.filter(x=>!x.primary_driver_user_id).length+'</b></div>';window._fleetV137=vv;v137FillDocTargets()}
async function v137SaveFleet(){if(!org)return;if(!fleetDescV137.value.trim())return msg('Informe a descrição do veículo',true);const r=await sb.from('km_vehicles').insert({organization_id:org.id,description:fleetDescV137.value.trim(),plate:fleetPlateV137.value.trim()||null,current_odometer:Number(fleetKmV137.value||0),category_id:fleetCatV137.value||null,primary_driver_user_id:fleetDriverV137.value||null,cargo_transport_enabled:fleetCargoV137.checked,created_by:ses.user.id});if(r.error)return msg(r.error.message,true);fleetDescV137.value='';fleetPlateV137.value='';fleetKmV137.value='';fleetCargoV137.checked=false;await refreshAll();await v137LoadFleet();msg('Veículo cadastrado na frota')}
function v137FillDocTargets(){const sel=document.getElementById('docTargetV137');if(!sel)return;const scope=docScopeV137.value;let a=[];if(scope==='vehicle'||scope==='cargo')a=(window._fleetV137||[]).map(x=>({id:x.id,n:x.description+(x.plate?' · '+x.plate:'')}));else if(scope==='driver')a=team.map(x=>({id:x.user_id,n:x.profile?.full_name||x.profile?.email||x.user_id}));else a=incidentsV137.map(x=>({id:x.id,n:(x.incident_type||'Sinistro')+' · '+new Date(x.occurred_at).toLocaleDateString('pt-BR')}));sel.innerHTML='<option value="">Selecione</option>'+a.map(x=>'<option value="'+x.id+'">'+v137Esc(x.n)+'</option>').join('')}
async function v137LoadDocs(){if(!org)return;const r=await sb.from('km_documents').select('*').eq('organization_id',org.id).order('expires_at',{ascending:true,nullsFirst:false});if(r.error)return msg(r.error.message,true);docsV137=r.data||[];const now=new Date();const list=document.getElementById('docsListV137');if(list)list.innerHTML=docsV137.length?docsV137.map(d=>{const exp=d.expires_at?new Date(d.expires_at+'T12:00:00'):null;const days=exp?Math.ceil((exp-now)/86400000):null;const st=days==null?'Sem vencimento':days<0?'Vencido há '+Math.abs(days)+' dia(s)':days<=30?'Vence em '+days+' dia(s)':'Válido';return '<div class="row"><b>'+v137Esc(d.title||d.document_type)+'</b> <span class="tag '+(days!=null&&days<=30?'warn':'')+'">'+v137Esc(st)+'</span><div class="muted small">'+v137Esc(d.document_number||'Sem número')+(d.expires_at?' · Vencimento '+new Date(d.expires_at+'T12:00:00').toLocaleDateString('pt-BR'):'')+'</div><div class="actions"><button class="sec" onclick="window.openDocV137(\\''+d.id+'\\')">Abrir arquivo</button></div></div>'}).join(''):'<div class="row muted">Nenhum documento anexado.</div>'}
window.openDocV137=async id=>{const d=docsV137.find(x=>x.id===id);if(!d)return;const r=await sb.storage.from('km-documents').createSignedUrl(d.storage_path,300);if(r.error)return msg(r.error.message,true);window.open(r.data.signedUrl,'_blank','noopener')};
async function v137UploadDoc(){const f=docFileV137.files?.[0];if(!f)return msg('Selecione o arquivo',true);if(f.size>15*1024*1024)return msg('Arquivo maior que 15 MB',true);if(!docTypeV137.value.trim())return msg('Informe o tipo do documento',true);if(!docTargetV137.value)return msg('Selecione o vínculo do documento',true);const scope=docScopeV137.value,ext=(f.name.split('.').pop()||'bin').toLowerCase(),path=org.id+'/'+ses.user.id+'/'+crypto.randomUUID()+'.'+ext;let r=await sb.storage.from('km-documents').upload(path,f,{upsert:false,contentType:f.type});if(r.error)return msg(r.error.message,true);const row={organization_id:org.id,scope,document_type:docTypeV137.value.trim().toLowerCase().replace(/\\s+/g,'_'),title:docTypeV137.value.trim(),document_number:docNumberV137.value.trim()||null,expires_at:docExpiryV137.value||null,storage_path:path,file_name:f.name,mime_type:f.type||null,file_size:f.size,uploaded_by:ses.user.id};if(scope==='vehicle'||scope==='cargo')row.vehicle_id=docTargetV137.value;else if(scope==='driver')row.user_id=docTargetV137.value;else row.incident_id=docTargetV137.value;r=await sb.from('km_documents').insert(row);if(r.error){await sb.storage.from('km-documents').remove([path]);return msg(r.error.message,true)}docFileV137.value='';docTypeV137.value='';docNumberV137.value='';docExpiryV137.value='';await v137LoadDocs();msg('Documento enviado com segurança')}
async function v137LoadIncidents(){if(!org)return;const r=await sb.from('km_incidents').select('*').eq('organization_id',org.id).order('occurred_at',{ascending:false});if(r.error)return msg(r.error.message,true);incidentsV137=r.data||[];const k=document.getElementById('incKpisV137');if(k)k.innerHTML='<div>Abertos<br><b>'+incidentsV137.filter(x=>!['closed','rejected'].includes(x.status)).length+'</b></div><div>Críticos<br><b>'+incidentsV137.filter(x=>x.severity==='critical').length+'</b></div><div>Em análise<br><b>'+incidentsV137.filter(x=>x.status==='under_review').length+'</b></div><div>Encerrados<br><b>'+incidentsV137.filter(x=>x.status==='closed').length+'</b></div>';const list=document.getElementById('incListV137');if(list)list.innerHTML=incidentsV137.length?incidentsV137.map(x=>{const v=(window._fleetV137||[]).find(z=>z.id===x.vehicle_id);return '<div class="row"><b>'+v137Esc(v?.description||'Veículo')+'</b> <span class="tag">'+v137Esc(x.incident_type)+'</span> <span class="tag">'+v137Esc(x.severity)+'</span><div class="muted small">'+new Date(x.occurred_at).toLocaleString('pt-BR')+' · '+v137Esc(x.status)+'</div><div>'+v137Esc(x.description)+'</div></div>'}).join(''):'<div class="row muted">Nenhum sinistro registrado.</div>';v137FillDocTargets()}
let geoV137=null;function v137UseGeo(){if(!navigator.geolocation)return msg('Geolocalização indisponível',true);navigator.geolocation.getCurrentPosition(p=>{geoV137={lat:p.coords.latitude,lng:p.coords.longitude};incAddressV137.value=geoV137.lat.toFixed(6)+','+geoV137.lng.toFixed(6);msg('Localização registrada')},()=>msg('Não foi possível obter a localização',true),{enableHighAccuracy:true,timeout:12000})}
async function v137SaveIncident(){if(!incVehicleV137.value)return msg('Selecione o veículo',true);if(!incDescV137.value.trim())return msg('Descreva o ocorrido',true);const when=incWhenV137.value?new Date(incWhenV137.value).toISOString():new Date().toISOString();const row={organization_id:org.id,vehicle_id:incVehicleV137.value,driver_user_id:ses.user.id,occurred_at:when,address:incAddressV137.value.trim()||null,incident_type:incTypeV137.value,severity:incSeverityV137.value,description:incDescV137.value.trim(),created_by:ses.user.id};if(geoV137){row.latitude=geoV137.lat;row.longitude=geoV137.lng}let r=await sb.from('km_incidents').insert(row).select().single();if(r.error)return msg(r.error.message,true);await sb.from('km_incident_events').insert({incident_id:r.data.id,organization_id:org.id,event_type:'reported',notes:'Sinistro registrado pelo aplicativo',created_by:ses.user.id});incDescV137.value='';incAddressV137.value='';geoV137=null;await v137LoadIncidents();msg('Sinistro registrado')}
async function initV137(){v137CreateUI();if(!ses||!org)return;await Promise.all([v137LoadPlan(),v137LoadFleet(),v137LoadIncidents()]);await v137LoadDocs();}
const showBaseV137=show;show=function(n){showBaseV137(n);if(n==='equipe')v137LoadPlan();if(n==='documentos'){v137LoadFleet();v137LoadIncidents().then(v137LoadDocs)}if(n==='sinistros'){v137LoadFleet().then(v137LoadIncidents)}};
const renderBaseV137=render;render=function(){renderBaseV137();setTimeout(()=>{v137CreateUI();if(org){v137LoadPlan();}},0)};
`;
rep('setTimeout(finishV136,2100);\ncarga();',js+'\nsetTimeout(finishV136,2100);setTimeout(initV137,2300);\ncarga();','startup');
rep('</style>',`\n/* v137 enterprise fleet/documents/incidents */\n.v137-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.v137-card h2{margin-bottom:10px}.v137-kpis{margin:10px 0}.v137-plan{border-left:4px solid #102451}.v137-planline{display:flex;gap:12px;flex-wrap:wrap;margin:8px 0}.oktxt{color:#21704b}.warntxt{color:#9a5b00}.v137-check{display:flex;align-items:center;gap:8px;border:1px solid var(--line);border-radius:12px;padding:10px;background:#fff}.v137-check input{width:auto!important}.v137-card input[type=file]{padding:8px;background:#fff}@media(max-width:700px){.v137-grid{grid-template-columns:1fr}.v137-kpis{grid-template-columns:1fr 1fr!important}.v137-planline{gap:6px}.v137-planline span{background:#f5f7fa;border-radius:8px;padding:6px 8px;font-size:10px}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v137.0: enterprise plan, fleet documents and incidents ready');