const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v138 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 137.0','Gestão de deslocamentos · versão 138.0','version');rep('<span class="tag">137.0</span>','<span class="tag">138.0</span>','help');rep("checks.push(['Versão','137.0']);","checks.push(['Versão','138.0']);",'diag');
const js=`
// v138 agenda + organization backup
let scheduledV138=[];
const v138FmtDT=x=>x?new Date(x).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—';
function v138CreateUI(){
 if(document.getElementById('p-agenda'))return;
 const nav=document.getElementById('sideMenuV136')||document.querySelector('.classic-module-nav')||document.querySelector('.nav');
 if(nav){const sair=nav.querySelector('#sair');[['agenda','Agenda'],['backup','Backup']].forEach(([p,t])=>{if(nav.querySelector('[data-p="'+p+'"]'))return;const b=document.createElement('button');b.type='button';b.dataset.p=p;b.textContent=t;b.onclick=()=>{show(p);nav.classList.remove('open-v136');document.getElementById('sideMenuShadeV136')?.classList.remove('open-v136')};nav.insertBefore(b,sair)});}
 const app=document.getElementById('app');
 app.insertAdjacentHTML('beforeend',\`
 <section id="p-agenda" class="hide"><div class="c v138-card"><h2>Agenda de deslocamentos</h2><div id="agendaKpisV138" class="stat v138-kpis"></div>
 <div class="v138-grid"><div><h3>Agendar deslocamento</h3><div class="r"><input id="agendaWhenV138" type="datetime-local"><select id="agendaUserV138"></select></div><div class="r" style="margin-top:8px"><select id="agendaVehicleV138"></select><select id="agendaUsageV138"><option value="business">Profissional</option><option value="commute">Casa / trabalho</option><option value="personal">Pessoal</option><option value="other">Outro</option></select></div><input id="agendaOriginV138" style="margin-top:8px" placeholder="Origem (opcional)"><input id="agendaDestV138" style="margin-top:8px" placeholder="Destino"><div class="r" style="margin-top:8px"><input id="agendaPurposeV138" placeholder="Objetivo / compromisso"><select id="agendaRecurrenceV138"><option value="none">Sem repetição</option><option value="daily">Diária</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option></select></div><textarea id="agendaNotesV138" style="margin-top:8px" placeholder="Observações"></textarea><button id="agendaSaveV138" style="margin-top:8px">Agendar deslocamento</button></div>
 <div><h3>Próximos compromissos</h3><div class="muted small">A agenda organiza os deslocamentos futuros por data, usuário e veículo. Administradores e gestores podem agendar para a equipe conforme as permissões da organização.</div><div id="agendaUpcomingV138" style="margin-top:10px"></div></div></div><div class="sep"></div><h3>Todos os agendamentos</h3><div id="agendaListV138"></div></div></section>
 <section id="p-backup" class="hide"><div class="c v138-card"><h2>Backup da organização</h2><div class="v138-backup-hero"><div><b>Backup portátil em JSON</b><p class="muted small">Gera uma cópia dos dados acessíveis da organização diretamente no seu dispositivo. O arquivo não contém senhas, chaves secretas nem os arquivos binários anexados; contém apenas os registros e caminhos de armazenamento.</p></div><button id="backupRunV138">Gerar backup agora</button></div><div id="backupStatusV138" class="row muted">Nenhum backup gerado nesta sessão.</div><div class="v138-grid" style="margin-top:12px"><div class="row"><b>Incluído no backup</b><div class="muted small">Organização, perfis e acessos permitidos, locais, veículos, viagens, paradas, despesas, anexos, rotas salvas, agenda, manutenção, custos, documentos, sinistros, notificações e configurações.</div></div><div class="row"><b>Segurança</b><div class="muted small">A exportação respeita as políticas RLS do banco. Somente os registros que o usuário atual pode consultar entram no arquivo.</div></div></div></div></section>\`);
 document.getElementById('agendaSaveV138').onclick=v138SaveSchedule;document.getElementById('backupRunV138').onclick=v138Backup;
}
function v138AgendaDefaults(){const d=document.getElementById('agendaWhenV138');if(d&&!d.value){const n=new Date(Date.now()+3600000);n.setMinutes(Math.ceil(n.getMinutes()/15)*15,0,0);d.value=new Date(n.getTime()-n.getTimezoneOffset()*60000).toISOString().slice(0,16)}}
async function v138LoadAgenda(){if(!org)return;const r=await sb.from('km_scheduled_trips').select('*').eq('organization_id',org.id).order('scheduled_at',{ascending:true});if(r.error){msg(r.error.message,true);return}scheduledV138=r.data||[];const u=document.getElementById('agendaUserV138');if(u)u.innerHTML=team.map(x=>'<option value="'+x.user_id+'" '+(x.user_id===ses.user.id?'selected':'')+'>'+v137Esc(x.profile?.full_name||x.profile?.email||x.user_id)+'</option>').join('');const v=document.getElementById('agendaVehicleV138');const vv=window._fleetV137||[];if(v)v.innerHTML='<option value="">Sem veículo definido</option>'+vv.map(x=>'<option value="'+x.id+'">'+v137Esc(x.description+(x.plate?' · '+x.plate:''))+'</option>').join('');v138AgendaDefaults();v138RenderAgenda()}
function v138RenderAgenda(){const now=Date.now(),future=scheduledV138.filter(x=>new Date(x.scheduled_at).getTime()>=now&&!['cancelled','done'].includes(x.status));const today=new Date();today.setHours(0,0,0,0);const week=today.getTime()+7*86400000;const k=document.getElementById('agendaKpisV138');if(k)k.innerHTML='<div>Próximos<br><b>'+future.length+'</b></div><div>Hoje<br><b>'+future.filter(x=>{const t=new Date(x.scheduled_at);return t.toDateString()===new Date().toDateString()}).length+'</b></div><div>7 dias<br><b>'+future.filter(x=>new Date(x.scheduled_at).getTime()<week).length+'</b></div><div>Concluídos<br><b>'+scheduledV138.filter(x=>x.status==='done').length+'</b></div>';const row=x=>{const usr=team.find(z=>z.user_id===x.user_id),veh=(window._fleetV137||[]).find(z=>z.id===x.vehicle_id),late=new Date(x.scheduled_at).getTime()<now&&!['done','cancelled'].includes(x.status);return '<div class="row v138-agenda-row"><div><b>'+v137Esc(x.destination)+'</b> <span class="tag '+(late?'warn':'')+'">'+v137Esc(v138FmtDT(x.scheduled_at))+'</span><div class="muted small">'+v137Esc(usr?.profile?.full_name||usr?.profile?.email||'Usuário')+(veh?' · '+v137Esc(veh.description):'')+(x.purpose?' · '+v137Esc(x.purpose):'')+(x.recurrence&&x.recurrence!=='none'?' · recorrência '+v137Esc(x.recurrence):'')+'</div></div><div class="actions"><button class="sec" onclick="v138AgendaStatus(\\''+x.id+'\\',\\'done\\')">Concluir</button><button class="sec" onclick="v138AgendaStatus(\\''+x.id+'\\',\\'cancelled\\')">Cancelar</button></div></div>'};const up=document.getElementById('agendaUpcomingV138');if(up)up.innerHTML=future.length?future.slice(0,5).map(row).join(''):'<div class="row muted">Nenhum deslocamento futuro.</div>';const all=document.getElementById('agendaListV138');if(all)all.innerHTML=scheduledV138.length?scheduledV138.map(row).join(''):'<div class="row muted">Nenhum agendamento cadastrado.</div>'}
window.v138AgendaStatus=async(id,statusValue)=>{const r=await sb.from('km_scheduled_trips').update({status:statusValue,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)return msg(r.error.message,true);await v138LoadAgenda();msg(statusValue==='done'?'Agendamento concluído':'Agendamento cancelado')};
async function v138SaveSchedule(){if(!org)return;const when=document.getElementById('agendaWhenV138').value,dest=document.getElementById('agendaDestV138').value.trim(),uid=document.getElementById('agendaUserV138').value;if(!when)return msg('Informe data e hora',true);if(!dest)return msg('Informe o destino',true);if(!uid)return msg('Selecione o usuário',true);const row={organization_id:org.id,user_id:uid,vehicle_id:document.getElementById('agendaVehicleV138').value||null,scheduled_at:new Date(when).toISOString(),origin:document.getElementById('agendaOriginV138').value.trim()||null,destination:dest,purpose:document.getElementById('agendaPurposeV138').value.trim()||null,recurrence:document.getElementById('agendaRecurrenceV138').value,status:'scheduled',created_by:ses.user.id,notes:document.getElementById('agendaNotesV138').value.trim()||null,usage_type:document.getElementById('agendaUsageV138').value,planned_stops:[],planned_expenses:[],odometer_mode:'manual',google_calendar_sync_status:'not_requested'};const r=await sb.from('km_scheduled_trips').insert(row);if(r.error)return msg(r.error.message,true);['agendaOriginV138','agendaDestV138','agendaPurposeV138','agendaNotesV138'].forEach(id=>document.getElementById(id).value='');document.getElementById('agendaWhenV138').value='';v138AgendaDefaults();await v138LoadAgenda();msg('Deslocamento agendado')}
const v138BackupTables=['km_organizations','km_user_profiles','km_user_access','km_user_location_access','km_locations','km_vehicles','km_fleet_categories','km_trips','km_stops','km_expenses','km_attachments','km_saved_routes','km_scheduled_trips','km_vehicle_maintenance','km_vehicle_costs','km_documents','km_incidents','km_incident_events','km_notifications','km_settings'];
async function v138Backup(){if(!org)return;const b=document.getElementById('backupRunV138'),st=document.getElementById('backupStatusV138');b.disabled=true;b.textContent='Gerando backup...';st.className='row';st.textContent='Consultando os dados permitidos...';try{const data={},errors=[];for(const table of v138BackupTables){let q=sb.from(table).select('*');if(table==='km_organizations')q=q.eq('id',org.id);else if(table==='km_user_profiles'){const ids=[...new Set(team.map(x=>x.user_id).concat([ses.user.id]))];q=q.in('user_id',ids)}else if(table==='km_attachments'){const tripIds=(data.km_trips||[]).map(x=>x.id);if(!tripIds.length){data[table]=[];continue}q=q.in('trip_id',tripIds)}else if(['km_expenses','km_stops'].includes(table)){const tripIds=(data.km_trips||[]).map(x=>x.id);if(!tripIds.length){data[table]=[];continue}q=q.in('trip_id',tripIds)}else q=q.eq('organization_id',org.id);const r=await q;if(r.error){errors.push({table,message:r.error.message});data[table]=[]}else data[table]=r.data||[]}
 const payload={format:'controle-facil-km-backup',version:'138.0',generated_at:new Date().toISOString(),organization:{id:org.id,name:org.name||null},generated_by:ses.user.id,tables:data,warnings:errors};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a'),name='controle-facil-km-backup-'+new Date().toISOString().slice(0,10)+'.json';a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);const count=Object.values(data).reduce((n,a)=>n+(Array.isArray(a)?a.length:0),0);st.className='row '+(errors.length?'warn':'');st.innerHTML='<b>Backup gerado: '+count+' registro(s)</b><div class="muted small">Arquivo: '+v137Esc(name)+(errors.length?' · '+errors.length+' tabela(s) não puderam ser exportadas por permissão ou disponibilidade.':' · Exportação concluída sem erros.')+'</div>';msg('Backup gerado no dispositivo')
 }catch(e){st.className='row warn';st.textContent='Falha ao gerar backup: '+(e.message||e);msg(e.message||'Falha ao gerar backup',true)}finally{b.disabled=false;b.textContent='Gerar backup agora'}}
function v138Finish(){v138CreateUI();if(org){v138LoadAgenda()}}
const renderBaseV138=render;render=function(){renderBaseV138();setTimeout(v138Finish,0)};setTimeout(v138Finish,2300);
`;
rep('carga();',js+'\ncarga();','startup');
rep('</style>',`\n/* v138 agenda + backup */\n.v138-card{max-width:1180px}.v138-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:14px}.v138-kpis{display:grid!important;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:14px}.v138-kpis>div{padding:10px;border:1px solid #e2e7ef;border-radius:12px;background:#fff}.v138-kpis b{font-size:18px}.v138-agenda-row{display:flex;align-items:center;justify-content:space-between;gap:10px}.v138-backup-hero{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:16px;border:1px solid #dbe4f2;border-radius:14px;background:#f8fbff}.v138-backup-hero p{margin:5px 0 0}.v138-backup-hero button{min-width:180px}.v138-agenda-row .actions{display:flex;gap:6px;flex-shrink:0}\n@media(max-width:760px){.v138-grid{grid-template-columns:1fr}.v138-kpis{grid-template-columns:repeat(2,1fr)}.v138-agenda-row,.v138-backup-hero{align-items:stretch;flex-direction:column}.v138-backup-hero button{width:100%}.v138-agenda-row .actions button{flex:1}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v138.0: agenda and organization backup ready');