const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v139 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 138.0','Gestão de deslocamentos · versão 139.0','version');rep('<span class="tag">138.0</span>','<span class="tag">139.0</span>','help');rep("checks.push(['Versão','138.0']);","checks.push(['Versão','139.0']);",'diag');
const js=`
// v139 Roteiros Operacionais — core, gated by contract feature route_operations
let routePlansV139=[];
const v139Esc=x=>String(x??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function v139FeatureEnabled(){const mods=orgSubscription?.modules||org?.modules||{};return mods?.route_operations===true;}
function v139CreateUI(){if(document.getElementById('p-routeops'))return;const nav=document.getElementById('sideMenuV136')||document.querySelector('.classic-module-nav')||document.querySelector('.nav');if(nav&&v139FeatureEnabled()){const sair=nav.querySelector('#sair');const b=document.createElement('button');b.type='button';b.dataset.p='routeops';b.textContent='Roteiros';b.onclick=()=>{show('routeops');nav.classList.remove('open-v136');document.getElementById('sideMenuShadeV136')?.classList.remove('open-v136')};nav.insertBefore(b,sair)}
 const app=document.getElementById('app');app.insertAdjacentHTML('beforeend',\`<section id="p-routeops" class="hide"><div class="c v139-card"><h2>Roteiros Operacionais</h2><div class="muted small">Planeje roteiros com motorista, veículo e sequência de paradas. Módulo contratual opcional.</div><div class="v139-grid" style="margin-top:12px"><div><h3>Novo roteiro</h3><input id="routeNameV139" placeholder="Nome do roteiro"><div class="r" style="margin-top:8px"><input id="routeDateV139" type="date"><select id="routeDriverV139"></select></div><div class="r" style="margin-top:8px"><select id="routeVehicleV139"></select><input id="routeCostV139" placeholder="Centro de custo"></div><label class="small" style="display:block;margin-top:8px"><input id="routeRoundV139" type="checkbox"> Retornar ao ponto inicial</label><textarea id="routeNotesV139" style="margin-top:8px" placeholder="Observações"></textarea><h3>Paradas</h3><div id="routeStopsDraftV139"></div><div class="r"><input id="routeStopNameV139" placeholder="Cliente / local"><input id="routeStopAddressV139" placeholder="Endereço"></div><button id="routeAddStopV139" class="sec" style="margin-top:8px">Adicionar parada</button><button id="routeSaveV139" style="margin-top:8px">Salvar roteiro</button></div><div><h3>Roteiros programados</h3><div id="routeListV139"></div></div></div></div></section>\`);document.getElementById('routeAddStopV139').onclick=v139AddStop;document.getElementById('routeSaveV139').onclick=v139Save;}
let routeDraftStopsV139=[];function v139AddStop(){const n=document.getElementById('routeStopNameV139').value.trim(),a=document.getElementById('routeStopAddressV139').value.trim();if(!n)return msg('Informe o local da parada',true);routeDraftStopsV139.push({name:n,address:a});document.getElementById('routeStopNameV139').value='';document.getElementById('routeStopAddressV139').value='';v139RenderDraft()}
function v139RenderDraft(){const d=document.getElementById('routeStopsDraftV139');if(d)d.innerHTML=routeDraftStopsV139.length?routeDraftStopsV139.map((x,i)=>'<div class="row"><b>'+(i+1)+'. '+v139Esc(x.name)+'</b><div class="muted small">'+v139Esc(x.address||'Endereço não informado')+'</div></div>').join(''):'<div class="row muted">Adicione ao menos uma parada.</div>'}
async function v139Load(){if(!org||!v139FeatureEnabled())return;const r=await sb.from('km_route_plans').select('*,km_route_stops(*)').eq('organization_id',org.id).order('route_date',{ascending:false});if(r.error)return msg(r.error.message,true);routePlansV139=r.data||[];const u=document.getElementById('routeDriverV139');if(u)u.innerHTML='<option value="">Motorista não definido</option>'+team.map(x=>'<option value="'+x.user_id+'">'+v139Esc(x.profile?.full_name||x.profile?.email||x.user_id)+'</option>').join('');const v=document.getElementById('routeVehicleV139'),vv=window._fleetV137||[];if(v)v.innerHTML='<option value="">Veículo não definido</option>'+vv.map(x=>'<option value="'+x.id+'">'+v139Esc(x.description+(x.plate?' · '+x.plate:''))+'</option>').join('');const dt=document.getElementById('routeDateV139');if(dt&&!dt.value)dt.value=new Date().toISOString().slice(0,10);v139RenderDraft();v139Render()}
function v139Render(){const el=document.getElementById('routeListV139');if(!el)return;el.innerHTML=routePlansV139.length?routePlansV139.map(x=>'<div class="row v139-route"><div><b>'+v139Esc(x.name)+'</b> <span class="tag">'+v139Esc(x.status)+'</span><div class="muted small">'+v139Esc(x.route_date)+' · '+((x.km_route_stops||[]).length)+' parada(s)'+(x.round_trip?' · ida e volta':'')+'</div></div></div>').join(''):'<div class="row muted">Nenhum roteiro cadastrado.</div>'}
async function v139Save(){if(!org||!v139FeatureEnabled())return msg('Módulo Roteiros não habilitado no contrato',true);const name=document.getElementById('routeNameV139').value.trim(),date=document.getElementById('routeDateV139').value;if(!name)return msg('Informe o nome do roteiro',true);if(!date)return msg('Informe a data',true);if(!routeDraftStopsV139.length)return msg('Adicione ao menos uma parada',true);const p={organization_id:org.id,name,route_date:date,driver_user_id:document.getElementById('routeDriverV139').value||null,vehicle_id:document.getElementById('routeVehicleV139').value||null,cost_center:document.getElementById('routeCostV139').value.trim()||null,round_trip:document.getElementById('routeRoundV139').checked,notes:document.getElementById('routeNotesV139').value.trim()||null,status:'draft',created_by:ses.user.id};const r=await sb.from('km_route_plans').insert(p).select('id').single();if(r.error)return msg(r.error.message,true);const stops=routeDraftStopsV139.map((x,i)=>({route_plan_id:r.data.id,organization_id:org.id,stop_order:i+1,name:x.name,address:x.address||null}));const sr=await sb.from('km_route_stops').insert(stops);if(sr.error){await sb.from('km_route_plans').delete().eq('id',r.data.id);return msg(sr.error.message,true)}routeDraftStopsV139=[];['routeNameV139','routeCostV139','routeNotesV139'].forEach(id=>document.getElementById(id).value='');await v139Load();msg('Roteiro salvo')}
function v139Finish(){v139CreateUI();if(org&&v139FeatureEnabled())v139Load()}
const renderBaseV139=render;render=function(){renderBaseV139();setTimeout(v139Finish,0)};setTimeout(v139Finish,2500);
`;
rep('carga();',js+'\ncarga();','startup');rep('</style>',`\n/* v139 route operations */\n.v139-card{max-width:1180px}.v139-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:16px}.v139-route{display:flex;justify-content:space-between;align-items:center}@media(max-width:760px){.v139-grid{grid-template-columns:1fr}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v139.0: route operations core ready');