const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v140 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 139.0','Gestão de deslocamentos · versão 140.0','version');rep('<span class="tag">139.0</span>','<span class="tag">140.0</span>','help');rep("checks.push(['Versão','139.0']);","checks.push(['Versão','140.0']);",'diag');
const js=`
// v140 optimized route planning with Google Routes
function v140DurationSeconds(x){const m=String(x||'').match(/^([0-9.]+)s$/);return m?Math.round(Number(m[1])||0):0}
function v140DurationText(sec){sec=Number(sec||0);const h=Math.floor(sec/3600),m=Math.round((sec%3600)/60);return h?(h+'h '+m+'min'):(m+' min')}
function v140RouteStops(plan){return [...(plan.km_route_stops||[])].sort((a,b)=>a.stop_order-b.stop_order)}
async function v140PlanRoute(id){const plan=routePlansV139.find(x=>x.id===id);if(!plan)return msg('Roteiro não encontrado',true);const stops=v140RouteStops(plan);if(stops.length<2)return msg('Inclua ao menos duas paradas para planejar a rota',true);if(stops.some(x=>!String(x.address||'').trim()))return msg('Todas as paradas precisam ter endereço para calcular a rota',true);const btn=document.querySelector('[data-plan-route-v140="'+id+'"]');if(btn){btn.disabled=true;btn.textContent='Calculando...'}try{const origin=stops[0].address,destination=plan.round_trip?stops[0].address:stops[stops.length-1].address,intermediate=plan.round_trip?stops.slice(1):stops.slice(1,-1);const r=await fetch('/api/routes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({origin,destination,stops:intermediate.map(x=>x.address),optimize:true})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Falha ao calcular rota');const item=j.items?.[0];if(!item)throw new Error('Google Routes não retornou uma rota');const sec=v140DurationSeconds(item.duration),km=Number(item.distanceMeters||0)/1000,toll=Number(item.tollTotalBRL||0);const ur=await sb.from('km_route_plans').update({planned_distance_km:km,planned_duration_seconds:sec,planned_toll_brl:toll,planned_polyline:item.polyline||null,planned_at:new Date().toISOString(),planned_source:'google_routes',status:'planned',updated_at:new Date().toISOString()}).eq('id',id);if(ur.error)throw ur.error;const order=item.optimizedIntermediateWaypointIndex||[];if(order.length===intermediate.length&&intermediate.length>1){const optimized=order.map(i=>intermediate[i]);const finalOrder=plan.round_trip?[stops[0],...optimized]:[stops[0],...optimized,stops[stops.length-1]];for(let i=0;i<finalOrder.length;i++){const rr=await sb.from('km_route_stops').update({stop_order:1000+i,updated_at:new Date().toISOString()}).eq('id',finalOrder[i].id);if(rr.error)throw rr.error}for(let i=0;i<finalOrder.length;i++){const rr=await sb.from('km_route_stops').update({stop_order:i+1,updated_at:new Date().toISOString()}).eq('id',finalOrder[i].id);if(rr.error)throw rr.error}}
 await v139Load();msg('Rota planejada: '+km.toFixed(1)+' km · '+v140DurationText(sec)+(toll>0?' · '+moeda(toll)+' em pedágios':''))}catch(e){msg(e.message||'Falha ao planejar rota',true)}finally{if(btn){btn.disabled=false;btn.textContent='Planejar e otimizar'}}}
window.v140PlanRoute=v140PlanRoute;
const v139RenderBaseV140=v139Render;v139Render=function(){v139RenderBaseV140();const el=document.getElementById('routeListV139');if(!el)return;routePlansV139.forEach(plan=>{const rows=[...el.querySelectorAll('.v139-route')],row=rows.find(r=>r.querySelector('b')?.textContent===plan.name);if(!row)return;let actions=row.querySelector('.v140-actions');if(!actions){actions=document.createElement('div');actions.className='v140-actions';row.appendChild(actions)}const hasPlan=Number(plan.planned_distance_km||0)>0;actions.innerHTML='<button type="button" class="sec" data-plan-route-v140="'+plan.id+'" onclick="v140PlanRoute(\\''+plan.id+'\\')">Planejar e otimizar</button>'+(hasPlan?'<div class="v140-plan-summary"><b>'+Number(plan.planned_distance_km).toFixed(1)+' km</b><span>'+v140DurationText(plan.planned_duration_seconds)+(Number(plan.planned_toll_brl||0)>0?' · '+moeda(Number(plan.planned_toll_brl)):'')+'</span></div>':'')})};
const v139LoadBaseV140=v139Load;v139Load=async function(){await v139LoadBaseV140();v139Render()};
`;
rep('carga();',js+'\ncarga();','startup');rep('</style>',`\n/* v140 optimized planning */\n.v140-actions{margin-left:auto;display:flex;align-items:center;gap:10px}.v140-plan-summary{display:flex;flex-direction:column;align-items:flex-end;font-size:10px}.v140-plan-summary b{font-size:12px}.v140-plan-summary span{color:#667085}@media(max-width:760px){.v139-route{align-items:stretch;flex-direction:column}.v140-actions{margin-left:0;align-items:stretch;flex-direction:column}.v140-plan-summary{align-items:flex-start}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v140.0: optimized operational route planning ready');