const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v141 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 140.0','Gestão de deslocamentos · versão 141.0','version');rep('<span class="tag">140.0</span>','<span class="tag">141.0</span>','help');rep("checks.push(['Versão','140.0']);","checks.push(['Versão','141.0']);",'diag');
const js=`
// v141 geofence + foreground route execution
let activeRouteExecutionV141=null,routeWatchIdV141=null,routeEventsV141=[],lastPointAtV141=0,lastPointV141=null;
function v141DistanceM(a,b,c,d){const R=6371000,toRad=x=>x*Math.PI/180,p1=toRad(a),p2=toRad(c),dp=toRad(c-a),dl=toRad(d-b),q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function v141PlanStops(plan){return [...(plan.km_route_stops||[])].sort((a,b)=>a.stop_order-b.stop_order)}
async function v141PrepareGeofence(id){const plan=routePlansV139.find(x=>x.id===id);if(!plan)return msg('Roteiro não encontrado',true);const stops=v141PlanStops(plan);if(stops.length<2)return msg('Inclua ao menos duas paradas',true);if(stops.some(x=>!String(x.address||'').trim()))return msg('Todas as paradas precisam ter endereço',true);const btn=document.querySelector('[data-geofence-v141="'+id+'"]');if(btn){btn.disabled=true;btn.textContent='Preparando GPS...'}try{const origin=stops[0].address,destination=plan.round_trip?stops[0].address:stops[stops.length-1].address,mid=plan.round_trip?stops.slice(1):stops.slice(1,-1);const r=await fetch('/api/routes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({origin,destination,stops:mid.map(x=>x.address),optimize:false})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Falha ao preparar geofence');const item=j.items?.[0],legs=item?.legs||[];if(!legs.length)throw new Error('Google Routes não retornou coordenadas');const coords=[legs[0].startLocation,...legs.map(x=>x.endLocation)];const useful=plan.round_trip?coords.slice(0,stops.length):coords.slice(0,stops.length);if(useful.length<stops.length)throw new Error('Coordenadas incompletas para as paradas');for(let i=0;i<stops.length;i++){const p=useful[i];if(!p||!Number.isFinite(Number(p.latitude))||!Number.isFinite(Number(p.longitude)))throw new Error('Coordenada inválida na parada '+(i+1));const u=await sb.from('km_route_stops').update({latitude:Number(p.latitude),longitude:Number(p.longitude),updated_at:new Date().toISOString()}).eq('id',stops[i].id);if(u.error)throw u.error}await v139Load();msg('Geofence preparado para '+stops.length+' parada(s)')}catch(e){msg(e.message||'Falha ao preparar geofence',true)}finally{if(btn){btn.disabled=false;btn.textContent='Preparar geofence'}}}
window.v141PrepareGeofence=v141PrepareGeofence;
async function v141LoadExecution(){if(!org||!v139FeatureEnabled())return;const r=await sb.from('km_route_executions').select('*').eq('organization_id',org.id).eq('status','in_progress').order('started_at',{ascending:false}).limit(1);if(!r.error)activeRouteExecutionV141=r.data?.[0]||null;if(activeRouteExecutionV141){const ev=await sb.from('km_route_stop_events').select('*').eq('execution_id',activeRouteExecutionV141.id).order('event_at');routeEventsV141=ev.data||[];v141StartWatch();}v139Render()}
async function v141StartExecution(id){const plan=routePlansV139.find(x=>x.id===id);if(!plan)return msg('Roteiro não encontrado',true);const stops=v141PlanStops(plan);if(stops.some(x=>x.latitude==null||x.longitude==null))return msg('Prepare o geofence antes de iniciar',true);if(activeRouteExecutionV141)return msg('Já existe um roteiro em execução',true);const pos=await new Promise((resolve,reject)=>navigator.geolocation?navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:12000,maximumAge:0}):reject(new Error('GPS indisponível'))).catch(e=>null);const row={organization_id:org.id,route_plan_id:id,driver_user_id:plan.driver_user_id||ses.user.id,vehicle_id:plan.vehicle_id||null,status:'in_progress',started_latitude:pos?.coords?.latitude||null,started_longitude:pos?.coords?.longitude||null,created_by:ses.user.id};const r=await sb.from('km_route_executions').insert(row).select().single();if(r.error)return msg(r.error.message,true);activeRouteExecutionV141=r.data;routeEventsV141=[];await sb.from('km_route_plans').update({status:'in_progress',updated_at:new Date().toISOString()}).eq('id',id);v141StartWatch();await v139Load();msg('Roteiro iniciado com acompanhamento por GPS')}
window.v141StartExecution=v141StartExecution;
async function v141FinishExecution(){if(!activeRouteExecutionV141)return;let lat=null,lng=null;try{const p=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:8000,maximumAge:30000}));lat=p.coords.latitude;lng=p.coords.longitude}catch{}const id=activeRouteExecutionV141.id,planId=activeRouteExecutionV141.route_plan_id;const r=await sb.from('km_route_executions').update({status:'completed',ended_at:new Date().toISOString(),ended_latitude:lat,ended_longitude:lng,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)return msg(r.error.message,true);await sb.from('km_route_plans').update({status:'completed',updated_at:new Date().toISOString()}).eq('id',planId);if(routeWatchIdV141!=null&&navigator.geolocation)navigator.geolocation.clearWatch(routeWatchIdV141);routeWatchIdV141=null;activeRouteExecutionV141=null;routeEventsV141=[];await v139Load();msg('Roteiro concluído')}
window.v141FinishExecution=v141FinishExecution;
function v141StartWatch(){if(!activeRouteExecutionV141||routeWatchIdV141!=null||!navigator.geolocation)return;routeWatchIdV141=navigator.geolocation.watchPosition(v141OnPosition,e=>{const st=document.getElementById('routeGpsStatusV141');if(st)st.textContent='GPS: '+(e.message||'indisponível')},{enableHighAccuracy:true,maximumAge:10000,timeout:20000})}
async function v141OnPosition(p){if(!activeRouteExecutionV141)return;const c=p.coords,now=Date.now(),st=document.getElementById('routeGpsStatusV141');if(st)st.textContent='GPS ativo · precisão ±'+Math.round(c.accuracy||0)+' m';const moved=!lastPointV141||v141DistanceM(lastPointV141.lat,lastPointV141.lng,c.latitude,c.longitude)>=30;if(now-lastPointAtV141>=30000||moved){lastPointAtV141=now;lastPointV141={lat:c.latitude,lng:c.longitude};await sb.from('km_route_location_points').insert({organization_id:org.id,execution_id:activeRouteExecutionV141.id,latitude:c.latitude,longitude:c.longitude,accuracy_m:c.accuracy||null,speed_mps:c.speed||null,heading_deg:c.heading||null,source:'foreground_web'})}const plan=routePlansV139.find(x=>x.id===activeRouteExecutionV141.route_plan_id);if(!plan)return;const stops=v141PlanStops(plan);for(const stop of stops){const radius=Number(stop.geofence_radius_m||120),dist=v141DistanceM(c.latitude,c.longitude,Number(stop.latitude),Number(stop.longitude));const ins=routeEventsV141.filter(e=>e.route_stop_id===stop.id&&e.event_type==='check_in'),outs=routeEventsV141.filter(e=>e.route_stop_id===stop.id&&e.event_type==='check_out');if(!ins.length&&dist<=radius){await v141Event(stop,'check_in',c,dist);break}else if(ins.length&&!outs.length&&dist>radius*1.3){await v141Event(stop,'check_out',c,dist);break}}}
async function v141Event(stop,type,c,dist){const r=await sb.from('km_route_stop_events').insert({organization_id:org.id,execution_id:activeRouteExecutionV141.id,route_stop_id:stop.id,event_type:type,event_at:new Date().toISOString(),latitude:c.latitude,longitude:c.longitude,accuracy_m:c.accuracy||null,source:'gps',note:'Geofence automático · distância '+Math.round(dist)+' m'}).select().single();if(r.error)return;routeEventsV141.push(r.data);await sb.from('km_route_stops').update({status:type==='check_in'?'arrived':'completed',updated_at:new Date().toISOString()}).eq('id',stop.id);msg((type==='check_in'?'Check-in':'Check-out')+' automático: '+stop.name);v139Render()}
const v139RenderBaseV141=v139Render;v139Render=function(){v139RenderBaseV141();const el=document.getElementById('routeListV139');if(!el)return;routePlansV139.forEach(plan=>{const rows=[...el.querySelectorAll('.v139-route')],row=rows.find(r=>r.querySelector('b')?.textContent===plan.name);if(!row)return;let box=row.querySelector('.v141-box');if(!box){box=document.createElement('div');box.className='v141-box';row.appendChild(box)}const stops=v141PlanStops(plan),ready=stops.length>1&&stops.every(x=>x.latitude!=null&&x.longitude!=null),running=activeRouteExecutionV141?.route_plan_id===plan.id;box.innerHTML='<button type="button" class="sec" data-geofence-v141="'+plan.id+'" onclick="v141PrepareGeofence(\\''+plan.id+'\\')">Preparar geofence</button>'+(running?'<button type="button" onclick="v141FinishExecution()">Concluir roteiro</button><div id="routeGpsStatusV141" class="muted small">GPS ativo</div>':'<button type="button" '+(!ready?'disabled':'')+' onclick="v141StartExecution(\\''+plan.id+'\\')">Iniciar roteiro</button>')+'<div class="muted small">'+(ready?'GPS das paradas preparado':'Prepare as coordenadas das paradas')+' · raio padrão 120 m</div>'})};
const v139LoadBaseV141=v139Load;v139Load=async function(){await v139LoadBaseV141();v139Render()};setTimeout(v141LoadExecution,3000);
`;
rep('carga();',js+'\ncarga();','startup');rep('</style>',`\n/* v141 geofence execution */\n.v141-box{display:flex;flex-wrap:wrap;gap:6px;align-items:center;margin-top:8px}.v141-box .small{width:100%}@media(max-width:760px){.v141-box button{flex:1}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v141.0: foreground geofence and automatic stop events ready');