const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v142 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 141.0','Gestão de deslocamentos · versão 142.0','version');rep('<span class="tag">141.0</span>','<span class="tag">142.0</span>','help');rep("checks.push(['Versão','141.0']);","checks.push(['Versão','142.0']);",'diag');
const js=`
// v142 proximity-safe geofence + customer ETA alerts
let v142CandidateStopId=null,v142CandidateSince=0;
function v142OpenCheckin(stopId){const ins=routeEventsV141.filter(e=>e.route_stop_id===stopId&&e.event_type==='check_in');const outs=routeEventsV141.filter(e=>e.route_stop_id===stopId&&e.event_type==='check_out');return ins.length>outs.length}
function v142Done(stopId){return routeEventsV141.some(e=>e.route_stop_id===stopId&&e.event_type==='check_out')}
function v142NextStop(plan){const stops=v141PlanStops(plan);return stops.find(x=>v142OpenCheckin(x.id))||stops.find(x=>!v142Done(x.id))||null}
const v141OnPositionBaseV142=v141OnPosition;
v141OnPosition=async function(p){if(!activeRouteExecutionV141)return;const c=p.coords,now=Date.now(),st=document.getElementById('routeGpsStatusV141');if(st)st.textContent='GPS ativo · precisão ±'+Math.round(c.accuracy||0)+' m';const moved=!lastPointV141||v141DistanceM(lastPointV141.lat,lastPointV141.lng,c.latitude,c.longitude)>=30;if(now-lastPointAtV141>=30000||moved){lastPointAtV141=now;lastPointV141={lat:c.latitude,lng:c.longitude};await sb.from('km_route_location_points').insert({organization_id:org.id,execution_id:activeRouteExecutionV141.id,latitude:c.latitude,longitude:c.longitude,accuracy_m:c.accuracy||null,speed_mps:c.speed||null,heading_deg:c.heading||null,source:'foreground_web'})}const plan=routePlansV139.find(x=>x.id===activeRouteExecutionV141.route_plan_id);if(!plan)return;const stop=v142NextStop(plan);if(!stop)return;const radius=Number(stop.geofence_radius_m||120),dist=v141DistanceM(c.latitude,c.longitude,Number(stop.latitude),Number(stop.longitude)),accuracy=Number(c.accuracy||999),speed=c.speed==null?0:Number(c.speed||0),open=v142OpenCheckin(stop.id);if(open){v142CandidateStopId=null;v142CandidateSince=0;const exitRadius=Math.max(radius*1.45,radius+60);if(dist>exitRadius&&accuracy<=100)await v141Event(stop,'check_out',c,dist);return}const quality=accuracy<=Math.min(80,Math.max(35,radius*.75));const inside=dist<=radius;const slowEnough=speed<=5;if(!(quality&&inside&&slowEnough)){if(v142CandidateStopId===stop.id){v142CandidateStopId=null;v142CandidateSince=0}return}if(v142CandidateStopId!==stop.id){v142CandidateStopId=stop.id;v142CandidateSince=now;return}if(now-v142CandidateSince>=25000){v142CandidateStopId=null;v142CandidateSince=0;await v141Event(stop,'check_in',c,dist)}};
function v142CreateAlertsUI(){if(document.getElementById('routeAlertsV142'))return;const p=document.getElementById('p-routeops');if(!p)return;p.querySelector('.c')?.insertAdjacentHTML('beforeend',\`<div class="sep"></div><div id="routeAlertsV142"><h3>Avisos ao cliente</h3><div class="muted small">Configure WhatsApp por parada. O envio é programado pelo ETA calculado da rota e pela antecedência escolhida.</div><div class="r" style="margin-top:8px"><select id="alertRouteV142"></select><select id="alertStopV142"></select></div><div class="r" style="margin-top:8px"><input id="alertCustomerV142" placeholder="Cliente"><input id="alertPhoneV142" placeholder="WhatsApp com DDI e DDD"></div><div class="r" style="margin-top:8px"><select id="alertLeadV142"><option value="15">15 min antes</option><option value="30" selected>30 min antes</option><option value="45">45 min antes</option><option value="60">1 hora antes</option><option value="120">2 horas antes</option></select><label class="small"><input id="alertEnabledV142" type="checkbox"> Avisar automaticamente</label></div><button id="alertSaveV142" style="margin-top:8px">Salvar aviso da parada</button><div id="alertInfoV142" class="muted small" style="margin-top:8px"></div></div>\`);document.getElementById('alertRouteV142').onchange=v142AlertRouteChanged;document.getElementById('alertStopV142').onchange=v142AlertStopChanged;document.getElementById('alertSaveV142').onclick=v142SaveAlertSettings}
function v142FillAlertRoutes(){const r=document.getElementById('alertRouteV142');if(!r)return;const old=r.value;r.innerHTML='<option value="">Selecione o roteiro</option>'+routePlansV139.map(x=>'<option value="'+x.id+'">'+v139Esc(x.name)+' · '+v139Esc(x.route_date)+'</option>').join('');if(routePlansV139.some(x=>x.id===old))r.value=old;v142AlertRouteChanged()}
function v142AlertRouteChanged(){const rid=document.getElementById('alertRouteV142')?.value,s=document.getElementById('alertStopV142');if(!s)return;const plan=routePlansV139.find(x=>x.id===rid),stops=plan?v141PlanStops(plan):[];s.innerHTML='<option value="">Selecione a parada</option>'+stops.map(x=>'<option value="'+x.id+'">'+x.stop_order+'. '+v139Esc(x.name)+'</option>').join('');v142AlertStopChanged()}
function v142AlertStopChanged(){const rid=document.getElementById('alertRouteV142')?.value,sid=document.getElementById('alertStopV142')?.value,plan=routePlansV139.find(x=>x.id===rid),stop=plan?.km_route_stops?.find(x=>x.id===sid);document.getElementById('alertCustomerV142').value=stop?.customer_name||stop?.name||'';document.getElementById('alertPhoneV142').value=stop?.customer_phone||'';document.getElementById('alertLeadV142').value=String(stop?.alert_lead_minutes||30);document.getElementById('alertEnabledV142').checked=!!stop?.alert_enabled;document.getElementById('alertInfoV142').textContent=stop?.alert_enabled?'Aviso automático ativo nesta parada.':'Aviso automático desativado nesta parada.'}
async function v142SaveAlertSettings(){const rid=document.getElementById('alertRouteV142').value,sid=document.getElementById('alertStopV142').value;if(!rid||!sid)return msg('Selecione roteiro e parada',true);const phone=document.getElementById('alertPhoneV142').value.replace(/\D/g,'');const enabled=document.getElementById('alertEnabledV142').checked;if(enabled&&phone.length<10)return msg('Informe um WhatsApp válido com DDI e DDD',true);const row={customer_name:document.getElementById('alertCustomerV142').value.trim()||null,customer_phone:phone||null,alert_lead_minutes:Number(document.getElementById('alertLeadV142').value||30),alert_enabled:enabled,updated_at:new Date().toISOString()};const r=await sb.from('km_route_stops').update(row).eq('id',sid);if(r.error)return msg(r.error.message,true);await v139Load();v142FillAlertRoutes();msg('Aviso da parada salvo')}
async function v142ScheduleAlerts(planId,executionId){const plan=routePlansV139.find(x=>x.id===planId);if(!plan)return;const stops=v141PlanStops(plan);if(stops.length<2)return;const eligible=stops.filter(x=>x.alert_enabled&&x.customer_phone);if(!eligible.length)return;try{const origin=stops[0].address,destination=plan.round_trip?stops[0].address:stops[stops.length-1].address,mid=plan.round_trip?stops.slice(1):stops.slice(1,-1);const r=await fetch('/api/routes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({origin,destination,stops:mid.map(x=>x.address),optimize:false})});const j=await r.json();if(!r.ok||!j.items?.[0])throw new Error(j.error||'Falha no ETA');const legs=j.items[0].legs||[];let cumulative=0;for(let i=0;i<stops.length;i++){if(i>0)cumulative+=v140DurationSeconds(legs[i-1]?.duration||'0s');if(i>1)cumulative+=Number(stops[i-1]?.expected_service_minutes||15)*60;const stop=stops[i];if(!stop.alert_enabled||!stop.customer_phone)continue;const etaAt=new Date(Date.now()+cumulative*1000),lead=Number(stop.alert_lead_minutes||30),sendAfter=new Date(etaAt.getTime()-lead*60000),text='Olá'+(stop.customer_name?' '+stop.customer_name:'')+'! Nossa previsão é chegar em aproximadamente '+Math.max(1,Math.round(cumulative/60))+' minutos para '+(plan.name||'a entrega/visita')+'. Por favor, programe-se para o recebimento/atendimento.';await sb.from('km_route_customer_alerts').upsert({organization_id:org.id,route_plan_id:planId,route_stop_id:stop.id,execution_id:executionId,customer_name:stop.customer_name||stop.name,phone:stop.customer_phone,channel:'whatsapp',trigger_type:'eta',lead_minutes:lead,eta_minutes:Math.round(cumulative/60),eta_at:etaAt.toISOString(),send_after:sendAfter.toISOString(),status:'pending',message_text:text,updated_at:new Date().toISOString()},{onConflict:'route_stop_id,execution_id,trigger_type,lead_minutes'})}}catch(e){console.warn('v142 alert schedule',e)}}
const v141StartExecutionBaseV142=v141StartExecution;v141StartExecution=async function(id){await v141StartExecutionBaseV142(id);if(activeRouteExecutionV141?.route_plan_id===id)await v142ScheduleAlerts(id,activeRouteExecutionV141.id)};window.v141StartExecution=v141StartExecution;
const v139LoadBaseV142=v139Load;v139Load=async function(){await v139LoadBaseV142();v142CreateAlertsUI();v142FillAlertRoutes();v139Render()};setTimeout(()=>{v142CreateAlertsUI();v142FillAlertRoutes()},3200);
`;
rep('carga();',js+'\ncarga();','startup');rep('</style>',`\n/* v142 alerts */\n#routeAlertsV142{padding-top:4px}#routeAlertsV142 .r{align-items:center}@media(max-width:760px){#routeAlertsV142 .r{flex-direction:column;align-items:stretch}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v142.0: proximity-safe geofence and ETA customer alerts ready');