const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v143 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 142.0','Gestão de deslocamentos · versão 143.0','version');rep('<span class="tag">142.0</span>','<span class="tag">143.0</span>','help');rep("checks.push(['Versão','142.0']);","checks.push(['Versão','143.0']);",'diag');
const js=`
// v143 dynamic ETA recalculation + close-stop manual confirmation
let v143LastEtaRefresh=0;
function v143StopsTooClose(plan){const stops=v141PlanStops(plan),out=new Set();for(let i=0;i<stops.length;i++)for(let j=i+1;j<stops.length;j++){const a=stops[i],b=stops[j];if(a.latitude==null||b.latitude==null)continue;const d=v141DistanceM(Number(a.latitude),Number(a.longitude),Number(b.latitude),Number(b.longitude));if(d<Math.max(Number(a.geofence_radius_m||120),Number(b.geofence_radius_m||120))*1.25){out.add(a.id);out.add(b.id)}}return out}
async function v143MarkCloseStops(plan){const close=v143StopsTooClose(plan);for(const st of v141PlanStops(plan)){const req=close.has(st.id);if(!!st.manual_checkin_required!==req){await sb.from('km_route_stops').update({manual_checkin_required:req,updated_at:new Date().toISOString()}).eq('id',st.id);st.manual_checkin_required=req}}}
async function v143ManualCheckin(stopId){if(!activeRouteExecutionV141)return msg('Nenhum roteiro em execução',true);const plan=routePlansV139.find(x=>x.id===activeRouteExecutionV141.route_plan_id),stop=plan&&v141PlanStops(plan).find(x=>x.id===stopId);if(!stop)return;let p;try{p=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:10000,maximumAge:0}))}catch{return msg('Não foi possível confirmar o GPS',true)}const d=v141DistanceM(p.coords.latitude,p.coords.longitude,Number(stop.latitude),Number(stop.longitude)),r=Number(stop.geofence_radius_m||120);if(d>Math.max(r*1.5,r+80))return msg('Você ainda está distante desta parada',true);await v141Event(stop,'check_in',p.coords,d)}
window.v143ManualCheckin=v143ManualCheckin;
const v141EventBaseV143=v141Event;v141Event=async function(stop,type,c,dist){await v141EventBaseV143(stop,type,c,dist);if(type==='check_out')setTimeout(()=>v143RefreshEta('parada concluída'),500)};window.v141Event=v141Event;
const v141OnPositionBaseV143=v141OnPosition;v141OnPosition=async function(p){const before=activeRouteExecutionV141;await v141OnPositionBaseV143(p);if(!before)return;const plan=routePlansV139.find(x=>x.id===before.route_plan_id);if(plan){await v143MarkCloseStops(plan);const next=v142NextStop(plan);if(next?.manual_checkin_required&&!v142OpenCheckin(next.id)){const dist=v141DistanceM(p.coords.latitude,p.coords.longitude,Number(next.latitude),Number(next.longitude)),radius=Number(next.geofence_radius_m||120);if(dist<=radius){v142CandidateStopId=null;v142CandidateSince=0;const st=document.getElementById('routeGpsStatusV141');if(st)st.textContent='Parada muito próxima de outra · confirme o check-in manualmente'}}}if(Date.now()-v143LastEtaRefresh>300000){v143LastEtaRefresh=Date.now();v143RefreshEta('atualização periódica')}};
async function v143RefreshEta(reason){if(!activeRouteExecutionV141)return;const plan=routePlansV139.find(x=>x.id===activeRouteExecutionV141.route_plan_id);if(!plan)return;const stops=v141PlanStops(plan),next=v142NextStop(plan);if(!next)return;let pos;try{pos=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:8000,maximumAge:20000}))}catch{return}const remaining=stops.filter(x=>!v142Done(x.id));if(!remaining.length)return;const destination=plan.round_trip?stops[0].address:remaining[remaining.length-1].address,mid=plan.round_trip?remaining.map(x=>x.address):remaining.slice(0,-1).map(x=>x.address);try{const r=await fetch('/api/routes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({origin:pos.coords.latitude+','+pos.coords.longitude,destination,stops:mid,optimize:false})});const j=await r.json();if(!r.ok||!j.items?.[0])return;const legs=j.items[0].legs||[];let cumulative=0;for(let i=0;i<remaining.length;i++){if(i>0)cumulative+=v140DurationSeconds(legs[i]?.duration||legs[i-1]?.duration||'0s');else cumulative+=v140DurationSeconds(legs[0]?.duration||'0s');if(i>0)cumulative+=Number(remaining[i-1].expected_service_minutes||15)*60;const stop=remaining[i];const q=await sb.from('km_route_customer_alerts').select('*').eq('execution_id',activeRouteExecutionV141.id).eq('route_stop_id',stop.id).in('status',['pending','queued']).limit(1);const a=q.data?.[0];if(!a)continue;const etaAt=new Date(Date.now()+cumulative*1000),lead=Number(a.lead_minutes||stop.alert_lead_minutes||30),sendAfter=new Date(etaAt.getTime()-lead*60000);await sb.from('km_route_customer_alerts').update({previous_eta_at:a.eta_at||null,eta_at:etaAt.toISOString(),eta_minutes:Math.max(1,Math.round(cumulative/60)),send_after:sendAfter.toISOString(),recalculated_at:new Date().toISOString(),eta_revision:Number(a.eta_revision||0)+1,adjustment_reason:reason,updated_at:new Date().toISOString()}).eq('id',a.id)}}catch(e){console.warn('v143 eta refresh',e)}}
window.v143RefreshEta=v143RefreshEta;
const v139RenderBaseV143=v139Render;v139Render=function(){v139RenderBaseV143();if(!activeRouteExecutionV141)return;const plan=routePlansV139.find(x=>x.id===activeRouteExecutionV141.route_plan_id),next=plan&&v142NextStop(plan);if(!plan||!next)return;v143MarkCloseStops(plan);const rows=[...document.querySelectorAll('.v139-route')],row=rows.find(r=>r.querySelector('b')?.textContent===plan.name);if(!row)return;let box=row.querySelector('.v143-next');if(!box){box=document.createElement('div');box.className='v143-next';row.appendChild(box)}box.innerHTML='<b>Próxima parada: '+v139Esc(next.name)+'</b>'+(next.manual_checkin_required&&!v142OpenCheckin(next.id)?'<button type="button" onclick="v143ManualCheckin(\\''+next.id+'\\')">Confirmar check-in</button><span class="muted small">Endereço muito próximo de outra parada: confirmação manual exigida.</span>':'<span class="muted small">Check-in automático protegido por sequência e permanência.</span>')+'<button type="button" class="sec" onclick="v143RefreshEta(\\'atualização manual\\')">Atualizar ETA</button>'};
`;
rep('carga();',js+'\ncarga();','startup');rep('</style>',`\n/* v143 */\n.v143-next{width:100%;display:flex;gap:8px;align-items:center;flex-wrap:wrap;padding:8px;border:1px dashed #d0d5dd;border-radius:10px;margin-top:6px}.v143-next .small{flex:1;min-width:180px}@media(max-width:760px){.v143-next{align-items:stretch;flex-direction:column}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v143.0: dynamic ETA and close-stop confirmation ready');