const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v145 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 144.0','Gestão de deslocamentos · versão 145.0','version');rep('<span class="tag">144.0</span>','<span class="tag">145.0</span>','help');rep("checks.push(['Versão','144.0']);","checks.push(['Versão','145.0']);",'diag');
const js=`
// v145 actual execution metrics + plan/actual comparison
function v145Dist(a,b){return v141DistanceM(Number(a.latitude),Number(a.longitude),Number(b.latitude),Number(b.longitude))}
function v145Seconds(a,b){return Math.max(0,Math.round((new Date(b)-new Date(a))/1000))}
async function v145ExecutionMetrics(execution){const r=await sb.from('km_route_location_points').select('*').eq('execution_id',execution.id).order('recorded_at',{ascending:true});if(r.error)throw r.error;const pts=(r.data||[]).filter(x=>Number(x.accuracy_m||999)<=100&&Number.isFinite(Number(x.latitude))&&Number.isFinite(Number(x.longitude)));let meters=0,moving=0;for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],dt=v145Seconds(a.recorded_at,b.recorded_at);if(dt<=0||dt>300)continue;const d=v145Dist(a,b),speed=d/dt;if(d>2000||speed>60)continue;if(d>=5)meters+=d;const sensor=Number(b.speed_mps);if((Number.isFinite(sensor)&&sensor>1.5)||speed>1.5)moving+=dt}const ev=await sb.from('km_route_stop_events').select('*').eq('execution_id',execution.id).in('event_type',['check_in','check_out']).order('event_at',{ascending:true});if(ev.error)throw ev.error;let service=0;const open=new Map();for(const e of ev.data||[]){if(e.event_type==='check_in'&&!open.has(e.route_stop_id))open.set(e.route_stop_id,e.event_at);else if(e.event_type==='check_out'&&open.has(e.route_stop_id)){service+=v145Seconds(open.get(e.route_stop_id),e.event_at);open.delete(e.route_stop_id)}}const ended=new Date().toISOString(),total=v145Seconds(execution.started_at,ended),stopped=Math.max(0,total-moving);return {actual_distance_km:Number((meters/1000).toFixed(3)),actual_duration_seconds:total,moving_duration_seconds:Math.min(total,moving),service_duration_seconds:Math.min(total,service),stopped_duration_seconds:Math.min(total,stopped),metrics_calculated_at:ended}}
const v141FinishExecutionBaseV145=v141FinishExecution;v141FinishExecution=async function(){if(!activeRouteExecutionV141)return;const ex={...activeRouteExecutionV141},id=ex.id;let metrics=null;try{metrics=await v145ExecutionMetrics(ex)}catch(e){console.warn('v145 metrics',e)}await v141FinishExecutionBaseV145();if(metrics){const r=await sb.from('km_route_executions').update(metrics).eq('id',id);if(r.error)console.warn('v145 metrics save',r.error);else msg('Roteiro concluído · '+metrics.actual_distance_km.toFixed(1)+' km reais · '+v140DurationText(metrics.actual_duration_seconds))}await v139Load()};window.v141FinishExecution=v141FinishExecution;
async function v145LoadLastExecution(planId){const r=await sb.from('km_route_executions').select('*').eq('route_plan_id',planId).eq('status','completed').order('ended_at',{ascending:false}).limit(1);return r.data?.[0]||null}
async function v145RenderMetrics(){const rows=[...document.querySelectorAll('#routeListV139 .v139-route[data-route-id]')];for(const row of rows){const id=row.dataset.routeId,plan=routePlansV139.find(x=>x.id===id);if(!plan)continue;let box=row.querySelector('.v145-metrics');if(!box){box=document.createElement('div');box.className='v145-metrics';row.appendChild(box)}const ex=await v145LoadLastExecution(id);if(!ex||ex.actual_distance_km==null){box.innerHTML='';continue}const pk=Number(plan.planned_distance_km||0),ak=Number(ex.actual_distance_km||0),pt=Number(plan.planned_duration_seconds||0),at=Number(ex.actual_duration_seconds||0),dk=pk?((ak-pk)/pk*100):0,dt=pt?((at-pt)/pt*100):0;box.innerHTML='<b>Planejado × realizado</b><div class="v145-kpis"><span><small>KM planejado</small><strong>'+pk.toFixed(1)+'</strong></span><span><small>KM real</small><strong>'+ak.toFixed(1)+'</strong></span><span><small>Tempo planejado</small><strong>'+v140DurationText(pt)+'</strong></span><span><small>Tempo real</small><strong>'+v140DurationText(at)+'</strong></span></div><div class="muted small">Variação: '+(dk>=0?'+':'')+dk.toFixed(1)+'% em KM · '+(dt>=0?'+':'')+dt.toFixed(1)+'% em tempo · em movimento '+v140DurationText(ex.moving_duration_seconds||0)+' · atendimento '+v140DurationText(ex.service_duration_seconds||0)+'</div>'}}
const v139RenderBaseV145=v139Render;v139Render=function(){v139RenderBaseV145();setTimeout(v145RenderMetrics,0)};const v139LoadBaseV145=v139Load;v139Load=async function(){await v139LoadBaseV145();setTimeout(v145RenderMetrics,0)};setTimeout(v145RenderMetrics,3900);
`;
rep('carga();',js+'\ncarga();','startup');rep('</style>',`\n/* v145 */\n.v145-metrics{width:100%;margin-top:8px;padding:10px;border:1px solid #dbe3ef;border-radius:12px;background:#f8faff}.v145-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin:7px 0}.v145-kpis span{padding:8px;border-radius:9px;background:#fff;border:1px solid #e3e8ef}.v145-kpis small,.v145-kpis strong{display:block}.v145-kpis small{font-size:9px;color:#6b7280}.v145-kpis strong{margin-top:3px;color:#102451}@media(max-width:760px){.v145-kpis{grid-template-columns:1fr 1fr}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v145.0: actual route execution metrics ready');