const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v146 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 145.0','Gestão de deslocamentos · versão 146.0','version');rep('<span class="tag">145.0</span>','<span class="tag">146.0</span>','help');rep("checks.push(['Versão','145.0']);","checks.push(['Versão','146.0']);",'diag');
const js=`
// v146 route corridor deviation detection
let v146CandidateSince=0,v146OpenDeviation=null;
function v146MetersPointToSeg(lat,lon,a,b){const k=111320,cl=Math.cos(lat*Math.PI/180),px=lon*k*cl,py=lat*k,ax=a[1]*k*cl,ay=a[0]*k,bx=b[1]*k*cl,by=b[0]*k,dx=bx-ax,dy=by-ay,t=dx||dy?Math.max(0,Math.min(1,((px-ax)*dx+(py-ay)*dy)/(dx*dx+dy*dy))):0,x=ax+t*dx,y=ay+t*dy;return Math.hypot(px-x,py-y)}
function v146DistanceFromRoute(plan,lat,lon){if(!plan?.planned_polyline)return Infinity;let pts=[];try{pts=decodePolylineV133(plan.planned_polyline)}catch{return Infinity}let best=Infinity;for(let i=1;i<pts.length;i++)best=Math.min(best,v146MetersPointToSeg(lat,lon,pts[i-1],pts[i]));return best}
async function v146Open(plan,c,dist){const r=await sb.from('km_route_deviations').insert({organization_id:org.id,execution_id:activeRouteExecutionV141.id,route_plan_id:plan.id,started_at:new Date().toISOString(),start_latitude:c.latitude,start_longitude:c.longitude,max_distance_from_route_m:Math.round(dist),status:'open',created_by:ses.user.id}).select().single();if(!r.error)v146OpenDeviation=r.data}
async function v146Close(c,dist){if(!v146OpenDeviation)return;const end=new Date().toISOString(),dur=Math.max(0,Math.round((new Date(end)-new Date(v146OpenDeviation.started_at))/1000));const r=await sb.from('km_route_deviations').update({ended_at:end,end_latitude:c.latitude,end_longitude:c.longitude,max_distance_from_route_m:Math.max(Number(v146OpenDeviation.max_distance_from_route_m||0),Math.round(dist)),duration_seconds:dur,status:'closed',updated_at:end}).eq('id',v146OpenDeviation.id).select().single();if(!r.error){v146OpenDeviation=null;msg('Veículo retornou ao corredor planejado')}}
async function v146TrackDeviation(p){if(!activeRouteExecutionV141)return;const plan=routePlansV139.find(x=>x.id===activeRouteExecutionV141.route_plan_id);if(!plan?.planned_polyline)return;const c=p.coords;if(Number(c.accuracy||999)>100)return;const dist=v146DistanceFromRoute(plan,c.latitude,c.longitude),now=Date.now();if(v146OpenDeviation){if(dist<=300)await v146Close(c,dist);else if(dist>Number(v146OpenDeviation.max_distance_from_route_m||0)){v146OpenDeviation.max_distance_from_route_m=Math.round(dist);await sb.from('km_route_deviations').update({max_distance_from_route_m:Math.round(dist),updated_at:new Date().toISOString()}).eq('id',v146OpenDeviation.id)}return}if(dist>500){if(!v146CandidateSince)v146CandidateSince=now;if(now-v146CandidateSince>=120000){v146CandidateSince=0;await v146Open(plan,c,dist);msg('Desvio relevante de rota detectado')}}else v146CandidateSince=0}
const v141OnPositionBaseV146=v141OnPosition;v141OnPosition=async function(p){await v141OnPositionBaseV146(p);await v146TrackDeviation(p)};window.v141OnPosition=v141OnPosition;
async function v146LoadOpenDeviation(){if(!activeRouteExecutionV141)return;const r=await sb.from('km_route_deviations').select('*').eq('execution_id',activeRouteExecutionV141.id).eq('status','open').order('started_at',{ascending:false}).limit(1);v146OpenDeviation=r.data?.[0]||null}
async function v146RenderDeviations(){const rows=[...document.querySelectorAll('#routeListV139 .v139-route[data-route-id]')];for(const row of rows){const id=row.dataset.routeId;let box=row.querySelector('.v146-deviation');if(!box){box=document.createElement('div');box.className='v146-deviation';row.appendChild(box)}const r=await sb.from('km_route_deviations').select('*').eq('route_plan_id',id).order('started_at',{ascending:false}).limit(20);const ds=r.data||[];if(!ds.length){box.innerHTML='';continue}const closed=ds.filter(x=>x.status==='closed'),seconds=closed.reduce((n,x)=>n+Number(x.duration_seconds||0),0),max=Math.max(...ds.map(x=>Number(x.max_distance_from_route_m||0)));box.innerHTML='<b>Desvios de rota</b><div class="muted small">'+ds.length+' ocorrência(s) · '+v140DurationText(seconds)+' fora do corredor · maior afastamento '+Math.round(max)+' m</div>'}}
const v139RenderBaseV146=v139Render;v139Render=function(){v139RenderBaseV146();setTimeout(v146RenderDeviations,0)};const v141LoadExecutionBaseV146=v141LoadExecution;v141LoadExecution=async function(){await v141LoadExecutionBaseV146();await v146LoadOpenDeviation();setTimeout(v146RenderDeviations,0)};setTimeout(()=>{v146LoadOpenDeviation();v146RenderDeviations()},4100);
`;
rep('carga();',js+'\ncarga();','startup');rep('</style>',`\n/* v146 */\n.v146-deviation{width:100%;margin-top:7px;padding:8px 10px;border-left:3px solid #c58b2a;background:#fffaf1;border-radius:8px}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v146.0: route deviation tracking ready');