const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v147 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 146.0','Gestão de deslocamentos · versão 147.0','version');rep('<span class="tag">146.0</span>','<span class="tag">147.0</span>','help');rep("checks.push(['Versão','146.0']);","checks.push(['Versão','147.0']);",'diag');
const js=`
// v147 offline GPS queue + operational performance dashboard
const V147_QUEUE_KEY='km_route_gps_queue_v147';
let v147Flushing=false,v147DashBusy=false;
function v147QueueRead(){try{const x=JSON.parse(localStorage.getItem(V147_QUEUE_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return []}}
function v147QueueWrite(rows){try{localStorage.setItem(V147_QUEUE_KEY,JSON.stringify(rows.slice(-5000)))}catch{}}
function v147QueuePoint(p){if(!activeRouteExecutionV141)return;const c=p.coords||{};const rows=v147QueueRead();rows.push({organization_id:org.id,execution_id:activeRouteExecutionV141.id,recorded_at:new Date(p.timestamp||Date.now()).toISOString(),latitude:Number(c.latitude),longitude:Number(c.longitude),accuracy_m:Number.isFinite(Number(c.accuracy))?Number(c.accuracy):null,speed_mps:Number.isFinite(Number(c.speed))?Number(c.speed):null,heading_deg:Number.isFinite(Number(c.heading))?Number(c.heading):null,source:'offline_web'});v147QueueWrite(rows);v147OfflineStatus()}
async function v147FlushQueue(){if(v147Flushing||!navigator.onLine)return;const rows=v147QueueRead();if(!rows.length)return v147OfflineStatus();v147Flushing=true;let left=[...rows];try{while(left.length){const batch=left.slice(0,100),r=await sb.from('km_route_location_points').insert(batch);if(r.error)throw r.error;left=left.slice(batch.length);v147QueueWrite(left)}msg('GPS offline sincronizado')}catch(e){console.warn('v147 offline sync',e)}finally{v147Flushing=false;v147OfflineStatus()}}
function v147OfflineStatus(){const el=document.getElementById('routeOfflineStatusV147');if(!el)return;const n=v147QueueRead().length;el.textContent=n?('Offline: '+n+' ponto(s) aguardando sincronização'):(navigator.onLine?'Sincronização GPS em dia':'Sem conexão · GPS será armazenado neste aparelho')}
window.v147FlushQueue=v147FlushQueue;
const v141OnPositionBaseV147=v141OnPosition;v141OnPosition=async function(p){if(!navigator.onLine)v147QueuePoint(p);await v141OnPositionBaseV147(p);v147OfflineStatus()};window.v141OnPosition=v141OnPosition;
window.addEventListener('online',()=>{v147OfflineStatus();v147FlushQueue()});window.addEventListener('offline',v147OfflineStatus);setInterval(v147FlushQueue,60000);
function v147FmtPct(n){return (n>=0?'+':'')+Number(n||0).toFixed(1)+'%'}
async function v147LoadDashboardData(){const orgId=org?.id;if(!orgId)return null;const [ex,plans,profiles,vehicles,devs]=await Promise.all([sb.from('km_route_executions').select('*').eq('organization_id',orgId).eq('status','completed').order('ended_at',{ascending:false}).limit(200),sb.from('km_route_plans').select('id,name,planned_distance_km,planned_duration_seconds,driver_user_id,vehicle_id').eq('organization_id',orgId),sb.from('km_user_profiles').select('user_id,full_name,email'),sb.from('km_vehicles').select('id,plate,description').eq('organization_id',orgId),sb.from('km_route_deviations').select('execution_id,duration_seconds,max_distance_from_route_m').eq('organization_id',orgId)]);return {executions:ex.data||[],plans:plans.data||[],profiles:profiles.data||[],vehicles:vehicles.data||[],deviations:devs.data||[]}}
function v147Aggregate(data){const pm=new Map(data.plans.map(x=>[x.id,x])),um=new Map(data.profiles.map(x=>[x.user_id,x.full_name||x.email||'Usuário'])),vm=new Map(data.vehicles.map(x=>[x.id,(x.plate||'')+(x.description?' · '+x.description:'')]));const rows=data.executions.map(e=>{const p=pm.get(e.route_plan_id)||{},dev=data.deviations.filter(d=>d.execution_id===e.id),plannedKm=Number(p.planned_distance_km||0),actualKm=Number(e.actual_distance_km||0),plannedSec=Number(p.planned_duration_seconds||0),actualSec=Number(e.actual_duration_seconds||0);return {...e,plan:p,driver:um.get(e.driver_user_id)||'Não informado',vehicle:vm.get(e.vehicle_id)||'Não informado',plannedKm,actualKm,plannedSec,actualSec,kmVar:plannedKm?((actualKm-plannedKm)/plannedKm*100):0,timeVar:plannedSec?((actualSec-plannedSec)/plannedSec*100):0,devCount:dev.length,devSec:dev.reduce((n,x)=>n+Number(x.duration_seconds||0),0)}});return rows}
function v147Group(rows,key){const m=new Map();for(const r of rows){const k=r[key]||'Não informado',x=m.get(k)||{name:k,count:0,km:0,plannedKm:0,time:0,service:0,dev:0};x.count++;x.km+=r.actualKm;x.plannedKm+=r.plannedKm;x.time+=Number(r.actual_duration_seconds||0);x.service+=Number(r.service_duration_seconds||0);x.dev+=r.devCount;m.set(k,x)}return [...m.values()].sort((a,b)=>b.km-a.km)}
function v147Table(title,items){if(!items.length)return '<div class="v147-table"><b>'+title+'</b><div class="muted small">Sem execuções concluídas</div></div>';return '<div class="v147-table"><b>'+title+'</b>'+items.slice(0,8).map(x=>'<div class="v147-row"><span>'+v139Esc(x.name)+'</span><strong>'+x.count+' rotas</strong><span>'+x.km.toFixed(1)+' km</span><span>'+v140DurationText(x.time)+'</span><span>'+x.dev+' desvios</span></div>').join('')+'</div>'}
async function v147RenderDashboard(){if(v147DashBusy||!v139FeatureEnabled())return;const list=document.getElementById('routeListV139');if(!list)return;v147DashBusy=true;let box=document.getElementById('routeOpsDashboardV147');if(!box){box=document.createElement('section');box.id='routeOpsDashboardV147';box.className='v147-dashboard';list.parentNode.insertBefore(box,list)}box.innerHTML='<div class="muted">Carregando indicadores operacionais...</div>';try{const data=await v147LoadDashboardData(),rows=v147Aggregate(data);const total=rows.length,km=rows.reduce((n,x)=>n+x.actualKm,0),planned=rows.reduce((n,x)=>n+x.plannedKm,0),service=rows.reduce((n,x)=>n+Number(x.service_duration_seconds||0),0),devs=rows.reduce((n,x)=>n+x.devCount,0),kmVar=planned?((km-planned)/planned*100):0;box.innerHTML='<div class="v147-head"><div><b>Painel operacional</b><div class="muted small">Desempenho dos últimos '+total+' roteiros concluídos</div></div><button type="button" class="sec" onclick="v147RenderDashboard()">Atualizar</button></div><div class="v147-kpis"><span><small>Roteiros</small><strong>'+total+'</strong></span><span><small>KM realizados</small><strong>'+km.toFixed(1)+'</strong></span><span><small>Variação KM</small><strong>'+v147FmtPct(kmVar)+'</strong></span><span><small>Atendimento</small><strong>'+v140DurationText(service)+'</strong></span><span><small>Desvios</small><strong>'+devs+'</strong></span></div><div id="routeOfflineStatusV147" class="v147-offline"></div><div class="v147-grids">'+v147Table('Por motorista',v147Group(rows,'driver'))+v147Table('Por veículo',v147Group(rows,'vehicle'))+'</div>';v147OfflineStatus()}catch(e){box.innerHTML='<div class="muted">Não foi possível carregar os indicadores agora.</div>';console.warn('v147 dashboard',e)}finally{v147DashBusy=false}}
window.v147RenderDashboard=v147RenderDashboard;
const v139RenderBaseV147=v139Render;v139Render=function(){v139RenderBaseV147();setTimeout(v147RenderDashboard,0);setTimeout(v147OfflineStatus,0)};const v139LoadBaseV147=v139Load;v139Load=async function(){await v139LoadBaseV147();setTimeout(v147RenderDashboard,0)};setTimeout(()=>{v147RenderDashboard();v147FlushQueue()},4500);
`;
rep('carga();',js+'\ncarga();','startup');rep('</style>',`\n/* v147 */\n.v147-dashboard{margin:10px 0 14px;padding:12px;border:1px solid #dbe3ef;border-radius:14px;background:#fbfcff}.v147-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.v147-kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:7px;margin:10px 0}.v147-kpis span{padding:9px;border-radius:10px;background:white;border:1px solid #e4e8ef}.v147-kpis small,.v147-kpis strong{display:block}.v147-kpis small{font-size:9px;color:#6b7280}.v147-kpis strong{font-size:16px;margin-top:3px;color:#102451}.v147-offline{padding:8px 10px;border-radius:9px;background:#f4f7fb;font-size:11px;margin-bottom:10px}.v147-grids{display:grid;grid-template-columns:1fr 1fr;gap:10px}.v147-table{border:1px solid #e3e8ef;border-radius:10px;background:#fff;padding:9px}.v147-row{display:grid;grid-template-columns:1.5fr .7fr .7fr .7fr .6fr;gap:6px;padding:6px 0;border-bottom:1px solid #eef1f5;font-size:10px}.v147-row:last-child{border-bottom:0}@media(max-width:760px){.v147-kpis{grid-template-columns:1fr 1fr}.v147-grids{grid-template-columns:1fr}.v147-row{grid-template-columns:1.5fr .8fr .8fr}.v147-row span:nth-of-type(n+3){display:none}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v147.0: offline GPS sync and operational dashboard ready');