const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v149 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 148.0','Gestão de deslocamentos · versão 149.0','version');rep('<span class="tag">148.0</span>','<span class="tag">149.0</span>','help');rep("checks.push(['Versão','148.0']);","checks.push(['Versão','149.0']);",'diag');
const js=`
// v149 extra stop during execution + unit ranking + executive summary
async function v149GpsNow(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('GPS indisponível'));navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:10000,maximumAge:0})})}
async function v149AddExtraStop(){if(!activeRouteExecutionV141)return msg('Nenhum roteiro em execução',true);const plan=routePlansV139.find(x=>x.id===activeRouteExecutionV141.route_plan_id);if(!plan)return msg('Roteiro ativo não encontrado',true);const name=(prompt('Nome da parada extra:','')||'').trim();if(!name)return;const address=(prompt('Endereço completo da parada extra:','')||'').trim();if(!address)return msg('Informe o endereço da parada extra',true);const customer=(prompt('Cliente/contato (opcional):','')||'').trim();let lat=null,lng=null;try{const p=await v149GpsNow(),r=await fetch('/api/routes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({origin:p.coords.latitude+','+p.coords.longitude,destination:address,stops:[],optimize:false})}),j=await r.json();if(r.ok&&j.items?.[0]?.legs?.[0]?.endLocation){lat=Number(j.items[0].legs[0].endLocation.latitude);lng=Number(j.items[0].legs[0].endLocation.longitude)}}catch(e){console.warn('v149 extra stop geocode',e)}const stops=v141PlanStops(plan),order=Math.max(0,...stops.map(x=>Number(x.stop_order||0)))+1,row={organization_id:org.id,route_plan_id:plan.id,stop_order:order,name,address,customer_name:customer||null,latitude:lat,longitude:lng,status:'planned',added_during_execution:true,geofence_radius_m:120,expected_service_minutes:15};const ins=await sb.from('km_route_stops').insert(row).select().single();if(ins.error)return msg(ins.error.message,true);msg('Parada extra adicionada ao roteiro');await v139Load();setTimeout(()=>v143RefreshEta('parada extra adicionada'),500)}
window.v149AddExtraStop=v149AddExtraStop;
function v149GroupLocation(rows,data){const lm=new Map((data.locations||[]).map(x=>[x.id,x.name||x.code||'Unidade'])),m=new Map();for(const r of rows){const id=r.plan.location_id||'',name=lm.get(id)||'Sem unidade',x=m.get(name)||{name,count:0,km:0,service:0,measurable:0,onTime:0,missed:0,extra:0};x.count++;x.km+=r.actualKm;x.service+=Number(r.service_duration_seconds||0);x.measurable+=r.measurable;x.onTime+=r.onTime;x.missed+=r.missed;x.extra+=r.extra;m.set(name,x)}return [...m.values()].sort((a,b)=>b.count-a.count)}
function v149Executive(rows){const total=rows.length,km=rows.reduce((n,x)=>n+x.actualKm,0),planned=rows.reduce((n,x)=>n+x.plannedKm,0),meas=rows.reduce((n,x)=>n+x.measurable,0),ont=rows.reduce((n,x)=>n+x.onTime,0),missed=rows.reduce((n,x)=>n+x.missed,0),extra=rows.reduce((n,x)=>n+x.extra,0),dev=rows.reduce((n,x)=>n+x.devCount,0),punct=meas?Math.round(ont/meas*100):null,kmVar=planned?((km-planned)/planned*100):0;let tone='Operação dentro do esperado';const alerts=[];if(punct!=null&&punct<85)alerts.push('pontualidade abaixo de 85%');if(missed>0)alerts.push(missed+' parada(s) não atendida(s)');if(dev>0)alerts.push(dev+' desvio(s) de rota');if(Math.abs(kmVar)>15)alerts.push('variação de KM '+v147FmtPct(kmVar));if(alerts.length)tone='Atenção: '+alerts.join(' · ');return '<div class="v149-exec"><b>Resumo executivo</b><div>'+tone+'</div><span>'+total+' roteiro(s) · '+km.toFixed(1)+' km realizados'+(punct==null?'':' · '+punct+'% pontualidade')+' · '+extra+' parada(s) extra(s)</span></div>'}
const v148DataBaseV149=v148Data;v148Data=async function(){const d=await v148DataBaseV149();if(!d)return d;const [l,p]=await Promise.all([sb.from('km_locations').select('id,code,name').eq('organization_id',org.id).eq('active',true).order('name'),sb.from('km_route_plans').select('id,location_id').eq('organization_id',org.id)]);d.locations=l.data||[];const locMap=new Map((p.data||[]).map(x=>[x.id,x.location_id]));d.plans=(d.plans||[]).map(x=>({...x,location_id:locMap.get(x.id)||x.location_id||null}));return d};window.v148Data=v148Data;
const v148RowsBaseV149=v148Rows;v148Rows=function(data,period,driverId,vehicleId){const rows=v148RowsBaseV149(data,period,driverId,vehicleId),pm=new Map(data.plans.map(x=>[x.id,x]));rows.forEach(r=>r.plan=pm.get(r.route_plan_id)||r.plan||{});return rows};window.v148Rows=v148Rows;
const v147RenderDashboardBaseV149=v147RenderDashboard;v147RenderDashboard=async function(){await v147RenderDashboardBaseV149();const box=document.getElementById('routeOpsDashboardV147');if(!box)return;const period=document.getElementById('routePeriodV148')?.value||'30',driver=document.getElementById('routeDriverV148')?.value||'',vehicle=document.getElementById('routeVehicleV148')?.value||'';try{const data=await v148Data(),rows=v148Rows(data,period,driver,vehicle);let exec=box.querySelector('.v149-exec');if(exec)exec.remove();box.insertAdjacentHTML('afterbegin',v149Executive(rows));let grids=box.querySelector('.v147-grids');if(grids&&!grids.querySelector('.v149-unit-table'))grids.insertAdjacentHTML('beforeend','<div class="v149-unit-table">'+v148Table('Por unidade',v149GroupLocation(rows,data))+'</div>')}catch(e){console.warn('v149 executive dashboard',e)}};window.v147RenderDashboard=v147RenderDashboard;
const v139RenderBaseV149=v139Render;v139Render=function(){v139RenderBaseV149();if(!activeRouteExecutionV141)return;const plan=routePlansV139.find(x=>x.id===activeRouteExecutionV141.route_plan_id);if(!plan)return;const row=document.querySelector('#routeListV139 .v139-route[data-route-id="'+plan.id+'"]');if(!row)return;let box=row.querySelector('.v149-extra-stop');if(!box){box=document.createElement('div');box.className='v149-extra-stop';box.innerHTML='<button type="button" class="sec" onclick="v149AddExtraStop()">+ Adicionar parada extra</button><span class="muted small">Inclui uma nova parada no roteiro já em execução e recalcula o ETA.</span>';row.appendChild(box)}};
`;
rep('carga();',js+'\ncarga();','startup');rep('</style>',`\n/* v149 */\n.v149-extra-stop{width:100%;display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:8px;padding:9px;border:1px dashed #b8c4d6;border-radius:10px;background:#fbfcff}.v149-exec{padding:10px 12px;border-radius:11px;background:#eef4ff;border:1px solid #d4e1f5;margin-bottom:10px}.v149-exec b,.v149-exec div,.v149-exec span{display:block}.v149-exec div{margin-top:4px;font-weight:700;color:#102451}.v149-exec span{margin-top:3px;font-size:10px;color:#667085}.v149-unit-table{grid-column:1/-1}@media(max-width:760px){.v149-extra-stop{align-items:stretch;flex-direction:column}.v149-extra-stop button{width:100%}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v149.0: live extra stops, unit ranking and executive summary ready');