const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v150 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 149.0','Gestão de deslocamentos · versão 150.0','version');rep('<span class="tag">149.0</span>','<span class="tag">150.0</span>','help');rep("checks.push(['Versão','149.0']);","checks.push(['Versão','150.0']);",'diag');
const js=`
// v150 route economics + live reoptimization
function v150VehicleCost(vehicle,km){km=Number(km||0);const avg=Number(vehicle?.average_kmpl||0),fuel=Number(vehicle?.fuel_price||0),reimb=Number(vehicle?.reimbursement_rate||0);if(avg>0&&fuel>0)return km/avg*fuel;if(reimb>0)return km*reimb;return 0}
async function v150ExecutionCosts(execution,plan){if(!execution||!plan)return null;const vr=await sb.from('km_vehicles').select('id,average_kmpl,fuel_price,reimbursement_rate').eq('id',execution.vehicle_id||plan.vehicle_id).maybeSingle(),vehicle=vr.data||null;const plannedFuel=v150VehicleCost(vehicle,plan.planned_distance_km),actualFuel=v150VehicleCost(vehicle,execution.actual_distance_km),plannedToll=Number(plan.planned_toll_brl||0);const payload={planned_cost_brl:Number((plannedFuel+plannedToll).toFixed(2)),fuel_cost_brl:Number(actualFuel.toFixed(2)),toll_cost_brl:plannedToll,other_cost_brl:Number(execution.other_cost_brl||0),actual_cost_brl:Number((actualFuel+plannedToll+Number(execution.other_cost_brl||0)).toFixed(2)),cost_calculated_at:new Date().toISOString()};const u=await sb.from('km_route_executions').update(payload).eq('id',execution.id);if(u.error)console.warn('v150 cost update',u.error);return payload}
const v145ExecutionMetricsBaseV150=v145ExecutionMetrics;v145ExecutionMetrics=async function(execution,plan){const r=await v145ExecutionMetricsBaseV150(execution,plan);try{await v150ExecutionCosts(execution,plan)}catch(e){console.warn('v150 costs',e)}return r};window.v145ExecutionMetrics=v145ExecutionMetrics;
async function v150ReoptimizeActive(){if(!activeRouteExecutionV141)return msg('Nenhum roteiro em execução',true);const plan=routePlansV139.find(x=>x.id===activeRouteExecutionV141.route_plan_id);if(!plan)return msg('Roteiro ativo não encontrado',true);const pending=v141PlanStops(plan).filter(x=>!v142Done(x));if(pending.length<2)return msg('Não há paradas suficientes para reordenar',true);let pos;try{pos=await v149GpsNow()}catch(e){return msg('GPS necessário para reotimizar',true)}const destination=pending[pending.length-1],middle=pending.slice(0,-1);try{const r=await fetch('/api/routes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({origin:pos.coords.latitude+','+pos.coords.longitude,destination:destination.address||destination.latitude+','+destination.longitude,stops:middle.map(x=>x.address||x.latitude+','+x.longitude),optimize:true})}),j=await r.json();if(!r.ok)throw new Error(j.error||'Falha ao recalcular rota');const order=j.items?.[0]?.optimizedIntermediateWaypointIndex||j.items?.[0]?.optimizedIntermediateWaypointIndices||[];if(Array.isArray(order)&&order.length===middle.length){const arranged=order.map(i=>middle[Number(i)]).filter(Boolean).concat(destination);for(let i=0;i<arranged.length;i++){const u=await sb.from('km_route_stops').update({stop_order:i+1}).eq('id',arranged[i].id);if(u.error)throw u.error}}await v139Load();await v143RefreshEta('reotimização operacional');msg('Roteiro reotimizado a partir da posição atual')}catch(e){msg(e.message||String(e),true)}}
window.v150ReoptimizeActive=v150ReoptimizeActive;
function v150Money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
const v149ExecutiveBaseV150=v149Executive;v149Executive=function(rows){const base=v149ExecutiveBaseV150(rows),planned=rows.reduce((n,x)=>n+Number(x.planned_cost_brl||0),0),actual=rows.reduce((n,x)=>n+Number(x.actual_cost_brl||0),0),delta=planned?((actual-planned)/planned*100):0;return base.replace('</div><span>','</div><div class="v150-cost">Custo planejado '+v150Money(planned)+' · realizado '+v150Money(actual)+(planned?' · '+v147FmtPct(delta):'')+'</div><span>')};window.v149Executive=v149Executive;
const v139RenderBaseV150=v139Render;v139Render=function(){v139RenderBaseV150();if(!activeRouteExecutionV141)return;const plan=routePlansV139.find(x=>x.id===activeRouteExecutionV141.route_plan_id),row=plan&&document.querySelector('#routeListV139 .v139-route[data-route-id="'+plan.id+'"]');if(!row||row.querySelector('.v150-reopt'))return;const b=document.createElement('button');b.type='button';b.className='sec v150-reopt';b.textContent='Reotimizar roteiro agora';b.onclick=v150ReoptimizeActive;row.appendChild(b)};
`;
rep('carga();',js+'\ncarga();','startup');rep('</style>',`\n/* v150 */\n.v150-reopt{margin-top:8px}.v150-cost{margin-top:5px;font-size:11px;font-weight:700;color:#315c37}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v150.0: route cost analytics and live reoptimization ready');