const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v151 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 150.0','Gestão de deslocamentos · versão 151.0','version');rep('<span class="tag">150.0</span>','<span class="tag">151.0</span>','help');rep("checks.push(['Versão','150.0']);","checks.push(['Versão','151.0']);",'diag');
const js=`
// v151 managerial cost efficiency dashboard
function v151CostRows(rows){return rows.map(r=>{const actual=Number(r.actual_cost_brl||0),planned=Number(r.planned_cost_brl||0),km=Number(r.actualKm||r.actual_distance_km||0),served=Math.max(0,Number(r.measurable||0)-Number(r.missed||0));return {...r,costActual:actual,costPlanned:planned,costPerKm:km?actual/km:0,costPerStop:served?actual/served:0,servedStops:served,costDelta:planned?((actual-planned)/planned*100):0}})}
function v151CostGroup(rows,key){const m=new Map();for(const r of v151CostRows(rows)){const name=r[key]||'Não informado',x=m.get(name)||{name,count:0,km:0,cost:0,planned:0,served:0};x.count++;x.km+=Number(r.actualKm||0);x.cost+=r.costActual;x.planned+=r.costPlanned;x.served+=r.servedStops;m.set(name,x)}return [...m.values()].map(x=>({...x,costPerKm:x.km?x.cost/x.km:0,costPerStop:x.served?x.cost/x.served:0,variance:x.planned?((x.cost-x.planned)/x.planned*100):0})).sort((a,b)=>b.cost-a.cost)}
function v151CostTable(title,items){if(!items.length)return '<div class="v151-table"><b>'+title+'</b><div class="muted small">Sem dados financeiros no período</div></div>';return '<div class="v151-table"><b>'+title+'</b>'+items.slice(0,10).map(x=>'<div class="v151-row"><span>'+v139Esc(x.name)+'</span><strong>'+v150Money(x.cost)+'</strong><span>'+v150Money(x.costPerKm)+'/km</span><span>'+v150Money(x.costPerStop)+'/parada</span><span>'+(x.planned?v147FmtPct(x.variance):'—')+'</span></div>').join('')+'</div>'}
function v151UnitCost(rows,data){const lm=new Map((data.locations||[]).map(x=>[x.id,x.name||x.code||'Unidade']));return v151CostGroup(rows.map(r=>({...r,unitName:lm.get(r.plan?.location_id)||'Sem unidade'})),'unitName')}
function v151EfficiencySummary(rows){const cr=v151CostRows(rows),cost=cr.reduce((n,x)=>n+x.costActual,0),planned=cr.reduce((n,x)=>n+x.costPlanned,0),km=cr.reduce((n,x)=>n+Number(x.actualKm||0),0),served=cr.reduce((n,x)=>n+x.servedStops,0),routes=cr.length,costKm=km?cost/km:0,costStop=served?cost/served:0,variance=planned?((cost-planned)/planned*100):0;let signal='Custos dentro da referência planejada';if(planned&&variance>10)signal='Atenção: custo realizado acima do planejado';else if(planned&&variance<-10)signal='Economia relevante frente ao planejado';return '<div class="v151-summary"><div><b>Eficiência financeira</b><span>'+signal+'</span></div><div class="v151-fin-kpis"><span><small>Custo realizado</small><strong>'+v150Money(cost)+'</strong></span><span><small>Custo / KM</small><strong>'+v150Money(costKm)+'</strong></span><span><small>Custo / parada</small><strong>'+v150Money(costStop)+'</strong></span><span><small>Variação planejado</small><strong>'+(planned?v147FmtPct(variance):'—')+'</strong></span><span><small>Rotas analisadas</small><strong>'+routes+'</strong></span></div></div>'}
const v148RowsBaseV151=v148Rows;v148Rows=function(data,period,driverId,vehicleId){const rows=v148RowsBaseV151(data,period,driverId,vehicleId);return rows.map(r=>({...r,planned_cost_brl:Number(r.planned_cost_brl||0),actual_cost_brl:Number(r.actual_cost_brl||0),fuel_cost_brl:Number(r.fuel_cost_brl||0),toll_cost_brl:Number(r.toll_cost_brl||0),other_cost_brl:Number(r.other_cost_brl||0)}))};window.v148Rows=v148Rows;
const v147RenderDashboardBaseV151=v147RenderDashboard;v147RenderDashboard=async function(){await v147RenderDashboardBaseV151();const box=document.getElementById('routeOpsDashboardV147');if(!box)return;const period=document.getElementById('routePeriodV148')?.value||'30',driver=document.getElementById('routeDriverV148')?.value||'',vehicle=document.getElementById('routeVehicleV148')?.value||'';try{const data=await v148Data(),rows=v148Rows(data,period,driver,vehicle);box.querySelector('.v151-summary')?.remove();const exec=box.querySelector('.v149-exec');if(exec)exec.insertAdjacentHTML('afterend',v151EfficiencySummary(rows));else box.insertAdjacentHTML('afterbegin',v151EfficiencySummary(rows));box.querySelector('.v151-cost-grids')?.remove();const cg=document.createElement('div');cg.className='v151-cost-grids';cg.innerHTML=v151CostTable('Custos por motorista',v151CostGroup(rows,'driver'))+v151CostTable('Custos por veículo',v151CostGroup(rows,'vehicle'))+v151CostTable('Custos por unidade',v151UnitCost(rows,data));box.appendChild(cg)}catch(e){console.warn('v151 managerial costs',e)}};window.v147RenderDashboard=v147RenderDashboard;
`;
// Ensure financial columns are fetched by v148 dashboard query
rep("sb.from('km_route_executions').select('*')","sb.from('km_route_executions').select('*')",'execution select');rep('carga();',js+'\ncarga();','startup');rep('</style>',`\n/* v151 */\n.v151-summary{margin:10px 0;padding:11px;border:1px solid #dfe7dc;border-radius:11px;background:#f7fbf5}.v151-summary>div:first-child{display:flex;justify-content:space-between;gap:10px;align-items:center}.v151-summary>div:first-child span{font-size:10px;color:#5d6d5b}.v151-fin-kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:7px;margin-top:9px}.v151-fin-kpis span{background:#fff;border:1px solid #e3e9e1;border-radius:9px;padding:8px}.v151-fin-kpis small,.v151-fin-kpis strong{display:block}.v151-fin-kpis small{font-size:9px;color:#6b7280}.v151-fin-kpis strong{margin-top:3px;font-size:14px}.v151-cost-grids{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}.v151-table{border:1px solid #e3e8ef;border-radius:10px;background:#fff;padding:9px}.v151-table:last-child{grid-column:1/-1}.v151-row{display:grid;grid-template-columns:1.4fr .8fr .8fr .9fr .6fr;gap:6px;padding:6px 0;border-bottom:1px solid #eef1f5;font-size:10px}.v151-row:last-child{border-bottom:0}@media(max-width:760px){.v151-summary>div:first-child{display:block}.v151-fin-kpis{grid-template-columns:1fr 1fr}.v151-cost-grids{grid-template-columns:1fr}.v151-table:last-child{grid-column:auto}.v151-row{grid-template-columns:1.3fr .9fr .9fr}.v151-row span:nth-of-type(n+3){display:none}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v151.0: managerial cost efficiency dashboard ready');