const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v153 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 152.0','Gestão de deslocamentos · versão 153.0','version');rep('<span class="tag">152.0</span>','<span class="tag">153.0</span>','help');rep("checks.push(['Versão','152.0']);","checks.push(['Versão','153.0']);",'diag');
const js=`
// v153 production hardening: idempotent offline GPS + deviation closure on confirmed finish
function v153Uuid(){try{return crypto.randomUUID()}catch{return '00000000-0000-4000-8000-'+Math.random().toString(16).slice(2,14).padEnd(12,'0')}}
const v147QueuePointBaseV153=v147QueuePoint;v147QueuePoint=function(p){if(!activeRouteExecutionV141)return;const c=p.coords||{},rows=v147QueueRead();rows.push({organization_id:org.id,execution_id:activeRouteExecutionV141.id,client_point_id:v153Uuid(),recorded_at:new Date(p.timestamp||Date.now()).toISOString(),latitude:Number(c.latitude),longitude:Number(c.longitude),accuracy_m:Number.isFinite(Number(c.accuracy))?Number(c.accuracy):null,speed_mps:Number.isFinite(Number(c.speed))?Number(c.speed):null,heading_deg:Number.isFinite(Number(c.heading))?Number(c.heading):null,source:'offline_web'});v147QueueWrite(rows);v147OfflineStatus()};window.v147QueuePoint=v147QueuePoint;
v147FlushQueue=async function(){if(v147Flushing||!navigator.onLine)return;let left=v147QueueRead();if(!left.length)return v147OfflineStatus();v147Flushing=true;try{while(left.length){const batch=left.slice(0,100).map(x=>({...x,client_point_id:x.client_point_id||v153Uuid()}));const r=await sb.from('km_route_location_points').upsert(batch,{onConflict:'execution_id,client_point_id',ignoreDuplicates:true});if(r.error)throw r.error;left=left.slice(batch.length);v147QueueWrite(left)}localStorage.setItem('km_route_gps_last_sync_v153',new Date().toISOString());msg('GPS offline sincronizado com segurança')}catch(e){console.warn('v153 offline sync',e)}finally{v147Flushing=false;v147OfflineStatus()}};window.v147FlushQueue=v147FlushQueue;
const v147OfflineStatusBaseV153=v147OfflineStatus;v147OfflineStatus=function(){const el=document.getElementById('routeOfflineStatusV147');if(!el)return;const n=v147QueueRead().length,last=localStorage.getItem('km_route_gps_last_sync_v153');if(n)el.textContent='Offline: '+n+' ponto(s) aguardando sincronização segura';else if(!navigator.onLine)el.textContent='Sem conexão · GPS será armazenado neste aparelho';else el.textContent='Sincronização GPS em dia'+(last?' · última '+new Date(last).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):'')};window.v147OfflineStatus=v147OfflineStatus;
async function v153CloseOpenDeviation(executionId){if(!executionId)return;const q=await sb.from('km_route_deviations').select('*').eq('execution_id',executionId).eq('status','open').order('started_at',{ascending:false}).limit(1);const d=q.data?.[0];if(!d)return;const now=new Date().toISOString(),lat=lastPointV141?.lat??null,lng=lastPointV141?.lng??null,dur=Math.max(0,Math.round((new Date(now)-new Date(d.started_at))/1000));const u=await sb.from('km_route_deviations').update({ended_at:now,end_latitude:lat,end_longitude:lng,duration_seconds:dur,status:'closed',reason:d.reason||'route_finished_outside_corridor',updated_at:now}).eq('id',d.id);if(!u.error){v146OpenDeviation=null;v146CandidateSince=0}}
const v141FinishExecutionBaseV153=v141FinishExecution;v141FinishExecution=async function(){if(!activeRouteExecutionV141)return;const ex={...activeRouteExecutionV141};await v147FlushQueue();await v141FinishExecutionBaseV153();const q=await sb.from('km_route_executions').select('id,status,ended_at').eq('id',ex.id).maybeSingle();if(q.data?.status==='completed'){await v153CloseOpenDeviation(ex.id);await v147FlushQueue();msg('Roteiro finalizado com GPS e desvios consolidados')}else console.warn('v153 finish not confirmed',q.error||q.data)};window.v141FinishExecution=v141FinishExecution;
async function v153Health(){const box=document.getElementById('routeOpsDashboardV147');if(!box)return;let el=box.querySelector('.v153-health');if(!el){el=document.createElement('div');el.className='v153-health';box.prepend(el)}const pending=v147QueueRead().length,open=activeRouteExecutionV141?(await sb.from('km_route_deviations').select('id',{count:'exact',head:true}).eq('execution_id',activeRouteExecutionV141.id).eq('status','open')).count||0:0;el.innerHTML='<b>Integridade operacional</b><span>'+(navigator.onLine?'Online':'Offline')+' · '+pending+' GPS pendente(s) · '+open+' desvio(s) aberto(s)</span>'}
const v147RenderDashboardBaseV153=v147RenderDashboard;v147RenderDashboard=async function(){await v147RenderDashboardBaseV153();await v153Health()};window.v147RenderDashboard=v147RenderDashboard;window.addEventListener('online',()=>setTimeout(v147FlushQueue,500));setTimeout(()=>{v147FlushQueue();v153Health()},5500);
`;
rep('carga();',js+'\ncarga();','startup');rep('</style>',`\n/* v153 */\n.v153-health{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:8px 10px;border:1px solid #d9e8dc;border-radius:10px;background:#f7fbf7;margin-bottom:9px}.v153-health span{font-size:10px;color:#5e6f61}@media(max-width:760px){.v153-health{display:block}.v153-health span{display:block;margin-top:3px}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v153.0: idempotent offline GPS and confirmed route finish hardening ready');