const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v154 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 153.0','Gestão de deslocamentos · versão 154.0','version');rep('<span class="tag">153.0</span>','<span class="tag">154.0</span>','help');rep("checks.push(['Versão','153.0']);","checks.push(['Versão','154.0']);",'diag');
const js=`
// v154 field validation diagnostics for mobile GPS/offline/geofence
let v154LastGps=null,v154Watch=null,v154Log=[];
function v154LogPush(type,text){v154Log.unshift({at:new Date().toISOString(),type,text});v154Log=v154Log.slice(0,50);v154RenderFieldPanel()}
function v154GpsText(){if(!v154LastGps)return 'Sem leitura';const c=v154LastGps.coords||{};return Number.isFinite(Number(c.accuracy))?'±'+Math.round(c.accuracy)+' m':'Precisão desconhecida'}
async function v154TestGps(){try{const p=await v149GpsNow();v154LastGps=p;v154LogPush('ok','GPS obtido · '+v154GpsText());return true}catch(e){v154LogPush('bad','Falha de GPS · '+(e.message||e));return false}}
async function v154TestDb(){try{const r=await sb.from('km_route_plans').select('id').eq('organization_id',org.id).limit(1);if(r.error)throw r.error;v154LogPush('ok','Supabase acessível e RLS respondeu');return true}catch(e){v154LogPush('bad','Falha Supabase · '+(e.message||e));return false}}
async function v154TestQueue(){try{const rows=v147QueueRead();v154LogPush('ok','Fila offline legível · '+rows.length+' ponto(s) pendente(s)');return true}catch(e){v154LogPush('bad','Fila offline indisponível');return false}}
async function v154TestRouteApi(){try{if(!v154LastGps)await v154TestGps();if(!v154LastGps)throw new Error('GPS necessário');const c=v154LastGps.coords,r=await fetch('/api/routes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({origin:c.latitude+','+c.longitude,destination:c.latitude+','+c.longitude,stops:[],optimize:false})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'HTTP '+r.status);v154LogPush('ok','API de rotas respondeu');return true}catch(e){v154LogPush('bad','API de rotas · '+(e.message||e));return false}}
async function v154RunFieldCheck(){v154Log=[];v154RenderFieldPanel();await v154TestGps();await v154TestDb();await v154TestQueue();await v154TestRouteApi();const pending=v147QueueRead().length,online=navigator.onLine;v154LogPush(online?'ok':'warn',(online?'Online':'Offline')+' · fila '+pending+' ponto(s)');}
window.v154RunFieldCheck=v154RunFieldCheck;
function v154StartLiveGps(){if(v154Watch!=null||!navigator.geolocation)return;v154Watch=navigator.geolocation.watchPosition(p=>{v154LastGps=p;v154RenderFieldPanel()},e=>v154LogPush('bad','Monitor GPS · '+(e.message||e)),{enableHighAccuracy:true,maximumAge:5000,timeout:15000});v154LogPush('ok','Monitor de GPS iniciado')}
function v154StopLiveGps(){if(v154Watch!=null&&navigator.geolocation)navigator.geolocation.clearWatch(v154Watch);v154Watch=null;v154LogPush('ok','Monitor de GPS encerrado')}
window.v154StartLiveGps=v154StartLiveGps;window.v154StopLiveGps=v154StopLiveGps;
function v154RenderFieldPanel(){const box=document.getElementById('routeOpsDashboardV147');if(!box)return;let p=box.querySelector('.v154-field');if(!p){p=document.createElement('section');p.className='v154-field';box.appendChild(p)}const c=v154LastGps?.coords||{},q=v147QueueRead().length,active=!!activeRouteExecutionV141;p.innerHTML='<div class="v154-head"><div><b>Homologação de campo</b><span>Diagnóstico rápido para celular, GPS, rede e roteiros</span></div><div class="v154-actions"><button type="button" class="sec" onclick="v154RunFieldCheck()">Executar diagnóstico</button><button type="button" class="sec" onclick="'+(v154Watch==null?'v154StartLiveGps()':'v154StopLiveGps()')+'">'+(v154Watch==null?'Monitorar GPS':'Parar GPS')+'</button></div></div><div class="v154-kpis"><span><small>Rede</small><strong>'+(navigator.onLine?'Online':'Offline')+'</strong></span><span><small>Precisão GPS</small><strong>'+v154GpsText()+'</strong></span><span><small>Velocidade</small><strong>'+(Number.isFinite(Number(c.speed))?(Number(c.speed)*3.6).toFixed(1)+' km/h':'—')+'</strong></span><span><small>Fila offline</small><strong>'+q+'</strong></span><span><small>Roteiro ativo</small><strong>'+(active?'Sim':'Não')+'</strong></span></div><div class="v154-checks">'+(v154Log.length?v154Log.map(x=>'<div class="v154-log '+x.type+'"><span>'+new Date(x.at).toLocaleTimeString('pt-BR')+'</span><b>'+v139Esc(x.text)+'</b></div>').join(''):'<div class="muted small">Use “Executar diagnóstico” antes de um teste real de rua.</div>')+'</div>'}
window.v154RenderFieldPanel=v154RenderFieldPanel;
window.addEventListener('online',v154RenderFieldPanel);window.addEventListener('offline',v154RenderFieldPanel);const v147RenderDashboardBaseV154=v147RenderDashboard;v147RenderDashboard=async function(){await v147RenderDashboardBaseV154();v154RenderFieldPanel()};window.v147RenderDashboard=v147RenderDashboard;setTimeout(v154RenderFieldPanel,5500);
`;
rep('carga();',js+'\ncarga();','startup');rep('</style>',`\n/* v154 */\n.v154-field{margin-top:12px;padding:12px;border:1px solid #dce3eb;border-radius:14px;background:#fff}.v154-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.v154-head span{display:block;font-size:10px;color:#6b7280;margin-top:2px}.v154-actions{display:flex;gap:6px}.v154-kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:7px;margin:10px 0}.v154-kpis span{padding:8px;border-radius:9px;background:#f6f8fb}.v154-kpis small,.v154-kpis strong{display:block}.v154-kpis small{font-size:9px;color:#6b7280}.v154-log{display:grid;grid-template-columns:70px 1fr;gap:8px;padding:6px 8px;border-radius:8px;margin-top:5px;background:#f7f7f7;font-size:10px}.v154-log.ok{background:#f1f8f2}.v154-log.warn{background:#fff8eb}.v154-log.bad{background:#fff1f1}@media(max-width:760px){.v154-head{align-items:stretch;flex-direction:column}.v154-actions{display:grid;grid-template-columns:1fr 1fr}.v154-kpis{grid-template-columns:1fr 1fr}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v154.0: mobile field validation diagnostics ready');