const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v155 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 154.0','Gestão de deslocamentos · versão 155.0','version');rep('<span class="tag">154.0</span>','<span class="tag">155.0</span>','help');rep("checks.push(['Versão','154.0']);","checks.push(['Versão','155.0']);",'diag');
const js=`
// v155 safe backup restore: validate + preview + merge, never destructive
let v155RestorePayload=null;
const v155RestoreOrder=['km_locations','km_fleet_categories','km_vehicles','km_trips','km_stops','km_expenses','km_attachments','km_saved_routes','km_scheduled_trips','km_vehicle_maintenance','km_vehicle_costs','km_documents','km_incidents','km_incident_events','km_notifications','km_settings'];
const v155ProtectedTables=['km_organizations','km_user_profiles','km_user_access','km_user_location_access'];
function v155Esc(x){return String(x??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function v155CreateRestoreUI(){const page=document.getElementById('p-backup');if(!page||document.getElementById('backupRestoreV155'))return;const card=page.querySelector('.v138-card')||page.querySelector('.c')||page;card.insertAdjacentHTML('beforeend',`<div class="sep"></div><section id="backupRestoreV155" class="v155-restore"><div class="v155-restore-head"><div><h3>Restaurar backup</h3><div class="muted small">Importação segura por mesclagem. O processo não apaga dados existentes e não sobrescreve organização, usuários ou permissões.</div></div><label class="v155-file">Selecionar arquivo JSON<input id="backupRestoreFileV155" type="file" accept="application/json,.json"></label></div><div id="backupRestoreStatusV155" class="row muted">Nenhum arquivo selecionado.</div><div id="backupRestorePreviewV155"></div><div class="actions v155-actions"><button type="button" class="sec" id="backupRestoreClearV155" disabled>Limpar seleção</button><button type="button" id="backupRestoreRunV155" disabled>Restaurar por mesclagem</button></div></section>`);document.getElementById('backupRestoreFileV155').addEventListener('change',v155ReadBackupFile);document.getElementById('backupRestoreClearV155').onclick=v155ClearRestore;document.getElementById('backupRestoreRunV155').onclick=v155RestoreMerge}
function v155VersionOk(v){const n=parseFloat(String(v||'0'));return Number.isFinite(n)&&n>=138&&n<=155.99}
function v155ValidatePayload(p){const errors=[],warnings=[];if(!p||typeof p!=='object')errors.push('Arquivo JSON inválido');if(p?.format!=='controle-facil-km-backup')errors.push('Formato de backup não reconhecido');if(!v155VersionOk(p?.version))errors.push('Versão de backup incompatível');if(!p?.tables||typeof p.tables!=='object')errors.push('Conteúdo de tabelas ausente');if(p?.organization?.id&&org?.id&&p.organization.id!==org.id)errors.push('O backup pertence a outra organização');for(const t of v155ProtectedTables)if(Array.isArray(p?.tables?.[t])&&p.tables[t].length)warnings.push(t+' será ignorada por segurança');return {errors,warnings}}
function v155PreviewHtml(p,validation){const tables=p?.tables||{},rows=v155RestoreOrder.map(t=>({t,n:Array.isArray(tables[t])?tables[t].length:0})).filter(x=>x.n>0),total=rows.reduce((n,x)=>n+x.n,0),generated=p?.generated_at?new Date(p.generated_at).toLocaleString('pt-BR'):'—';return '<div class="v155-meta"><span><small>Organização</small><strong>'+v155Esc(p?.organization?.name||p?.organization?.id||'—')+'</strong></span><span><small>Versão</small><strong>'+v155Esc(p?.version||'—')+'</strong></span><span><small>Gerado em</small><strong>'+v155Esc(generated)+'</strong></span><span><small>Registros restauráveis</small><strong>'+total+'</strong></span></div>'+(validation.warnings.length?'<div class="v155-warn"><b>Proteção de acesso</b><div class="small">'+validation.warnings.map(v155Esc).join(' · ')+'</div></div>':'')+'<div class="v155-list">'+(rows.length?rows.map(x=>'<div><span>'+v155Esc(x.t.replace(/^km_/,'').replaceAll('_',' '))+'</span><b>'+x.n+'</b></div>').join(''):'<div class="row muted">Nenhum registro operacional restaurável neste arquivo.</div>')+'</div><div class="v155-note">Modo de restauração: <b>mesclar</b>. Registros com o mesmo ID são atualizados quando as permissões permitirem; registros novos são inseridos. Nada é excluído.</div>'}
async function v155ReadBackupFile(ev){const file=ev.target.files?.[0],st=document.getElementById('backupRestoreStatusV155'),pv=document.getElementById('backupRestorePreviewV155'),run=document.getElementById('backupRestoreRunV155'),clear=document.getElementById('backupRestoreClearV155');v155RestorePayload=null;run.disabled=true;clear.disabled=!file;if(!file){st.textContent='Nenhum arquivo selecionado.';pv.innerHTML='';return}st.className='row';st.textContent='Validando '+file.name+'...';try{if(file.size>50*1024*1024)throw new Error('Arquivo acima de 50 MB. Divida o backup antes da restauração.');const text=await file.text(),p=JSON.parse(text),v=v155ValidatePayload(p);if(v.errors.length)throw new Error(v.errors.join(' · '));v155RestorePayload=p;pv.innerHTML=v155PreviewHtml(p,v);const count=v155RestoreOrder.reduce((n,t)=>n+(Array.isArray(p.tables?.[t])?p.tables[t].length:0),0);st.className='row '+(v.warnings.length?'warn':'');st.innerHTML='<b>Backup validado</b><div class="muted small">'+v155Esc(file.name)+' · '+count+' registro(s) operacionais disponíveis para mesclagem.</div>';run.disabled=count===0}catch(e){st.className='row warn';st.textContent='Arquivo recusado: '+(e.message||e);pv.innerHTML='';msg(e.message||'Backup inválido',true)}}
function v155ClearRestore(){v155RestorePayload=null;const f=document.getElementById('backupRestoreFileV155');if(f)f.value='';document.getElementById('backupRestorePreviewV155').innerHTML='';const st=document.getElementById('backupRestoreStatusV155');st.className='row muted';st.textContent='Nenhum arquivo selecionado.';document.getElementById('backupRestoreRunV155').disabled=true;document.getElementById('backupRestoreClearV155').disabled=true}
function v155SanitizeRows(table,rows){return (rows||[]).filter(x=>x&&typeof x==='object').map(row=>{const x={...row};if('organization_id' in x)x.organization_id=org.id;if(table==='km_notifications'&&x.user_id&&x.user_id!==ses.user.id&&!(team||[]).some(u=>u.user_id===x.user_id))return null;return x}).filter(Boolean)}
async function v155UpsertChunks(table,rows){let done=0;for(let i=0;i<rows.length;i+=100){const batch=rows.slice(i,i+100),r=await sb.from(table).upsert(batch,{onConflict:'id',ignoreDuplicates:false});if(r.error)throw new Error(table+': '+r.error.message);done+=batch.length;const st=document.getElementById('backupRestoreStatusV155');if(st)st.textContent='Restaurando '+table+' · '+done+'/'+rows.length}return done}
async function v155RestoreMerge(){if(!v155RestorePayload||!org)return;const validation=v155ValidatePayload(v155RestorePayload);if(validation.errors.length)return msg(validation.errors.join(' · '),true);if(!confirm('Restaurar este backup por mesclagem? Nenhum dado atual será apagado.'))return;const run=document.getElementById('backupRestoreRunV155'),st=document.getElementById('backupRestoreStatusV155');run.disabled=true;let restored=0,failed=[];try{for(const table of v155RestoreOrder){const raw=v155RestorePayload.tables?.[table];if(!Array.isArray(raw)||!raw.length)continue;const rows=v155SanitizeRows(table,raw);try{restored+=await v155UpsertChunks(table,rows)}catch(e){failed.push(e.message||String(e))}}st.className='row '+(failed.length?'warn':'');st.innerHTML='<b>Restauração concluída: '+restored+' registro(s) processado(s)</b><div class="muted small">'+(failed.length?failed.length+' etapa(s) foram recusadas pelo banco/permissão e permaneceram inalteradas.':'Mesclagem concluída sem erros.')+'</div>';msg(failed.length?'Restauração concluída com avisos':'Backup restaurado por mesclagem',!!failed.length);try{await render()}catch{} }catch(e){st.className='row warn';st.textContent='Falha na restauração: '+(e.message||e);msg(e.message||'Falha na restauração',true)}finally{run.disabled=false}}
window.v155RestoreMerge=v155RestoreMerge;window.v155ClearRestore=v155ClearRestore;
const v138CreateUIBaseV155=v138CreateUI;v138CreateUI=function(){v138CreateUIBaseV155();setTimeout(v155CreateRestoreUI,0)};setTimeout(v155CreateRestoreUI,2600);
`;
rep('carga();',js+'\ncarga();','startup');rep('</style>',`\n/* v155 backup restore */\n.v155-restore{margin-top:12px}.v155-restore-head{display:flex;justify-content:space-between;align-items:center;gap:14px}.v155-restore-head h3{margin:0 0 4px}.v155-file{display:inline-flex;align-items:center;justify-content:center;padding:9px 12px;border:1px solid #cfd8e6;border-radius:9px;background:#fff;cursor:pointer;font-size:12px;font-weight:700}.v155-file input{display:none}.v155-meta{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin:10px 0}.v155-meta span{padding:9px;border:1px solid #e2e7ef;border-radius:10px;background:#fff}.v155-meta small,.v155-meta strong{display:block}.v155-meta small{font-size:9px;color:#6b7280}.v155-meta strong{margin-top:3px;font-size:12px}.v155-list{display:grid;grid-template-columns:repeat(2,1fr);gap:6px;margin:8px 0}.v155-list>div{display:flex;justify-content:space-between;gap:8px;padding:8px 10px;border-radius:9px;background:#f7f9fc;font-size:11px;text-transform:capitalize}.v155-warn{padding:9px 10px;border:1px solid #eed7ac;background:#fff9ec;border-radius:9px;margin:8px 0}.v155-note{padding:9px 10px;border-left:3px solid #5673a8;background:#f5f8fd;border-radius:8px;font-size:11px}.v155-actions{justify-content:flex-end;margin-top:10px}@media(max-width:760px){.v155-restore-head{align-items:stretch;flex-direction:column}.v155-meta{grid-template-columns:1fr 1fr}.v155-list{grid-template-columns:1fr}.v155-file{width:100%}.v155-actions{display:grid;grid-template-columns:1fr}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v155.0: safe backup restore preview and merge ready');