const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v156 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 155.0','Gestão de deslocamentos · versão 156.0','version');rep('<span class="tag">155.0</span>','<span class="tag">156.0</span>','help');rep("checks.push(['Versão','155.0']);","checks.push(['Versão','156.0']);",'diag');
const js=`
// v156 agenda recurrence, reminders and one-tap trip creation
function v156AddRecurrence(date,kind,n){const d=new Date(date);if(kind==='daily')d.setDate(d.getDate()+n);else if(kind==='weekly')d.setDate(d.getDate()+7*n);else if(kind==='monthly')d.setMonth(d.getMonth()+n);return d}
function v156Occurrences(kind){return kind==='daily'?14:kind==='weekly'?8:kind==='monthly'?6:1}
async function v156SaveSchedule(){if(!org)return;const when=document.getElementById('agendaWhenV138').value,dest=document.getElementById('agendaDestV138').value.trim(),uid=document.getElementById('agendaUserV138').value;if(!when)return msg('Informe data e hora',true);if(!dest)return msg('Informe o destino',true);if(!uid)return msg('Selecione o usuário',true);const recurrence=document.getElementById('agendaRecurrenceV138').value||'none',base=new Date(when),count=v156Occurrences(recurrence),common={organization_id:org.id,user_id:uid,vehicle_id:document.getElementById('agendaVehicleV138').value||null,origin:document.getElementById('agendaOriginV138').value.trim()||null,destination:dest,purpose:document.getElementById('agendaPurposeV138').value.trim()||null,recurrence,status:'scheduled',created_by:ses.user.id,notes:document.getElementById('agendaNotesV138').value.trim()||null,usage_type:document.getElementById('agendaUsageV138').value,planned_stops:[],planned_expenses:[],odometer_mode:'manual',google_calendar_sync_status:'not_requested'};const rows=[];for(let i=0;i<count;i++)rows.push({...common,scheduled_at:v156AddRecurrence(base,recurrence,i).toISOString()});const r=await sb.from('km_scheduled_trips').insert(rows);if(r.error)return msg(r.error.message,true);['agendaOriginV138','agendaDestV138','agendaPurposeV138','agendaNotesV138'].forEach(id=>document.getElementById(id).value='');document.getElementById('agendaWhenV138').value='';document.getElementById('agendaRecurrenceV138').value='none';v138AgendaDefaults();await v138LoadAgenda();msg(count>1?('Série criada com '+count+' agendamentos'):'Deslocamento agendado')}
window.v138SaveSchedule=v156SaveSchedule;const saveBtn=document.getElementById('agendaSaveV138');if(saveBtn)saveBtn.onclick=v156SaveSchedule;
function v156ReminderLevel(x){const ms=new Date(x.scheduled_at)-Date.now(),m=Math.round(ms/60000);if(ms<0)return {cls:'warn',txt:'Atrasado'};if(m<=15)return {cls:'warn',txt:'Sai em '+m+' min'};if(m<=60)return {cls:'',txt:'Em '+m+' min'};return null}
async function v156StartScheduledTrip(id){const a=scheduledV138.find(x=>x.id===id);if(!a)return msg('Agendamento não encontrado',true);if(a.trip_id)return msg('Este agendamento já foi transformado em viagem',true);const km=Number(prompt('KM inicial do veículo'));if(!Number.isFinite(km)||km<0)return msg('Informe um KM inicial válido',true);const started=new Date().toISOString(),trip={organization_id:org.id,location_id:a.location_id||null,user_id:a.user_id,vehicle_id:a.vehicle_id||null,trip_date:started.slice(0,10),started_at:started,origin:a.origin||null,destination:a.destination,start_odometer:km,end_odometer:null,distance_km:null,notes:a.notes||null,status:'in_progress',usage_type:a.usage_type||'work',purpose:a.purpose||null};const r=await sb.from('km_trips').insert(trip).select().single();if(r.error)return msg(r.error.message,true);const up=await sb.from('km_scheduled_trips').update({trip_id:r.data.id,status:'done',updated_at:new Date().toISOString()}).eq('id',id);if(up.error)console.warn('agenda link trip',up.error);await v138LoadAgenda();try{if(typeof load==='function')await load();}catch{}msg('Viagem iniciada a partir da agenda')}
window.v156StartScheduledTrip=v156StartScheduledTrip;
async function v156CreateRouteFromSchedule(id){const a=scheduledV138.find(x=>x.id===id);if(!a)return msg('Agendamento não encontrado',true);if(typeof v139FeatureEnabled==='function'&&!v139FeatureEnabled())return msg('Módulo de roteiros operacionais não está habilitado',true);if(!String(a.origin||'').trim())return msg('Informe uma origem no agendamento antes de criar o roteiro',true);const name=(a.purpose||a.destination||'Roteiro agendado')+' · '+new Date(a.scheduled_at).toLocaleDateString('pt-BR'),plan={organization_id:org.id,name,route_date:new Date(a.scheduled_at).toISOString().slice(0,10),driver_user_id:a.user_id,vehicle_id:a.vehicle_id||null,location_id:a.location_id||null,status:'draft',planned_start_at:a.scheduled_at,round_trip:false,notes:'Criado a partir da Agenda',created_by:ses.user.id};const pr=await sb.from('km_route_plans').insert(plan).select().single();if(pr.error)return msg(pr.error.message,true);const stops=[{organization_id:org.id,route_plan_id:pr.data.id,stop_order:1,name:'Origem',address:a.origin,status:'pending'},{organization_id:org.id,route_plan_id:pr.data.id,stop_order:2,name:a.destination,address:a.destination,status:'pending'}];const sr=await sb.from('km_route_stops').insert(stops);if(sr.error){await sb.from('km_route_plans').delete().eq('id',pr.data.id);return msg(sr.error.message,true)};if(typeof v139Load==='function')await v139Load();msg('Roteiro criado a partir do agendamento')}
window.v156CreateRouteFromSchedule=v156CreateRouteFromSchedule;
const v138RenderAgendaBaseV156=v138RenderAgenda;v138RenderAgenda=function(){v138RenderAgendaBaseV156();document.querySelectorAll('#agendaUpcomingV138 .v138-agenda-row,#agendaListV138 .v138-agenda-row').forEach(row=>{const b=row.querySelector('b');if(!b)return;const txt=b.textContent;const a=scheduledV138.find(x=>x.destination===txt&&!row.dataset.v156Bound);if(!a)return;row.dataset.v156Bound='1';const actions=row.querySelector('.actions');if(actions){actions.insertAdjacentHTML('afterbegin','<button class="sec" onclick="v156StartScheduledTrip(\\''+a.id+'\\')">Iniciar viagem</button><button class="sec" onclick="v156CreateRouteFromSchedule(\\''+a.id+'\\')">Criar roteiro</button>')}const rem=v156ReminderLevel(a);if(rem){const t=document.createElement('span');t.className='tag '+rem.cls;t.textContent=rem.txt;b.insertAdjacentElement('afterend',t)}})};window.v138RenderAgenda=v138RenderAgenda;
function v156AgendaSummary(){const box=document.getElementById('p-agenda');if(!box)return;let el=document.getElementById('agendaReminderV156');if(!el){el=document.createElement('div');el.id='agendaReminderV156';el.className='v156-reminder';const card=box.querySelector('.v138-card');card?.insertBefore(el,card.children[1]||null)}const next=scheduledV138.filter(x=>x.status==='scheduled').map(x=>({...x,ms:new Date(x.scheduled_at)-Date.now()})).filter(x=>x.ms>=-86400000).sort((a,b)=>a.ms-b.ms)[0];if(!next){el.innerHTML='<b>Próximo compromisso</b><span>Nenhum agendamento futuro.</span>';return}const rem=v156ReminderLevel(next);el.innerHTML='<b>Próximo compromisso</b><span>'+v137Esc(v138FmtDT(next.scheduled_at))+' · '+v137Esc(next.destination)+(rem?' · '+v137Esc(rem.txt):'')+'</span>'}
const v138LoadAgendaBaseV156=v138LoadAgenda;v138LoadAgenda=async function(){await v138LoadAgendaBaseV156();v156AgendaSummary()};window.v138LoadAgenda=v138LoadAgenda;setInterval(()=>{if(document.getElementById('p-agenda')&&!document.getElementById('p-agenda').classList.contains('hide')){v138RenderAgenda();v156AgendaSummary()}},60000);
`;
rep('carga();',js+'\ncarga();','startup');rep('</style>',`\n/* v156 */\n.v156-reminder{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:10px 12px;margin:0 0 12px;border:1px solid #e4dccf;border-radius:11px;background:#fffaf4}.v156-reminder span{font-size:11px;color:#6b7280}@media(max-width:760px){.v156-reminder{align-items:flex-start;flex-direction:column}.v138-agenda-row .actions{flex-wrap:wrap}.v138-agenda-row .actions button{min-width:44%}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v156.0: agenda recurrence, reminders and trip/route conversion ready');