const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v157 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 156.0','Gestão de deslocamentos · versão 157.0','version');rep('<span class="tag">156.0</span>','<span class="tag">157.0</span>','help');rep("checks.push(['Versão','156.0']);","checks.push(['Versão','157.0']);",'diag');
const js=`
// v157 internal fleet completeness: maintenance, costs, documents, incidents, alerts
let v157Maintenance=[],v157Costs=[],v157Alerts=[];
const v157Money=n=>'R$ '+Number(n||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const v157Date=d=>d?new Date(String(d).length===10?d+'T12:00:00':d).toLocaleDateString('pt-BR'):'—';
function v157Vehicle(id){return (window._fleetV137||[]).find(x=>x.id===id)}
function v157Days(d){if(!d)return null;return Math.ceil((new Date(d+'T12:00:00')-new Date())/86400000)}
function v157Due(m){const v=v157Vehicle(m.vehicle_id),dd=v157Days(m.due_date),km=m.due_odometer==null?null:Number(m.due_odometer)-Number(v?.current_odometer||0);if(m.completed_at)return {level:'ok',text:'Concluída'};if((dd!=null&&dd<0)||(km!=null&&km<0))return {level:'danger',text:'Vencida'};if((dd!=null&&dd<=30)||(km!=null&&km<=1000))return {level:'warn',text:'Próxima'};return {level:'ok',text:'Em dia'}}
function v157EnsureUI(){const p=document.querySelector('#p-documentos .v137-card');if(p&&!document.getElementById('v157FleetOps')){p.insertAdjacentHTML('beforeend',\`<div class="sep"></div><section id="v157FleetOps"><h3>Manutenção preventiva e custos</h3><div class="v157-grid"><div class="row"><b>Programar manutenção</b><select id="v157MaintVehicle"></select><div class="r"><select id="v157MaintType"><option value="oil">Troca de óleo</option><option value="tires">Pneus</option><option value="brakes">Freios</option><option value="filters">Filtros</option><option value="inspection">Revisão</option><option value="other">Outro</option></select><input id="v157MaintDesc" placeholder="Descrição"></div><div class="r"><input id="v157MaintDate" type="date"><input id="v157MaintKm" type="number" step="1" placeholder="KM limite"></div><button type="button" onclick="v157SaveMaintenance()">Programar</button></div><div class="row"><b>Registrar custo do veículo</b><select id="v157CostVehicle"></select><div class="r"><select id="v157CostType"><option value="fuel">Combustível</option><option value="maintenance">Manutenção</option><option value="insurance">Seguro</option><option value="tax">Licenciamento/imposto</option><option value="toll">Pedágio</option><option value="parking">Estacionamento</option><option value="other">Outro</option></select><input id="v157CostAmount" type="number" min="0" step="0.01" placeholder="Valor"></div><input id="v157CostDesc" placeholder="Descrição"><button type="button" onclick="v157SaveCost()">Registrar custo</button></div></div><div id="v157FleetSummary" class="v157-summary"></div><div id="v157MaintList"></div></section>\`)}const si=document.querySelector('#p-sinistros .v137-card');if(si&&!document.getElementById('v157IncidentPanel'))si.insertAdjacentHTML('beforeend',\`<section id="v157IncidentPanel"><div class="sep"></div><h3>Gestão da ocorrência</h3><div class="muted small">Atualize responsável, custos, seguradora e andamento até o encerramento.</div><div id="v157IncidentManage"></div></section>\`)} }
function v157FillVehicles(){const opts='<option value="">Selecione o veículo</option>'+(window._fleetV137||[]).map(v=>'<option value="'+v.id+'">'+v137Esc(v.description+(v.plate?' · '+v.plate:''))+'</option>').join('');['v157MaintVehicle','v157CostVehicle'].forEach(id=>{const e=document.getElementById(id);if(e)e.innerHTML=opts})}
async function v157LoadFleetOps(){if(!org)return;const [m,c]=await Promise.all([sb.from('km_vehicle_maintenance').select('*').eq('organization_id',org.id).order('due_date',{ascending:true,nullsFirst:false}),sb.from('km_vehicle_costs').select('*').eq('organization_id',org.id).order('cost_date',{ascending:false}).limit(300)]);v157Maintenance=m.data||[];v157Costs=c.data||[];v157RenderFleetOps();await v157InternalAlerts()}
window.v157SaveMaintenance=async()=>{const vehicle_id=document.getElementById('v157MaintVehicle')?.value,due_date=document.getElementById('v157MaintDate')?.value||null,due_odometer=Number(document.getElementById('v157MaintKm')?.value||0)||null;if(!vehicle_id)return msg('Selecione o veículo',true);if(!due_date&&!due_odometer)return msg('Informe a data ou o KM limite',true);const r=await sb.from('km_vehicle_maintenance').insert({organization_id:org.id,vehicle_id,maintenance_type:document.getElementById('v157MaintType').value,description:document.getElementById('v157MaintDesc').value.trim()||null,due_date,due_odometer,created_by:ses.user.id});if(r.error)return msg(r.error.message,true);await v157LoadFleetOps();msg('Manutenção programada')};
window.v157CompleteMaintenance=async id=>{const m=v157Maintenance.find(x=>x.id===id);if(!m)return;const km=prompt('KM do veículo na conclusão',String(v157Vehicle(m.vehicle_id)?.current_odometer||''));if(km===null)return;const amount=prompt('Valor da manutenção (opcional)','0');const now=new Date().toISOString();const r=await sb.from('km_vehicle_maintenance').update({completed_at:now,completed_odometer:Number(km||0)||null,amount:Number(amount||0)||null,updated_at:now}).eq('id',id);if(r.error)return msg(r.error.message,true);if(Number(km)>0)await sb.from('km_vehicles').update({current_odometer:Number(km),updated_at:now}).eq('id',m.vehicle_id);await v157LoadFleetOps();await v137LoadFleet();msg('Manutenção concluída')};
window.v157SaveCost=async()=>{const vehicle_id=document.getElementById('v157CostVehicle')?.value,amount=Number(document.getElementById('v157CostAmount')?.value||0);if(!vehicle_id||!(amount>0))return msg('Selecione o veículo e informe um valor',true);const r=await sb.from('km_vehicle_costs').insert({organization_id:org.id,vehicle_id,cost_type:document.getElementById('v157CostType').value,description:document.getElementById('v157CostDesc').value.trim()||null,amount,cost_date:new Date().toISOString().slice(0,10),created_by:ses.user.id,recurrence:'one_time',include_in_total:true});if(r.error)return msg(r.error.message,true);document.getElementById('v157CostAmount').value='';document.getElementById('v157CostDesc').value='';await v157LoadFleetOps();msg('Custo registrado')};
function v157RenderFleetOps(){const sum=document.getElementById('v157FleetSummary');const open=v157Maintenance.filter(x=>!x.completed_at),over=open.filter(x=>v157Due(x).level==='danger'),near=open.filter(x=>v157Due(x).level==='warn'),month=new Date().toISOString().slice(0,7),cost=v157Costs.filter(x=>String(x.cost_date).startsWith(month)&&x.include_in_total!==false).reduce((n,x)=>n+Number(x.amount||0),0);if(sum)sum.innerHTML='<span><small>Manutenções abertas</small><b>'+open.length+'</b></span><span><small>Vencidas</small><b>'+over.length+'</b></span><span><small>Próximas</small><b>'+near.length+'</b></span><span><small>Custos no mês</small><b>'+v157Money(cost)+'</b></span>';const list=document.getElementById('v157MaintList');if(list)list.innerHTML=open.length?open.map(m=>{const v=v157Vehicle(m.vehicle_id),d=v157Due(m);return '<div class="row v157-maint '+d.level+'"><div><b>'+v137Esc(v?.description||'Veículo')+' · '+v137Esc(m.maintenance_type)+'</b> <span class="tag">'+d.text+'</span><div class="muted small">'+v137Esc(m.description||'')+(m.due_date?' · até '+v157Date(m.due_date):'')+(m.due_odometer?' · '+Number(m.due_odometer).toLocaleString('pt-BR')+' km':'')+'</div></div><button class="sec" onclick="v157CompleteMaintenance(\\''+m.id+'\\')">Concluir</button></div>'}).join(''):'<div class="row muted">Nenhuma manutenção pendente.</div>'}
async function v157InternalAlerts(){if(!org||!ses?.user?.id)return;const alerts=[];for(const d of docsV137||[]){const days=v157Days(d.expires_at);if(days!=null&&days<=30)alerts.push({key:'doc:'+d.id,title:days<0?'Documento vencido':'Documento próximo do vencimento',body:(d.title||d.document_type)+' · '+(days<0?'vencido':'vence em '+days+' dia(s)'),severity:days<0?'danger':'warning',document_id:d.id})}for(const m of v157Maintenance.filter(x=>!x.completed_at)){const du=v157Due(m);if(du.level!=='ok')alerts.push({key:'maint:'+m.id,title:du.level==='danger'?'Manutenção vencida':'Manutenção próxima',body:(v157Vehicle(m.vehicle_id)?.description||'Veículo')+' · '+m.maintenance_type,severity:du.level==='danger'?'danger':'warning',vehicle_id:m.vehicle_id})}v157Alerts=alerts;for(const a of alerts){const q=await sb.from('km_notifications').select('id').eq('organization_id',org.id).eq('user_id',ses.user.id).eq('event_type',a.key).limit(1);if(!(q.data||[]).length)await sb.from('km_notifications').insert({organization_id:org.id,user_id:ses.user.id,title:a.title,body:a.body,event_type:a.key,created_by:ses.user.id,vehicle_id:a.vehicle_id||null,document_id:a.document_id||null,severity:a.severity})}}
function v157RenderIncidentManage(){const box=document.getElementById('v157IncidentManage');if(!box)return;box.innerHTML=(incidentsV137||[]).filter(x=>x.status!=='closed').map(x=>{const v=v157Vehicle(x.vehicle_id);return '<div class="row v157-inc"><b>'+v137Esc(v?.description||'Veículo')+' · '+v137Esc(x.incident_type)+'</b><div class="muted small">Status: '+v137Esc(x.status)+' · estimado '+v157Money(x.estimated_cost)+' · final '+v157Money(x.final_cost)+'</div><div class="actions"><button class="sec" onclick="v157AdvanceIncident(\\''+x.id+'\\')">Atualizar</button><button onclick="v157CloseIncident(\\''+x.id+'\\')">Encerrar</button></div></div>'}).join('')||'<div class="row muted">Nenhum sinistro aberto.</div>'}
window.v157AdvanceIncident=async id=>{const x=incidentsV137.find(z=>z.id===id);if(!x)return;const status=prompt('Status: open, under_review, repair, awaiting_insurer, resolved',x.status||'under_review');if(!status)return;const est=prompt('Custo estimado',String(x.estimated_cost||0));const insurer=prompt('Seguradora',x.insurer||'');const claim=prompt('Número do sinistro',x.claim_number||'');const note=prompt('Observação desta atualização','')||'';const now=new Date().toISOString();let r=await sb.from('km_incidents').update({status,estimated_cost:Number(est||0)||null,insurer:insurer||null,claim_number:claim||null,responsible_user_id:ses.user.id,updated_at:now}).eq('id',id);if(r.error)return msg(r.error.message,true);await sb.from('km_incident_events').insert({incident_id:id,organization_id:org.id,event_type:'status_update',notes:note||null,data:{status,estimated_cost:Number(est||0)||0},created_by:ses.user.id});await v137LoadIncidents();v157RenderIncidentManage();msg('Sinistro atualizado')};
window.v157CloseIncident=async id=>{const x=incidentsV137.find(z=>z.id===id);if(!x)return;const final=prompt('Custo final',String(x.final_cost||x.estimated_cost||0));if(final===null)return;const reimb=prompt('Reembolso da seguradora',String(x.insurer_reimbursement||0));if(reimb===null)return;const note=prompt('Observação de encerramento','')||'';const f=Number(final||0),rmb=Number(reimb||0),now=new Date().toISOString();const r=await sb.from('km_incidents').update({status:'closed',final_cost:f,insurer_reimbursement:rmb,company_net_cost:Math.max(0,f-rmb),closed_at:now,updated_at:now}).eq('id',id);if(r.error)return msg(r.error.message,true);await sb.from('km_incident_events').insert({incident_id:id,organization_id:org.id,event_type:'closed',notes:note||null,data:{final_cost:f,insurer_reimbursement:rmb,company_net_cost:Math.max(0,f-rmb)},created_by:ses.user.id});await v137LoadIncidents();v157RenderIncidentManage();msg('Sinistro encerrado')};
const v137LoadFleetBaseV157=v137LoadFleet;v137LoadFleet=async function(){await v137LoadFleetBaseV157();v157EnsureUI();v157FillVehicles();await v157LoadFleetOps()};
const v137LoadDocsBaseV157=v137LoadDocs;v137LoadDocs=async function(){await v137LoadDocsBaseV157();setTimeout(v157InternalAlerts,0)};
const v137LoadIncidentsBaseV157=v137LoadIncidents;v137LoadIncidents=async function(){await v137LoadIncidentsBaseV157();v157RenderIncidentManage()};
const renderBaseV157=render;render=function(){renderBaseV157();setTimeout(()=>{v157EnsureUI();v157FillVehicles();v157RenderFleetOps();v157RenderIncidentManage()},0)};setTimeout(()=>{v157EnsureUI();v157FillVehicles();v157LoadFleetOps();v157RenderIncidentManage()},3200);
`;
rep('carga();',js+'\ncarga();','startup');rep('</style>',`\n/* v157 internal fleet completeness */\n.v157-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.v157-grid .row{display:flex;flex-direction:column;gap:7px}.v157-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:12px 0}.v157-summary span{padding:10px;border:1px solid #e1e6ef;border-radius:11px;background:#fff}.v157-summary small,.v157-summary b{display:block}.v157-summary b{font-size:17px;margin-top:3px}.v157-maint{display:flex;justify-content:space-between;align-items:center;gap:10px}.v157-maint.warn{border-left:3px solid #d49a22}.v157-maint.danger{border-left:3px solid #c84f4f}.v157-inc .actions{display:flex;gap:6px;margin-top:7px}@media(max-width:760px){.v157-grid,.v157-summary{grid-template-columns:1fr 1fr}.v157-grid{grid-template-columns:1fr}.v157-maint{align-items:stretch;flex-direction:column}.v157-maint button{width:100%}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v157.0: fleet maintenance, costs, document alerts and incident lifecycle ready');