const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v158 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 157.0','Gestão de deslocamentos · versão 158.0','version');rep('<span class="tag">157.0</span>','<span class="tag">158.0</span>','help');rep("checks.push(['Versão','157.0']);","checks.push(['Versão','158.0']);",'diag');
const js=`
// v158 internal user roles + location access
let v158Locations=[],v158LocationAccess=[];
function v158CanManageUsers(){return ['admin','manager'].includes(acc?.module_role)}
async function v158LoadAccessData(){if(!org)return;const [l,a]=await Promise.all([sb.from('km_locations').select('*').eq('organization_id',org.id).order('name'),sb.from('km_user_location_access').select('*').eq('organization_id',org.id)]);v158Locations=l.data||[];v158LocationAccess=a.data||[];v158RenderAccess()}
function v158EnsureUI(){const p=document.querySelector('#p-equipe .c');if(!p||document.getElementById('v158Access'))return;p.insertAdjacentHTML('beforeend',\`<div class="sep"></div><section id="v158Access"><h3>Perfis e permissões</h3><div class="muted small">Administração interna por função e unidades permitidas. Administrador possui acesso integral; gerente e supervisor podem operar conforme as políticas da organização.</div><div id="v158AccessList" style="margin-top:10px"></div></section>\`)}
function v158RenderAccess(){v158EnsureUI();const box=document.getElementById('v158AccessList');if(!box)return;box.innerHTML=(team||[]).map(u=>{const role=u.module_role||u.role||'driver',locs=v158LocationAccess.filter(x=>x.user_id===u.user_id).map(x=>v158Locations.find(l=>l.id===x.location_id)?.name).filter(Boolean),name=u.profile?.full_name||u.profile?.email||u.user_id,disabled=!v158CanManageUsers()||u.user_id===ses.user.id;return '<div class="row v158-user"><div><b>'+v137Esc(name)+'</b><div class="muted small">'+v137Esc(role)+' · '+(locs.length?v137Esc(locs.join(', ')):'Todas/sem restrição explícita')+'</div></div><div class="v158-actions"><select '+(disabled?'disabled':'')+' onchange="v158Role(\\''+u.user_id+'\\',this.value)"><option value="driver" '+(role==='driver'?'selected':'')+'>Motorista</option><option value="supervisor" '+(role==='supervisor'?'selected':'')+'>Supervisor</option><option value="manager" '+(role==='manager'?'selected':'')+'>Gerente</option><option value="admin" '+(role==='admin'?'selected':'')+'>Administrador</option></select><button class="sec" '+(disabled?'disabled':'')+' onclick="v158LocationsDialog(\\''+u.user_id+'\\')">Unidades</button><button class="sec" '+(disabled?'disabled':'')+' onclick="v158ToggleUser(\\''+u.user_id+'\\','+(u.active===false?'true':'false')+')">'+(u.active===false?'Ativar':'Desativar')+'</button></div></div>'}).join('')||'<div class="row muted">Nenhum usuário cadastrado.</div>'}
window.v158Role=async(userId,role)=>{if(!v158CanManageUsers())return msg('Sem permissão',true);const r=await sb.from('km_user_access').update({module_role:role,updated_at:new Date().toISOString()}).eq('organization_id',org.id).eq('user_id',userId);if(r.error)return msg(r.error.message,true);await refreshAll();await v158LoadAccessData();msg('Perfil atualizado')};
window.v158ToggleUser=async(userId,active)=>{if(!v158CanManageUsers())return msg('Sem permissão',true);const r=await sb.from('km_user_access').update({active,updated_at:new Date().toISOString()}).eq('organization_id',org.id).eq('user_id',userId);if(r.error)return msg(r.error.message,true);await refreshAll();await v158LoadAccessData();msg(active?'Usuário ativado':'Usuário desativado')};
window.v158LocationsDialog=async userId=>{if(!v158CanManageUsers())return msg('Sem permissão',true);if(!v158Locations.length)return msg('Cadastre unidades antes de restringir o acesso',true);const current=new Set(v158LocationAccess.filter(x=>x.user_id===userId).map(x=>x.location_id));const text=v158Locations.map((l,i)=>(i+1)+'. '+l.name+(current.has(l.id)?' [ATIVA]':'')).join('\\n');const ans=prompt('Digite os números das unidades permitidas separados por vírgula. Deixe vazio para remover restrições.\\n\\n'+text,[...current].map(id=>v158Locations.findIndex(l=>l.id===id)+1).filter(x=>x>0).join(','));if(ans===null)return;const ids=String(ans).trim()?String(ans).split(',').map(x=>Number(x.trim())-1).filter(i=>i>=0&&i<v158Locations.length).map(i=>v158Locations[i].id):[];let r=await sb.from('km_user_location_access').delete().eq('organization_id',org.id).eq('user_id',userId);if(r.error)return msg(r.error.message,true);if(ids.length){r=await sb.from('km_user_location_access').insert(ids.map(location_id=>({organization_id:org.id,user_id:userId,location_id})));if(r.error)return msg(r.error.message,true)}await v158LoadAccessData();msg('Unidades permitidas atualizadas')};
const renderBaseV158=render;render=function(){renderBaseV158();setTimeout(()=>{v158EnsureUI();v158RenderAccess()},0)};setTimeout(()=>{v158EnsureUI();v158LoadAccessData()},3500);
`;
rep('carga();',js+'\ncarga();','startup');rep('</style>',`\n/* v158 user access */\n.v158-user{display:flex;align-items:center;justify-content:space-between;gap:10px}.v158-actions{display:flex;gap:6px;align-items:center}.v158-actions select{min-width:130px}@media(max-width:760px){.v158-user{align-items:stretch;flex-direction:column}.v158-actions{display:grid;grid-template-columns:1fr 1fr}.v158-actions select{grid-column:1/-1;width:100%}}\n</style>`,'css');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v158.0: user roles and location access ready');