const fs=require('fs');let s=fs.readFileSync('dist/index.html','utf8');const rep=(a,b,l)=>{if(!s.includes(a))throw new Error('v160 anchor '+l);s=s.replace(a,b)};
rep('Gestão de deslocamentos · versão 159.0','Gestão de deslocamentos · versão 160.0','version');rep('<span class="tag">159.0</span>','<span class="tag">160.0</span>','help');rep("checks.push(['Versão','159.0']);","checks.push(['Versão','160.0']);",'diag');
const js=`
// v160 agenda/db constraint alignment found by E2E
function v160Usage(v){return v==='personal'?'personal':'work'}
function v160FixAgendaSelect(){const x=document.getElementById('agendaUsageV138');if(!x)return;x.innerHTML='<option value="work">Profissional</option><option value="personal">Pessoal</option>';if(!['work','personal'].includes(x.value))x.value='work'}
async function v160SaveSchedule(){if(!org)return;const when=document.getElementById('agendaWhenV138').value,dest=document.getElementById('agendaDestV138').value.trim(),uid=document.getElementById('agendaUserV138').value;if(!when)return msg('Informe data e hora',true);if(!dest)return msg('Informe o destino',true);if(!uid)return msg('Selecione o usuário',true);const recurrence=document.getElementById('agendaRecurrenceV138').value||'none',base=new Date(when),count=v156Occurrences(recurrence),common={organization_id:org.id,user_id:uid,vehicle_id:document.getElementById('agendaVehicleV138').value||null,origin:document.getElementById('agendaOriginV138').value.trim()||null,destination:dest,purpose:document.getElementById('agendaPurposeV138').value.trim()||null,recurrence,status:'scheduled',created_by:ses.user.id,notes:document.getElementById('agendaNotesV138').value.trim()||null,usage_type:v160Usage(document.getElementById('agendaUsageV138').value),planned_stops:[],planned_expenses:[],odometer_mode:'start_end',google_calendar_sync_status:'pending'};const rows=[];for(let i=0;i<count;i++)rows.push({...common,scheduled_at:v156AddRecurrence(base,recurrence,i).toISOString()});const r=await sb.from('km_scheduled_trips').insert(rows);if(r.error)return msg(r.error.message,true);['agendaOriginV138','agendaDestV138','agendaPurposeV138','agendaNotesV138'].forEach(id=>document.getElementById(id).value='');document.getElementById('agendaWhenV138').value='';document.getElementById('agendaRecurrenceV138').value='none';v138AgendaDefaults();await v138LoadAgenda();msg(count>1?('Série criada com '+count+' agendamentos'):'Deslocamento agendado')}
window.v138SaveSchedule=v160SaveSchedule;
window.v138AgendaStatus=async(id,statusValue)=>{const normalized=statusValue==='done'?'completed':statusValue;const r=await sb.from('km_scheduled_trips').update({status:normalized,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)return msg(r.error.message,true);await v138LoadAgenda();msg(normalized==='completed'?'Agendamento concluído':'Agendamento cancelado')};
async function v160StartScheduledTrip(id){const a=scheduledV138.find(x=>x.id===id);if(!a)return msg('Agendamento não encontrado',true);if(a.trip_id)return msg('Este agendamento já foi transformado em viagem',true);const km=Number(prompt('KM inicial do veículo'));if(!Number.isFinite(km)||km<0)return msg('Informe um KM inicial válido',true);const started=new Date().toISOString(),trip={organization_id:org.id,location_id:a.location_id||null,user_id:a.user_id,vehicle_id:a.vehicle_id||null,trip_date:started.slice(0,10),started_at:started,origin:a.origin||null,destination:a.destination,start_odometer:km,end_odometer:null,notes:a.notes||null,status:'in_progress',usage_type:v160Usage(a.usage_type),purpose:a.purpose||null};const r=await sb.from('km_trips').insert(trip).select().single();if(r.error)return msg(r.error.message,true);const up=await sb.from('km_scheduled_trips').update({trip_id:r.data.id,status:'completed',updated_at:new Date().toISOString()}).eq('id',id);if(up.error)console.warn('agenda link trip',up.error);await v138LoadAgenda();try{if(typeof load==='function')await load()}catch{}msg('Viagem iniciada a partir da agenda')}
window.v156StartScheduledTrip=v160StartScheduledTrip;
const v138RenderAgendaBaseV160=v138RenderAgenda;v138RenderAgenda=function(){v138RenderAgendaBaseV160();document.querySelectorAll('#agendaUpcomingV138 .v138-agenda-row,#agendaListV138 .v138-agenda-row').forEach(row=>{const buttons=[...row.querySelectorAll('button')];for(const b of buttons){if(b.textContent==='Concluir'){const oc=b.getAttribute('onclick')||'';b.setAttribute('onclick',oc.replace("'done'","'completed'"))}}});v160FixAgendaSelect()};window.v138RenderAgenda=v138RenderAgenda;
setTimeout(()=>{v160FixAgendaSelect();const b=document.getElementById('agendaSaveV138');if(b)b.onclick=v160SaveSchedule},3600);
`;
rep('carga();',js+'\ncarga();','startup');fs.writeFileSync('dist/index.html',s);console.log('Controle KM v160.0: agenda constraints aligned by E2E');