const fs=require('fs');
let s=fs.readFileSync('dist/index.html','utf8');
const js=`
// v162.92: bottom navigation owns mobile, agenda calendar reads real scheduled trips and preserves Google Calendar handoff.
(function(){
 const byId=id=>document.getElementById(id), pad=n=>String(n).padStart(2,'0');
 function trips(){try{if(Array.isArray(globalThis.scheduledTrips))return globalThis.scheduledTrips}catch(_){}return []}
 function dateOf(x){const raw=x?.scheduled_at||x?.date||x?.data||x?.agData||'';if(!raw)return'';try{return new Date(raw).toISOString().slice(0,10)}catch(_){return String(raw).slice(0,10)}}
 function googleUrl(x){try{if(typeof globalThis.googleCalendarUrlV120==='function')return globalThis.googleCalendarUrlV120(x)}catch(_){}const raw=x?.scheduled_at||new Date().toISOString(),start=new Date(raw),end=new Date(start.getTime()+3600000),fmt=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z'),title=encodeURIComponent(x?.purpose||'Viagem programada - Movvant'),details=encodeURIComponent(((x?.origin||'')+(x?.origin&&x?.destination?' → ':'')+(x?.destination||''))+(x?.notes?'\\n'+x.notes:'')),loc=encodeURIComponent(x?.destination||'');return 'https://calendar.google.com/calendar/render?action=TEMPLATE&text='+title+'&dates='+fmt(start)+'/'+fmt(end)+'&details='+details+'&location='+loc}
 function openGoogle(x){window.open(googleUrl(x),'_blank','noopener')}
 function dayTrips(iso){return trips().filter(x=>dateOf(x)===iso)}
 function renderSelected(iso){const box=byId('mvAgendaSelected91');if(!box)return;const xs=dayTrips(iso),title=new Date(iso+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});box.innerHTML='<b>'+title+'</b>'+(xs.length?'<div class="mv-dayevents92"></div>':'<span>Nenhum compromisso programado para esta data.</span>');const list=box.querySelector('.mv-dayevents92');if(!list)return;xs.forEach(x=>{const row=document.createElement('div');row.className='mv-dayevent92';const t=x.scheduled_at?new Date(x.scheduled_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):'',label=x.purpose||x.destination||'Compromisso';row.innerHTML='<div><strong>'+label+'</strong><small>'+(t?t+' · ':'')+(x.destination||'Sem destino')+'</small></div><button type="button">Google Agenda</button>';row.querySelector('button').onclick=()=>openGoogle(x);list.appendChild(row)})}
 function bindCalendar(){document.querySelectorAll('#mvAgendaCal91 [data-date91],#mvDashCal91 [data-date91]').forEach(b=>{if(b.dataset.mv92)return;b.dataset.mv92='1';const iso=b.dataset.date91;if(dayTrips(iso).length)b.classList.add('has');b.addEventListener('click',()=>renderSelected(iso))})}
 function syncCalendarDots(){document.querySelectorAll('#mvAgendaCal91 [data-date91],#mvDashCal91 [data-date91]').forEach(b=>b.classList.toggle('has',dayTrips(b.dataset.date91).length>0))}
 function googleStatus(){const side=document.querySelector('#mvAgenda91 .mv-agenda-side91');if(!side||byId('mvGoogleAgenda92'))return;const box=document.createElement('div');box.id='mvGoogleAgenda92';box.className='mv-google92';box.innerHTML='<div><b>Google Agenda</b><span>Programações da Movvant podem ser enviadas ao Google Agenda.</span></div><small>A sincronização atual abre o evento pronto para confirmação no Google. Conexão automática em duas vias requer autorização OAuth da conta.</small>';side.appendChild(box)}
 function mobileShell(){const top=byId('mvTopNavV16282');if(top)top.classList.add('mv-mobiletop-hidden92');document.body.classList.add('mv-bottom-primary92')}
 function sync(){mobileShell();bindCalendar();syncCalendarDots();googleStatus()}
 [0,120,350,800,1500,2800].forEach(ms=>setTimeout(sync,ms));document.addEventListener('click',()=>setTimeout(sync,100),true);globalThis.mvAgendaV16292={sync,renderSelected,openGoogle};
})();
`;
if(!s.includes('carga();'))throw new Error('v162.92 startup anchor');s=s.replace('carga();',js+'\ncarga();');
const css=`
/* v162.92 */
.mv-dayevents92{display:grid;gap:7px;margin-top:9px}.mv-dayevent92{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:center;padding:9px;border:1px solid #e5eaf1;border-radius:6px;background:#fafcff}.mv-dayevent92 strong{display:block;font-size:11px;color:#22334d}.mv-dayevent92 small{display:block;margin-top:3px;font-size:9px;color:#7d8899}.mv-dayevent92 button{width:auto!important;min-height:30px!important;padding:0 9px!important;border-radius:5px!important;background:#fff!important;color:#0b63e5!important;border:1px solid #cdd8e7!important;font-size:9px!important}.mv-google92{margin-top:14px;padding-top:12px;border-top:1px solid #edf0f4;display:grid;gap:7px}.mv-google92>div{display:grid;gap:2px}.mv-google92 b{font-size:11px;color:#253750}.mv-google92 span,.mv-google92 small{font-size:9px;line-height:1.4;color:#7b8798}.mv-days91>button.has i{display:block!important}
@media(max-width:899px){#mvTopNavV16282.mv-mobiletop-hidden92{display:none!important;visibility:hidden!important;height:0!important;min-height:0!important;margin:0!important;padding:0!important;border:0!important;overflow:hidden!important;pointer-events:none!important}body.mv-bottom-primary92 #app{padding-top:0!important}body.mv-bottom-primary92 #app>section{padding-top:10px!important}#mvBottomDock85{display:grid!important}.mv-dayevent92{grid-template-columns:1fr}.mv-dayevent92 button{width:100%!important}}
`;
if(!s.includes('</style>'))throw new Error('v162.92 css anchor');s=s.replace('</style>',css+'\n</style>');fs.writeFileSync('dist/index.html',s);console.log('Movvant v162.92: mobile top legacy shell removed; agenda bound to scheduled trips and Google handoff');