const fs=require('fs');
let s=fs.readFileSync('dist/index.html','utf8');
const js=`
// v162.86: one coherent reference-driven design system across every Movvant screen.
(function(){
  const byId=id=>document.getElementById(id);
  const meta={
    inicio:['Dashboard','Visão geral da operação'],viagem:['Novo percurso','Planeje, salve ou inicie um deslocamento'],historico:['Viagens','Acompanhe percursos em andamento e finalizados'],agenda:['Agenda','Compromissos e deslocamentos programados'],rotas:['Rotas','Rotas frequentes e planejamento'],veiculos:['Frota','Veículos, quilometragem e disponibilidade'],custos:['Despesas','Custos e despesas da operação'],equipe:['Equipe','Usuários, perfis e acessos'],relatorios:['Relatórios','Indicadores e análise da operação'],ajuda:['Central de ajuda','Orientações para uso do Movvant'],perfil:['Meu perfil','Dados pessoais e permissões'],painel:['Painel administrativo','Visão consolidada da operação'],notificacoes:['Avisos','Alertas e movimentações recentes'],auditoria:['Auditoria','Registro de movimentações do sistema'],backup:['Backup / Restauração','Proteção e portabilidade dos dados'],config:['Configurações','Preferências, políticas e parâmetros da empresa'],recursos:['Recursos','Recursos disponíveis para esta assinatura'],assinatura:['Assinatura','Plano, limites e recursos contratados']
  };
  const icon={inicio:'⌂',viagem:'↗',historico:'▤',agenda:'▦',rotas:'⌁',veiculos:'▥',custos:'▣',equipe:'♙',relatorios:'▧',ajuda:'?',perfil:'●',painel:'◇',notificacoes:'!',auditoria:'✓',backup:'↻',config:'⚙',recursos:'＋',assinatura:'★'};
  function pageName(sec){return sec?.id?.replace(/^p-/,'')||''}
  function pageHeader(sec){
    const p=pageName(sec);if(!p)return;const m=meta[p]||[p.charAt(0).toUpperCase()+p.slice(1),''];
    let head=sec.querySelector(':scope > .mv-page86');
    if(!head){head=document.createElement('header');head.className='mv-page86';head.innerHTML='<div class="mv-page-title86"><span class="mv-page-icon86">'+(icon[p]||'•')+'</span><div><h1></h1><p></p></div></div><div class="mv-page-actions86"></div>';sec.insertAdjacentElement('afterbegin',head)}
    head.querySelector('h1').textContent=m[0];head.querySelector('p').textContent=m[1]||'';
    // Preserve only useful contextual primary actions in the header.
    const actions=head.querySelector('.mv-page-actions86');
    if(!actions.dataset.ready){
      if(p==='inicio'){actions.innerHTML='<button type="button" class="mv-primary86" data-mv86="viagem">＋ Novo percurso</button>'}
      else if(p==='veiculos'){actions.innerHTML='<button type="button" class="mv-primary86" data-mv86focus="descVeic">＋ Novo veículo</button>'}
      else if(p==='agenda'){actions.innerHTML='<button type="button" class="mv-primary86" data-mv86focus="agData">＋ Novo compromisso</button>'}
      actions.dataset.ready='1';
    }
    sec.querySelectorAll(':scope > .c h2:first-child,:scope > .mv-surface84 h2:first-child').forEach(h=>h.classList.add('mv-original-title86'));
  }
  function classify(sec){
    const p=pageName(sec);sec.classList.add('mv-module86','mv-module-'+p+'86');
    [...sec.children].forEach(el=>{if(el.classList?.contains('c')||el.classList?.contains('mv-surface84'))el.classList.add('mv-card86')});
    sec.querySelectorAll('.row').forEach(r=>r.classList.add('mv-row86'));
    sec.querySelectorAll('.stat').forEach(r=>r.classList.add('mv-stat86'));
    sec.querySelectorAll('.actions').forEach(r=>r.classList.add('mv-actions86'));
    sec.querySelectorAll('h3').forEach(h=>h.classList.add('mv-section-title86'));
    sec.querySelectorAll('input,select,textarea').forEach(x=>x.classList.add('mv-field86'));
    sec.querySelectorAll('button').forEach(x=>{if(!x.closest('.nav')&&!x.closest('#mvBottomDock85')&&!x.closest('.mv-topnav-v16282'))x.classList.add('mv-button86')});
    sec.querySelectorAll('.tag').forEach(x=>x.classList.add('mv-chip86'));
  }
  function special(){
    const dash=byId('p-inicio');if(dash){dash.classList.add('mv-dashboard86');byId('mvDashboardHead85')?.remove();const main=[...dash.children].find(x=>x.classList?.contains('mv-card86'));main?.classList.add('mv-dashboard-summary86');main?.querySelector('.stat')?.classList.add('mv-kpi-grid86');const hero=dash.querySelector('.hero');hero?.classList.add('mv-dashboard-detail86')}
    const trip=byId('p-viagem');if(trip){byId('novaViagem')?.classList.add('mv-form-card86');byId('viagemAtiva')?.classList.add('mv-active-card86')}
    const hist=byId('p-historico');hist?.querySelector('.r')?.classList.add('mv-filterbar86');
    const agenda=byId('p-agenda');agenda?.querySelector('.r3')?.classList.add('mv-filterbar86');
    const fleet=byId('p-veiculos');fleet?.querySelector('.r')?.classList.add('mv-filterbar86');
    const audit=byId('p-auditoria');audit?.querySelector('input')?.parentElement?.classList.add('mv-audit-card86');
    const cfg=byId('p-config');cfg?.classList.add('mv-settings86');
    const backup=byId('p-backup');backup?.classList.add('mv-backup86');
    const reports=byId('p-relatorios');reports?.classList.add('mv-reports86');
  }
  function shell(){
    document.body.classList.add('mv-system86');
    const nav=document.querySelector('#app>.nav');if(nav){nav.classList.add('mv-sidebar86');nav.querySelectorAll('[data-p]').forEach(b=>{const p=b.dataset.p;if(!b.querySelector('.mv-nav86')){const text=(meta[p]?.[0]||b.textContent||p);b.innerHTML='<span class="mv-nav86">'+(icon[p]||'•')+'</span><span>'+text+'</span>'}})}
  }
  function sync(){shell();document.querySelectorAll('#app>section').forEach(sec=>{pageHeader(sec);classify(sec)});special()}
  document.addEventListener('click',e=>{
    const go=e.target.closest?.('[data-mv86]');if(go){globalThis.mvNavigationV16282?.navigate?.(go.dataset.mv86);return}
    const f=e.target.closest?.('[data-mv86focus]');if(f){const el=byId(f.dataset.mv86focus);el?.scrollIntoView?.({behavior:'smooth',block:'center'});setTimeout(()=>el?.focus?.(),250);return}
    if(e.target.closest?.('[data-p],[data-p-jump],#mvBottomDock85'))setTimeout(sync,60)
  },true);
  [0,120,350,800,1600,3000].forEach(ms=>setTimeout(sync,ms));
  globalThis.mvUnifiedUiV16286={sync};
})();
`;
if(!s.includes('carga();'))throw new Error('v162.86 startup anchor not found');s=s.replace('carga();',js+'\ncarga();');
const css=`
/* v162.86 unified visual language — matched to supplied reference */
:root{--mv86-bg:#f6f8fb;--mv86-card:#fff;--mv86-border:#e1e6ed;--mv86-text:#172033;--mv86-muted:#737e90;--mv86-blue:#0968e8;--mv86-blue-hover:#075bc9;--mv86-navy:#071a31;--mv86-navy2:#0b284a;--mv86-green:#149654;--mv86-green-bg:#eaf7ef;--mv86-red:#e22f38;--mv86-red-bg:#fdecee;--mv86-amber:#c98400;--mv86-amber-bg:#fff6dc;--mv86-radius:7px;--mv86-shadow:0 1px 2px rgba(16,24,40,.04)}
body.mv-system86{background:var(--mv86-bg)!important;color:var(--mv86-text)!important;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif!important;font-size:13px!important}.mv-system86>.w{max-width:none!important;padding:0!important;margin:0!important}.mv-system86>.w>div.c:first-child{display:none!important}
.mv-module86{width:100%!important;max-width:1320px!important;margin:0 auto!important;padding:18px 22px 34px!important}.mv-page86{display:flex!important;justify-content:space-between!important;align-items:center!important;gap:18px!important;min-height:48px!important;margin:0 0 14px!important}.mv-page-title86{display:flex;align-items:center;gap:10px;min-width:0}.mv-page-icon86{display:none}.mv-page-title86 h1{font-size:20px!important;line-height:1.2!important;margin:0!important;font-weight:760!important;color:#111827!important;letter-spacing:-.015em}.mv-page-title86 p{font-size:11px!important;color:var(--mv86-muted)!important;margin:3px 0 0!important}.mv-page-actions86{display:flex;gap:8px;align-items:center}.mv-page-actions86:empty{display:none}.mv-primary86{width:auto!important;min-height:36px!important;padding:0 13px!important;border-radius:5px!important;background:var(--mv86-blue)!important;color:#fff!important;border:1px solid var(--mv86-blue)!important;font-size:12px!important;font-weight:680!important}.mv-primary86:hover{background:var(--mv86-blue-hover)!important}
.mv-original-title86{display:none!important}.mv-card86{background:var(--mv86-card)!important;border:1px solid var(--mv86-border)!important;border-radius:var(--mv86-radius)!important;box-shadow:var(--mv86-shadow)!important;padding:17px!important;margin:0 0 12px!important}.mv-card86.hero{background:#fff!important}.mv-row86{background:#fff!important;border:1px solid var(--mv86-border)!important;border-radius:6px!important;padding:12px!important;margin:8px 0!important}.mv-section-title86{font-size:13px!important;line-height:1.3!important;font-weight:720!important;color:#2b3545!important;margin:18px 0 9px!important}.mv-section-title86:first-child{margin-top:0!important}.mv-stat86{gap:0!important;border:1px solid var(--mv86-border)!important;border-radius:6px!important;overflow:hidden!important;background:#fff!important}.mv-stat86>div{border:0!important;border-right:1px solid var(--mv86-border)!important;border-radius:0!important;padding:12px 14px!important;background:#fff!important}.mv-stat86>div:last-child{border-right:0!important}.mv-stat86 b{font-size:18px!important;color:#123d78!important}.mv-actions86{gap:7px!important;margin-top:10px!important}
.mv-field86{min-height:39px!important;padding:8px 10px!important;background:#fff!important;border:1px solid #d7dde6!important;border-radius:5px!important;color:#1d2735!important;font-size:12px!important;box-shadow:none!important;transition:border-color .15s,box-shadow .15s}.mv-field86:focus{outline:0!important;border-color:#6da5ef!important;box-shadow:0 0 0 3px rgba(9,104,232,.08)!important}.mv-field86::placeholder{color:#9aa4b3!important}.mv-button86{min-height:38px!important;border-radius:5px!important;font-size:12px!important;font-weight:660!important;box-shadow:none!important}.mv-button86:not(.sec):not(.danger){background:var(--mv86-blue)!important;color:#fff!important}.mv-button86.sec{background:#fff!important;color:#344257!important;border:1px solid #d7dde6!important}.mv-button86.danger{background:var(--mv86-red)!important;color:#fff!important}.mv-chip86,.tag{border-radius:999px!important;padding:4px 8px!important;font-size:10px!important;font-weight:650!important}.ok.mv-chip86,.tag.ok{background:var(--mv86-green-bg)!important;color:var(--mv86-green)!important}.err.mv-chip86,.tag.err{background:var(--mv86-red-bg)!important;color:var(--mv86-red)!important}.warn.mv-chip86,.tag.warn{background:var(--mv86-amber-bg)!important;color:var(--mv86-amber)!important}
.mv-filterbar86{background:#fafbfd!important;border:1px solid var(--mv86-border)!important;border-radius:6px!important;padding:10px!important;gap:8px!important;margin-bottom:12px!important}.mv-form-card86{max-width:720px!important;margin-left:auto!important;margin-right:auto!important}.mv-form-card86>.r,.mv-form-card86>.r3{gap:10px!important}.mv-form-card86 textarea{min-height:64px!important}.mv-plan-hint84{border-radius:5px!important;background:#f7f9fc!important;border:1px solid var(--mv86-border)!important}.mv-save84{border-radius:5px!important;background:#fff!important;border:1px solid var(--mv86-blue)!important;color:var(--mv86-blue)!important}
.mv-active-card86{max-width:820px!important;margin-left:auto!important;margin-right:auto!important;background:transparent!important;border:0!important;box-shadow:none!important;padding:0!important}.mv-active-route-summary-v16283{border-radius:7px!important;border:1px solid var(--mv86-border)!important;box-shadow:none!important;background:#fff!important}.mv-active-route-summary-v16283 .mv-live83{background:var(--mv86-green-bg)!important;color:var(--mv86-green)!important;padding:4px 7px!important;border-radius:4px!important}.mv-active-route-summary-v16283 .mv-metrics83>div{border:1px solid var(--mv86-border)!important;border-radius:5px!important;background:#fff!important}.mv-fold84{border:1px solid var(--mv86-border)!important;border-radius:7px!important;background:#fff!important}.mv-fold84>summary{padding:13px 14px!important}.mv-fold84[open]>summary{background:#f9fafc!important;border-bottom:1px solid var(--mv86-border)!important}
.mv-dashboard86{display:grid!important;grid-template-columns:minmax(0,1.6fr) minmax(280px,.75fr)!important;gap:12px!important;align-items:start!important}.mv-dashboard86>.mv-page86{grid-column:1/-1!important}.mv-dashboard-summary86{grid-column:1!important}.mv-dashboard-detail86{grid-column:1!important}.mv-dashboard86>.mv-card86:not(.mv-dashboard-summary86):not(.mv-dashboard-detail86):not(.hide){grid-column:2!important}.mv-kpi-grid86{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important}.mv-kpi-grid86>div .muted{font-size:10px!important}.mv-kpi-grid86>div b{font-size:19px!important}.mv-dashboard86 .hero{background:#fff!important}.mv-dashboard86 .actions button{width:auto!important}
.mv-settings86 .mv-card86,.mv-backup86 .mv-card86,.mv-reports86 .mv-card86{max-width:980px!important;margin-left:auto!important;margin-right:auto!important}.mv-settings86 .mv-row86{padding:14px!important}.mv-settings86 label{display:flex!important;align-items:center!important;gap:8px!important;padding:8px 0!important;border-bottom:1px solid #eef1f5!important}.mv-settings86 label input{width:auto!important;min-height:auto!important}.mv-backup86 .actions{display:flex!important}.mv-backup86 .actions button{flex:1!important}.mv-audit-card86{max-width:980px!important;margin:auto!important}
#hist>div,#agendaLista>div,#listaVeic>div,#listaCustos>div,#equipeLista>div,#auditLista>div,#avisosLista>div,#rotasLista>div{border:1px solid var(--mv86-border)!important;border-radius:6px!important;background:#fff!important;margin:7px 0!important;padding:12px!important;box-shadow:none!important}
@media(min-width:821px){
  #app{padding-left:205px!important;min-height:100vh!important}.mv-sidebar86{position:fixed!important;inset:0 auto 0 0!important;width:205px!important;height:100vh!important;display:flex!important;flex-direction:column!important;gap:2px!important;background:var(--mv86-navy)!important;border:0!important;border-radius:0!important;padding:0 8px 10px!important;margin:0!important;overflow-y:auto!important;z-index:120!important;box-shadow:none!important}.mv-sidebar86 #mvBrand85{padding:17px 9px 14px!important;margin-bottom:8px!important}.mv-sidebar86 button{display:flex!important;align-items:center!important;gap:8px!important;width:100%!important;min-height:34px!important;padding:7px 9px!important;background:transparent!important;border:0!important;border-radius:5px!important;color:#c7d2df!important;font-size:11px!important;font-weight:520!important;text-align:left!important;white-space:nowrap!important}.mv-sidebar86 button:hover{background:var(--mv86-navy2)!important;color:#fff!important}.mv-sidebar86 [data-p].mv-current-v16282{background:var(--mv86-blue)!important;color:#fff!important;outline:0!important}.mv-sidebar86 .mv-nav86{width:18px!important;text-align:center!important;font-weight:800!important}.mv-sidebar86 #mvSideUser85{margin-top:auto!important}.mv-system86 .mv-topnav-v16282{position:sticky!important;top:0!important;z-index:90!important;height:48px!important;min-height:48px!important;padding:7px 20px!important;margin:0!important;border:0!important;border-bottom:1px solid var(--mv86-border)!important;border-radius:0!important;background:#fff!important;color:#263246!important;box-shadow:none!important;grid-template-columns:34px 34px minmax(0,1fr)!important}.mv-system86 .mv-topnav-v16282 button{width:32px!important;height:32px!important;min-height:32px!important;border:1px solid #dfe4eb!important;border-radius:5px!important;background:#fff!important;color:#46556b!important}.mv-system86 #mvPageTitleV16282{font-size:12px!important;color:#425067!important}#mvBottomDock85{display:none!important}
}
@media(max-width:820px){
  body.mv-system86{background:#f7f9fc!important}.mv-module86{padding:14px 12px 88px!important}.mv-page86{margin-bottom:10px!important}.mv-page-title86 h1{font-size:18px!important}.mv-page-title86 p{display:none!important}.mv-page-actions86 .mv-primary86{font-size:11px!important;padding:0 10px!important}.mv-card86{padding:13px!important;margin-bottom:9px!important;border-radius:7px!important}.mv-dashboard86{display:block!important}.mv-dashboard86>.mv-card86{margin-bottom:9px!important}.mv-kpi-grid86{grid-template-columns:1fr 1fr!important}.mv-kpi-grid86>div:nth-child(2){border-right:0!important}.mv-kpi-grid86>div{border-bottom:1px solid var(--mv86-border)!important}.mv-kpi-grid86>div:nth-last-child(-n+2){border-bottom:0!important}.mv-stat86{grid-template-columns:1fr 1fr!important}.mv-field86{font-size:14px!important;min-height:43px!important}.mv-button86{min-height:43px!important;font-size:13px!important}.mv-form-card86,.mv-active-card86,.mv-settings86 .mv-card86,.mv-backup86 .mv-card86,.mv-reports86 .mv-card86{max-width:none!important}.mv-system86 .mv-topnav-v16282{height:48px!important;min-height:48px!important;padding:7px 10px!important;background:#fff!important;border-bottom:1px solid var(--mv86-border)!important;color:#263246!important}.mv-system86 .mv-topnav-v16282 button{background:#fff!important;color:#35445b!important;border:1px solid #e0e5ec!important;border-radius:5px!important}.mv-system86 #mvPageTitleV16282{color:#1f2937!important;font-size:12px!important}.mv-system86 #mvBottomDock85{display:grid!important;position:fixed!important;left:0!important;right:0!important;bottom:0!important;height:64px!important;grid-template-columns:repeat(5,1fr)!important;background:#fff!important;border-top:1px solid var(--mv86-border)!important;z-index:130!important;padding:3px 4px calc(3px + env(safe-area-inset-bottom))!important;box-shadow:0 -3px 12px rgba(15,23,42,.04)!important}.mv-system86 #mvBottomDock85 button{display:grid!important;place-items:center!important;align-content:center!important;gap:1px!important;background:transparent!important;color:#566478!important;border:0!important;border-radius:4px!important;min-height:54px!important;padding:4px!important}.mv-system86 #mvBottomDock85 button span{font-size:17px!important}.mv-system86 #mvBottomDock85 button small{font-size:9px!important}.mv-system86 #mvBottomDock85 button.active{color:var(--mv86-blue)!important;background:#f0f6ff!important}.mv-system86 .nav{background:var(--mv86-navy)!important}.mv-active-route-summary-v16283 .mv-metrics83{grid-template-columns:1fr 1fr!important}
}
`;
if(!s.includes('</style>'))throw new Error('v162.86 css anchor not found');s=s.replace('</style>',css+'\n</style>');
fs.writeFileSync('dist/index.html',s);console.log('Movvant v162.86: unified reference design system applied to every module');
