const fs=require('fs');
let s=fs.readFileSync('dist/index.html','utf8');
const js=`
// v162.50 structural dashboard rebuild — reference-first, preserving existing data/handlers
(function(){
 const icon={inicio:'▦',viagem:'＋',historico:'↗',agenda:'▣',rotas:'⌁',veiculos:'▰',custos:'$',equipe:'♙',relatorios:'▥',ajuda:'?',perfil:'○',painel:'⚙',notificacoes:'!',auditoria:'✓',backup:'⇩',config:'⚙'};
 const label={inicio:'Dashboard',viagem:'Novo percurso',historico:'Viagens',agenda:'Agenda',rotas:'Rotas',veiculos:'Frota',custos:'Despesas',equipe:'Equipe',relatorios:'Relatórios',ajuda:'Ajuda',perfil:'Meu perfil',painel:'Painel ADM',notificacoes:'Ocorrências',auditoria:'Auditoria',backup:'Backup',config:'Configurações'};
 function sidebar(){
  const nav=document.getElementById('sideMenuV136');if(!nav)return;
  nav.classList.add('mv50-side');
  nav.querySelectorAll('[data-p]').forEach(b=>{const p=b.dataset.p;b.innerHTML='<span class="mv50-ico">'+(icon[p]||'•')+'</span><span>'+(label[p]||b.textContent.trim())+'</span>';});
  let brand=nav.querySelector('.side-menu-head-v136');if(brand)brand.innerHTML='<div class="mv50-mark">M</div><div class="mv50-brandcopy"><strong>MOVVANT</strong><small>INTELIGÊNCIA COMERCIAL EM CAMPO</small></div><button id="sideMenuCloseV136" type="button">×</button>';
  const close=document.getElementById('sideMenuCloseV136');if(close)close.onclick=()=>{nav.classList.remove('open-v136');document.getElementById('sideMenuShadeV136')?.classList.remove('open-v136');document.body.classList.remove('menu-open-v136')};
 }
 function topbar(){
  const top=document.querySelector('.classic-app-header');if(!top||top.dataset.mv50)return;top.dataset.mv50='1';top.classList.add('mv50-top');
  const title=top.querySelector('.classic-title');if(title)title.innerHTML='<b>MOVVANT</b><small>Inteligência comercial em campo</small>';
 }
 function dashboard(){
  const p=document.getElementById('p-inicio');if(!p)return;p.classList.add('mv50-dashboard');
  const main=p.querySelector('.home-main-card-v136')||p.querySelector('.c');if(!main)return;main.classList.add('mv50-summary');
  const title=main.querySelector('#empresa');if(title)title.textContent='Dashboard';
  const user=main.querySelector('#usuario');if(user)user.classList.add('mv50-welcome');
  const newTrip=main.querySelector('[data-p-jump="viagem"]');if(newTrip){newTrip.innerHTML='<span>＋</span> Novo percurso';newTrip.classList.add('mv50-newtrip');}
  const stats=main.querySelector('.stat');if(stats){stats.classList.add('mv50-kpis');const cards=[...stats.children];const meta=[['Distância percorrida','km','↗'],['Despesas','R$','$'],['Viagens','', '▣'],['Média por viagem','km','⌁']];cards.forEach((c,i)=>{const m=meta[i];if(!m)return;c.classList.add('mv50-kpi');const small=c.querySelector('.small');if(small)small.textContent=m[0];if(!c.querySelector('.mv50-kpi-icon'))c.insertAdjacentHTML('afterbegin','<i class="mv50-kpi-icon">'+m[2]+'</i>');});}
  const secondary=[...main.querySelectorAll(':scope>.r .row')];secondary.forEach(x=>x.classList.add('mv50-mini'));
  main.querySelectorAll('#usoBox,#orcamentoBox,#economiaBox,#rateioBox').forEach(x=>x.classList.add('mv50-strip'));
  const quick=[...p.querySelectorAll('.c')].find(c=>c.querySelector('h3')?.textContent.trim()==='Ações rápidas');if(quick){quick.classList.add('mv50-quick');quick.querySelector('h3').textContent='Ações rápidas';}
  const manager=p.querySelector('.hero');if(manager){manager.classList.add('mv50-manager');const h=manager.querySelector('h3');if(h)h.textContent='Visão geral';}
 }
 function pages(){document.querySelectorAll('#app>section').forEach(x=>x.classList.add('mv50-page'));const trip=document.getElementById('novaViagem');if(trip){trip.classList.add('mv50-form');trip.querySelector('h2').textContent='Novo percurso';}}
 function mobile(){const bar=document.getElementById('mvBottomV16249');if(bar)bar.classList.add('mv50-bottom');}
 function apply(){sidebar();topbar();dashboard();pages();mobile();}
 const r0=render;render=function(){const r=r0();requestAnimationFrame(apply);return r};setTimeout(apply,80);setTimeout(apply,700);
})();
`;
if(!s.includes('carga();'))throw new Error('v162.50 startup anchor missing');s=s.replace('carga();',js+'\ncarga();');
const css=`
/* v162.50 — structural fidelity to supplied reference */
:root{--m50-blue:#1264e8;--m50-deep:#0a2f63;--m50-side:#073b79;--m50-bg:#f4f7fb;--m50-line:#dfe5ee;--m50-text:#172033;--m50-muted:#748095}
body{background:var(--m50-bg)!important;font-size:13px!important}.w{max-width:none!important;margin:0!important;padding:14px 22px 80px!important}
#app .c{border:1px solid var(--m50-line)!important;border-radius:4px!important;box-shadow:0 1px 3px #1620330b!important;margin:9px 0!important;padding:16px!important}
.mv50-top{height:58px!important;min-height:58px!important;padding:8px 16px!important;border:0!important;border-bottom:1px solid var(--m50-line)!important;border-radius:0!important;margin:-14px -22px 14px!important;background:#fff!important;box-shadow:none!important}.mv50-top .classic-title b{display:block!important;font-size:14px!important;letter-spacing:.8px!important;color:#12345b!important}.mv50-top .classic-title small{display:block!important;font-size:8px!important;color:#7a8799!important;font-weight:500!important;margin-top:1px!important}
.mv50-dashboard{max-width:1120px!important;margin:0 auto!important}.mv50-summary{position:relative!important;padding:18px!important}.mv50-summary #empresa{font-size:18px!important;margin:0 0 3px!important}.mv50-welcome{font-size:10px!important;margin:0 0 18px!important}.mv50-newtrip{position:absolute!important;right:18px!important;top:16px!important;width:auto!important;min-height:34px!important;padding:7px 12px!important;font-size:10px!important;border-radius:3px!important}
.mv50-summary>h3{font-size:9px!important;text-transform:uppercase!important;letter-spacing:.7px!important;color:#7a8799!important;margin:12px 0 7px!important}.mv50-kpis{display:grid!important;grid-template-columns:repeat(4,1fr)!important;gap:9px!important}.mv50-kpi{position:relative!important;min-height:82px!important;padding:13px 12px!important;border:1px solid var(--m50-line)!important;border-radius:4px!important}.mv50-kpi .small{font-size:9px!important;color:#778399!important}.mv50-kpi b{display:block!important;font-size:21px!important;line-height:1.2!important;color:#172033!important;margin-top:8px!important}.mv50-kpi-icon{position:absolute!important;right:10px!important;top:10px!important;width:25px!important;height:25px!important;border-radius:4px!important;background:#eaf2ff!important;color:var(--m50-blue)!important;display:grid!important;place-items:center!important;font-style:normal!important;font-size:12px!important}.mv50-mini{min-height:58px!important;padding:10px 12px!important}.mv50-strip{padding:9px 11px!important;margin:6px 0!important;border:1px solid #e6eaf0!important;border-radius:3px!important;font-size:10px!important}.mv50-quick h3,.mv50-manager h3{font-size:12px!important;margin:0 0 10px!important}.mv50-quick .actions button{font-size:10px!important;min-height:33px!important;padding:7px 10px!important}.mv50-manager{border-top:1px solid var(--m50-line)!important;background:#fff!important}.mv50-manager .row{font-size:10px!important;padding:10px!important}
.mv50-page:not(#p-inicio){max-width:980px!important;margin:0 auto!important}.mv50-form{max-width:780px!important;margin:10px auto!important}.mv50-form h2{font-size:18px!important;border-bottom:1px solid #e6eaf0!important;padding-bottom:12px!important}.mv50-form input,.mv50-form select,.mv50-form textarea{font-size:11px!important;border-radius:3px!important;min-height:39px!important}.mv50-form button{font-size:11px!important;border-radius:3px!important}
@media(min-width:901px){body{padding-left:205px!important}.mv50-side{width:205px!important;background:var(--m50-side)!important;padding:12px 9px!important}.mv50-side .side-menu-head-v136{display:grid!important;grid-template-columns:35px 1fr!important;gap:8px!important;padding:7px 5px 15px!important;border-bottom:1px solid #ffffff24!important;margin-bottom:10px!important}.mv50-side .side-menu-head-v136>button{display:none!important}.mv50-mark{width:31px!important;height:31px!important;border-radius:50%!important;background:#fff!important;color:var(--m50-blue)!important;display:grid!important;place-items:center!important;font-weight:900!important;font-size:15px!important}.mv50-brandcopy strong{display:block!important;color:#fff!important;font-size:12px!important;letter-spacing:1px!important}.mv50-brandcopy small{display:block!important;color:#b9cbe1!important;font-size:6px!important;line-height:1.3!important;margin-top:2px!important}.mv50-side button[data-p]{display:flex!important;align-items:center!important;gap:10px!important;background:transparent!important;color:#dce8f7!important;border:0!important;border-radius:3px!important;min-height:35px!important;padding:7px 9px!important;font-size:10px!important;font-weight:600!important}.mv50-side button[data-p="inicio"]{background:#1768d8!important;color:#fff!important}.mv50-ico{width:17px!important;text-align:center!important;font-size:13px!important;color:#cfe0f5!important}.mv50-side #sair{margin-top:auto!important;background:transparent!important;color:#c5d5e8!important;border:0!important;border-top:1px solid #ffffff20!important;border-radius:0!important;font-size:10px!important}}
@media(max-width:900px){body{background:#f7f9fc!important}.w{padding:56px 9px 76px!important}.mv50-top{position:fixed!important;left:0!important;right:0!important;top:0!important;z-index:45!important;margin:0!important;height:50px!important;min-height:50px!important;padding:6px 9px 6px 52px!important}.mv50-dashboard{max-width:100%!important}.mv50-summary{padding:12px!important}.mv50-summary #empresa{font-size:17px!important}.mv50-newtrip{position:static!important;width:100%!important;margin:8px 0 12px!important}.mv50-kpis{grid-template-columns:1fr 1fr!important;gap:7px!important}.mv50-kpi{min-height:74px!important;padding:10px!important}.mv50-kpi b{font-size:18px!important}.mv50-kpi-icon{width:22px!important;height:22px!important}.mv50-summary>.r{grid-template-columns:1fr 1fr!important;gap:7px!important}.mv50-bottom{height:62px!important;padding:4px 2px max(4px,env(safe-area-inset-bottom))!important}.mv50-bottom button{font-size:8px!important;min-height:48px!important}.mv50-bottom button span{font-size:17px!important}.mv50-form{margin:0!important}.mv50-form .r,.mv50-form .r3{grid-template-columns:1fr!important}}
`;
if(!s.includes('</style>'))throw new Error('v162.50 css anchor missing');s=s.replace('</style>',css+'\n</style>');fs.writeFileSync('dist/index.html',s);console.log('Movvant v162.50: structural reference layout rebuilt');
