import React,{useEffect,useMemo,useState}from'react';
import{createClient}from'@supabase/supabase-js';
import{LayoutDashboard,ShoppingCart,Users,CalendarDays,Route,Car,Truck,BrainCircuit,FileText,BarChart3,Settings,Shield,Search,Bell,HelpCircle,Plus,ChevronDown,TrendingUp,Target,MapPin,Gauge,AlertTriangle,RefreshCw}from'lucide-react';

const sb=createClient('https://aaqbwdrqmhuzqdesywze.supabase.co','sb_publishable_FDSQxTSJYyBdfRuV8ZwmGw_RwzO9-_Z',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const NAV=[['Visão Geral',LayoutDashboard],['Comercial',ShoppingCart],['Clientes',Users],['Agenda e Visitas',CalendarDays],['Rotas',Route],['Frota / KM',Car],['Logística',Truck],['Inteligência',BrainCircuit],['Relatórios',FileText],['Dashboards',BarChart3],['Configurações',Settings],['Administração',Shield]] as const;
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const pct=(v:number)=>`${v.toLocaleString('pt-BR',{maximumFractionDigits:1})}%`;

type Kpi={metric_code:string;period_date:string;metric_value:number};
type Action={customer_code?:string;customer_name?:string;seller_name?:string;branch_code?:string;status?:string;revenue_gap?:number;opportunity_score?:number;recommended_action?:string;lost_mix_gap?:number;lost_mix_count?:number;customer_ready?:boolean;seller_ready?:boolean};

default function App(){
 const[active,setActive]=useState('Inteligência');const[tab,setTab]=useState('Dashboard');const[loading,setLoading]=useState(true);const[kpis,setKpis]=useState<Kpi[]>([]);const[actions,setActions]=useState<Action[]>([]);const[branches,setBranches]=useState<any[]>([]);const[branch,setBranch]=useState('');const[from,setFrom]=useState('2026-01-01');const[to,setTo]=useState('2026-08-31');const[sessionLabel,setSessionLabel]=useState('Movvant Enterprise');
 useEffect(()=>{(async()=>{try{const{data:{session}}=await sb.auth.getSession();let companyId='67e35b1d-f5b8-44cb-ac9a-7ee100495e28';if(session){const{data:ra}=await sb.from('user_role_assignments').select('company_id,branch_id,roles(slug,name)').eq('user_id',session.user.id).eq('active',true).limit(1);if(ra?.[0]?.company_id)companyId=ra[0].company_id;const{data:p}=await sb.from('profiles').select('full_name').eq('user_id',session.user.id).maybeSingle();setSessionLabel(p?.full_name||session.user.email||'Movvant');}
 const[{data:b},{data:k},{data:a}]=await Promise.all([sb.from('branches').select('id,code,name').eq('company_id',companyId).eq('active',true).order('name'),sb.from('kpi_snapshots').select('metric_code,period_date,metric_value').eq('company_id',companyId).contains('dimension',{source:'historical_sales_2026',scope:'company'}),sb.from('v_historical_commercial_action_center').select('*').eq('company_id',companyId).order('priority_score',{ascending:false}).limit(50)]);setBranches(b||[]);setKpis((k||[])as Kpi[]);setActions((a||[])as Action[]);}finally{setLoading(false)}})()},[]);
 const summary=useMemo(()=>{const rows=kpis.filter(x=>x.period_date>=from&&x.period_date<=to);const sum=(c:string)=>rows.filter(x=>x.metric_code===c).reduce((s,x)=>s+Number(x.metric_value||0),0);const avg=(c:string)=>{const r=rows.filter(x=>x.metric_code===c);return r.length?r.reduce((s,x)=>s+Number(x.metric_value||0),0)/r.length:0};return{revenue:sum('commercial.revenue'),orders:sum('commercial.orders'),profit:sum('commercial.net_profit'),margin:avg('commercial.margin_pct'),ticket:avg('commercial.ticket_average'),customers:avg('commercial.active_customers'),mix:avg('commercial.product_mix')}} ,[kpis,from,to]);
 const filteredActions=useMemo(()=>actions.filter(x=>!branch||x.branch_code===branches.find(b=>b.id===branch)?.code),[actions,branch,branches]);
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="logoMark">◆</span><div><strong>MOVVANT</strong><small>ENTERPRISE</small></div></div><nav>{NAV.map(([label,Icon])=><button key={label} className={active===label?'navItem active':'navItem'} onClick={()=>setActive(label)}><Icon size={18}/><span>{label}</span>{['Comercial','Agenda e Visitas','Frota / KM','Logística','Inteligência','Configurações','Administração'].includes(label)&&<ChevronDown size={14} className="navChevron"/>}</button>)}</nav><button className="collapse">◉ <span>Recolher Menu</span></button></aside>
 <main><header className="topbar"><div className="search"><Search size={16}/><input placeholder="Buscar clientes, pedidos, visitas, produtos..."/></div><button className="newBtn"><Plus size={16}/>Novo</button><button className="iconBtn"><Bell size={18}/><i>12</i></button><button className="iconBtn"><HelpCircle size={18}/></button><div className="user"><div className="avatar">M</div><div><b>{sessionLabel}</b><small>Gestão Comercial</small></div><ChevronDown size={15}/></div></header>
 <section className="content">{active==='Inteligência'?<Intelligence tab={tab} setTab={setTab} loading={loading} summary={summary} actions={filteredActions} branches={branches} branch={branch} setBranch={setBranch} from={from} setFrom={setFrom} to={to} setTo={setTo}/>:<Placeholder title={active}/>}</section></main></div>
}

function Intelligence(p:any){const tabs=['Dashboard','Oportunidades','Análise de Carteira','Metas','KPIs'];return <><div className="pageHead"><div><h1>Inteligência Comercial</h1><p>Decisões orientadas por dados • histórico comercial + operação de campo</p></div><button className="outline"><RefreshCw size={15}/>Atualizar</button></div><div className="tabs">{tabs.map(t=><button className={p.tab===t?'tab active':''} onClick={()=>p.setTab(t)}>{t}</button>)}</div><div className="filters"><label>Período<select><option>Jan–Ago/2026</option></select></label><label>Filial<select value={p.branch} onChange={(e)=>p.setBranch(e.target.value)}><option value="">Todas</option>{p.branches.map((b:any)=><option value={b.id}>{b.name}</option>)}</select></label><label>De<input type="date" value={p.from} onChange={(e)=>p.setFrom(e.target.value)}/></label><label>Até<input type="date" value={p.to} onChange={(e)=>p.setTo(e.target.value)}/></label></div>{p.loading?<div className="loading">Carregando dados reais do Movvant Enterprise...</div>:p.tab==='Dashboard'?<Dashboard s={p.summary} actions={p.actions}/>:p.tab==='Oportunidades'?<Opportunities rows={p.actions}/>:p.tab==='Análise de Carteira'?<Portfolio rows={p.actions}/>:<KpiPage s={p.summary} title={p.tab}/>}</>}
function Dashboard({s,actions}:{s:any,actions:Action[]}){const risk=actions.filter(x=>['inactive','strong_drop','strong_decline'].includes(x.status||''));const potential=actions.reduce((a,x)=>a+Number(x.revenue_gap||0),0);return <><div className="kpi-grid"><Kpi icon={<TrendingUp/>} label="Faturamento" value={money(s.revenue)} note="Jan–Ago/2026"/><Kpi icon={<Target/>} label="Oportunidades" value={String(actions.length)} note={`${money(potential)} em gaps analisados`}/><Kpi icon={<Users/>} label="Clientes ativos / mês" value={Math.round(s.customers).toLocaleString('pt-BR')} note="média do período"/><Kpi icon={<ShoppingCart/>} label="Pedidos" value={Math.round(s.orders).toLocaleString('pt-BR')} note={`Ticket ${money(s.ticket)}`}/><Kpi icon={<Gauge/>} label="Margem média" value={pct(s.margin)} note={`Lucro ${money(s.profit)}`}/><Kpi icon={<BarChart3/>} label="Mix médio / mês" value={Math.round(s.mix).toLocaleString('pt-BR')} note="produtos vendidos"/></div><div className="grid2"><div className="card"><div className="cardTitle"><div><h3>Desempenho Comercial</h3><small>Receita líquida mensal • Jan–Ago/2026</small></div></div><RevenueChart/></div><div className="card"><div className="cardTitle"><div><h3>Central de Atenção</h3><small>Exceções e oportunidades prioritárias</small></div></div><div className="attention"><Row dot="red" label="Clientes em risco" value={risk.length}/><Row dot="amber" label="Oportunidades priorizadas" value={actions.length}/><Row dot="blue" label="Potencial analisado" value={money(potential)}/><Row dot="green" label="Backend" value="Movvant Enterprise"/></div></div></div><div className="grid2 lower"><div className="card"><h3>Oportunidades prioritárias</h3><ActionTable rows={actions.slice(0,7)}/></div><div className="card"><h3>Eficiência de campo</h3><div className="empty"><MapPin size={36}/><b>Agenda + Rotas + KM conectados</b><span>A conversão visita → venda será exibida quando os vínculos cadastrais reais forem reconciliados.</span></div></div></div></>}
function Opportunities({rows}:{rows:Action[]}){return <div className="card full"><div className="cardTitle"><div><h3>Central de Ações Comerciais</h3><small>Queda de faturamento, inatividade e perda de mix</small></div></div><ActionTable rows={rows}/></div>}
function Portfolio({rows}:{rows:Action[]}){return <div className="grid2"><div className="card"><h3>Carteira em risco</h3><ActionTable rows={rows.filter(x=>['inactive','strong_drop','strong_decline'].includes(x.status||'')).slice(0,20)}/></div><div className="card"><h3>Qualidade do vínculo</h3><div className="attention"><Row dot="green" label="Oportunidades históricas" value={rows.length}/><Row dot="amber" label="Aguardando cliente real" value={rows.filter(x=>!x.customer_ready).length}/><Row dot="amber" label="Aguardando vendedor real" value={rows.filter(x=>!x.seller_ready).length}/><Row dot="blue" label="Fonte" value="Jan–Ago/2026"/></div></div></div>}
function KpiPage({s,title}:{s:any,title:string}){return <div className="card full"><h3>{title}</h3><div className="kpi-grid compact"><Kpi label="Receita" value={money(s.revenue)}/><Kpi label="Margem" value={pct(s.margin)}/><Kpi label="Pedidos" value={Math.round(s.orders).toLocaleString('pt-BR')}/><Kpi label="Ticket" value={money(s.ticket)}/></div></div>}
function Kpi({label,value,note,icon}:{label:string,value:string,note?:string,icon?:any}){return <div className="kpi card"><div className="kpiTop"><span>{label}</span>{icon&&<i>{React.cloneElement(icon,{size:18})}</i>}</div><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
function Row({dot,label,value}:{dot:string,label:string,value:any}){return <div className="attRow"><span className={`dot ${dot}`}/><span>{label}</span><b>{value}</b></div>}
function ActionTable({rows}:{rows:Action[]}){return <div className="tableWrap"><table><thead><tr><th>Cliente</th><th>Vendedor</th><th>Situação</th><th>Potencial</th><th>Score</th><th>Ação</th></tr></thead><tbody>{rows.length?rows.map((x,i)=><tr key={i}><td><b>{x.customer_name||x.customer_code||'Cliente'}</b><small>{x.branch_code&&`Filial ${x.branch_code}`}</small></td><td>{x.seller_name||'A reconciliar'}</td><td><span className={`pill ${(x.status||'').includes('inactive')?'red':'amber'}`}>{labelStatus(x.status)}</span></td><td>{money(Number(x.revenue_gap||0))}</td><td><b>{Math.round(Number(x.opportunity_score||0))}</b></td><td><button className="linkBtn">{x.customer_ready&&x.seller_ready?'Agendar visita':'Ver análise'}</button></td></tr>):<tr><td colSpan={6} className="emptyRow">Sem registros nesse filtro.</td></tr>}</tbody></table></div>}
function labelStatus(v?:string){return({inactive:'Inativo',strong_drop:'Queda forte',strong_decline:'Queda forte',decline:'Em queda',lost_mix:'Mix perdido',anomaly:'Revisar devolução'}as any)[v||'']||v||'Oportunidade'}
function RevenueChart(){const vals=[29.0,24.2,31.7,32.1,27.0,30.0,34.2,31.4],m=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago'],max=36;return <div className="chart"><div className="bars">{vals.map((v,i)=><div className="barCol"><span>{v.toFixed(1)}</span><div className="bar" style={{height:`${v/max*180}px`}}/><small>{m[i]}</small></div>)}</div><div className="legend"><i/>Receita líquida (R$ milhões)</div></div>}
function Placeholder({title}:{title:string}){return <><div className="pageHead"><div><h1>{title}</h1><p>Módulo preservado da versão Web moderna do Movvant Enterprise.</p></div></div><div className="card full"><div className="empty"><LayoutDashboard size={38}/><b>{title}</b><span>Este transplante preserva o módulo; a implementação original será reconectada nesta mesma base.</span></div></div></>}
