import React,{useCallback,useEffect,useMemo,useState}from'react';
import{createClient}from'@supabase/supabase-js';
import{LayoutDashboard,ShoppingCart,Users,CalendarDays,Route,Car,Truck,BrainCircuit,FileText,BarChart3,Settings,Shield,Search,Bell,HelpCircle,Plus,ChevronDown,TrendingUp,Target,MapPin,Gauge,RefreshCw,LockKeyhole}from'lucide-react';

const sb=createClient('https://aaqbwdrqmhuzqdesywze.supabase.co','sb_publishable_FDSQxTSJYyBdfRuV8ZwmGw_RwzO9-_Z',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const NAV=[['Visão Geral',LayoutDashboard],['Comercial',ShoppingCart],['Clientes',Users],['Agenda e Visitas',CalendarDays],['Rotas',Route],['Frota / KM',Car],['Logística',Truck],['Inteligência',BrainCircuit],['Relatórios',FileText],['Dashboards',BarChart3],['Configurações',Settings],['Administração',Shield]] as const;
const money=(v:number)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const pct=(v:number)=>`${Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:1})}%`;
const managerRoles=new Set(['owner','admin','director','commercial_director','regional_supervisor','branch_manager']);

type Kpi={metric_code:string;period_date:string;metric_value:number};
type Branch={id:string;code:string;name:string};
type Action={opportunity_id?:number;company_id?:string;branch_id?:string;branch_code?:string;customer_code?:string;customer_name?:string;seller_name?:string;reference_month?:string;baseline_revenue?:number;current_revenue?:number;revenue_gap?:number;change_pct?:number;status?:string;opportunity_score?:number;lost_mix_items?:number;mix_gap?:number;combined_score?:number;target_customer_id?:string;seller_user_id?:string;can_schedule_visit?:boolean;recommended_action?:string};

export default function App(){
 const[active,setActive]=useState('Inteligência');const[tab,setTab]=useState('Dashboard');const[loading,setLoading]=useState(true);const[authRequired,setAuthRequired]=useState(false);const[error,setError]=useState('');const[kpis,setKpis]=useState<Kpi[]>([]);const[actions,setActions]=useState<Action[]>([]);const[branches,setBranches]=useState<Branch[]>([]);const[branch,setBranch]=useState('');const[seller,setSeller]=useState('');const[from,setFrom]=useState('2026-01-01');const[to,setTo]=useState('2026-08-31');const[sessionLabel,setSessionLabel]=useState('Movvant Enterprise');const[companyId,setCompanyId]=useState('');const[scopeBranchId,setScopeBranchId]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const{data:{session}}=await sb.auth.getSession();if(!session){setAuthRequired(true);setKpis([]);setActions([]);setBranches([]);return}setAuthRequired(false);const{data:assignments,error:roleError}=await sb.from('user_role_assignments').select('company_id,branch_id,roles(slug,name)').eq('user_id',session.user.id).eq('active',true);if(roleError)throw roleError;const ra:any=(assignments||[])[0];if(!ra?.company_id)throw new Error('Usuário sem empresa/permissão ativa no Movvant Enterprise.');const cid=ra.company_id as string;setCompanyId(cid);const roleSlug=ra?.roles?.slug||'';const restrictedBranch=!managerRoles.has(roleSlug)&&ra?.branch_id?String(ra.branch_id):'';setScopeBranchId(restrictedBranch);if(restrictedBranch)setBranch(restrictedBranch);const{data:p}=await sb.from('profiles').select('full_name').eq('user_id',session.user.id).maybeSingle();setSessionLabel(p?.full_name||session.user.email||'Movvant');
 let bq=sb.from('branches').select('id,code,name').eq('company_id',cid).eq('active',true).order('name');if(restrictedBranch)bq=bq.eq('id',restrictedBranch);
 let aq=sb.from('v_historical_commercial_action_center').select('*').eq('company_id',cid).order('combined_score',{ascending:false}).limit(200);if(restrictedBranch)aq=aq.eq('branch_id',restrictedBranch);
 const[{data:b,error:be},{data:k,error:ke},{data:a,error:ae}]=await Promise.all([bq,sb.from('kpi_snapshots').select('metric_code,period_date,metric_value').eq('company_id',cid).contains('dimension',{source:'historical_sales_2026',scope:'company'}).order('period_date'),aq]);if(be)throw be;if(ke)throw ke;if(ae)throw ae;setBranches((b||[])as Branch[]);setKpis((k||[])as Kpi[]);setActions((a||[])as Action[]);}catch(e:any){setError(e?.message||'Falha ao carregar Inteligência Comercial.')}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const{data:{subscription}}=sb.auth.onAuthStateChange(()=>load());return()=>subscription.unsubscribe()},[load]);
 const summary=useMemo(()=>{const rows=kpis.filter(x=>x.period_date>=from&&x.period_date<=to);const sum=(c:string)=>rows.filter(x=>x.metric_code===c).reduce((s,x)=>s+Number(x.metric_value||0),0);const avg=(c:string)=>{const r=rows.filter(x=>x.metric_code===c);return r.length?r.reduce((s,x)=>s+Number(x.metric_value||0),0)/r.length:0};return{revenue:sum('commercial.revenue'),orders:sum('commercial.orders'),profit:sum('commercial.net_profit'),margin:avg('commercial.margin_pct'),ticket:avg('commercial.ticket_average'),customers:avg('commercial.active_customers'),mix:avg('commercial.product_mix')}} ,[kpis,from,to]);
 const revenueSeries=useMemo(()=>kpis.filter(x=>x.metric_code==='commercial.revenue'&&x.period_date>=from&&x.period_date<=to).sort((a,b)=>a.period_date.localeCompare(b.period_date)),[kpis,from,to]);
 const sellers=useMemo(()=>Array.from(new Set(actions.map(x=>x.seller_name).filter(Boolean) as string[])).sort((a,b)=>a.localeCompare(b,'pt-BR')),[actions]);
 const filteredActions=useMemo(()=>{const bc=branches.find(b=>b.id===branch)?.code;return actions.filter(x=>(!branch||x.branch_id===branch||x.branch_code===bc)&&(!seller||x.seller_name===seller))},[actions,branch,seller,branches]);
 const scheduleAction=(x:Action)=>{if(!x.can_schedule_visit)return;localStorage.setItem('movvant.commercialActionDraft',JSON.stringify({source:'commercial_intelligence',opportunityId:x.opportunity_id,customerId:x.target_customer_id,customerCode:x.customer_code,customerName:x.customer_name,sellerUserId:x.seller_user_id,sellerName:x.seller_name,branchId:x.branch_id,branchCode:x.branch_code,recommendedAction:x.recommended_action,revenueGap:x.revenue_gap,mixGap:x.mix_gap,createdAt:new Date().toISOString()}));setActive('Agenda e Visitas')};
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="logoMark">◆</span><div><strong>MOVVANT</strong><small>ENTERPRISE</small></div></div><nav>{NAV.map(([label,Icon])=><button key={label} className={active===label?'navItem active':'navItem'} onClick={()=>setActive(label)}><Icon size={18}/><span>{label}</span>{['Comercial','Agenda e Visitas','Frota / KM','Logística','Inteligência','Configurações','Administração'].includes(label)&&<ChevronDown size={14} className="navChevron"/>}</button>)}</nav><button className="collapse">◉ <span>Recolher Menu</span></button></aside>
 <main><header className="topbar"><div className="search"><Search size={16}/><input placeholder="Buscar clientes, pedidos, visitas, produtos..."/></div><button className="newBtn"><Plus size={16}/>Novo</button><button className="iconBtn"><Bell size={18}/></button><button className="iconBtn"><HelpCircle size={18}/></button><div className="user"><div className="avatar">M</div><div><b>{sessionLabel}</b><small>Gestão Comercial</small></div><ChevronDown size={15}/></div></header>
 <section className="content">{active==='Inteligência'?<Intelligence tab={tab} setTab={setTab} loading={loading} authRequired={authRequired} error={error} onRefresh={load} summary={summary} actions={filteredActions} branches={branches} branch={branch} setBranch={setBranch} branchLocked={!!scopeBranchId} seller={seller} setSeller={setSeller} sellers={sellers} from={from} setFrom={setFrom} to={to} setTo={setTo} revenueSeries={revenueSeries} onSchedule={scheduleAction} companyReady={!!companyId}/>:<Placeholder title={active}/>}</section></main></div>
}

function Intelligence(p:any){const tabs=['Dashboard','Oportunidades','Análise de Carteira','Metas','KPIs'];return <><div className="pageHead"><div><h1>Inteligência Comercial</h1><p>Decisões orientadas por dados • histórico comercial + operação de campo</p></div><button className="outline" onClick={p.onRefresh}><RefreshCw size={15}/>Atualizar</button></div><div className="tabs">{tabs.map((t:string)=><button key={t} className={p.tab===t?'tab active':'tab'} onClick={()=>p.setTab(t)}>{t}</button>)}</div><div className="filters"><label>Filial<select value={p.branch} disabled={p.branchLocked} onChange={(e)=>p.setBranch(e.target.value)}><option value="">Todas</option>{p.branches.map((b:Branch)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Vendedor<select value={p.seller} onChange={(e)=>p.setSeller(e.target.value)}><option value="">Todos</option>{p.sellers.map((s:string)=><option key={s} value={s}>{s}</option>)}</select></label><label>De<input type="date" value={p.from} onChange={(e)=>p.setFrom(e.target.value)}/></label><label>Até<input type="date" value={p.to} onChange={(e)=>p.setTo(e.target.value)}/></label></div>{p.loading?<div className="loading">Carregando dados reais do Movvant Enterprise...</div>:p.authRequired?<AuthRequired/>:p.error?<div className="loading">{p.error}</div>:p.tab==='Dashboard'?<Dashboard s={p.summary} actions={p.actions} revenueSeries={p.revenueSeries} onSchedule={p.onSchedule}/>:p.tab==='Oportunidades'?<Opportunities rows={p.actions} onSchedule={p.onSchedule}/>:p.tab==='Análise de Carteira'?<Portfolio rows={p.actions} onSchedule={p.onSchedule}/>:<KpiPage s={p.summary} title={p.tab}/>}</>}
function AuthRequired(){return <div className="card full"><div className="empty"><LockKeyhole size={38}/><b>Sessão Movvant necessária</b><span>Os indicadores reais são protegidos por empresa, filial e perfil. Entre pela sessão autenticada do Movvant para visualizar os dados.</span></div></div>}
function Dashboard({s,actions,revenueSeries,onSchedule}:{s:any,actions:Action[],revenueSeries:Kpi[],onSchedule:(x:Action)=>void}){const risk=actions.filter(x=>['inactive','strong_drop','strong_decline'].includes(x.status||''));const potential=actions.reduce((a,x)=>a+Math.max(0,Number(x.revenue_gap||0)),0);return <><div className="kpi-grid"><Kpi icon={<TrendingUp/>} label="Faturamento" value={money(s.revenue)} note="período selecionado"/><Kpi icon={<Target/>} label="Oportunidades" value={String(actions.length)} note={`${money(potential)} em gaps analisados`}/><Kpi icon={<Users/>} label="Clientes ativos / mês" value={Math.round(s.customers).toLocaleString('pt-BR')} note="média do período"/><Kpi icon={<ShoppingCart/>} label="Pedidos" value={Math.round(s.orders).toLocaleString('pt-BR')} note={`Ticket ${money(s.ticket)}`}/><Kpi icon={<Gauge/>} label="Margem média" value={pct(s.margin)} note={`Lucro ${money(s.profit)}`}/><Kpi icon={<BarChart3/>} label="Mix médio / mês" value={Math.round(s.mix).toLocaleString('pt-BR')} note="produtos vendidos"/></div><div className="grid2"><div className="card"><div className="cardTitle"><div><h3>Desempenho Comercial</h3><small>Receita líquida mensal • dados persistidos</small></div></div><RevenueChart rows={revenueSeries}/></div><div className="card"><div className="cardTitle"><div><h3>Central de Atenção</h3><small>Exceções e oportunidades prioritárias</small></div></div><div className="attention"><Row dot="red" label="Clientes em risco" value={risk.length}/><Row dot="amber" label="Oportunidades priorizadas" value={actions.length}/><Row dot="blue" label="Potencial analisado" value={money(potential)}/><Row dot="green" label="Fonte" value="Movvant Enterprise"/></div></div></div><div className="grid2 lower"><div className="card"><h3>Oportunidades prioritárias</h3><ActionTable rows={actions.slice(0,7)} onSchedule={onSchedule}/></div><div className="card"><h3>Eficiência de campo</h3><div className="empty"><MapPin size={36}/><b>Agenda + Rotas + KM</b><span>Oportunidades reconciliadas podem ser enviadas para a Agenda; o resultado será cruzado com execução de rota/KM e venda posterior.</span></div></div></div></>}
function Opportunities({rows,onSchedule}:{rows:Action[],onSchedule:(x:Action)=>void}){return <div className="card full"><div className="cardTitle"><div><h3>Central de Ações Comerciais</h3><small>Queda de faturamento, inatividade e perda de mix</small></div></div><ActionTable rows={rows} onSchedule={onSchedule}/></div>}
function Portfolio({rows,onSchedule}:{rows:Action[],onSchedule:(x:Action)=>void}){return <div className="grid2"><div className="card"><h3>Carteira em risco</h3><ActionTable rows={rows.filter(x=>['inactive','strong_drop','strong_decline'].includes(x.status||'')).slice(0,20)} onSchedule={onSchedule}/></div><div className="card"><h3>Qualidade do vínculo</h3><div className="attention"><Row dot="green" label="Oportunidades históricas" value={rows.length}/><Row dot="amber" label="Aguardando cliente real" value={rows.filter(x=>!x.target_customer_id).length}/><Row dot="amber" label="Aguardando vendedor real" value={rows.filter(x=>!x.seller_user_id).length}/><Row dot="blue" label="Prontas para Agenda" value={rows.filter(x=>x.can_schedule_visit).length}/></div></div></div>}
function KpiPage({s,title}:{s:any,title:string}){return <div className="card full"><h3>{title}</h3><div className="kpi-grid compact"><Kpi label="Receita" value={money(s.revenue)}/><Kpi label="Margem" value={pct(s.margin)}/><Kpi label="Pedidos" value={Math.round(s.orders).toLocaleString('pt-BR')}/><Kpi label="Ticket" value={money(s.ticket)}/></div></div>}
function Kpi({label,value,note,icon}:{label:string,value:string,note?:string,icon?:any}){return <div className="kpi card"><div className="kpiTop"><span>{label}</span>{icon&&<i>{React.cloneElement(icon,{size:18})}</i>}</div><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
function Row({dot,label,value}:{dot:string,label:string,value:any}){return <div className="attRow"><span className={`dot ${dot}`}/><span>{label}</span><b>{value}</b></div>}
function ActionTable({rows,onSchedule}:{rows:Action[],onSchedule:(x:Action)=>void}){return <div className="tableWrap"><table><thead><tr><th>Cliente</th><th>Vendedor</th><th>Situação</th><th>Potencial</th><th>Mix perdido</th><th>Score</th><th>Ação</th></tr></thead><tbody>{rows.length?rows.map((x,i)=><tr key={x.opportunity_id||i}><td><b>{x.customer_name||x.customer_code||'Cliente'}</b><small>{x.branch_code&&`Filial ${x.branch_code}`}</small></td><td>{x.seller_name||'A reconciliar'}</td><td><span className={`pill ${(x.status||'').includes('inactive')?'red':'amber'}`}>{labelStatus(x.status)}</span></td><td>{money(Math.max(0,Number(x.revenue_gap||0)))}</td><td>{x.lost_mix_items?`${x.lost_mix_items} itens · ${money(Number(x.mix_gap||0))}`:'—'}</td><td><b>{Math.round(Number(x.combined_score||x.opportunity_score||0))}</b></td><td><button className="linkBtn" disabled={!x.can_schedule_visit} onClick={()=>onSchedule(x)}>{x.can_schedule_visit?'Agendar visita':'Vínculo pendente'}</button></td></tr>):<tr><td colSpan={7} className="emptyRow">Sem registros nesse filtro.</td></tr>}</tbody></table></div>}
function labelStatus(v?:string){return({inactive:'Inativo',strong_drop:'Queda forte',strong_decline:'Queda forte',decline:'Em queda',lost_mix:'Mix perdido',anomaly:'Revisar devolução'}as any)[v||'']||v||'Oportunidade'}
function RevenueChart({rows}:{rows:Kpi[]}){if(!rows.length)return <div className="empty"><BarChart3 size={32}/><b>Sem série mensal disponível neste filtro</b><span>Nenhum valor é simulado no frontend.</span></div>;const vals=rows.map(x=>Number(x.metric_value||0)/1_000_000),max=Math.max(...vals,1);return <div className="chart"><div className="bars">{rows.map((x,i)=>{const d=new Date(`${x.period_date}T12:00:00`);const label=d.toLocaleDateString('pt-BR',{month:'short'}).replace('.','');return <div className="barCol" key={`${x.period_date}-${i}`}><span>{vals[i].toLocaleString('pt-BR',{maximumFractionDigits:1})}</span><div className="bar" style={{height:`${Math.max(4,vals[i]/max*180)}px`}}/><small>{label}</small></div>})}</div><div className="legend"><i/>Receita líquida real (R$ milhões)</div></div>}
function Placeholder({title}:{title:string}){const draft=title==='Agenda e Visitas'?localStorage.getItem('movvant.commercialActionDraft'):null;return <><div className="pageHead"><div><h1>{title}</h1><p>Módulo preservado da versão Web moderna do Movvant Enterprise.</p></div></div><div className="card full"><div className="empty"><LayoutDashboard size={38}/><b>{title}</b><span>{draft?'Existe uma oportunidade comercial pronta para ser recebida pela Agenda original durante a reconexão do módulo.':'A implementação original será reconectada nesta mesma base; este preview não substitui o módulo aprovado.'}</span></div></div></>}
